### ISSUE TITLE
Mask R-CNN AttributeError: 'module' object has no attribute 'fullmatch'

### ISSUE THREAD

**Issue by Ujang24** [matterport/Mask_RCNN#1025]
Dear all, I tried the balloon sample.
When I trained the model with balloon dataset, on windows, it was ok. 
But when I tried in a GPU server, it gave the following error:

```
Traceback (most recent call last):
  File "balloon.py", line 385, in <module>
    train(model)
  File "balloon.py", line 203, in train
    layers='heads')
  File "build/bdist.linux-x86_64/egg/mrcnn/model.py", line 2353, in train
  File "build/bdist.linux-x86_64/egg/mrcnn/model.py", line 2227, in set_trainable
AttributeError: 'module' object has no attribute 'fullmatch'

inside model.py there were code lines:
import re
..
..
trainable = bool(re.fullmatch(layer_regex, layer.name))
..
```

I have installed all the requirements.
I have done also the setup.py

My environment in the server:
HPCT R 425 gs - 10 GP | Ubuntu Server 16.04 | | 385 GB | Titan V * 10

Suggestions and solutions are very welcomed

**Comment by fastlater** [comment]
Maybe #199

**Comment by Ujang24** [comment]
Thank you fastlater. 

Btw, #199 is not the answer. 
Actually it was my fault.

Previously I used my laptop which only contains python 3.5
I used `python `command to execute the script and it went well

The error message came out when I executed the codes in the server.
I didn't know that there was 2 versions of python inside.
I used python command which called python 2.7.
While 'fullmatch' was implemented starting from python 3.4
So please bear in mind guys to use `python3 `at the command line
I close this
