### ISSUE TITLE
image_id is empty in data_generator function

### ISSUE THREAD

**Issue by zq1995012** [matterport/Mask_RCNN#1085]
This is the complete error output:
` File "S:\anaconda\envs\research\lib\site-packages\mask_rcnn-2.1-py3.6.egg\mrcnn\model.py", line 1692, in data_generator
ZeroDivisionError: integer division or modulo by zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ape.py", line 366, in <module>
    train(model)
  File "ape.py", line 198, in train
    layers='heads')
  File "S:\anaconda\envs\research\lib\site-packages\mask_rcnn-2.1-py3.6.egg\mrcnn\model.py", line 2374, in train
  File "S:\anaconda\envs\research\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "S:\anaconda\envs\research\lib\site-packages\keras\engine\training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "S:\anaconda\envs\research\lib\site-packages\keras\engine\training_generator.py", line 234, in fit_generator
    workers=0)
  File "S:\anaconda\envs\research\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "S:\anaconda\envs\research\lib\site-packages\keras\engine\training.py", line 1472, in evaluate_generator
    verbose=verbose)
  File "S:\anaconda\envs\research\lib\site-packages\keras\engine\training_generator.py", line 330, in evaluate_generator
    generator_output = next(output_generator)
  File "S:\anaconda\envs\research\lib\site-packages\mask_rcnn-2.1-py3.6.egg\mrcnn\model.py", line 1810, in data_generator
UnboundLocalError: local variable 'image_id' referenced before assignment`

This is the dataset class that I implemented:
`def load_ape(self, dataset_dir, subset):
        """Load a subset of the Balloon dataset.
        dataset_dir: Root directory of the dataset.
        subset: Subset to load: train or val
        """
        # Add classes. We have only one class to add.
        self.add_class("ape", 1, "ape")
        count = 0
        # Train or validation dataset?
        assert subset in ["train", "val"]
        if subset == "train":
            count = 1
            file = "train.txt"
        else:
            print("entering val")
            count = 3
            file = "test.txt"
        file_path = os.path.join(dataset_dir, file)
        image_ids = []
        with open(file_path, 'r') as f:
            for line in f.readlines():
                temp = line.split("/")
                image_ids.append(temp[3].strip())
        # if subset == "val":
        #     print(image_ids)
        image_dir = "JPEGImages"
        dataset_dir = os.path.join(dataset_dir, image_dir)

       # Add images
        for image_id in image_ids:
            image_path = os.path.join(dataset_dir, image_id)
            image = skimage.io.imread(image_path)
            height, width = image.shape[:2]

            self.add_image(
                "ape",
                image_id=count,
                path=image_path)
            print("count is {}".format(count))
            count+=1
     

    def load_mask(self, image_id):
        """Generate instance masks for an image.
       Returns:
        masks: A bool array of shape [height, width, instance count] with
            one mask per instance.
        class_ids: a 1D array of class IDs of the instance masks.
        """
        # If not a balloon dataset image, delegate to parent class.
        info = self.image_info[image_id]
        # Get mask directory from image path
        mask_dir = os.path.join(os.path.dirname(os.path.dirname(info['path'])), "mask")
        file_to_find = info['path'][-10:]
        # print("image_id is this: {}".format(file_to_find))
        # print("mask_dir is this: {}".format(mask_dir))
        # Read mask files from .png image
        # mask = []
        mask = None
        for f in next(os.walk(mask_dir))[2]:
            if f.endswith(".png"):
                file_name_temp = f.split(".")
                file_name_temp = file_name_temp[0]
                file_name_temp = file_name_temp+".jpg"
                # print("file_name_temp is this: {}".format(file_name_temp))
                if file_name_temp == file_to_find[2:]:
                    m = skimage.io.imread(os.path.join(mask_dir, f)).astype(np.bool)
                    # mask.append(m)
                    mask = m
        # print("masks has {} items".format(len(mask)))
        # mask = np.stack(mask, axis=0)
        # print("mask's shape is {}".format(mask.shape))
        # print("mask's shape is {}".format(mask.shape[-1]))

        # Return mask, and array of class IDs of each instance. Since we have
        # one class ID, we return an array of ones
        return mask, np.ones([mask.shape[-1]], dtype=np.int32)`

Does anyone know how to fix it?

**Comment by fastlater** [comment]
wrong path? Maybe wrong file format? 
`UnboundLocalError: local variable 'image_id' referenced before assignment`` is more a python warning than mask rcnn error.

**Comment by zq1995012** [comment]
@fastlater Thanks for replying. Both validate dataset and train dataset have been successfully loaded, this error occurred at the end of an epoch. The original images are jpg and masks are png format.

**Comment by keineahnung2345** [comment]
@zq1995012 The error sounds like https://github.com/matterport/Mask_RCNN/issues/871, which has empty annotation files in the validation set.

**Comment by zq1995012** [comment]
@keineahnung2345 Thanks for replying. I have checked that post as well, but unfortunately we have the different situation. My dataset is something like this:
images/{all original images}
masks/{all masks}
train.txt
test.txt

So my training script follows the nucleus sample style with minor modifications.
I can confirm that there are no other files than images in both images and masks folder, and all files listed in train and test text file exsists.

**Comment by keineahnung2345** [comment]
To the error message,
> ` File "S:\anaconda\envs\research\lib\site-packages\mask_rcnn-2.1-py3.6.egg\mrcnn\model.py", line 1692, in data_generator
ZeroDivisionError: integer division or modulo by zero

it seems len(image_ids) is equal to 0 for your dataset, you can check it by printing `len(image_ids)` before https://github.com/matterport/Mask_RCNN/blob/master/mrcnn/model.py#L1693.

**Comment by keineahnung2345** [comment]
```
self.add_image(
            "ape",
            image_id=count,
            path=image_path)
```
In the code above, `image_id=count` should be replaced with `image_id=image_id`!

**Comment by zq1995012** [comment]
@keineahnung2345 I used to set image_id=image_id and this problem occurred, then I followed some solution to set the image_id to the consecutive numbers, but still not work...

**Comment by keineahnung2345** [comment]
Or you should change the `count=3` after `print("entering val")` to `count=0`.

**Comment by LightStrand** [comment]
Getting this same issue

**Comment by gethubwy** [comment]
> @zq1995012 The error sounds like #871, which has empty annotation files in the validation set.

Yes,(1)empty annotation files in the validation set.(2)wrong annotation files in the validation set.
I want to know how to generating annotation files in the validation set?

**Comment by ignacioduquevega** [comment]
I was having the same issue, maybe is a little late, but after loading the dataset is necessary to execute `dataset.prepare()` and this will populate the `image_ids` list.

**Comment by kakinola23** [comment]
Hello, I am currently having the same issue. Can someone help me out please. We can chat on zoom to trouble shoot this error please
