### ISSUE TITLE
errors when trying to train balloon samples

### ISSUE THREAD

**Issue by lunasdejavu** [matterport/Mask_RCNN#1093]
My enviroment is windows 10 x64  ,GPU :GeForce GTX 1060 3GB CUDA9.0 cudnn7.1.4
anaconda under venv: python 3.6  tensorflow-gpu      1.11.0

I only modified balloon.py for `ROOT_DIR = os.path.abspath("C:/HSIR/Mask_RCNN/")`

when I typed this:
`python balloon.py train --dataset=C:/HSIR/Mask_RCNN/datasets/balloon_dataset/balloon/ --weights=coco`

it showed the error:
Loading weights  C:\HSIR\Mask_RCNN\mask_rcnn_coco.h5
2018-10-30 14:15:41.495794: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2018-10-30 14:15:41.812090: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1405] Found device 0 with properties:
name: GeForce GTX 1060 3GB major: 6 minor: 1 memoryClockRate(GHz): 1.759
pciBusID: 0000:01:00.0
totalMemory: 3.00GiB freeMemory: 2.42GiB
2018-10-30 14:15:41.812250: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1484] Adding visible gpu devices: 0
2018-10-30 14:15:42.486622: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-10-30 14:15:42.486782: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:971]      0
2018-10-30 14:15:42.490780: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:984] 0:   N
2018-10-30 14:15:42.491521: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2125 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060 3GB, pci bus id: 0000:01:00.0, compute capability: 6.1)
Training network heads
Traceback (most recent call last):
  File "balloon.py", line 364, in <module>
    train(model)
  File "balloon.py", line 199, in train
    layers='heads')
  File "C:\HSIR\Mask_RCNN\mrcnn\model.py", line 2341, in train
    histogram_freq=0, write_graph=True, write_images=False),
  File "C:\Users\willy_sung\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\keras\callbacks.py", line 745, in __init__
    from tensorflow.contrib.tensorboard.plugins import projector
  File "C:\Users\willy_sung\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\tensorflow\contrib\__init__.py", line 31, in <module>
    from tensorflow.contrib import coder
  File "C:\Users\willy_sung\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\tensorflow\contrib\coder\__init__.py", line 22, in <module>
    from tensorflow.contrib.coder.python.layers.entropybottleneck import *
  File "C:\Users\willy_sung\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\tensorflow\contrib\coder\python\layers\entropybottleneck.py", line 24, in <module>
    from tensorflow.contrib.coder.python.ops import coder_ops
  File "C:\Users\willy_sung\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\tensorflow\contrib\coder\python\ops\coder_ops.py", line 30, in <module>
    resource_loader.get_path_to_datafile("_coder_ops.so"))
  File "C:\Users\willy_sung\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\tensorflow\contrib\util\loader.py", line 56, in load_op_library
    ret = load_library.load_op_library(path)
  File "C:\Users\willy_sung\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\tensorflow\python\framework\load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: C:\Users\willy_sung\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\tensorflow\contrib\coder\python\ops\_coder_ops.so not found

but when I try some basic function of tensorflow ,nothing is wrong .
can someone help me please?

**Comment by keineahnung2345** [comment]
I use TF1.9 and haven't meet this kind of error. Maybe you could try with TF1.9.

**Comment by lunasdejavu** [comment]
@keineahnung2345  thanks.After I reinstalled tensorflow then there was no error after all.

**Comment by ybxbupt** [comment]
keras 2.2.1, tensorflow-gpu 1.11.0
I test OK
