### ISSUE TITLE
class_ids = class_ids[_idx] & IndexError

### ISSUE THREAD

**Issue by synioe** [matterport/Mask_RCNN#1104]
when I try to train mask-rcnn on my own data,I got the following error.I used the VIA notation tools(2.0).
---------------------------------------------------------------------------------------------------------
Checkpoint Path: /home/root1/Mask_RCNN/logs/defect20181105T2153/mask_rcnn_defect_{epoch:04d}.h5
Selecting layers to train
fpn_c5p5               (Conv2D)
fpn_c4p4               (Conv2D)
fpn_c3p3               (Conv2D)
fpn_c2p2               (Conv2D)
fpn_p5                 (Conv2D)
fpn_p2                 (Conv2D)
fpn_p3                 (Conv2D)
fpn_p4                 (Conv2D)
In model:  rpn_model
    rpn_conv_shared        (Conv2D)
    rpn_class_raw          (Conv2D)
    rpn_bbox_pred          (Conv2D)
mrcnn_mask_conv1       (TimeDistributed)
mrcnn_mask_bn1         (TimeDistributed)
mrcnn_mask_conv2       (TimeDistributed)
mrcnn_mask_bn2         (TimeDistributed)
mrcnn_class_conv1      (TimeDistributed)
mrcnn_class_bn1        (TimeDistributed)
mrcnn_mask_conv3       (TimeDistributed)
mrcnn_mask_bn3         (TimeDistributed)
mrcnn_class_conv2      (TimeDistributed)
mrcnn_class_bn2        (TimeDistributed)
mrcnn_mask_conv4       (TimeDistributed)
mrcnn_mask_bn4         (TimeDistributed)
mrcnn_bbox_fc          (TimeDistributed)
mrcnn_mask_deconv      (TimeDistributed)
mrcnn_class_logits     (TimeDistributed)
mrcnn_mask             (TimeDistributed)
/home/root1/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py:97: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
/home/root1/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/engine/training_generator.py:46: UserWarning: Using a generator with `use_multiprocessing=True` and multiple workers may duplicate your data. Please consider using the`keras.utils.Sequence class.
  UserWarning('Using a generator with `use_multiprocessing=True`'
[name id] [1]
[name id] [1]
[name id] [4]
[name id] [1]
[name id] [1]
[name id] [1]
[name id] [3]
[name id] [1]
[name id] [1]
ERROR:root:Error processing image ……
Traceback (most recent call last):
  File "/home/root1/Mask_RCNN/mrcnn/model.py", line 1709, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/root1/Mask_RCNN/mrcnn/model.py", line 1265, in load_image_gt
    class_ids = class_ids[_idx]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 1 but corresponding boolean dimension is 2
……………………………………………………
1/100 [..............................] - ETA: 28:31 - loss: 9.1306 - rpn_class_loss: 0.0014 - rpn_bbox_loss: 0.1050 - mrcnn_class_loss: 6.4022 - mrcnn_bbox_loss: 1.9416 - mrcnn_mask_loss: 0.6804Traceback (most recent call last):
  File "defect_detection.py", line 387, in <module>
    train(model)
  File "defect_detection.py", line 222, in train
    layers='heads')
  File "/home/root1/Mask_RCNN/mrcnn/model.py", line 2374, in train
    use_multiprocessing=True,
  File "/home/root1/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/root1/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/engine/training.py", line 1415, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/root1/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/engine/training_generator.py", line 177, in fit_generator
    generator_output = next(output_generator)
  File "/home/root1/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/utils/data_utils.py", line 793, in get
    six.reraise(value.__class__, value, value.__traceback__)
  File "/home/root1/anaconda3/envs/tensorflow/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
IndexError: boolean index did not match indexed array along dimension 0; dimension is 1 but corresponding boolean dimension is 4
-------------------------------------------------------------------------------------------
and I cannot figure out the solution to solve it,is there any one can give a suggestion.THX in advance.

**Comment by enoceanwei** [comment]
Hello,

Please check your configuration in <mrcnn-->config.py>, the 'NUM_CLASSES = X'', where X should your truly classes, cuz, your problem is dimension problem, thanks.

Kind regards

Wei

**Comment by littleTaodog** [comment]
> Hello,
> 
> Please check your configuration in config.py>, the 'NUM_CLASSES = X'', where X should your truly classes, cuz, your problem is dimension problem, thanks.
> 
> Kind regards
> 
> Wei
you mean modify "NUM_CLASSED" in class Config?

class CatVSDogConfig(Config):
    """Configuration for training on the toy  dataset.
    Derives from the base Config class and overrides some values.
    """
    # Give the configuration a recognizable name
    NAME = "catvsdog"

    # We use a GPU with 12GB memory, which can fit two images.
    # Adjust down if you use a smaller GPU.
    IMAGES_PER_GPU = 1

    # Number of classes (including background)
    NUM_CLASSES = 1 + 3  # Background + cat + dog + not_defined

    # Number of training steps per epoch
    STEPS_PER_EPOCH = 100

    # Skip detections with < 90% confidence
    DETECTION_MIN_CONFIDENCE = 0.9

**Comment by popper0912** [comment]
> ## when I try to train mask-rcnn on my own data,I got the following error.I used the VIA notation tools(2.0).
> ## Checkpoint Path: /home/root1/Mask_RCNN/logs/defect20181105T2153/mask_rcnn_defect_{epoch:04d}.h5
> Selecting layers to train
> fpn_c5p5 (Conv2D)
> fpn_c4p4 (Conv2D)
> fpn_c3p3 (Conv2D)
> fpn_c2p2 (Conv2D)
> fpn_p5 (Conv2D)
> fpn_p2 (Conv2D)
> fpn_p3 (Conv2D)
> fpn_p4 (Conv2D)
> In model: rpn_model
> rpn_conv_shared (Conv2D)
> rpn_class_raw (Conv2D)
> rpn_bbox_pred (Conv2D)
> mrcnn_mask_conv1 (TimeDistributed)
> mrcnn_mask_bn1 (TimeDistributed)
> mrcnn_mask_conv2 (TimeDistributed)
> mrcnn_mask_bn2 (TimeDistributed)
> mrcnn_class_conv1 (TimeDistributed)
> mrcnn_class_bn1 (TimeDistributed)
> mrcnn_mask_conv3 (TimeDistributed)
> mrcnn_mask_bn3 (TimeDistributed)
> mrcnn_class_conv2 (TimeDistributed)
> mrcnn_class_bn2 (TimeDistributed)
> mrcnn_mask_conv4 (TimeDistributed)
> mrcnn_mask_bn4 (TimeDistributed)
> mrcnn_bbox_fc (TimeDistributed)
> mrcnn_mask_deconv (TimeDistributed)
> mrcnn_class_logits (TimeDistributed)
> mrcnn_mask (TimeDistributed)
> /home/root1/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py:97: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
> "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
> /home/root1/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/engine/training_generator.py:46: UserWarning: Using a generator with `use_multiprocessing=True` and multiple workers may duplicate your data. Please consider using the`keras.utils.Sequence class. UserWarning('Using a generator with `use_multiprocessing=True`'
> [name id] [1]
> [name id] [1]
> [name id] [4]
> [name id] [1]
> [name id] [1]
> [name id] [1]
> [name id] [3]
> [name id] [1]
> [name id] [1]
> ERROR:root:Error processing image ……
> Traceback (most recent call last):
> File "/home/root1/Mask_RCNN/mrcnn/model.py", line 1709, in data_generator
> use_mini_mask=config.USE_MINI_MASK)
> File "/home/root1/Mask_RCNN/mrcnn/model.py", line 1265, in load_image_gt
> class_ids = class_ids[_idx]
> IndexError: boolean index did not match indexed array along dimension 0; dimension is 1 but corresponding boolean dimension is 2
> ……………………………………………………
> 1/100 [..............................] - ETA: 28:31 - loss: 9.1306 - rpn_class_loss: 0.0014 - rpn_bbox_loss: 0.1050 - mrcnn_class_loss: 6.4022 - mrcnn_bbox_loss: 1.9416 - mrcnn_mask_loss: 0.6804Traceback (most recent call last):
> File "defect_detection.py", line 387, in 
> train(model)
> File "defect_detection.py", line 222, in train
> layers='heads')
> File "/home/root1/Mask_RCNN/mrcnn/model.py", line 2374, in train
> use_multiprocessing=True,
> File "/home/root1/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
> return func(*args, **kwargs)
> File "/home/root1/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/engine/training.py", line 1415, in fit_generator
> initial_epoch=initial_epoch)
> File "/home/root1/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/engine/training_generator.py", line 177, in fit_generator
> generator_output = next(output_generator)
> File "/home/root1/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/utils/data_utils.py", line 793, in get
> six.reraise(value.**class**, value, value.**traceback**)
> File "/home/root1/anaconda3/envs/tensorflow/lib/python3.6/site-packages/six.py", line 693, in reraise
> raise value
> IndexError: boolean index did not match indexed array along dimension 0; dimension is 1 but corresponding boolean dimension is 4
> and I cannot figure out the solution to solve it,is there any one can give a suggestion.THX in advance.

Do u fix it?

**Comment by wangyujiewj** [comment]
i met the same question and i do not know how to fix it

**Comment by flit86** [comment]
hi @wangyujiewj my problem was with not correct the label in JSON file. i fixed it, and now - ok.
![image](https://user-images.githubusercontent.com/42639987/59667087-cd8e9c80-91be-11e9-84b2-f38e4084025f.png)

**Comment by Aassifh** [comment]
No solution ? did you fix it ?
