### ISSUE TITLE
Training with Grayscale images

### ISSUE THREAD

**Issue by lunasdejavu** [matterport/Mask_RCNN#1121]
I followed the instructions on the wiki and modified the code from train_shapes.ipynb
> >1. In your subclass of Config, set IMAGE_CHANNEL_COUNT to N.
> 2. In the same class, change MEAN_PIXEL from 3 values to N values.
> 3. The load_image() method in the Dataset class is designed for RGB. It converts Grayscale images to RGB and removes the 4th channel if present (because typically it's an alpha channel). You'll need to override this method to handle your images.
```
def load_image(self, image_id):
        image = skimage.io.imread(self.image_info[image_id]['path'])
        return image
```
> 4.Since you're changing the shape of the input, the shape of the first Conv layer (Conv1) will change as well. So you can't use the provided pre-trained weights. To get around that, use the exclude parameter when you load the weights to exclude the first layer. This allows you to load weights of all layers except conv1, which will be initialized to random weights.
```
model.load_weights(COCO_MODEL_PATH, by_name=True,
                       exclude=["mrcnn_class_logits", "mrcnn_bbox_fc", 
                                "mrcnn_bbox", "mrcnn_mask", "conv1"])
```
> 5.If you train a subset of layers, remember to include conv1 since it's initialized to random weights. This is relevant if you pass layers="head" or layers="4+", ...etc. when you call train().
```
# Train the head branches
# Passing layers="heads" freezes all layers except the head
# layers. You can also pass a regular expression to select
# which layers to train by name pattern.
print("start training")
model.train(dataset_train, dataset_val, 
            learning_rate=config.LEARNING_RATE, 
            epochs=40, 
            layers='heads',augmentation=augmentation)
# Fine tune all layers
# Passing layers="all" trains all layers. You can also 
# pass a regular expression to select which layers to
# train by name pattern.
model.train(dataset_train, dataset_val, 
            learning_rate=config.LEARNING_RATE / 10,
            epochs=10, 
            layers="all",augmentation=augmentation)
```
it showed the error like this:
ERROR:root:Error processing image {'id': 1132, 'source': 'Newton Ring', 'path':
'C:/imageandmask\\img-1493_json/img.png', 'width': 2448, 'height': 2048, 'mask_p
ath': 'C:/imageandmask\\img-1493_json/label.png', 'yaml_path': 'C:/imageandmask\
\img-1493_json/info.yaml'}
Traceback (most recent call last):
  File "C:\Users\willy_sung\AppData\Local\Continuum\anaconda3\envs\venv2\lib\sit
e-packages\numpy\lib\arraypad.py", line 935, in _normalize_shape
    shape_arr = np.broadcast_to(shape_arr, (ndims, 2))
  File "C:\Users\willy_sung\AppData\Local\Continuum\anaconda3\envs\venv2\lib\sit
e-packages\numpy\lib\stride_tricks.py", line 176, in broadcast_to
    return _broadcast_to(array, shape, subok=subok, readonly=True)
  File "C:\Users\willy_sung\AppData\Local\Continuum\anaconda3\envs\venv2\lib\sit
e-packages\numpy\lib\stride_tricks.py", line 128, in _broadcast_to
    op_flags=[op_flag], itershape=shape, order='C')
ValueError: operands could not be broadcast together with remapped shapes [origi
nal->remapped]: (3,2) and requested shape (2,2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Mask_RCNN\mrcnn\model.py", line 1710, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "C:\Mask_RCNN\mrcnn\model.py", line 1220, in load_image_gt
    mode=config.IMAGE_RESIZE_MODE)
  File "C:\Mask_RCNN\mrcnn\utils.py", line 457, in resize_image
    image = np.pad(image, padding, mode='constant', constant_values=0)
  File "C:\Users\willy_sung\AppData\Local\Continuum\anaconda3\envs\venv2\lib\sit
e-packages\numpy\lib\arraypad.py", line 1200, in pad
    pad_width = _validate_lengths(narray, pad_width)
  File "C:\Users\willy_sung\AppData\Local\Continuum\anaconda3\envs\venv2\lib\sit
e-packages\numpy\lib\arraypad.py", line 979, in _validate_lengths
    normshp = _normalize_shape(narray, number_elements)
  File "C:\Users\willy_sung\AppData\Local\Continuum\anaconda3\envs\venv2\lib\sit
e-packages\numpy\lib\arraypad.py", line 938, in _normalize_shape
    raise ValueError(fmt % (shape,))
ValueError: Unable to create correctly shaped tuple from [(83, 84), (0, 0), (0,
0)]
Traceback (most recent call last):
  File "C:\Users\willy_sung\AppData\Local\Continuum\anaconda3\envs\venv2\lib\sit
e-packages\numpy\lib\arraypad.py", line 935, in _normalize_shape
    shape_arr = np.broadcast_to(shape_arr, (ndims, 2))
  File "C:\Users\willy_sung\AppData\Local\Continuum\anaconda3\envs\venv2\lib\sit
e-packages\numpy\lib\stride_tricks.py", line 176, in broadcast_to
    return _broadcast_to(array, shape, subok=subok, readonly=True)
  File "C:\Users\willy_sung\AppData\Local\Continuum\anaconda3\envs\venv2\lib\sit
e-packages\numpy\lib\stride_tricks.py", line 128, in _broadcast_to
    op_flags=[op_flag], itershape=shape, order='C')
ValueError: operands could not be broadcast together with remapped shapes [origi
nal->remapped]: (3,2) and requested shape (2,2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_shapes.py", line 262, in <module>
    layers='heads',augmentation=augmentation)
  File "C:\Mask_RCNN\mrcnn\model.py", line 2376, in train
    use_multiprocessing=True,
  File "C:\Users\willy_sung\AppData\Local\Continuum\anaconda3\envs\venv2\lib\sit
e-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\willy_sung\AppData\Local\Continuum\anaconda3\envs\venv2\lib\sit
e-packages\keras\engine\training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Users\willy_sung\AppData\Local\Continuum\anaconda3\envs\venv2\lib\sit
e-packages\keras\engine\training_generator.py", line 181, in fit_generator
    generator_output = next(output_generator)
  File "C:\Mask_RCNN\mrcnn\model.py", line 1710, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "C:\Mask_RCNN\mrcnn\model.py", line 1220, in load_image_gt
    mode=config.IMAGE_RESIZE_MODE)
  File "C:\Mask_RCNN\mrcnn\utils.py", line 457, in resize_image
    image = np.pad(image, padding, mode='constant', constant_values=0)
  File "C:\Users\willy_sung\AppData\Local\Continuum\anaconda3\envs\venv2\lib\sit
e-packages\numpy\lib\arraypad.py", line 1200, in pad
    pad_width = _validate_lengths(narray, pad_width)
  File "C:\Users\willy_sung\AppData\Local\Continuum\anaconda3\envs\venv2\lib\sit
e-packages\numpy\lib\arraypad.py", line 979, in _validate_lengths
    normshp = _normalize_shape(narray, number_elements)
  File "C:\Users\willy_sung\AppData\Local\Continuum\anaconda3\envs\venv2\lib\sit
e-packages\numpy\lib\arraypad.py", line 938, in _normalize_shape
    raise ValueError(fmt % (shape,))
ValueError: Unable to create correctly shaped tuple from [(83, 84), (0, 0), (0,
0)]

I know the problem is still about the number of channels, but I don't know what else I have to modify or change,can someone tell me please?

**Comment by lunasdejavu** [comment]
I found the padding of the resize function should be modified which someone should add it to the wiki.
I don't know why but I couldn't modify padding in resize_mask() by append() or extend() since it is not a numpy array.
util.py:
```
def resize_image(image, min_dim=None, max_dim=None, min_scale=None, mode="square"):
      padding = [(top_pad, bottom_pad), (left_pad, right_pad)]
      image = np.pad(image, padding, mode='constant', constant_values=0)
def resize_mask(mask, scale, padding, crop=None):
         padding2 = [(0, 0),(0,0)]
         padding2[0:1] =padding
        mask = np.pad(mask, padding2, mode='constant', constant_values=0)
```
then there is another error
# Init batch arrays
Traceback (most recent call last):
  File "train_shapes.py", line 259, in <module>
    layers='heads',augmentation=augmentation)
  File "C:\Mask_RCNN\mrcnn\model.py", line 2380, in train
    use_multiprocessing=True,
  File "C:\Users\willy_sung\AppData\Local\Continuum\anaconda3\envs\venv2\lib\sit
e-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\willy_sung\AppData\Local\Continuum\anaconda3\envs\venv2\lib\sit
e-packages\keras\engine\training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Users\willy_sung\AppData\Local\Continuum\anaconda3\envs\venv2\lib\sit
e-packages\keras\engine\training_generator.py", line 217, in fit_generator
    class_weight=class_weight)
  File "C:\Users\willy_sung\AppData\Local\Continuum\anaconda3\envs\venv2\lib\sit
e-packages\keras\engine\training.py", line 1211, in train_on_batch
    class_weight=class_weight)
  File "C:\Users\willy_sung\AppData\Local\Continuum\anaconda3\envs\venv2\lib\sit
e-packages\keras\engine\training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "C:\Users\willy_sung\AppData\Local\Continuum\anaconda3\envs\venv2\lib\sit
e-packages\keras\engine\training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_image to have 4 dimensions
, but got array with shape (1, 1024, 1024)

**Comment by lunasdejavu** [comment]
the error is in model.py
def data_generator(...)
```
     # Batch full?
            if b >= batch_size:
                inputs = [batch_images, batch_image_meta, batch_rpn_match, batch_rpn_bbox,
                          batch_gt_class_ids, batch_gt_boxes, batch_gt_masks]
                outputs = []
                if random_rois:
                    inputs.extend([batch_rpn_rois])
                ...
                yield inputs, outputs
```
it encountered the error at the last command.

**Comment by lunasdejavu** [comment]
@keineahnung2345 
thank you!!
so I should add 
```
import numpy as np
img = img[..., np.newaxis]
```
in` load_image()`?

**Comment by keineahnung2345** [comment]
Yes, please try it.

**Comment by chengchu88** [comment]
> it works fine now thanks!

Hello @lunasdejavu ,

Are you able to train it with grayscale now? After I added the line:

 img = img[..., np.newaxis]

I got new error as below:

=======================================
Traceback (most recent call last):
  File "manos2_coco_all_gray.py", line 547, in <module>
    train(model, args.train_target)
  File "manos2_coco_all_gray.py", line 288, in train
    augmentation=aug)
  File "C:\Users\Sandisk\Anaconda3\envs\tensorflow\lib\site-packages\mrcnn\model
.py", line 2417, in train
    use_multiprocessing=True,
  File "C:\Users\Sandisk\Anaconda3\envs\tensorflow\lib\site-packages\keras\legac
y\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Sandisk\Anaconda3\envs\tensorflow\lib\site-packages\keras\engin
e\training.py", line 1417, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Users\Sandisk\Anaconda3\envs\tensorflow\lib\site-packages\keras\engin
e\training_generator.py", line 213, in fit_generator
    class_weight=class_weight)
  File "C:\Users\Sandisk\Anaconda3\envs\tensorflow\lib\site-packages\keras\engin
e\training.py", line 1211, in train_on_batch
    class_weight=class_weight)
  File "C:\Users\Sandisk\Anaconda3\envs\tensorflow\lib\site-packages\keras\engin
e\training.py", line 750, in _standardize_user_data
    exception_prefix='input')
  File "C:\Users\Sandisk\Anaconda3\envs\tensorflow\lib\site-packages\keras\engin
e\training_utils.py", line 139, in standardize_input_data
    str(data_shape))
ValueError: Error when checking input: expected input_gt_masks to have shape (10
24, 1024, None) but got array with shape (2048, 2048, 100)
==============================

Any idea?

Thanks!

**Comment by pieterbl86** [comment]
@lunasdejavu great that it worked. I'm wondering where exactely you inserted the following code block:

``import numpy as np ``
`img = img[..., np.newaxis]`

In this snippet of code?

```
def load_image(self, image_id):
        image = skimage.io.imread(self.image_info[image_id]['path'])
        return image
```

What exactly did you change to make this work (it's a bit hard to read through all errors, I'm sorry)?

**Comment by chengchu88** [comment]
i will go look at my code/note and get back to you..

**Comment by lunasdejavu** [comment]
> np.newaxis



> @lunasdejavu great that it worked. I'm wondering where exactely you inserted the following code block:
> 
> `import numpy as np `
> `img = img[..., np.newaxis]`
> 
> In this snippet of code?
> 
> ```
> def load_image(self, image_id):
>         image = skimage.io.imread(self.image_info[image_id]['path'])
>         return image
> ```
> Or in the def load_image in the utils.py? What exactly did you change to make this work (it's a bit hard to read through all errors, I'm sorry)?
well just change all the channels which was 3 to 1 ,but I didn't use it later since it is very easy to be overfitting after all.

**Comment by pieterbl86** [comment]
@lunasdejavu I understand that np.newaxis is the key, but where exactely did you put this command? In the def load_image of the utils.py?

**Comment by davidb1** [comment]
> @lunasdejavu I understand that np.newaxis is the key, but where exactely did you put this command? In the def load_image of the utils.py?

He meant you should have something like this:

`    def load_image(self, image_id):
        """Load the specified image and return a [H,W,1] Numpy array.
        """
        # Load image
        image = skimage.io.imread(self.image_info[image_id]['path'])
        # Convert to grayscale for consistency.
        if image.ndim != 1:
            image = skimage.color.rgb2gray(image)

        # Extending the size of the image to be (h,w,1)
        image = image[..., np.newaxis]
        return image`

**Comment by davidb1** [comment]
> ValueError: operands could not be broadcast together with remapped shapes [origi
> nal->remapped]: (3,2) and requested shape (2,2)

@lunasdejavu I can't get past the error you had there:
```ValueError: operands could not be broadcast together with remapped shapes [origi
nal->remapped]: (3,2) and requested shape (2,2)```

Any hints?

**Comment by ApoorvaSuresh** [comment]
Hi, does anyone have an idea as to how the pretrained weights are used for the 4th channel? are they even used at all?

**Comment by patriciacs1994** [comment]
Hi @lunasdejavu , I am trying to train mask_rcnn with grayscale in order to speed up the process. I have done everything you have put here, but I did not succeed. 
**I got this error:**
ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (2,2) and requested shape (3,2)
**In this part of the code:**
File "C:\Users\PASI\Desktop\Object_detection\Mask_RCNN-master\mrcnn\utils.py", line 460, in resize_image
image = np.pad(image, padding, mode='constant', constant_values=0)

I have changed it already as you said before. Any idea?
Thank you in advance

**Comment by Genius-farmer** [comment]
Any solutions please? #2534
