### ISSUE TITLE
ERROR:root:Error processing image IndexError: boolean index did not match indexed array along dimension 0; dimension is 0 but corresponding boolean dimension is 10

### ISSUE THREAD

**Issue by hengai** [matterport/Mask_RCNN#1129]
WARNING:tensorflow:From /home/hp/Mask_RCNN-2.1/model.py:2078: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
image_id 6
/home/hp/anaconda3/lib/python3.5/site-packages/scipy/misc/pilutil.py:482: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if issubdtype(ts, int):
/home/hp/anaconda3/lib/python3.5/site-packages/scipy/misc/pilutil.py:485: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  elif issubdtype(type(size), float):
/home/hp/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py:100: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
/home/hp/anaconda3/lib/python3.5/site-packages/keras/engine/training_generator.py:46: UserWarning: Using a generator with `use_multiprocessing=True` and multiple workers may duplicate your data. Please consider using the`keras.utils.Sequence class.
  UserWarning('Using a generator with `use_multiprocessing=True`'
Epoch 1/10
image_id 22
image_id 68
ERROR:root:Error processing image {'height': 500, 'mask_path': 'train_data/cv2_mask/0325.png', 'width': 500, 'id': 22, 'path': 'train_data/pic/0325.jpg', 'yaml_path': 'train_data/labelme_json/0325_json/info.yaml', 'source': 'shapes'}
Traceback (most recent call last):
  File "/home/hp/Mask_RCNN-2.1/model.py", line 1637, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/hp/Mask_RCNN-2.1/model.py", line 1210, in load_image_gt
    class_ids = class_ids[_idx]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 0 but corresponding boolean dimension is 4

Does anyone know how to solve this ?

**Comment by hengai** [comment]
> I met the same problem, have you solved it? thank you so much!

Modify config.py file:  USE_MINI_MASK = True to USE_MINI_MASK = False ,and I solve it.

**Comment by HAMZARaouia** [comment]
Have you solved this ?

 @hengai your option doesnt' solve the pbm :/

**Comment by SWHL** [comment]
> Error processing image IndexError: boolean index did not match indexed array along dimension 0; dimension is 8 but corresponding boolean dimension is 5.

Code:
```python
_idx = np.sum(mask, axis=(0, 1)) > 0
print(f'idx:{_idx}')
print(f'mask shape:{mask.shape}')
mask = mask[:, :, _idx]
print(f'class_ids:{class_ids}')
class_ids = class_ids[_idx]
# output
idx:[False False  True False False]
mask shape:(384, 384, 5)
class_ids:[1 2 3 4 5 6 7 8]
```
I meet the same problem, but I fix it here.
the reason is that **idx only has 5 dimensions**, but **class_ids has 8 dimensions**. We only need track the mask, and **fix the shape of the mask**. In my code, it is as follow:
```python
def load_mask(self, image_id):
 """Generate instance masks for shapes of the given image ID.
"""
        global iter_num
        print("image_id", image_id)
        info = self.image_info[image_id]
        # count = 1  # number of object
        count = len(info['shapes'])  # number of object
        img = Image.open(info['mask_path'])
        
        # Here，num_obj = self.get_obj_index(img) is the before code,
        # num_obj = self.get_obj_index(img)
       # Modify the follow:
        num_obj = 8
        mask = np.zeros([info['height'], info['width'], num_obj], dtype=np.uint8)
        mask = self.draw_mask(num_obj, mask, img, image_id)
        ....
        ...
```
Hope to help.
