### ISSUE TITLE
Possible to use google colaboratory's GPU to train model?

### ISSUE THREAD

**Issue by darvida** [matterport/Mask_RCNN#1140]
Hey have anyoune tried to use google colaboratory's GPU to train your model with, if ur computer does not have enough GPU memory. 
If anyone has done it please let me know how 👍

**Comment by MI-LA01** [comment]
I'm currently using it and it works very well.

**Comment by salahsabri** [comment]
I am using colab, but I am getting the error message 
"Traceback (most recent call last):
  File "nucleus.py", line 487, in <module>
    train(model, args.dataset, args.subset)
  File "nucleus.py", line 259, in train
    dataset_train.load_nucleus(dataset_dir, subset)
  File "nucleus.py", line 209, in load_nucleus
    image_ids = next(os.walk(dataset_dir))[1]
StopIteration"

**Comment by darvida** [comment]
@MI-LA01 Do you know a tutorial of some kind that i can follow ?

**Comment by saskra** [comment]
> I am using colab, but I am getting the error message
> "Traceback (most recent call last):
> File "nucleus.py", line 487, in
> train(model, args.dataset, args.subset)
> File "nucleus.py", line 259, in train
> dataset_train.load_nucleus(dataset_dir, subset)
> File "nucleus.py", line 209, in load_nucleus
> image_ids = next(os.walk(dataset_dir))[1]
> StopIteration"

There is another thread for this problem: https://github.com/matterport/Mask_RCNN/issues/520#issuecomment-549349086
