### ISSUE TITLE
Error in training model

### ISSUE THREAD

**Issue by yamuna83** [matterport/Mask_RCNN#1145]
I am using google cloud instance to train the model. and I am getting error while training.
jet/var/python/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py:108: UserWarning: Converting sparse IndexedSlic
es to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
/jet/var/python/lib/python3.6/site-packages/keras/engine/training_generator.py:46: UserWarning: Using a generator with `use_multipr
ocessing=True` and multiple workers may duplicate your data. Please consider using the`keras.utils.Sequence class.
  UserWarning('Using a generator with `use_multiprocessing=True`'
Epoch 1/30
Traceback (most recent call last):
  File "/jet/var/python/lib/python3.6/site-packages/keras/utils/data_utils.py", line 678, in _data_generator_task
    self.queue.put((True, generator_output))
  File "<string>", line 2, in put
  File "/jet/var/python/lib/python3.6/multiprocessing/managers.py", line 757, in _callmethod
    kind, result = conn.recv()
  File "/jet/var/python/lib/python3.6/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/jet/var/python/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/jet/var/python/lib/python3.6/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError

**Comment by keineahnung2345** [comment]
You got the same error as https://github.com/matterport/Mask_RCNN/issues/334. Try set `use_multiprocessing = False` and `workers=1` in model.py

**Comment by yamuna83** [comment]
Thanks, this works for training 3 images. If I train with 10 images I am getting segmentation error.
I trien both mask_RCNN Master branch and mask_RCNN-2.1.

Selecting layers to train
fpn_c5p5               (Conv2D)
fpn_c4p4               (Conv2D)
fpn_c3p3               (Conv2D)
fpn_c2p2               (Conv2D)
fpn_p5                 (Conv2D)
fpn_p2                 (Conv2D)
fpn_p3                 (Conv2D)
fpn_p4                 (Conv2D)
In model:  rpn_model
    rpn_conv_shared        (Conv2D)
    rpn_class_raw          (Conv2D)
    rpn_bbox_pred          (Conv2D)
mrcnn_mask_conv1       (TimeDistributed)
mrcnn_mask_bn1         (TimeDistributed)
mrcnn_mask_conv2       (TimeDistributed)
mrcnn_mask_bn2         (TimeDistributed)
mrcnn_class_conv1      (TimeDistributed)
mrcnn_class_bn1        (TimeDistributed)
mrcnn_mask_conv3       (TimeDistributed)
mrcnn_mask_bn3         (TimeDistributed)
mrcnn_class_conv2      (TimeDistributed)
mrcnn_class_bn2        (TimeDistributed)
mrcnn_mask_conv4       (TimeDistributed)
mrcnn_mask_bn4         (TimeDistributed)
mrcnn_bbox_fc          (TimeDistributed)
mrcnn_mask_deconv      (TimeDistributed)
mrcnn_class_logits     (TimeDistributed)
mrcnn_mask             (TimeDistributed)
/jet/var/python/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py:108: UserWarning: Converting sparse IndexedSlic
es to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Epoch 1/2
OMP: Info #247: KMP_AFFINITY: pid 8523 tid 8540 thread 1 bound to OS proc set {1}
OMP: Info #247: KMP_AFFINITY: pid 8523 tid 8573 thread 3 bound to OS proc set {3}
OMP: Info #247: KMP_AFFINITY: pid 8523 tid 8574 thread 4 bound to OS proc set {0}
OMP: Info #247: KMP_AFFINITY: pid 8523 tid 8572 thread 2 bound to OS proc set {2}
OMP: Info #247: KMP_AFFINITY: pid 8523 tid 8541 thread 5 bound to OS proc set {1}
OMP: Info #247: KMP_AFFINITY: pid 8523 tid 8575 thread 6 bound to OS proc set {2}
OMP: Info #247: KMP_AFFINITY: pid 8523 tid 8576 thread 7 bound to OS proc set {3}
OMP: Info #247: KMP_AFFINITY: pid 8523 tid 8577 thread 8 bound to OS proc set {0}
 1/20 [>.............................] - ETA: 33:55 - loss: 4.3394 - rpn_class_loss: 3.3814e-05 - rpn_bbox_loss: 0.5826 - mrcnn_cla
ss_loss: 0.1902 - mrcnn_bbox_loss: 1.2196 - mrcnn_mask_loss: 2.3470
Segmentation fault

**Comment by keineahnung2345** [comment]
Which version of Keras and TensorFlow do you use? Try using Keras 2.1.3 and TF 1.9.

**Comment by yamuna83** [comment]
Keras 2.2.2
* TensorFlow 1.10.0
* Jupyter Notebook 5.1.0
* Python 3.6.3
* OpenBLAS 0.2.20
* cc 4.9.4
* git 2.14.3
* Python numpy 1.13.3
* Python pandas 0.20.2
* Python pydot 1.2.3
* Python scipy 1.0.0
