### ISSUE TITLE
KeyError: 'Unable to open object (wrong B-tree signature)'

### ISSUE THREAD

**Issue by LeBronChen1** [matterport/Mask_RCNN#1155]
When I was running the project which is based on Mask R-CNN, I am stuck with this problem. The configuration is cuda=9.0 cudnn=7.1.4 tensorflow-gpu=1.9.0 and keras-gpu=2.2.4 However, when this program is running in Spyder of Anaconda3 in Windows10. It has encountered with above problem which is described more closely as this:
`Traceback (most recent call last):

   File "<ipython-input-5-e5959b6300f2>", line 1, in <module>
    runfile('D:/Mask R-CNN/test.py', wdir='D:/Mask R-CNN')

   File "D:\Anaconda3\Anaconda3-5.3.0\envs\cv2\lib\site- 
    packages\spyder_kernels\customize\spydercustomize.py", line 704, in runfile
    execfile(filename, namespace)

   File "D:\Anaconda3\Anaconda3-5.3.0\envs\cv2\lib\site- 
    packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

   File "D:/Mask R-CNN/test.py", line 49, in <module>
    model.load_weights(COCO_MODEL_PATH, by_name=True, exclude=[ 
   "mrcnn_class_logits", "mrcnn_bbox_fc"])

   File "D:\Mask R-CNN\mrcnn\model.py", line 2131, in load_weights
    saving.load_weights_from_hdf5_group_by_name(f, layers)

   File "D:\Anaconda3\Anaconda3-5.3.0\envs\cv2\lib\site- 
    packages\keras\engine\saving.py", line 1104, in 
    load_weights_from_hdf5_group_by_name
    g = f[name]

   File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper

   File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper

   File "D:\Anaconda3\Anaconda3-5.3.0\envs\cv2\lib\site- 
    packages\h5py\_hl\group.py", line 177, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)

   File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper

   File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper

   File "h5py\h5o.pyx", line 190, in h5py.h5o.open

   KeyError: 'Unable to open object (wrong B-tree signature)'`
I can ensure that I have installed any other things like pycoco and vs2015 building tools.
Could anybody answer my question.
It is my work to use Mask R-CNN!
SOS!

**Comment by mcamila777** [comment]
This is not a solution per-se but this solved this problem for me.

I got a similar error: `OSError: Can't read data (wrong B-tree signature)
` when trying to use a keras `fit_generator` when this one reads data from a `hdf5_file`, also inside an `anaconda3` virtual env. 

In my case I created a new virtual environment and re-installed the needed dependencies of the specific versions in which it was supposed to work, with this my code ran smoothly.
