### ISSUE TITLE
missmatch problem

### ISSUE THREAD

**Issue by frankdeepl** [matterport/Mask_RCNN#1182]
hi guys,

I tried to train own model on raccoon dataset, and I just have one class.

However, I faced below problem when I using the file inspect_model.ipynb.

`Traceback (most recent call last):

  File "<ipython-input-10-dc894f72be4e>", line 1, in <module>
    runfile('/home/dongs/Documents/Project/mask-rcnn/Mask_RCNN-master/samples/raccoon/inspect_model.py', wdir='/home/dongs/Documents/Project/mask-rcnn/Mask_RCNN-master/samples/raccoon')

  File "/home/dongs/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "/home/dongs/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/dongs/Documents/Project/mask-rcnn/Mask_RCNN-master/samples/raccoon/inspect_model.py", line 130, in <module>
    r['rois'], r['class_ids'], r['scores'], r['masks'])

  File "/home/dongs/Documents/Project/mask-rcnn/Mask_RCNN-master/mrcnn/utils.py", line 728, in compute_ap
    iou_threshold)

  File "/home/dongs/Documents/Project/mask-rcnn/Mask_RCNN-master/mrcnn/utils.py", line 680, in compute_matches
    overlaps = compute_overlaps_masks(pred_masks, gt_masks)

  File "/home/dongs/Documents/Project/mask-rcnn/Mask_RCNN-master/mrcnn/utils.py", line 108, in compute_overlaps_masks
    masks1 = np.reshape(masks1 > .5, (-1, masks1.shape[-1])).astype(np.float32)

  File "/home/dongs/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 279, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)

  File "/home/dongs/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 51, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)

ValueError: cannot reshape array of size 0 into shape (0)`

I find the problem is the r['class_id'] is null, is there anybody know how to resolve it?

**Comment by keineahnung2345** [comment]
Do you use the latest version? https://github.com/matterport/Mask_RCNN/pull/1054 should have fixed the problem.

**Comment by frankdeepl** [comment]
Hi @keineahnung2345 ,

Yes, I tried to filter it by myself.

**Comment by frankdeepl** [comment]
Hi, @keineahnung2345 

Yes, I have fixed this problem. Thanks for your help!

**Comment by babbu3682** [comment]
@frankdeepl how to fix...??  same issue... my r['class_id'] is null, too

**Comment by nandita96** [comment]
@frankdeepl  ..............how you fixed i am facing still same issue,, please need your help
