### ISSUE TITLE
boolean index did not match indexed array along dimension 0; dimension is 0 but corresponding boolean dimension is 1

### ISSUE THREAD

**Issue by qingyuzi** [matterport/Mask_RCNN#1198]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 0 but corresponding boolean dimension is 1
Traceback (most recent call last):

  File "<ipython-input-1-126eea77609c>", line 1, in <module>
    runfile('E:/Wex/TensorFlow/DeepLearning/Mask_RCNN/samples/shapes/train_shapes.py', wdir='E:/Wex/TensorFlow/DeepLearning/Mask_RCNN/samples/shapes')

  File "D:\Anaconda3\envs\python3.5\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "D:\Anaconda3\envs\python3.5\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "E:/Wex/TensorFlow/DeepLearning/Mask_RCNN/samples/shapes/train_shapes.py", line 279, in <module>
    layers='heads')

  File "E:\Wex\TensorFlow\DeepLearning\Mask_RCNN\mrcnn\model.py", line 2363, in train
    use_multiprocessing=True,

  File "D:\Anaconda3\envs\python3.5\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)

  File "D:\Anaconda3\envs\python3.5\lib\site-packages\keras\engine\training.py", line 2194, in fit_generator
    generator_output = next(output_generator)

  File "E:\Wex\TensorFlow\DeepLearning\Mask_RCNN\mrcnn\model.py", line 1707, in data_generator
    use_mini_mask=config.USE_MINI_MASK)

  File "E:\Wex\TensorFlow\DeepLearning\Mask_RCNN\mrcnn\model.py", line 1275, in load_image_gt
    class_ids = class_ids[_idx]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 0 but corresponding boolean dimension is 1
Does anyone know how to solve this ?

**Comment by popper0912** [comment]
> IndexError: boolean index did not match indexed array along dimension 0; dimension is 0 but corresponding boolean dimension is 1
> Traceback (most recent call last):
> 
> File "", line 1, in 
> runfile('E:/Wex/TensorFlow/DeepLearning/Mask_RCNN/samples/shapes/train_shapes.py', wdir='E:/Wex/TensorFlow/DeepLearning/Mask_RCNN/samples/shapes')
> 
> File "D:\Anaconda3\envs\python3.5\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
> execfile(filename, namespace)
> 
> File "D:\Anaconda3\envs\python3.5\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
> exec(compile(f.read(), filename, 'exec'), namespace)
> 
> File "E:/Wex/TensorFlow/DeepLearning/Mask_RCNN/samples/shapes/train_shapes.py", line 279, in 
> layers='heads')
> 
> File "E:\Wex\TensorFlow\DeepLearning\Mask_RCNN\mrcnn\model.py", line 2363, in train
> use_multiprocessing=True,
> 
> File "D:\Anaconda3\envs\python3.5\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
> return func(*args, **kwargs)
> 
> File "D:\Anaconda3\envs\python3.5\lib\site-packages\keras\engine\training.py", line 2194, in fit_generator
> generator_output = next(output_generator)
> 
> File "E:\Wex\TensorFlow\DeepLearning\Mask_RCNN\mrcnn\model.py", line 1707, in data_generator
> use_mini_mask=config.USE_MINI_MASK)
> 
> File "E:\Wex\TensorFlow\DeepLearning\Mask_RCNN\mrcnn\model.py", line 1275, in load_image_gt
> class_ids = class_ids[_idx]
> 
> IndexError: boolean index did not match indexed array along dimension 0; dimension is 0 but corresponding boolean dimension is 1
> Does anyone know how to solve this ?

Do you fix it?

**Comment by Akhiladdh** [comment]
Is this issue resolved?

**Comment by Rorywh** [comment]
Maybe you can try following methods :
1. Using lower version of tensorflow like 1.4 and keras like 2.1
2. Sometimes this problem is caused by the data you labelled, maybe there is inconsistency between the labels you named in the dataset and the labels you use in the code.
hope this will solve your issues

**Comment by soumyaiitkgp** [comment]
I am facing the same problem. Has anyone solved it yet?

**Comment by mgarnett21** [comment]
the same problem

**Comment by erihengz** [comment]
Any solutions?

**Comment by soumyaiitkgp** [comment]
> Any solutions?

In my case, the problem was with the name and labelling.

**Comment by MajidNikoogoftar** [comment]
> > Any solutions?
> 
> In my case, the problem was with the name and labelling.

@soumyaiitkgp 
Hello
I used your Custom_MaskRCNN code. But I modified it, because I have some out of points and I have rectangle and polygons. Here it is my code:

class CustomConfig(Config):
    """Configuration for training on the custom dataset.
    Derives from the base Config class and overrides some values.
    """
    # Give the configuration a recognizable name
    NAME = "custom"

    # We use a GPU with 12GB memory, which can fit two images.
    # Adjust down if you use a smaller GPU.
    IMAGES_PER_GPU = 1

    # Number of classes (including background)
    NUM_CLASSES = 1 + 4  # Background + number of classes (Here, 2)

    # Number of training steps per epoch
    STEPS_PER_EPOCH = 100

    # Skip detections with < 90% confidence
    DETECTION_MIN_CONFIDENCE = 0.9


############################################################
#  Dataset
############################################################

class CustomDataset(utils.Dataset):

    def load_custom(self, dataset_dir, subset):
        """Load a subset of the custom dataset.
        dataset_dir: Root directory of the dataset.
        subset: Subset to load: train or val
        """
        # Add classes according to the numbe of classes required to detect
        self.add_class("custom", 0, "mound")
        self.add_class("custom", 1, "tree")
        self.add_class("custom", 2, "water")
        self.add_class("custom", 3, "debris")

        # Train or validation dataset?
        assert subset in ["train", "val"]
        dataset_dir = os.path.join(dataset_dir, subset)

        # Load annotations
        # VGG Image Annotator (up to version 1.6) saves each image in the form:
        # { 'filename': '28503151_5b5b7ec140_b.jpg',
        #   'regions': {
        #       '0': {
        #           'region_attributes': {},
        #           'shape_attributes': {
        #               'all_points_x': [...],
        #               'all_points_y': [...],
        #               'name': 'polygon'}},
        #       ... more regions ...
        #   },
        #   'size': 100202
        # }
        # We mostly care about the x and y coordinates of each region
        # Note: In VIA 2.0, regions was changed from a dict to a list.
        annotations1 = json.load(open(os.path.join(dataset_dir, "via_region_data.json")))

        annotations = list(annotations1.values()) # don't need the dict keys

        # The VIA tool saves images in the JSON even if they don't have any
        # annotations. Skip unannotated images.
        annotations = [a for a in annotations if a['regions']]

        # Add images
        for a in annotations:
            # Get the x, y coordinaets of points of the polygons that make up
            # the outline of each object instance. These are stores in the
            # shape_attributes (see json format above)
            # The if condition is needed to support VIA versions 1.x and 2.x.
            polygons = [r['shape_attributes'] for r in a['regions']]
            #labelling each class in the given image to a number

            custom = [s['region_attributes'] for s in a['regions']]
            
            num_ids=[]
            #Add the classes according to the requirement
            for n in custom:
                try:
                    if n['name']=="mound":
                        num_ids.append(0)
                    elif n['name']=='tree':
                        num_ids.append(1)
                    elif n['name']=="water":
                        num_ids.append(2)
                    elif n['name']=="debris":
                        num_ids.append(3)
                except:
                    pass


            # load_mask() needs the image size to convert polygons to masks.
            # Unfortunately, VIA doesn't include it in JSON, so we must read
            # the image. This is only managable since the dataset is tiny.
            image_path = os.path.join(dataset_dir, a['filename'])
            image = skimage.io.imread(image_path)
            height, width = image.shape[:2]

            self.add_image(
                "custom",
                image_id=a['filename'],  # use file name as a unique image id
                path=image_path,
                width=width, height=height,
                polygons=polygons,
                num_ids=num_ids)

    def load_mask(self, image_id):
        """Generate instance masks for an image.
       Returns:
        masks: A bool array of shape [height, width, instance count] with
            one mask per instance.
        class_ids: a 1D array of class IDs of the instance masks.
        """
        # If not a custom dataset image, delegate to parent class.
        image_info = self.image_info[image_id]
        if image_info["source"] != "custom":
            return super(self.__class__, self).load_mask(image_id)
        num_ids = image_info['num_ids']	
        #print("Here is the numID",num_ids)

        # Convert polygons to a bitmap mask of shape
        # [height, width, instance_count]
        info = self.image_info[image_id]
        mask = np.zeros([info["height"], info["width"], len(info["polygons"])],
                        dtype=np.uint8)
        for i, p in enumerate(info["polygons"]):
            if p['name'] == 'polygon':
            # Get indexes of pixels inside the polygon and set them to 1
                rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
            else:
                rr, cc = skimage.draw.rectangle((p['y'], p['x']), extent=(p['height'], p['width']))

            rr[rr > mask.shape[0]-1] = mask.shape[0]-1
            cc[cc > mask.shape[1]-1] = mask.shape[1]-1


            mask[rr, cc, i] = 1

        # Return mask, and array of class IDs of each instance. Since we have
        # one class ID only, we return an array of 1s
        #num_ids = np.array(num_ids, dtype=np.int32)	
        #return mask.astype(np.bool), num_ids#.astype(np.bool), np.ones([mask.shape[-1]], dtype=np.int32),
        return mask.astype(np.bool), np.ones([mask.shape[-1]], dtype=np.int32)  # --> works but only detect 1 class
        


    def image_reference(self, image_id):
        """Return the path of the image."""
        info = self.image_info[image_id]
        if info["source"] == "custom":
            return info["path"]
        else:
            super(self.__class__, self).image_reference(image_id)


--------------------------------------------------------------------------------------
I am not sure about the modification.
Whenever I use these two lines:
    num_ids = np.array(num_ids, dtype=np.int32)	
    return mask.astype(np.bool), num_ids
 I recevie error of boolean index ...
 
 
In case of using this code: return mask.astype(np.bool), np.ones([mask.shape[-1]], dtype=np.int32)
My model works fine, but it cannot recognise the name of other classes and it only returns the name of class 1 for any objects.

Any help is appreciated.
