### ISSUE TITLE
Running out of RAM

### ISSUE THREAD

**Issue by phuongho43** [matterport/Mask_RCNN#1221]
I'm getting MemoryError trying to train with 16GB of RAM:
```
MemoryError
ERROR:root:Error processing image {'id': '5afb7932e9c7328f4fb1d7a8166a3699d6cdc5192b93758a75e9956f1513c5a3', 'source': 'nucleus', 'path': 'data/stage1_train/5afb7932e9c7328f4fb1d7a8166a3699d6cdc5192b93758a75e9956f1513c5a3/images/5afb7932e9c7328f4fb1d7a8166a3699d6cdc5192b93758a75e9956f1513c5a3.png'}
Traceback (most recent call last):
  File "/home/phuong/Mask_RCNN/mrcnn/model.py", line 1710, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/phuong/Mask_RCNN/mrcnn/model.py", line 1213, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "nucleus.py", line 238, in load_mask
    mask = np.stack(mask, axis=-1)
  File "/home/phuong/anaconda3/envs/cy/lib/python3.6/site-packages/numpy/core/shape_base.py", line 360, in stack
    return _nx.concatenate(expanded_arrays, axis=axis, out=out)
```
However, it uses less RAM with
IMAGE_MIN_DIM = 256
IMAGE_MAX_DIM = 256
IMAGE_MIN_SCALE = 1.0
Is that expected and I just need more RAM?

**Comment by torta24x** [comment]
Could you post your training configuration and hardware system configuration?
