### ISSUE TITLE
Does data augmentation works for VGG Segmentations ? (model.train, augmentation=augmentation)

### ISSUE THREAD

**Issue by nayzen** [matterport/Mask_RCNN#1229]
Hi everyone!
Firstly, thank you for this repo, it is amazing.
I have 134 classes (for about 2800 photos --- 21 photos / classe). I used VGG image annotator tool to do my annotations (2800 segmentations...)
![segment](https://user-images.githubusercontent.com/37196095/51232686-dfe28100-1967-11e9-8873-93e24e65c0ea.png)

I have quite good results bu I would like to augment my database using the augmentation parameter below (in model.train) if the segmentations will be augmented too ?

![augmentation](https://user-images.githubusercontent.com/37196095/51232725-086a7b00-1968-11e9-95dc-8e0144c9ca78.PNG)

My segmentations are coordinates in a .JSON file and I would like to do like the Imgaug example below:

![example_segmaps](https://user-images.githubusercontent.com/37196095/51232837-67c88b00-1968-11e9-9e3d-30a51d5a0531.jpg)

Except if the augmentation parameter already does what I want..
Waiting for your help.. Thanks !

**Comment by bilgan** [comment]
Yes, it does what you want.

**Comment by eyildiz-ugoe** [comment]
I try to do the same, but I get:

```
Traceback (most recent call last):
  File "components_inside.py", line 539, in <module>
    train(model)
  File "components_inside.py", line 248, in train
    layers='heads', augmentation=augmentation)
NameError: name 'augmentation' is not defined

```

Does anyone know why it doesn't work?

**Comment by nayzen** [comment]
@eyildiz-ugoe  You need to define "augmentation" before. Like in this example :

![augmentation](https://user-images.githubusercontent.com/37196095/52634444-82d6de00-2ec7-11e9-929a-5d009d85c47f.PNG)

Regards,
Antoine

**Comment by nikhil-occipitaltech** [comment]
@nayzen Hey man, your solution works. But how exactly, is something I am struggling to grasp. Augmentating the images is not that big of a deal but how excatly the related json with the the contour points is getting modified?

**Comment by nayzen** [comment]
Hey @nikhil-occipitaltech , I don't really know how the contour points is getting modified and I'm interested in finding out as well. But it seems that the imgaug library does automatically this task.

**Comment by nikhil-occipitaltech** [comment]
@nayzen  I am trusting it to be correct.
