### ISSUE TITLE
raise StopIteration() while tried to train balloon.py

### ISSUE THREAD

**Issue by godblezzme29** [matterport/Mask_RCNN#1258]
Hello I tried to train balloon based on the blog post in medium
but I get an error with StopIteration() , the error is shown below :

F:\Anaconda3\envs\MaskRCNN\lib\site-packages\tensorflow\python\ops\gradients_impl.py:96: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Epoch 1/30
Traceback (most recent call last):
  File "balloon.py", line 364, in <module>
    train(model)
  File "balloon.py", line 199, in train
    layers='heads')
  File "F:\Anaconda3\envs\MaskRCNN\lib\site-packages\mask_rcnn-2.1-py3.6.egg\mrcnn\model.py", line 2375, in train
  File "F:\Anaconda3\envs\MaskRCNN\lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "F:\Anaconda3\envs\MaskRCNN\lib\site-packages\keras\engine\training.py", line 2065, in fit_generator
    generator_output = next(output_generator)
  File "F:\Anaconda3\envs\MaskRCNN\lib\site-packages\keras\utils\data_utils.py", line 710, in get
    raise StopIteration()
StopIteration

Is there anyone have this error and able to solve this error?? In my opinion this because maybe my GPU memory is too small
Thank you

My enviroment is windows 10 x64 ,GPU :GeForce GTX 1050 2GB CUDA8.0 cudnn6
anaconda under venv: python 3.6 tensorflow-gpu 1.4.0

**Comment by greatdt** [comment]
I also met the same question. Have you solved it?

**Comment by xiongshuai520** [comment]
I also met the same question. Have you solved it?

**Comment by wangjunyiwhut** [comment]
I met the same issue, hope someone to solve it! thank u

**Comment by FengZhiheng** [comment]
I met the same issue, hope someone to solve it~

**Comment by SS-HY** [comment]
I met the same issue, hope someone to solve it.

**Comment by Dgs29** [comment]
Did you solve this?

**Comment by minalmeg** [comment]
Try using keras 2.2. Worked for me.

**Comment by mariepastora** [comment]
Had the same problem, and using keras 2.2 didn't work for me.
