### ISSUE TITLE
KeyError: 'all_points_y'

### ISSUE THREAD

**Issue by eyildiz-ugoe** [matterport/Mask_RCNN#1275]
During training one of the images cannot be processed: 

```

> Traceback (most recent call last):
>   File "/home/name/.local/lib/python3.6/site-packages/mrcnn/model.py", line 1710, in data_generator
>     use_mini_mask=config.USE_MINI_MASK)
>   File "/home/name/.local/lib/python3.6/site-packages/mrcnn/model.py", line 1213, in load_image_gt
>     mask, class_ids = dataset.load_mask(image_id)
>   File "components_inside.py", line 144, in load_mask
>     rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
> KeyError: 'all_points_y'
> 
```

**Comment by eyildiz-ugoe** [comment]
Caused by annotating the images with non-polygonal shapes.
