### ISSUE TITLE
Error for train_data

### ISSUE THREAD

**Issue by ChuanqiL** [matterport/Mask_RCNN#1316]

**Comment by ChuanqiL** [comment]
When I train my own dataset, the error comes out like this:

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Epoch 1/10
ERROR:root:Error processing image {'height': 768, 'path': 'train_data/pic/196.jpg', 'mask_path': 'train_data/cv2_mask/196.png', 'width': 1280, 'id': 61, 'source': 'shapes', 'yaml_path': 'train_data/labelme_json/196_json/info.yaml'}
Traceback (most recent call last):
  File "/home/chuanqi/fengji_jiance /Mask_RCNN-master/samples/shapes/../../mrcnn/model.py", line 1711, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/chuanqi/fengji_jiance /Mask_RCNN-master/samples/shapes/../../mrcnn/model.py", line 1266, in load_image_gt
    class_ids = class_ids[_idx]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 1 but corresponding boolean dimension is 128
image_id 6
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Is there anyone faced with this problem, how to solve it? Thanks.

**Comment by nyck33** [comment]
@ChuanqiL did you find a solution?

I'm getting something similar:  https://github.com/matterport/Mask_RCNN/issues/1480

**Comment by jasdal365** [comment]
@ChuanqiL Could you solve this problem?

**Comment by MajidNikoogoftar** [comment]
@ChuanqiL 
Did you solve the issue?
I have exactly the same problem as you!
