### ISSUE TITLE
ModuleNotFoundError: No module named 'imgaug'

### ISSUE THREAD

**Issue by rakehsaleem** [matterport/Mask_RCNN#1355]
So, I have been working on concrete crack detection and before writing in the files i tried the balloon example but when i switched to balloon example as cracks are also small compared to balloons and nucleus example was good  start to work as reference. But I am getting this error and I have tried installing various packages but all in vein. No success so far so if anyone of you have gone through the same error please, let me know.

Thank you
-Rakeh

**Comment by davidb1** [comment]
pip install imgaug

**Comment by rakehsaleem** [comment]
This is the output of doing pip install imgaug and did not run the demo code..

```
(venv) C:\projects\keras_talk\Matterpot_Mask_RCNN_Balloon>pip install git+https://github.com/aleju/imgaug
Collecting git+https://github.com/aleju/imgaug
  Cloning https://github.com/aleju/imgaug to c:\users\lenovo\appdata\local\temp\pip-req-build-4ppy6mb4
Requirement already satisfied: scipy in c:\programdata\anaconda3\envs\venv\lib\site-packages (from imgaug==0.2.8) (1.2.0)
Requirement already satisfied: scikit-image>=0.11.0 in c:\programdata\anaconda3\envs\venv\lib\site-packages (from imgaug==0.2.8) (0.14.2)
Requirement already satisfied: numpy>=1.15.0 in c:\programdata\anaconda3\envs\venv\lib\site-packages (from imgaug==0.2.8) (1.15.4)
Requirement already satisfied: six in c:\programdata\anaconda3\envs\venv\lib\site-packages (from imgaug==0.2.8) (1.12.0)
Collecting imageio (from imgaug==0.2.8)
  Using cached https://files.pythonhosted.org/packages/af/0a/943c965d372dae0b1f1482677d29030ab834351a61a9a632fd62f27f1523/imageio-2.5.0-py3-none-any.whl
Requirement already satisfied: Pillow in c:\programdata\anaconda3\envs\venv\lib\site-packages (from imgaug==0.2.8) (5.2.0)
Requirement already satisfied: matplotlib in c:\programdata\anaconda3\envs\venv\lib\site-packages (from imgaug==0.2.8) (3.0.2)
Collecting Shapely (from imgaug==0.2.8)
  Using cached https://files.pythonhosted.org/packages/a2/fb/7a7af9ef7a35d16fa23b127abee272cfc483ca89029b73e92e93cdf36e6b/Shapely-1.6.4.post2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Lenovo\AppData\Local\Temp\pip-install-32drioao\Shapely\setup.py", line 80, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "C:\Users\Lenovo\AppData\Local\Temp\pip-install-32drioao\Shapely\shapely\_buildcfg.py", line 200, in <module>
        lgeos = CDLL("geos_c.dll")
      File "c:\programdata\anaconda3\envs\venv\lib\ctypes\__init__.py", line 348, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: [WinError 126] The specified module could not be found

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Lenovo\AppData\Local\Temp\pip-install-32drioao\Shapely\

```
Any idea how to solve this.. I am doing this in root directory and have installed the pycocotools from philpherie repository. Still no luck

**Comment by davidb1** [comment]
Try running **conda install -c conda-forge geos**  before the pip install imgaug

**Comment by rakehsaleem** [comment]
Thank you @davidb1 . I tried your way and it works both Tensorflow cpu and gpu and big thanks as it causes alot of mess over the last weekend.

**Comment by martinschnurer** [comment]
I solve this issue by manually cloning imgaug repository, then add path of the imgaug repository into sys.path, after that, import imgaug.

**Comment by LevaYin** [comment]
conda install -c conda-forge shapely
it work

**Comment by iampythoneer** [comment]
C:\Users\admin\AppData\Local\Programs\Python\Python37-32\python.exe C:/Users/admin/AppData/Local/Programs/Python/Python37-32/Scripts/ppe.py
Traceback (most recent call last):
  File "C:/Users/admin/AppData/Local/Programs/Python/Python37-32/Scripts/ppe.py", line 18, in <module>
    from imgaug import augmenters as iaa
ModuleNotFoundError: No module named 'imgaug'

Process finished with exit code 1

**Comment by iampythoneer** [comment]
C:\Users\admin\AppData\Local\Programs\Python\Python37-32\python.exe C:/Users/admin/AppData/Local/Programs/Python/Python37-32/Scripts/ppe.py
Traceback (most recent call last):
  File "C:/Users/admin/AppData/Local/Programs/Python/Python37-32/Scripts/ppe.py", line 18, in <module>
    from imgaug import augmenters as iaa
ModuleNotFoundError: No module named 'imgaug'

Process finished with exit code 1

How to fix this error! Please Help!

**Comment by rakehsaleem** [comment]
try the command suggested by davidb1, and it worked for me. Although it took alot of time back then but it was worth saving the mess..

**Comment by iampythoneer** [comment]
C:\Users\admin\AppData\Local\Programs\Python\Python37-32\python.exe C:/Users/admin/Desktop/new.py
  File "C:/Users/admin/Desktop/new.py", line 55
    net.setInput (blob)
      ^
SyntaxError: invalid syntax

Process finished with exit code 1

**Comment by AkshatRepo** [comment]
The complete process to install imgaug is described in this article which works perfectly fine and this article will clear your related error as well. The link of that article is
<a href="https://www.akshatvasistha.com/2019/10/how-do-real-time-image-segmentation-mask-rcnn.html"> Real-time image segmentation with MaskRCNN </a>

**Comment by sangramsingnk** [comment]
File "/Users/sing/NLP/audio-sentiment-analysis-pipeline/AudioSentimentPipeline.py", line 25, in <module>
    from audio_sentiment_analysis import classify
  File "/Users/sing/NLP/audio-sentiment-analysis-pipeline/audio_sentiment_analysis/classify.py", line 23, in <module>
    from hmm_morency import HmmMorency
ModuleNotFoundError: No module named 'hmm_morency'
