### ISSUE TITLE
Loading partial weights, is it possible?

### ISSUE THREAD

**Issue by elektronika-ba** [matterport/Mask_RCNN#1361]
Hi,

My detection works great, but it takes ~9 seconds to complete for a single image! I don't have GPU capabilities and my CPU is i5 at 3.2GHz.

The idea I am having is to somehow load the provided h5 file partially, with only the classes that are of my interest. For example if I want to detect only vehicles (cars, trucks and buses) I don't want it analyzing trees, birds and so on.

```
class MaskRCNNConfig(mrcnn.config.Config):
    NAME = "coco_pretrained_model_config"
    IMAGES_PER_GPU = 1
    GPU_COUNT = 1
    NUM_CLASSES = 1 + 80  # COCO dataset has 80 classes + one background class
    DETECTION_MIN_CONFIDENCE = 0.6
model = MaskRCNN(mode="inference", model_dir=MODEL_DIR, config=MaskRCNNConfig())
model.load_weights(COCO_MODEL_PATH, by_name=True, exclude=["**CAN I EXCLUDE EVERYTHING BUT VEHICLES HERE?**"])
```

Question: Can I load weights only for certain class IDs? This should speed things up greatly!

Thanks

**Comment by disign-ming** [comment]
By_name=True Do not load the layer name can be changed to something else

**Comment by elektronika-ba** [comment]
I don't understand.

I was wondering if it is possible to exclude some classIds from being loaded in the "mask_rcnn_coco.h5" file. That way when I start the analysis, it would work faster because I only want vehicles to be detected.

If it is not possible, I will need to train my own model - which I am trying to avoid doing.

**Comment by disign-ming** [comment]
Yes, you can tailor the pre-training weights, and then eliminate unnecessary classifications. You can refer to a jupyter in SSD keras, which has detailed instructions.

**Comment by elektronika-ba** [comment]
Thanks for the explanation. I will dig in, and if I succeed I will report here for others to see the solution.

**Comment by elektronika-ba** [comment]
I found the fine-tuning tutorial you @disign-ming recommended and followed it. It fails for the supplied Mask_RCNN h5 file because layer names do not match.
Does someone know the names of classification layers in file `mask_rcnn_coco.h5`?
I need them in this section of the example:
`classifier_names = ['conv4_3_norm_mbox_conf',
                    'fc7_mbox_conf',
                    'conv6_2_mbox_conf',
                    'conv7_2_mbox_conf',
                    'conv8_2_mbox_conf',
                    'conv9_2_mbox_conf']`
Tutorial is here: https://github.com/pierluigiferrari/ssd_keras/blob/master/weight_sampling_tutorial.ipynb

Thanks a lot.

**Comment by elektronika-ba** [comment]
I investigated these layers and found that these ones have ['kernel:0] and ['bias:0']:

`'mrcnn_class_conv1','mrcnn_class_conv2','mrcnn_mask','mrcnn_mask_conv1','mrcnn_mask_conv2','mrcnn_mask_conv3','mrcnn_mask_conv4'`

However, when I do the tutorial on these layers, it finishes without issues but when I start my program, it gives out errors I don't understand:

`Traceback (most recent call last):  
  File "mure1.py", line 54, in <module>  
    model.load_weights(COCO_MODEL_PATH, by_name=True)  
  File "D:\tmp\ParkProject\Mask_RCNN\mrcnn\model.py", line 2130, in load_weights  
    saving.load_weights_from_hdf5_group_by_name(f, layers)  
  File "d:\ProgramData\Miniconda3\envs\park1\lib\site-packages\keras\engine\saving.py", line 1149, in load_weights_from_hdf5_group_by_name  
    str(weight_values[i].shape) + '.')  
ValueError: Layer #369 (named "mrcnn_mask_conv1"), weight <tf.Variable 'mrcnn_mask_conv1/kernel:0' shape=(3, 3, 256, 256) dtype=float32_ref> has shape (3, 3, 256, 256), but the saved weight has shape (15, 256, 3, 3).`

So I tried leaving some layers unchanged without luck. Don't know what's going on here :-)

**Comment by VinniaKemala** [comment]
You can
# Coco class names
class_names = ['BG', 'person', 'bicycle', 'car', 'motorcycle', 'airplane',
               'bus', 'train', 'truck', 'boat', 'traffic light',
               'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird',
               'cat', 'dog', 'horse', 'sheep', 'cow', 'elephant', 'bear',
               'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie',
               'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball',
               'kite', 'baseball bat', 'baseball glove', 'skateboard',
               'surfboard', 'tennis racket', 'bottle', 'wine glass', 'cup',
               'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple',
               'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza',
               'donut', 'cake', 'chair', 'couch', 'potted plant', 'bed',
               'dining table', 'toilet', 'tv', 'laptop', 'mouse', 'remote',
               'keyboard', 'cell phone', 'microwave', 'oven', 'toaster',
               'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors',
               'teddy bear', 'hair drier', 'toothbrush']

**Comment by VinniaKemala** [comment]
You can 'filter out' classes you don't need after you run the detection but it doesn't prune the weights though. So, I'm not sure it would speed things up. Hope it helps.
```
# COCO class names
class_names = ['BG', 'person', 'bicycle', 'car', 'motorcycle', 'airplane',
               'bus', 'train', 'truck', 'boat', 'traffic light',
               'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird',
               'cat', 'dog', 'horse', 'sheep', 'cow', 'elephant', 'bear',
               'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie',
               'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball',
               'kite', 'baseball bat', 'baseball glove', 'skateboard',
               'surfboard', 'tennis racket', 'bottle', 'wine glass', 'cup',
               'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple',
               'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza',
               'donut', 'cake', 'chair', 'couch', 'potted plant', 'bed',
               'dining table', 'toilet', 'tv', 'laptop', 'mouse', 'remote',
               'keyboard', 'cell phone', 'microwave', 'oven', 'toaster',
               'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors',
               'teddy bear', 'hair drier', 'toothbrush']

# Class Index
id_car = class_names.index('car')
id_truck = class_names.index('truck')
id_bus = class_names.index('bus')

# Read Image
image = cv2.imread(os.path.join(path_input)) # BGR
image = image[..., ::-1] # BGR --> RGB

# Run detection
r = model.detect([image], verbose=0)[0]

# Exclude other classes except car,bus, & truck
r['class_ids_new'], r['rois_new']= [],[]
r['masks_new'], r['scores_new']= [],[]
r['masks'] = np.transpose(r['masks'], (2, 1, 0))
for idx in range(len(r['class_ids'])):
     if r['class_ids'][idx] == id_car or r['class_ids'][idx] == id_truck or r['class_ids'][idx] == id_bus:
          r['class_ids_new'].append(r['class_ids'][idx])
          r['rois_new'].append(r['rois'][idx])
          r['masks_new'].append(r['masks'][idx])
          r['scores_new'].append(r['scores'][idx])  
del(r['class_ids'], r['rois'], r['masks'], r['scores'])
```

**Comment by elektronika-ba** [comment]
Thanks for the example code. It does not run detection any faster because I need to remove those classes from the h5 file, before the detection is run.
You code does eliminate detected objects but that does not speed the detection, unfortunately.

I still haven't come up with a solution for this problem.

**Comment by BigTimeStats** [comment]
Thanks for the code @VinniaKemala but I am getting errors when calling `display_instances()` to just show the 'sports ball':

```
# !wget http://dcdoubles.com/lq-18-open.jpg -P ./images 

image = skimage.io.imread(os.path.join(IMAGE_DIR, 'lq-18-open.jpg'))

r = model.detect([image], verbose=1)[0]

id_ball = class_names.index('sports ball')
print(id_ball)

# Exclude other classes except ball
r['class_ids_new'], r['rois_new']= [],[]
r['masks_new'], r['scores_new']= [],[]

r['masks'] = np.transpose(r['masks'], (2, 1, 0))

for idx in range(len(r['class_ids'])):
     if r['class_ids'][idx] == id_ball:
            r['class_ids_new'].append(r['class_ids'][idx])
            r['rois_new'].append(r['rois'][idx])
            r['masks_new'].append(r['masks'][idx])
            r['scores_new'].append(r['scores'][idx])  
            
del(r['class_ids'], r['rois'], r['masks'], r['scores'])

print(type(r))
print(r)

visualize.display_instances(image, r['rois_new'], r['masks_new'], r['class_ids_new'], 
                            class_names, r['scores_new'])

```

Here is my output:

```
Processing 1 images
image                    shape: (720, 960, 3)         min:    0.00000  max:  255.00000
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  151.10000
image_metas              shape: (1, 89)               min:    0.00000  max: 1024.00000
33
<class 'dict'>
{'class_ids_new': [33, 33], 'rois_new': [array([322, 722, 402, 814], dtype=int32), array([324, 380, 395, 460], dtype=int32)], 'masks_new': [array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8), array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)], 'scores_new': [0.98706806, 0.79765177]}
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-123-f626c634b7f1> in <module>()
     27 
     28 visualize.display_instances(image, r['rois_new'], r['masks_new'], r['class_ids_new'], 
---> 29                             class_names, r['scores_new'])

/content/Mask_RCNN/visualize.py in display_instances(image, boxes, masks, class_ids, class_names, scores, title, figsize, ax)
     86     """
     87     # Number of instances
---> 88     N = boxes.shape[0]
     89     if not N:
     90         print("\n*** No instances to display *** \n")

AttributeError: 'list' object has no attribute 'shape'
```

I also don't see why one cannot just do:

```
import numpy as np
index = np.where(r['class_ids'] == 33)[0]

r['rois'] = r['rois'][index]
r['masks'] = r['masks'][index]
r['scores'] = r['scores'][index]
r['class_ids'] = r['class_ids'][index]
```

Thanks!

**Comment by BigTimeStats** [comment]
I solved it by subsetting the last dimension of r['masks'], no for loop required!

```
image = skimage.io.imread(os.path.join(IMAGE_DIR, 'lq-18-open.jpg'))

r = model.detect([image], verbose=1)[0]

id_ball = class_names.index('sports ball')

import numpy as np
index = np.where(r['class_ids'] == id_ball)[0]

r['scores'] = r['scores'][index]

r['rois'] = r['rois'][index]
r['masks'] = r['masks'][:,:,index]
r['class_ids'] = r['class_ids'][index]

visualize.display_instances(image, r['rois'], r['masks'], r['class_ids'], 
                            class_names, r['scores'])
```
