### ISSUE TITLE
Calculation type error during training

### ISSUE THREAD

**Issue by zhouhao-learning** [matterport/Mask_RCNN#1365]
When I created the model for training, I was able to train normally on my computer, but when someone else executed my code I got the following unexpected error:

```
Traceback (most recent call last):
  File "/worker/bin/run.py", line 384, in task_main
    await module_run(api) if iscoroutinefunction(module_run) else module_run(api)
  File "/worker/package/MaskRcnn_Object_Detection_pxwhK/MaskRcnn_train/__init__.py", line 250, in run
    model = MaskRCNN(mode="training", config=config)
  File "/worker/package/MaskRcnn_Object_Detection_pxwhK/model.py", line 1833, in __init__
    self.keras_model = self.build(mode=mode, config=config)
  File "/worker/package/MaskRcnn_Object_Detection_pxwhK/model.py", line 1926, in build
    anchors = self.get_anchors(config.IMAGE_SHAPE)
  File "/worker/package/MaskRcnn_Object_Detection_pxwhK/model.py", line 2610, in get_anchors
    self.config.RPN_ANCHOR_STRIDE)
  File "/worker/package/MaskRcnn_Object_Detection_pxwhK/utils.py", line 637, in generate_pyramid_anchors
    feature_strides[i], anchor_stride))
  File "/worker/package/MaskRcnn_Object_Detection_pxwhK/utils.py", line 598, in generate_anchors
    heights = scales / np.sqrt(ratios)
TypeError: ufunc 'true_divide' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

I understand what this is wrong, the parameters I pass are basically the default parameters, please guide me some, thank you

**Comment by light82** [comment]
It seems that the types of `scales` and `ratios` cause the problem.
