### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by jieshaoxxiansen** [matterport/Mask_RCNN#1374]
VIDEOIO ERROR: V4L: can't open camera by index 0
Traceback (most recent call last):
  File "/home/njust/ZB/Mask_RCNN-master/samples/demo.py", line 81, in <module>
    results = model.detect([frame], verbose=1)
  File "/home/njust/ZB/Mask_RCNN-master/mrcnn/model.py", line 2503, in detect
    molded_images, image_metas, windows = self.mold_inputs(images)
  File "/home/njust/ZB/Mask_RCNN-master/mrcnn/model.py", line 2401, in mold_inputs
    mode=self.config.IMAGE_RESIZE_MODE)
  File "/home/njust/ZB/Mask_RCNN-master/mrcnn/utils.py", line 420, in resize_image
    image_dtype = image.dtype
AttributeError: 'NoneType' object has no attribute 'dtype'
Processing 1 images
image

Process finished with exit code 1

**Comment by light82** [comment]
Probably the image is`[]`. Read error and get a `none`:`[]`. So `[].dtype` produces `None Type` has no attribute `dtype`.

**Comment by light82** [comment]
You can `print(image)` and observe the value of `image`

**Comment by angyee** [comment]
> You can `print(image)` and observe the value of `image`
from forward import ForwardModel
import cv2
import numpy as np

frozen_graph_path = "/home/deepedge/mask_rcnn-master/mask_dent_frozen_graph.pb"
assign your own Config class

my_config = "/home/deepedge/mask_rcnn-master/mrcnn/config.py"

forward_model = ForwardModel(frozen_graph_path, my_config)

def test_one_image(image):
images = np.expand_dims(image, axis=0)
results = forward_model(images)
return results

if name == "main":
test_image_path = '/home/deepedge/mask_rcnn-master/mask-rcnn-bottle-training-master/dataset/val/car39.jpg'
image = cv2.imread(test_image_path)
r = test_one_image(image)
print(r)

error

$ python3 anomaly.py

2019-07-01 11:02:29.101152: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-07-01 11:02:29.120748: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3600000000 Hz
2019-07-01 11:02:29.121268: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0xe58be0 executing computations on platform Host. Devices:
2019-07-01 11:02:29.121280: I tensorflow/compiler/xla/service/service.cc:158] StreamExecutor device (0): ,
Traceback (most recent call last):
File "anomaly.py", line 20, in
r = test_one_image(image)
File "anomaly.py", line 14, in test_one_image
results = forward_model(images)
File "/home/deepedge/mask_rcnn-master/mrcnn_serving_ready-master/forward.py", line 218, in call
molded_images, image_metas, windows = self.mold_inputs(images)
File "/home/deepedge/mask_rcnn-master/mrcnn_serving_ready-master/forward.py", line 93, in mold_inputs
min_dim=self.config.IMAGE_MIN_DIM,
AttributeError: 'str' object has no attribute 'IMAGE_MIN_DIM'

@light82
