### ISSUE TITLE
balloon.py error message

### ISSUE THREAD

**Issue by GongliDuan** [matterport/Mask_RCNN#1424]
Hi,

I try to run balloon.py. However, I meet this error:

Has someone meet the similar thing? Thanks!

(Actually I re-run code on python3 and it's solved. Is it possible to run this code and train custom data on python2? Thanks!)

ERROR:root:Error processing image {'source': 'balloon', 'width': 2048, 'path': u'/users/drseh/Mask_RCNN-master/balloon/val/8053085540_a72bd21a64_k.jpg', 'height': 1595, 'id': u'8053085540_a72bd21a64_k.jpg', 'polygons': [{u'all_points_x': [1085, 1095, 1098, 1100, 1100, 1093, 1083, 1073, 1055, 1037, 1019, 1011, 1002, 998, 995, 991, 990, 993, 994, 994, 1003, 1010, 1017, 1023, 1028, 1028, 1025, 1019, 1024, 1035, 1049, 1061, 1073, 1085], u'all_points_y': [197, 212, 221, 233, 249, 266, 281, 290, 299, 304, 302, 300, 297, 296, 295, 295, 293, 292, 292, 289, 283, 274, 261, 250, 229, 215, 198, 189, 185, 182, 181, 183, 188, 197], u'name': u'polygon'}, {u'all_points_x': [981, 998, 1008, 1016, 1023, 1024, 1023, 1019, 1014, 1008, 997, 984, 977, 969, 963, 950, 943, 937, 929, 918, 911, 907, 906, 909, 917, 928, 938, 950, 963, 972, 981], u'all_points_y': [66, 74, 84, 97, 113, 133, 147, 158, 168, 177, 169, 165, 163, 163, 164, 167, 170, 174, 180, 168, 154, 138, 124, 107, 90, 76, 70, 66, 63, 63, 66], u'name': u'polygon'}, {u'all_points_x': [838, 849, 862, 874, 888, 901, 909, 916, 921, 927, 928, 928, 922, 912, 910, 913, 917, 920, 919, 907, 894, 883, 872, 861, 847, 841, 839, 832, 827, 824, 825, 829, 833, 838], u'all_points_y': [175, 167, 159, 157, 157, 161, 163, 168, 172, 178, 180, 182, 189, 205, 223, 242, 258, 266, 267, 256, 245, 241, 239, 239, 245, 252, 254, 245, 234, 218, 205, 191, 183, 175], u'name': u'polygon'}, {u'all_points_x': [917, 914, 911, 910, 913, 919, 926, 934, 946, 958, 973, 987, 999, 1012, 1023, 1029, 1027, 1023, 1015, 1007, 996, 986, 974, 968, 962, 960, 957, 954, 952, 953, 948, 939, 932, 927, 923, 920, 917], u'all_points_y': [259, 249, 234, 220, 205, 194, 185, 176, 169, 165, 163, 166, 170, 182, 194, 215, 234, 248, 264, 277, 287, 293, 297, 299, 299, 302, 305, 304, 301, 298, 294, 288, 283, 278, 272, 266, 259], u'name': u'polygon'}, {u'all_points_x': [900, 879, 857, 842, 821, 806, 797, 796, 799, 803, 808, 815, 825, 827, 829, 833, 838, 847, 861, 870, 885, 895, 909, 919, 925, 933, 941, 945, 946, 946, 944, 948, 949, 951, 951, 950, 949, 946, 944, 937, 929, 921, 908, 900], u'all_points_y': [373, 374, 371, 366, 358, 343, 327, 314, 307, 297, 291, 284, 277, 276, 270, 261, 253, 246, 240, 239, 242, 247, 257, 266, 275, 287, 302, 317, 329, 339, 344, 344, 343, 343, 347, 350, 351, 350, 349, 355, 362, 368, 372, 373], u'name': u'polygon'}, {u'all_points_x': [994, 984, 969, 954, 943, 932, 924, 932, 938, 941, 945, 949, 950, 950, 949, 947, 944, 946, 945, 941, 938, 931, 930, 940, 948, 953, 952, 954, 957, 962, 969, 980, 986, 992, 994, 994, 990, 990, 995, 997, 1006, 1009, 1010, 1008, 1006, 1000, 994], u'all_points_y': [352, 363, 372, 373, 373, 370, 366, 361, 356, 350, 349, 351, 347, 343, 342, 344, 344, 334, 318, 303, 295, 284, 280, 290, 294, 298, 301, 305, 304, 300, 299, 295, 292, 288, 290, 292, 293, 295, 296, 296, 298, 305, 319, 329, 338, 347, 352], u'name': u'polygon'}]}
Traceback (most recent call last):
  File "users/drseh/Mask_RCNN-master/mrcnn/model.py", line 1715, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/users/drseh/Mask_RCNN-master/mrcnn/model.py", line 1225, in load_image_gt
    mode=config.IMAGE_RESIZE_MODE)
  File "/users/drseh/Mask_RCNN-master/mrcnn/utils.py", line 449, in resize_image
    preserve_range=True)
  File "/users/drseh/Mask_RCNN-master/mrcnn/utils.py", line 905, in resize
    anti_aliasing_sigma=anti_aliasing_sigma)
  File "/usr/lib64/python2.7/site-packages/skimage/transform/_warps.py", line 165, in resize
    tform.estimate(src_corners, dst_corners)
  File "/usr/lib64/python2.7/site-packages/skimage/transform/_geometric.py", line 679, in estimate
    _, _, V = np.linalg.svd(A)
  File "/usr/lib64/python2.7/site-packages/numpy/linalg/linalg.py", line 1612, in svd
    u, s, vh = gufunc(a, signature=signature, extobj=extobj)
  File "/usr/lib64/python2.7/site-packages/numpy/linalg/linalg.py", line 106, in _raise_linalgerror_svd_nonconvergence
    raise LinAlgError("SVD did not converge")
LinAlgError: SVD did not converge

**Comment by mortadhaaj** [comment]
I'm facing similar issue when trying to rescale an image
`skimage.transform.rescale(img, (4,4))`

skimage version: 0.14.2
scripy version: 1.2.1

Update:
It turned out the issue is caused because img shape is (0,500)! So, basically img is empty.

**Comment by maxwellgreene** [comment]
> Update:
> It turned out the issue is caused because img shape is (0,500)! So, basically img is empty.
How did you solve this issue!? thanks!

**Comment by mortadhaaj** [comment]
I just filtered out the arrays that were causing the issue. Those arrays should've been filtered anyway.

**Comment by andrew-jeremy** [comment]
> I just filtered out the arrays that were causing the issue. Those arrays should've been filtered anyway.

can you please post a snippet of that filtering code. I am running into the same issue when I try to run inference on python 2.7 though it works fine for python 3.7
