### ISSUE TITLE
Crashing during prediction with Nvidia GTX 750 Ti

### ISSUE THREAD

**Issue by Arham-Aalam** [matterport/Mask_RCNN#1426]
It also consuming (System's) 4 GB of RAM while running with GPU but workes fine with the CPU.
Can you see what's going wrong!!
```
DEVICE = "/gpu:0"

model = modellib.MaskRCNN(mode="inference", model_dir=self.MODEL_DIR,
                                    config=self.config)
results = model.detect([frame])
```

OS: windows 7
RAM : 6 GB
processor: i5 2nd generation
GPU: GTX 750 Ti 1GB
CUDA: 9.0
CuDNN: 7.0.5

***here is the log*** :
Using TensorFlow backend.
number of frames 98 in file :  vid_1.avi
Starting processing in : S MODE
Loading weights  trained-models\model-b\mask_rcnn_sp_0020_17_03.h5
2019-04-10 17:13:53.870175: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructi
ons that this TensorFlow binary was not compiled to use: AVX
2019-04-10 17:13:53.982181: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\gpu\gpu_device.cc:1105] Found device 0 with pro
perties:
name: GeForce GTX 750 Ti major: 5 minor: 0 memoryClockRate(GHz): 1.15
pciBusID: 0000:01:00.0
totalMemory: 1.00GiB freeMemory: 903.19MiB

2019-04-10 17:13:53.985182: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\gpu\gpu_device.cc:1195] Creating TensorFlow dev
ice (/device:GPU:0) -> (device: 0, name: GeForce GTX 750 Ti, pci bus id: 0000:01
:00.0, compute capability: 5.0)
2019-04-10 17:10:54.218899: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\bfc_allocator.cc:680] 42 Chunks of size 512 tot
alling 21.0KiB
2019-04-10 17:10:54.218899: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\bfc_allocator.cc:680] 281 Chunks of size 1024 t
otalling 281.0KiB
2019-04-10 17:10:54.219900: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\bfc_allocator.cc:680] 1 Chunks of size 1280 tot
alling 1.3KiB
2019-04-10 17:10:54.219900: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\bfc_allocator.cc:680] 58 Chunks of size 2048 to
talling 116.0KiB
2019-04-10 17:10:54.219900: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\bfc_allocator.cc:680] 132 Chunks of size 4096 t
otalling 528.0KiB
2019-04-10 17:10:54.220900: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\bfc_allocator.cc:680] 1 Chunks of size 6144 tot
alling 6.0KiB
2019-04-10 17:10:54.220900: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\bfc_allocator.cc:680] 23 Chunks of size 8192 to
talling 184.0KiB
2019-04-10 17:10:54.221900: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\bfc_allocator.cc:680] 1 Chunks of size 12288 to
talling 12.0KiB
2019-04-10 17:10:54.221900: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\bfc_allocator.cc:680] 2 Chunks of size 16384 to
talling 32.0KiB
2019-04-10 17:10:54.221900: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\bfc_allocator.cc:680] 1 Chunks of size 24576 to
talling 24.0KiB
2019-04-10 17:10:54.222900: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\bfc_allocator.cc:680] 1 Chunks of size 32768 to
talling 32.0KiB
2019-04-10 17:10:54.222900: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\bfc_allocator.cc:680] 1 Chunks of size 37632 to
talling 36.8KiB
2019-04-10 17:10:54.222900: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\bfc_allocator.cc:680] 1 Chunks of size 48384 to
talling 47.3KiB
2019-04-10 17:10:54.223900: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\bfc_allocator.cc:680] 7 Chunks of size 65536 to
talling 448.0KiB
2019-04-10 17:10:54.223900: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\bfc_allocator.cc:680] 1 Chunks of size 81920 to
talling 80.0KiB
2019-04-10 17:10:54.223900: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\bfc_allocator.cc:680] 3 Chunks of size 131072 t
otalling 384.0KiB
2019-04-10 17:10:54.224900: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\bfc_allocator.cc:680] 3 Chunks of size 147456 t
otalling 432.0KiB
2019-04-10 17:10:54.224900: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\bfc_allocator.cc:680] 9 Chunks of size 262144 t
otalling 2.25MiB
2019-04-10 17:10:54.225900: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\bfc_allocator.cc:680] 1 Chunks of size 393216 t
otalling 384.0KiB
2019-04-10 17:10:54.225900: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\bfc_allocator.cc:680] 3 Chunks of size 524288 t
otalling 1.50MiB
2019-04-10 17:10:54.225900: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\bfc_allocator.cc:680] 4 Chunks of size 589824 t
otalling 2.25MiB
2019-04-10 17:10:54.226900: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\bfc_allocator.cc:680] 48 Chunks of size 1048576
 totalling 48.00MiB
2019-04-10 17:10:54.226900: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\bfc_allocator.cc:680] 1 Chunks of size 1228800
totalling 1.17MiB
2019-04-10 17:10:54.226900: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\bfc_allocator.cc:680] 2 Chunks of size 2097152
totalling 4.00MiB
2019-04-10 17:10:54.227900: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\bfc_allocator.cc:680] 29 Chunks of size 2359296
 totalling 65.25MiB
2019-04-10 17:10:54.227900: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\bfc_allocator.cc:680] 1 Chunks of size 2383872
totalling 2.27MiB
2019-04-10 17:10:54.227900: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\bfc_allocator.cc:680] 1 Chunks of size 2883584
totalling 2.75MiB
2019-04-10 17:10:54.228900: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\bfc_allocator.cc:680] 1 Chunks of size 3145728
totalling 3.00MiB
2019-04-10 17:10:54.228900: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\bfc_allocator.cc:680] 1 Chunks of size 4190208
totalling 4.00MiB
2019-04-10 17:10:54.229900: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\bfc_allocator.cc:680] 5 Chunks of size 4194304
totalling 20.00MiB
2019-04-10 17:10:54.229900: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\bfc_allocator.cc:680] 2 Chunks of size 4718592
totalling 9.00MiB
2019-04-10 17:10:54.229900: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\bfc_allocator.cc:680] 1 Chunks of size 5255168
totalling 5.01MiB
2019-04-10 17:10:54.230900: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\bfc_allocator.cc:680] 1 Chunks of size 8257536
totalling 7.88MiB
2019-04-10 17:10:54.230900: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\bfc_allocator.cc:680] 3 Chunks of size 9437184
totalling 27.00MiB
2019-04-10 17:10:54.231900: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\bfc_allocator.cc:680] 1 Chunks of size 11534336
 totalling 11.00MiB
2019-04-10 17:10:54.231900: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\bfc_allocator.cc:680] 1 Chunks of size 17829888
 totalling 17.00MiB
2019-04-10 17:10:54.231900: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\bfc_allocator.cc:680] 1 Chunks of size 51380224
 totalling 49.00MiB
2019-04-10 17:10:54.232900: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\bfc_allocator.cc:680] 2 Chunks of size 67108864
 totalling 128.00MiB
2019-04-10 17:10:54.232900: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\bfc_allocator.cc:680] 1 Chunks of size 13421772
8 totalling 128.00MiB
2019-04-10 17:10:54.233900: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\bfc_allocator.cc:684] Sum Total of in-use chunk
s: 541.34MiB
2019-04-10 17:10:54.233900: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\bfc_allocator.cc:686] Stats:
Limit:                   668930048
InUse:                   567633152
MaxInUse:                659720448
NumAllocs:                    2702
MaxAllocSize:            245523456

2019-04-10 17:10:54.234900: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\common_runtime\bfc_allocator.cc:277] *************************
*******_********************************************************___________
2019-04-10 17:10:54.234900: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
6\tensorflow\core\framework\op_kernel.cc:1198] Resource exhausted: OOM when allo
cating tensor with shape[1,512,256,256] and type float on /job:localhost/replica
:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Traceback (most recent call last):
  File "C:\Users\lainsy\Desktop\spa-app-gpu\spa-project\spaenv\lib\site-packages
\tensorflow\python\client\session.py", line 1350, in _do_call
    return fn(*args)
  File "C:\Users\lainsy\Desktop\spa-app-gpu\spa-project\spaenv\lib\site-packages
\tensorflow\python\client\session.py", line 1329, in _run_fn
    status, run_metadata)
  File "C:\Users\lainsy\Desktop\spa-app-gpu\spa-project\spaenv\lib\site-packages
\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocat
ing tensor with shape[1,512,256,256] and type float on /job:localhost/replica:0/
task:0/device:GPU:0 by allocator GPU_0_bfc
         [[Node: rpn_model/rpn_conv_shared/convolution = Conv2D[T=DT_FLOAT, data
_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], us
e_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](fpn
_p2/BiasAdd, rpn_conv_shared/kernel/read)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add repor
t_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[Node: mrcnn_detection/TopKV2/_4265 = _Recv[client_terminated=false, r
ecv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:loc
alhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="e
dge_2641_mrcnn_detection/TopKV2", tensor_type=DT_INT32, _device="/job:localhost/
replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add repor
t_tensor_allocations_upon_oom to RunOptions for current allocation info.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "spa.py", line 1254, in <module>
    startSPA()
  File "spa.py", line 1239, in startSPA
    sp_utils.initTracker(frames, sp, file)
  File "spa.py", line 854, in initTracker
    result = sp.predict([frame])[0]
  File "spa.py", line 90, in predict
    results = self.model.detect(frames)
  File "C:\Users\lainsy\Desktop\spa-app-gpu\spa-project\mrcnn\model.py", line 25
06, in detect
    self.keras_model.predict([molded_images, image_metas, anchors], verbose=0)
  File "C:\Users\lainsy\Desktop\spa-app-gpu\spa-project\spaenv\lib\site-packages
\keras\engine\training.py", line 1169, in predict
    steps=steps)
  File "C:\Users\lainsy\Desktop\spa-app-gpu\spa-project\spaenv\lib\site-packages
\keras\engine\training_arrays.py", line 294, in predict_loop
    batch_outs = f(ins_batch)
  File "C:\Users\lainsy\Desktop\spa-app-gpu\spa-project\spaenv\lib\site-packages
\keras\backend\tensorflow_backend.py", line 2721, in __call__
    return self._legacy_call(inputs)
  File "C:\Users\lainsy\Desktop\spa-app-gpu\spa-project\spaenv\lib\site-packages
\keras\backend\tensorflow_backend.py", line 2693, in _legacy_call
    **self.session_kwargs)
  File "C:\Users\lainsy\Desktop\spa-app-gpu\spa-project\spaenv\lib\site-packages
\tensorflow\python\client\session.py", line 895, in run
    run_metadata_ptr)
  File "C:\Users\lainsy\Desktop\spa-app-gpu\spa-project\spaenv\lib\site-packages
\tensorflow\python\client\session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\lainsy\Desktop\spa-app-gpu\spa-project\spaenv\lib\site-packages
\tensorflow\python\client\session.py", line 1344, in _do_run
    options, run_metadata)
  File "C:\Users\lainsy\Desktop\spa-app-gpu\spa-project\spaenv\lib\site-packages
\tensorflow\python\client\session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocat
ing tensor with shape[1,512,256,256] and type float on /job:localhost/replica:0/
task:0/device:GPU:0 by allocator GPU_0_bfc
         [[Node: rpn_model/rpn_conv_shared/convolution = Conv2D[T=DT_FLOAT, data
_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], us
e_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](fpn
_p2/BiasAdd, rpn_conv_shared/kernel/read)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add repor
t_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[Node: mrcnn_detection/TopKV2/_4265 = _Recv[client_terminated=false, r
ecv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:loc
alhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="e
dge_2641_mrcnn_detection/TopKV2", tensor_type=DT_INT32, _device="/job:localhost/
replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add repor
t_tensor_allocations_upon_oom to RunOptions for current allocation info.

Caused by op 'rpn_model/rpn_conv_shared/convolution', defined at:
  File "spa.py", line 1254, in <module>
    startSPA()
  File "spa.py", line 1239, in startSPA
    sp_utils.initTracker(frames, sp, file)
  File "spa.py", line 854, in initTracker
    result = sp.predict([frame])[0]
  File "spa.py", line 87, in predict
    self.getSess()
  File "spa.py", line 81, in getSess
    config=self.config)
  File "C:\Users\lainsy\Desktop\spa-app-gpu\spa-project\mrcnn\model.py", line 18
32, in __init__
    self.keras_model = self.build(mode=mode, config=config)
  File "C:\Users\lainsy\Desktop\spa-app-gpu\spa-project\mrcnn\model.py", line 19
39, in build
    layer_outputs.append(rpn([p]))
  File "C:\Users\lainsy\Desktop\spa-app-gpu\spa-project\spaenv\lib\site-packages
\keras\engine\base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "C:\Users\lainsy\Desktop\spa-app-gpu\spa-project\spaenv\lib\site-packages
\keras\engine\network.py", line 564, in call
    output_tensors, _, _ = self.run_internal_graph(inputs, masks)
  File "C:\Users\lainsy\Desktop\spa-app-gpu\spa-project\spaenv\lib\site-packages
\keras\engine\network.py", line 721, in run_internal_graph
    layer.call(computed_tensor, **kwargs))
  File "C:\Users\lainsy\Desktop\spa-app-gpu\spa-project\spaenv\lib\site-packages
\keras\layers\convolutional.py", line 171, in call
    dilation_rate=self.dilation_rate)
  File "C:\Users\lainsy\Desktop\spa-app-gpu\spa-project\spaenv\lib\site-packages
\keras\backend\tensorflow_backend.py", line 3650, in conv2d
    data_format=tf_data_format)
  File "C:\Users\lainsy\Desktop\spa-app-gpu\spa-project\spaenv\lib\site-packages
\tensorflow\python\ops\nn_ops.py", line 754, in convolution
    return op(input, filter)
  File "C:\Users\lainsy\Desktop\spa-app-gpu\spa-project\spaenv\lib\site-packages
\tensorflow\python\ops\nn_ops.py", line 838, in __call__
    return self.conv_op(inp, filter)
  File "C:\Users\lainsy\Desktop\spa-app-gpu\spa-project\spaenv\lib\site-packages
\tensorflow\python\ops\nn_ops.py", line 502, in __call__
    return self.call(inp, filter)
  File "C:\Users\lainsy\Desktop\spa-app-gpu\spa-project\spaenv\lib\site-packages
\tensorflow\python\ops\nn_ops.py", line 190, in __call__
    name=self.name)
  File "C:\Users\lainsy\Desktop\spa-app-gpu\spa-project\spaenv\lib\site-packages
\tensorflow\python\ops\gen_nn_ops.py", line 725, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "C:\Users\lainsy\Desktop\spa-app-gpu\spa-project\spaenv\lib\site-packages
\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\lainsy\Desktop\spa-app-gpu\spa-project\spaenv\lib\site-packages
\tensorflow\python\framework\ops.py", line 3160, in create_op
    op_def=op_def)
  File "C:\Users\lainsy\Desktop\spa-app-gpu\spa-project\spaenv\lib\site-packages
\tensorflow\python\framework\ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-
access

ResourceExhaustedError (see above for traceback): OOM when allocating tensor wit
h shape[1,512,256,256] and type float on /job:localhost/replica:0/task:0/device:
GPU:0 by allocator GPU_0_bfc
         [[Node: rpn_model/rpn_conv_shared/convolution = Conv2D[T=DT_FLOAT, data
_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], us
e_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](fpn
_p2/BiasAdd, rpn_conv_shared/kernel/read)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add repor
t_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[Node: mrcnn_detection/TopKV2/_4265 = _Recv[client_terminated=false, r
ecv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:loc
alhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="e
dge_2641_mrcnn_detection/TopKV2", tensor_type=DT_INT32, _device="/job:localhost/
replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add repor
t_tensor_allocations_upon_oom to RunOptions for current allocation info.

![Screenshot (63)](https://user-images.githubusercontent.com/23229365/56028904-d5514100-5d36-11e9-84dd-8339dfc10ca7.png)

**Comment by Arham-Aalam** [comment]
@waleedka can you take a quick look (out of your valuable time)?
