### ISSUE TITLE
Issue when loading PNGs

### ISSUE THREAD

**Issue by SpicySyntax** [matterport/Mask_RCNN#1463]
I followed the example from [the nucleus sample](https://github.com/matterport/Mask_RCNN/tree/master/samples/nucleus). 
See a gist with my notebook code [Here](https://gist.github.com/SpicySyntax/c8fd433c52e13bc28f68cd7ea300378e)
I swapped out the class of nucleus with crack (for cracks in infrastructure). I added the my data in the same format:
I.E. (train/image1/images/Image1.png  train/image1/masks/m1.png ...) However when I train now it is unable to load my PNGs:

> ERROR:root:Error processing image {'id': 'image-289', 'source': 'crack', 'path': 'D:\\git_projects\\CrackSegmentation\\train\\image-289\\images/image-289.png'}
Traceback (most recent call last):
  File "c:\users\nick.purcell\appdata\local\continuum\miniconda3\envs\pocmaskrcnn\lib\site-packages\mask_rcnn-2.1-py3.7.egg\mrcnn\model.py", line 1709, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "c:\users\nick.purcell\appdata\local\continuum\miniconda3\envs\pocmaskrcnn\lib\site-packages\mask_rcnn-2.1-py3.7.egg\mrcnn\model.py", line 1220, in load_image_gt
    mask = utils.resize_mask(mask, scale, padding, crop)
  File "c:\users\nick.purcell\appdata\local\continuum\miniconda3\envs\pocmaskrcnn\lib\site-packages\mask_rcnn-2.1-py3.7.egg\mrcnn\utils.py", line 508, in resize_mask
    mask = scipy.ndimage.zoom(mask, zoom=[scale, scale, 1], order=0)
  File "c:\users\nick.purcell\appdata\local\continuum\miniconda3\envs\pocmaskrcnn\lib\site-packages\scipy\ndimage\interpolation.py", line 595, in zoom
    zoom = _ni_support._normalize_sequence(zoom, input.ndim)
  File "c:\users\nick.purcell\appdata\local\continuum\miniconda3\envs\pocmaskrcnn\lib\site-packages\scipy\ndimage\_ni_support.py", line 65, in _normalize_sequence
    raise RuntimeError(err)
RuntimeError: sequence argument must have length equal to input rank

This happens with multiple images and it ultimately fails. 
Is it expecting a different input shape or something?

I am not sure where I went wrong

**Comment by deg4uss3r** [comment]
Hi @SpicySyntax (awesome handle by the way), I found out his has to do with this bit below:

```python
    # Random crops of size 512x512    # Random crops of size 512x512
    IMAGE_RESIZE_MODE = "crop"
    IMAGE_MIN_DIM = 512
    IMAGE_MAX_DIM = 512
    IMAGE_MIN_SCALE = 2.0
```

I was getting the same error without adjusting that, my images were 2577 x 2564 so changing the scale from `2.0` to `5.0` worked for me allowing for crops at 512, but blowing the images back up (for me 2577/512 = ~5.0) to 2577x2564, at least I hope, it won't be done training for a while, but the `RuntimeError`s stopped :)

**Comment by harshgrovr** [comment]
@deg4uss3r  scaling, Did it work?

**Comment by deg4uss3r** [comment]
Yes, this worked.

**Comment by harshgrovr** [comment]
@deg4uss3r 
I am getting this warning, what does it mean?

/home/harsh/anaconda3/envs/maskrcnntensorflowgpu/lib/python3.6/site-packages/PIL/TiffImagePlugin.py:786: UserWarning: Possibly corrupt EXIF data.  Expecting to read 669057 bytes but only got 65171. Skipping tag 34675
  " Skipping tag %s" % (size, len(data), tag)

**Comment by KatharinaSchmidt** [comment]
I have the same issue as above, but my images are just 640x480. 
Do you have any advice for solving it?
