### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by Ashish-Jr** [matterport/Mask_RCNN#1480]
I trained my own model by annotating with VIA tool, but was getting this error:
IndexError: index 1000 is out of bounds for axis 1 with size 1000
Is there any solution for this?

**Comment by nyck33** [comment]
I'm getting something similar after annotating with VIA tool using the circle and making minor changes to the `DataSet` code.

```
Epoch 1/1
ERROR:root:Error processing image {'id': 'frame177.jpg', 'source': 'tennisball', 'path': '/content/drive/My Drive/matterport-balltracker/sample2/train/frame177.jpg', 'width': 640, 'height': 360, 'circles': [{'name': 'circle', 'cx': 368, 'cy': 103, 'r': 10}]}
Traceback (most recent call last):
  File "/content/drive/My Drive/matterport-balltracker/mrcnn/model.py", line 1709, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/content/drive/My Drive/matterport-balltracker/mrcnn/model.py", line 1212, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "/content/drive/My Drive/matterport-balltracker/balloon.py", line 193, in load_mask
    mask[rr, cc, i] = 1
IndexError: index 360 is out of bounds for axis 0 with size 360
ERROR:root:Error processing image {'id': 'frame177.jpg', 'source': 'tennisball', 'path': '/content/drive/My Drive/matterport-balltracker/sample2/train/frame177.jpg', 'width': 640, 'height': 360, 'circles': [{'name': 'circle', 'cx': 368, 'cy': 103, 'r': 10}]}
Traceback (most recent call last):
  File "/content/drive/My Drive/matterport-balltracker/mrcnn/model.py", line 1709, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/content/drive/My Drive/matterport-balltracker/mrcnn/model.py", line 1212, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "/content/drive/My Drive/matterport-balltracker/balloon.py", line 193, in load_mask
    mask[rr, cc, i] = 1
IndexError: index 360 is out of bounds for axis 0 with size 360
```
@Anish-Jr did you find a solution?

**Comment by nyck33** [comment]
Solution here: https://github.com/matterport/Mask_RCNN/issues/636

Closes: #1480

**Comment by Sarathchandra-Janapati** [comment]
Did anyone solve this issue
