### ISSUE TITLE
raise StopIteration(), when I change tensorflow to tensorflow-gpu

### ISSUE THREAD

**Issue by FengZhiheng** [matterport/Mask_RCNN#1484]
How can I fix this problem. When I run my code CTA.py using TensorFlow, it works. But when I use Tensorflow-gpu, it reports such error.

Epoch 1/1
Traceback (most recent call last):
  File "D:/KerasProject/MaskRCNN/samples/CTA/CTA.py", line 400, in <module>
    train(model)
  File "D:/KerasProject/MaskRCNN/samples/CTA/CTA.py", line 201, in train
    layers='heads')
  File "D:\KerasProject\MaskRCNN\mrcnn\model.py", line 2375, in train
    use_multiprocessing=False,
  File "C:\Users\FengZhiheng\Anaconda3\envs\FengZhihengKeras\lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\FengZhiheng\Anaconda3\envs\FengZhihengKeras\lib\site-packages\keras\engine\training.py", line 2065, in fit_generator
    generator_output = next(output_generator)
  File "C:\Users\FengZhiheng\Anaconda3\envs\FengZhihengKeras\lib\site-packages\keras\utils\data_utils.py", line 710, in get
    raise StopIteration()
StopIteration

thanks very much

**Comment by xiongshuai520** [comment]
I also meet this problem, who can give me some inspiration? thanks a lot

**Comment by lucascannelloni** [comment]
Same problem. Did you find a solution?

**Comment by xiongshuai520** [comment]
yes，i solve it，you should change the version of a package，but i don't remember which package




| |
徐允
|
|
邮箱：15215697800@163.com
|

签名由 网易邮箱大师 定制

On 10/23/2019 19:28, johan lind wrote:

Same problem. Did you find a solution?
