### ISSUE TITLE
Train Mask R-CNN with PASCAL VOC 2012 datasets

### ISSUE THREAD

**Issue by Buithienbao** [matterport/Mask_RCNN#1520]
I want to train mask-rcnn with pascal voc 2012 datasets and I use the code in #51 .
However, when training I encounter this error:
`ERROR:root:Error processing image {'id': 1122, 'source': 'voc', 'path': '/content/VOCdevkit/VOC2012/JPEGImages/2010_003532.jpg', 'mask_path': '/content/VOCdevkit/VOC2012/SegmentationObject/2010_003532.png', 'objs': [OrderedDict([('name', 'horse'), ('bndbox', OrderedDict([('xmax', '432'), ('xmin', '66'), ('ymax', '364'), ('ymin', '41')])), ('difficult', '0'), ('occluded', '1'), ('pose', 'Unspecified'), ('truncated', '0')]), OrderedDict([('name', 'horse'), ('bndbox', OrderedDict([('xmax', '147'), ('xmin', '10'), ('ymax', '211'), ('ymin', '19')])), ('difficult', '0'), ('occluded', '1'), ('pose', 'Left'), ('truncated', '1')])], 'width': '500', 'height': '375'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1709, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/usr/local/lib/python3.6/dist-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1212, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "/content/Mask_RCNN/samples/pascal_voc/pascal_voc.py", line 180, in load_mask
    mask = np.ones(tmp_mask.shape[:2]).astype(np.bool)
AttributeError: 'bool' object has no attribute 'shape'`

Anyone know how to fix this? I really appreciate.
P:s/ I train on Google Colab

**Comment by AloshkaD** [comment]
Check your load_mask method in utils and make sure you are loading your mask correctly. 
btw, Shape[:2] is referring to the third channel where you stack masks from the different objects you are training on which means if you had 3 annotated objects with different ids you need to have three masks stacked there.

**Comment by genausz** [comment]
You may check my implementation of TRAINING Mask_RCNN with PASCAL VOC 2012 dataset.

> https://github.com/genausz/Mask_RCNN

code are in dir ./samples/voc

**Comment by harshgrovr** [comment]
@genausz 

When we specify IMAGE_MAX_DIM = 1024 in Config in MaskR-CNN, does it mean that all the images, masks and bounding box will be normalized according to this size automatically?
