### ISSUE TITLE
 File "tf_text_graph_mask_rcnn.py", line 93, in <module>

### ISSUE THREAD

**Issue by buaacarzp** [matterport/Mask_RCNN#1571]
when I use the 
```
python tf_text_graph_mask_rcnn.py --input "./mask_rcnn_inception_v2_coco_2018_01_28/mask_frozen_graph.pb" --config "./mask_rcnn_inception_v2_coco_2018_01_28/mask_rcnn_inception_resnet_v2_atrous_coco.config" --output "./mask_rcnn_inception_v2_coco_2018_01_28/graph_zhoutest.pbtxt"
```
to create the pbtxt file , but it give me a wrong message:
```
Traceback (most recent call last):
  File "tf_text_graph_mask_rcnn.py", line 93, in <module>
    print("graph_def.node[0].op  is :",graph_def.node[0].op )
IndexError: list index out of range
```

**Comment by zrx1046** [comment]
Hello. Have you solved it yet? I'm the same question.

**Comment by zrx1046** [comment]
@buaacarzp Hello. Have you solved it yet? I'm the same question.
