### ISSUE TITLE
Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by ElegantLin** [matterport/Mask_RCNN#1652]
My environment is 

```
ubuntu 18.04
Cuda 10.0
cudnn 10.0
TensorFlow 1.14.0 (pip install)
anaconda python 3.6
RTX 2080
```

When I am trying to run the training demo on coco dataset, I met the following problem

```
2019-07-22 08:22:14.252711: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-07-22 08:22:14.259491: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
Traceback (most recent call last):
  File "samples/coco/coco.py", line 504, in <module>
    augmentation=augmentation)
  File "/home/aidance/anaconda3/envs/py36/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 2374, in train
  File "/home/aidance/anaconda3/envs/py36/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/aidance/anaconda3/envs/py36/lib/python3.6/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/aidance/anaconda3/envs/py36/lib/python3.6/site-packages/keras/engine/training_generator.py", line 217, in fit_generator
    class_weight=class_weight)
  File "/home/aidance/anaconda3/envs/py36/lib/python3.6/site-packages/keras/engine/training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/aidance/anaconda3/envs/py36/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/home/aidance/anaconda3/envs/py36/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/home/aidance/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/home/aidance/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node conv1/convolution}}]]
	 [[{{node ROI/strided_slice_22}}]]
```
I am sure that Tensorflow has utilized the GPU sources and load the dynamic library correctly because I found it failed to do so for the Cuda version.

I searched for the error and it shows that I have to do the 
`sudo rm -rf ~/.nv/ `, but it still does not work.

I also found the solution to set
`config.gpu_options.allow_growth = True`, but I do not know how to add it to the code.

Could you please tell me?

Thanks!

**Comment by i-chaochen** [comment]
I met the same issue as your.

I tried to  ```rm -rf ~/.nv/``` and set ```config.gpu_options.allow_growth = True```

solve this problem! Thanks!

You can set ```config.gpu_options.allow_growth = True``` at the beginning of your tf.session

https://www.tensorflow.org/guide/using_gpu

**Comment by laygond** [comment]
In `mrcnn/model.py` after the imports and before the "Utility Functions" section, I placed the following
```
#Allow GPU Growth
from keras.backend.tensorflow_backend import set_session
import tensorflow as tf
tfconfig = tf.ConfigProto()
tfconfig.gpu_options.allow_growth = True  # dynamically grow the memory used on the GPU
tfconfig.log_device_placement = False  # to log device placement (on which device the operation ran)
sess = tf.Session(config=tfconfig)
set_session(sess)  # set this TensorFlow session as the default session for Keras
```
