### ISSUE TITLE
import imgaug error

### ISSUE THREAD

**Issue by jeevasakthits** [matterport/Mask_RCNN#1657]
>>> import imgaug
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramFiles\Anaconda2\lib\site-packages\imgaug\__init__.py", line 6, in <module>
    from imgaug.imgaug import *
  File "C:\ProgramFiles\Anaconda2\lib\site-packages\imgaug\imgaug.py", line 12, in <module>
    import cv2
  File "C:\ProgramFiles\Anaconda2\lib\site-packages\cv2\__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: DLL load failed: %1 is not a valid Win32 application.

**Comment by jeevasakthits** [comment]
I'm getting this error how could i solve it

**Comment by dimartinot** [comment]
You could try re-installing it by removing it first with pip :

`pip remove imgaug`

Then re-installing it, first from pypi :

`pip install imgaug`

Then, if it still does not work, try to build the wheel yourself by downloading the corresponding .whl file at this [link](https://pypi.org/simple/imgaug/), then typing the command :

`pip install C:/some-dir/imgaug-<version>-py2.py3-none-any.whl`

**Comment by Dayan-Zhanchi** [comment]
I stumbled across this problem recently and NONE of the below worked for me:

- Removing and installing opencv-python or imgaug
- Recreating conda envs/virtualens and pip install over again
- Recloning the github repo and start over with the installs

I recon that there could be different solutions to this problem, so the solution I'm proposing might not necessarily work for everyone and I think this solution is more suitable for Windows users. But there's also one approach that non-windows users can use.

The core problem for me was the opencv-python library, since cv2 is part of it.
I found the solution that worked for me on this link:
https://stackoverflow.com/questions/52349669/dll-load-failed-when-import-cv2-opencv/54321350

> This can happen if you are using windows 10 N distribution, the N distributions does not come pre installed with windows media feature pack, which is required after OpenCV version 3.4 and onwards.
The preferred solution is to install the feature pack at : https://www.microsoft.com/en-us/software-download/mediafeaturepack

> If that is not an option, fall back to an earlier version of OpenCV that does not have dll dependencies, you can do that by: pip install opencv-python=3.3.0.9

Installing media feature pack made it work for me! You can alternatively just install an older version of opencv-python, if you don't want to deal with DLL dependencies and it should also work.
