### ISSUE TITLE
Issue while installing imgaug

### ISSUE THREAD

**Issue by nourelhoudahamoudaa** [matterport/Mask_RCNN#1679]
Pip version: 19.2.1
Python version: Python 3.7.4
Operating system: windows 10

I'm getting this error message:
Collecting imgaug
  Using cached https://files.pythonhosted.org/packages/17/a9/36de8c0e1ffb2d86f871cac60e5caa910cbbdb5f4741df5ef856c47f4445/imgaug-0.2.9-py2.py3-none-any.whl
Requirement already satisfied: scipy in c:\users\nourelhouda\appdata\roaming\python\python37\site-packages (from imgaug) (1.3.0)
Collecting Shapely (from imgaug)
  Using cached https://files.pythonhosted.org/packages/a2/fb/7a7af9ef7a35d16fa23b127abee272cfc483ca89029b73e92e93cdf36e6b/Shapely-1.6.4.post2.tar.gz

    ERROR: Command errored out with exit status 1:
     command: 'C:\Python\Python37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Nourelhouda\\AppData\\Local\\Temp\\pycharm-packaging\\Shapely\\setup.py'"'"'; __file__='"'"'C:\\Users\\Nourelhouda\\AppData\\Local\\Temp\\pycharm-packaging\\Shapely\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\Nourelhouda\AppData\Local\Temp\pycharm-packaging\Shapely\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Nourelhouda\AppData\Local\Temp\pycharm-packaging\Shapely\setup.py", line 80, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "C:\Users\Nourelhouda\AppData\Local\Temp\pycharm-packaging\Shapely\shapely\_buildcfg.py", line 200, in <module>
        lgeos = CDLL("geos_c.dll")
      File "C:\Python\Python37\lib\ctypes\__init__.py", line 364, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: [WinError 126] Le module spécifié est introuvable
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by kaulrohit** [comment]
I also got this error, I tried manually downloading the shapely wheel file and then tried to install it and it worked for me. 
This link has the whl file: https://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely

**Comment by nourelhoudahamoudaa** [comment]
@kaulrohit  thank you, it's work .
have you a solution for the installing of pycocotools _ coco .... ??

**Comment by kaulrohit** [comment]
Check out issue 6,  I think you will find your solution there
#6

**Comment by AkshatRepo** [comment]
The complete process to install imgaug is described in this article which works perfectly fine and this article will clear your related error as well. The link of that article is
<a href="https://www.akshatvasistha.com/2019/10/how-do-real-time-image-segmentation-mask-rcnn.html"> Real-time image segmentation with MaskRCNN </a>
