### ISSUE TITLE
Error when reducing the scales of fpn from 5 to 3 and adding custom anchors.

### ISSUE THREAD

**Issue by dvlshah** [matterport/Mask_RCNN#1717]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Input to reshape is a tensor with 2048 values, but the requested shape requires a multiple of 204800
	 [[{{node tower_0/mask_rcnn/mrcnn_class_bn1/Reshape_1}}]]
	 [[tower_1/mask_rcnn/proposal_targets/strided_slice_54/_2135]]
  (1) Invalid argument: Input to reshape is a tensor with 2048 values, but the requested shape requires a multiple of 204800
	 [[{{node tower_0/mask_rcnn/mrcnn_class_bn1/Reshape_1}}]]
0 successful operations.
1 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "coco.py", line 507, in <module>
    augmentation=augmentation)
  File "/tmp/Mask_RCNN/mrcnn/model.py", line 2419, in train
    use_multiprocessing=True,
  File "/usr/local/lib/python3.6/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 2177, in fit_generator
    class_weight=class_weight)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1849, in train_on_batch
    outputs = self.train_function(ins)
  File "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py", line 2475, in __call__
    **self.session_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Input to reshape is a tensor with 2048 values, but the requested shape requires a multiple of 204800
	 [[node tower_0/mask_rcnn/mrcnn_class_bn1/Reshape_1 (defined at /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:1891) ]]
	 [[tower_1/mask_rcnn/proposal_targets/strided_slice_54/_2135]]
  (1) Invalid argument: Input to reshape is a tensor with 2048 values, but the requested shape requires a multiple of 204800
	 [[node tower_0/mask_rcnn/mrcnn_class_bn1/Reshape_1 (defined at /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:1891) ]]
0 successful operations.
1 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node tower_0/mask_rcnn/mrcnn_class_bn1/Reshape_1:
 tower_0/mask_rcnn/mrcnn_class_bn1/batchnorm/add_1 (defined at /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:1853)

Input Source operations connected to node tower_0/mask_rcnn/mrcnn_class_bn1/Reshape_1:
 tower_0/mask_rcnn/mrcnn_class_bn1/batchnorm/add_1 (defined at /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:1853)

Original stack trace for 'tower_0/mask_rcnn/mrcnn_class_bn1/Reshape_1':
  File "coco.py", line 458, in <module>
    model_dir=args.logs)
  File "/tmp/Mask_RCNN/mrcnn/model.py", line 1877, in __init__
    self.keras_model = self.build(mode=mode, config=config)
  File "/tmp/Mask_RCNN/mrcnn/model.py", line 2105, in build
    model = ParallelModel(model, config.GPU_COUNT)
  File "/tmp/Mask_RCNN/mrcnn/parallel_model.py", line 37, in __init__
    merged_outputs = self.make_parallel()
  File "/tmp/Mask_RCNN/mrcnn/parallel_model.py", line 81, in make_parallel
    outputs = self.inner_model(inputs)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/topology.py", line 617, in __call__
    output = self.call(inputs, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/topology.py", line 2078, in call
    output_tensors, _, _ = self.run_internal_graph(inputs, masks)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/topology.py", line 2229, in run_internal_graph
    output_tensors = _to_list(layer.call(computed_tensor, **kwargs))
  File "/usr/local/lib/python3.6/dist-packages/keras/layers/wrappers.py", line 208, in call
    y = K.reshape(y, (-1, input_length) + output_shape[2:])
  File "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py", line 1891, in reshape
    return tf.reshape(x, shape)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 7715, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

Changed this part of code.                                                             

if callable(config.BACKBONE):
            _, C2, C3, C4, C5 = config.BACKBONE(input_image, stage5=True,
                                                train_bn=config.TRAIN_BN)
        else:
            _, C2, C3, C4, C5 = resnet_graph(input_image, config.BACKBONE,
                                             stage5=True, train_bn=config.TRAIN_BN)
        **# Top-down Layers
        # TODO: add assert to varify feature map sizes match what's in config
        P5 = KL.Conv2D(config.TOP_DOWN_PYRAMID_SIZE, (1, 1), name='fpn_c5p5')(C5)
        P4 = KL.Add(name="fpn_p4add")([
            KL.UpSampling2D(size=(2, 2), name="fpn_p5upsampled")(P5),
            KL.Conv2D(config.TOP_DOWN_PYRAMID_SIZE, (1, 1), name='fpn_c4p4')(C4)])
        P3 = KL.Add(name="fpn_p3add")([
            KL.UpSampling2D(size=(2, 2), name="fpn_p4upsampled")(P4),
            KL.Conv2D(config.TOP_DOWN_PYRAMID_SIZE, (1, 1), name='fpn_c3p3')(C3)])
        #P2 = KL.Add(name="fpn_p2add")([
        #    KL.UpSampling2D(size=(2, 2), name="fpn_p3upsampled")(P3),
        #    KL.Conv2D(config.TOP_DOWN_PYRAMID_SIZE, (1, 1), name='fpn_c2p2')(C2)])
        # Attach 3x3 conv to all P layers to get the final feature maps.
        #P2 = KL.Conv2D(config.TOP_DOWN_PYRAMID_SIZE, (3, 3), padding="SAME", name="fpn_p2")(P2)
        P3 = KL.Conv2D(config.TOP_DOWN_PYRAMID_SIZE, (3, 3), padding="SAME", name="fpn_p3")(P3)
        P4 = KL.Conv2D(config.TOP_DOWN_PYRAMID_SIZE, (3, 3), padding="SAME", name="fpn_p4")(P4)
        P5 = KL.Conv2D(config.TOP_DOWN_PYRAMID_SIZE, (3, 3), padding="SAME", name="fpn_p5")(P5)
        #P6 is used for the 5th anchor scale in RPN. Generated by
        # subsampling from P5 with stride of 2.
        #P6 = KL.MaxPooling2D(pool_size=(1, 1), strides=2, name="fpn_p6")(P5)**

        # Note that P6 is used in RPN, but not in the classifier heads.
        **#rpn_feature_maps = [P2, P3, P4, P5, P6]
        rpn_feature_maps = [P3, P4, P5]
        mrcnn_feature_maps = [P3, P4, P5]
        #mrcnn_feature_maps = [P2, P3, P4, P5]**

Inside the PyramidROIAlign Class 
 for i, level **in enumerate(range(3, 6)):** (from 2 to 3 for fpn layers p3,p4,p5)

Custom anchors are provided in config file as

     BACKBONE_STRIDES = [4, 8, 16]

    # Size of the fully-connected layers in the classification graph
    FPN_CLASSIF_FC_LAYERS_SIZE = 1024

    # Size of the top-down layers used to build the feature pyramid
    TOP_DOWN_PYRAMID_SIZE = 256

    # Number of classification classes (including background)
    NUM_CLASSES = 1  # Override in sub-classes

    # Length of square anchor side in pixels
    # RPN_ANCHOR_SCALES = (32, 64, 128, 256, 512)
    RPN_ANCHOR_SCALES = (32, 64, 128)

    #ANCHORS for 608x608 image -> 608/4 , 608/8 , 608/16 scales
    RPN_ANCHOR_SCALES_W = (132,81,128,21,31,15,5,3,1)
    RPN_ANCHOR_SCALES_H = (131,126,50,61,33,44,14,7,3)

    Input_image_size = (608, 608)

I don't want to use P2 and P6 fpn features. 

Can someone please help asap?

**Comment by dvlshah** [comment]
I was able to solve by changing this bit of code.

Line 429 in model.py
   Old    ` roi_level = tf.minimum(5, tf.maximum(2, 4 + tf.cast(tf.round(roi_level), tf.int32)))`
   New  ` roi_level = tf.minimum(5, tf.maximum(3, 4 + tf.cast(tf.round(roi_level), tf.int32)))`

![image](https://user-images.githubusercontent.com/16095226/64104820-a2b1ee80-cd92-11e9-8f21-a9cee4fed4c3.png)

The minimum FPN level assumed in the code is 2 and maximum is 5. But if you want to alter the FPN scales as per your need you need to change it like mentioned above.

**Comment by dvlshah** [comment]
``
