### ISSUE TITLE
Error during evaluation

### ISSUE THREAD

**Issue by akashdeepjassal** [matterport/Mask_RCNN#1752]
Here coco2017 script is just renamed coco.py script with COCO year changed to 2017.
`Traceback (most recent call last):
  File "train/coco2017.py", line 503, in <module>
    evaluate_coco(model, dataset_val, coco, "segm", limit=int(args.limit))
  File "train/coco2017.py", line 340, in evaluate_coco
    r = model.detect([image], verbose=0)[0]
  File "/usr/local/lib/python3.6/dist-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 2911, in detect
  File "/usr/local/lib/python3.6/dist-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 2813, in mold_inputs
AttributeError: 'NoneType' object has no attribute 'shape'`

**Comment by Hunain-Gillani** [comment]
I'm have an error related to this. I think this is a library issue. I'm also working on it though.

**Comment by akashdeepjassal** [comment]
@Hunain-G  any success ?

**Comment by akashdeepjassal** [comment]
@Hunain-G any success?
