### ISSUE TITLE
Problems to train Mask_RCNN

### ISSUE THREAD

**Issue by alexst07** [matterport/Mask_RCNN#1786]
I am trying train the mask-rcnn using coco dataset:

```
python3 samples/coco/coco.py train --dataset=/path/to/coco/ --model=imagenet
```
But it gave me the follows error:
```
Traceback (most recent call last):
│  File "samples/coco/coco.py", line 504, in <module>
│    augmentation=augmentation)
│  File "/home/alex/anaconda3/lib/python3.7/site-packages/mask_rcnn-2.1-py3.7.egg/mrcnn/model.py", line 2354, in train
│  File "/home/alex/anaconda3/lib/python3.7/site-packages/mask_rcnn-2.1-py3.7.egg/mrcnn/model.py", line 2199, in compile
│AttributeError: 'Model' object has no attribute 'metrics_tensors'
```

My keras version is 2.3.0.

**Comment by freitaucher** [comment]
you might try to find the suitable combination experimentally. For me worked:  keras 2.2.0, tf 1.6.0, python3.6. Another nice question is - how to make it parallel?

**Comment by travishsu** [comment]
refer to issue #1754
