### ISSUE TITLE
Some tips about running code on your own data set

### ISSUE THREAD

**Issue by Mabinogiysk** [matterport/Mask_RCNN#179]
It takes me two days to running this code on my own data set. I thought there should be more details in the guidance.
1.  When using `add_image()` in the `utils.Dataset` class, the `image_id` must be consecutive integer from 1 to some number, because `image_id` is the index of a list.
2. Class number also should be consecutive integer from 1 to some number, or you will get an `nan` loss.

**Comment by chenyuZha** [comment]
@Mabinogiysk Thanks for your response. I also tried to train  with my own dataset, when I created the function **load_mask()**, as  the input just need **image_id**, but in my case I stored all of my masks in another folder, it seems that add the path of folder in the input couldn't work.. Do you have some idea of this? I'm new to Class stuff... Thanks !

**Comment by dexter1608** [comment]
@Mabinogiysk hi i've prepared my dataset using labelme annotation tool in which i have json files with their respective json files how should i load my dataset can you please help me ?

**Comment by priyanka-chaudhary** [comment]
@Mabinogiysk : Can you tell how did you annotate your images?

 I am using my own dataset and I have annotated the images. My groundtruth is an image of same size and for every pixel I have a number which is the class ID.

Like for Person class my ground truth image has pixel colour (1,1,1) same as COCO dataset. My question is if there are two person in an image should both be annotated with colour (1,1,1) or is there a different rule?
As to show two instances of an object we need some kind of distinction. Do you know how they are being annotated in the MS COCO dataset?

**Comment by Mabinogiysk** [comment]
@dexter1608 There is a demo "train_shapes.ipynb", you only need to override some functions in dataset class.

**Comment by Mabinogiysk** [comment]
@priyanka-chaudhary I am not sure what you want to do. In my opinion, two person are two objects and you should make mask for each of the object respectively. In each of the mask, there should be only one person.

**Comment by priyanka-chaudhary** [comment]
@Mabinogiysk : Well the point is I want to generate json file with annotations in same format as MS COCO dataset. I have png images for ground-truth with class_id as pixel value. So if for 2 person I have ID for example 1 and 2. How to reach to same category_id like shown below?

```{"segmentation": [[413.03,131.72,...,132.36]],"area": 1067.9535499999993,"iscrowd": 0,"image_id": 1000,"bbox": [405.93,120.42,37.13,45.52],"category_id": 1,"id": 1245349}

{"segmentation": [[277.59,392.37,...,380.01]],"area": 14372.617749999994,"iscrowd": 0,"image_id": 1000,"bbox": [265.33,95.86,88.92,315.88],"category_id": 1,"id": 1259139}

{"segmentation": [[281.11,418.74,...,423.72]],"area": 11511.253450000006,"iscrowd": 0,"image_id": 1000,"bbox": [209.23,174.64,99.63,249.08],"category_id": 1,"id": 1269164}```

Did you use same annotation format as mentioned in json files? Or something else?
If you did use the same, can you please tell me the process? 
I couldn't find any information for the same.

Thanks a lot!

**Comment by maryamag85** [comment]
I have same issue using my own dataset. COCO has it's special file format. how about if we want to use a dataset composed of 2 tensors, one training images and the other mask of those images?

**Comment by jaydipsinh0738** [comment]
hello can anyone help me for use myu own dataset. i want to create my own dataset and run that in this masking.if anyone have doc then sent me on jaydip.parmar.if@gmail.com.
please help me

**Comment by AliceDinh** [comment]
@Mabinogiysk 
I can see that I am in the same position with many people here: I did prepare my own dataset of identification cards, I made the annotation file and follow the code of coco.py, train_shape without success. 

That would be great if you can provide us the code (from train_shape that you modified) if possible. We are here to learn from each other and help to gain more knowledge and we will really appreciate your help. 
Many thanks

**Comment by AliceDinh** [comment]
@Mabinogiysk 
How did you modify and use add_image() in the utils.Dataset class, I have below error and I think of your suggestion with image_id and class_id. I check my json file, image_id is from 1 to 5 (I use less image to see how the training going), and the class_id is from 1 to 3:
```
ERROR:root:Error processing image {'id': 4, 'source': 'coco', 'path': 'D:\\DATA\\Number-dataset/val2018\\NUM_14.jpg', 'width': '416', 'height': '660', 'annotations': [{'id': 4, 'image_id': 4, 'iscrowd': 0, 'category_id': 3, 'segmentation': [[535, 360, 535, 414, 567, 414, 567, 360]], 'area': 1728.0, 'bbox': [535, 360, 567, 414]}]}
Traceback (most recent call last):
  File "C:\Users\Alice\Mask_RCNN\model.py", line 1632, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "C:\Users\Alice\Mask_RCNN\model.py", line 1191, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "coco.py", line 244, in load_mask
    image_info["width"])
  File "coco.py", line 303, in annToMask
    rle = self.annToRLE(ann, height, width)
  File "coco.py", line 288, in annToRLE
    rles = maskUtils.frPyObjects(segm, height, width)
  File "pycocotools\_mask.pyx", line 295, in pycocotools._mask.frPyObjects
  File "pycocotools\_mask.pyx", line 260, in pycocotools._mask.frPoly
TypeError: an integer is required
```

**Comment by waspinator** [comment]
do annotations in coco need to be in polygon (for iscrowd: 0) and uncompressed RLE format (for iscrowd: 1) to work with matterport's MaskRCNN implementation? I can't find a way to encode masks to uncompressed RLE. Are crowded images used at all in training?

**Comment by enchantress1016** [comment]
@priyanka-chaudhary Hi, did you solve the problem? I also have my ground-truth label as png files and need to convert them into one json file. Could you please elaborate on how I could convert them? Thank you so much!

**Comment by waspinator** [comment]
@enchantress1016 try https://patrickwasp.com/create-your-own-coco-style-dataset/

**Comment by enchantress1016** [comment]
@waspinator Thank you!! It's really helpful :)

**Comment by eyildiz-ugoe** [comment]
@waspinator  I have a coco-style dataset but there is no sample which loads such, so I am unable to run it. Do you happen to have a sample?

**Comment by waspinator** [comment]
@eyildiz-ugoe https://patrickwasp.com/train-a-mask-r-cnn-model-on-your-own-dataset/

**Comment by eyildiz-ugoe** [comment]
@waspinator  I've seen that page of yours but honestly it doesn't help if you don't use docker. And coco.py does not load the dataset out of the box without modifications, which aren't mentioned in that article. The only thing is the [implementation in the notebook](https://github.com/waspinator/deep-learning-explorer/blob/master/mask-rcnn/notebooks/mask_rcnn.ipynb) and that also does not load the dataset.

**Comment by waspinator** [comment]
@eyildiz-ugoe everything should work with or without docker. docker just makes getting set up easier. If you create your dataset using https://patrickwasp.com/create-your-own-coco-style-dataset/ you can train on it using the notebook you linked to.

**Comment by eyildiz-ugoe** [comment]
@waspinator  Well, I did use that approach and I have my dataset, however, that notebook does not load it. Gives error such as `TypeError: list indices must be integers or slices, not str`.

**Comment by waspinator** [comment]
@eyildiz-ugoe It should work with any coco-style dataset. Did you try training on the example shapes dataset? If you get shapes to work but not your dataset, then there might be an issue with the way you generate it.

**Comment by eyildiz-ugoe** [comment]
@waspinator Shapes one works, but it generates everything by itself (random image generation and loading), so it is not the same with my dataset in which the images/masks are being loaded from folders.  

Nucleus works, but again, it only has 1 class and many hardcoded values which I have no clue what for. 

Balloon one works, but the dataset is not coco-style, and you cannot load more than 1 class there either. 

All in all these examples do not help for someone who wants to load a coco-style dataset with multiple classes, which is not given by your link, neither the authors of Mask R-CNN. It's getting extremely frustrating..

**Comment by waspinator** [comment]
oh no, I meant to look at my deep-learning-explorer repo. It has a
coco-style shapes dataset you can test with.

**Comment by eyildiz-ugoe** [comment]
There I get the problem of docker, I don't have it and I can't install it due to dependency problems. And without the docker the module does not work, since there is no setup which took place and no /keras folder for instance.

**Comment by waspinator** [comment]
@eyildiz-ugoe if you can't run docker, you can try to run all the commands it normally runs for you. There's a bunch of stuff you'd have to change though, so it's not super easy.

https://github.com/waspinator/deep-learning-explorer/blob/master/mask-rcnn/docker/keras.dockerfile
