### ISSUE TITLE
What do I specify for weights when training a new rgbd model?

### ISSUE THREAD

**Issue by smorford** [matterport/Mask_RCNN#1809]
Hi all, 

I'm trying to develop a tree detection algorithm from aerial imagery that incorporates RGB and a depth channel that represents tree height/geometry (called a canopy height model). I've tiled my input array to 1024 x 1024 x 4. I've successfully worked through the balloons sample on RGB imagery, and I've been using the WIKI to update the code in the necessary locations to support 4 channels. Item's 1 through 4 on the wiki seem pretty straight forward.

However,  I'm not clear on what I should specify for the weights for training. I've tried using the coco weights:

`python3 trees_rgbz.py train --dataset=/home/smorf/Mask_RCNN/datasets/forest/ --weights=coco
`

and it returns...

`Loading weights  /home/smorf/Mask_RCNN/mask_rcnn_coco.h5
Traceback (most recent call last):
  File "trees_rgbz.py", line 365, in <module>
    model.load_weights(weights_path, by_name=True, exclude=["conv1"])
  File "/home/smorf/Mask_RCNN/mrcnn/model.py", line 2328, in load_weights
    saving.load_weights_from_hdf5_group_by_name(f, layers)
  File "/home/smorf/.local/lib/python3.6/site-packages/keras/engine/saving.py", line 1018, in load_weights_from_hdf5_group_by_name
    str(weight_values[i].shape) + '.')
ValueError: Layer #389 (named "mrcnn_bbox_fc"), weight <tf.Variable 'mrcnn_bbox_fc/kernel:0' shape=(1024, 8) dtype=float32_ref> has shape (1024, 8), but the saved weight has shape (1024, 324).
`

I've tried updating model.load.weights() to exclude the layers it has issues with

` model.load_weights(weights_path, by_name=True, exclude=[
     "conv1", "mrcnn_class_logits", "mrcnn_bbox_fc",
      "mrcnn_bbox", "mrcnn_mask"])
`

And I get the error.....

`Traceback (most recent call last):
  File "/home/smorf/Mask_RCNN/mrcnn/model.py", line 1968, in data_generator
    batch_images[b] = mold_image(image.astype(np.float32), self.config)
  File "/home/smorf/Mask_RCNN/mrcnn/model.py", line 3001, in mold_image
    return images.astype(np.float32) - config.MEAN_PIXEL
ValueError: operands could not be broadcast together with shapes (1024,1024,3) (4,)`

I appreciate any help or suggestions.

**Comment by ChienWong** [comment]
you need to train a new Classification of net, then move the trained weight to mrcnn

**Comment by orestis-z** [comment]
Hi there, you can have look at this code snippet https://github.com/orestis-z/mask-rcnn-rgbd/blob/d590e0f5085f8cbe895a6698e284426fd0116aa4/instance_segmentation/sceneNet/train.py#L66-L85 for an example of how to extend the first convolution for RGB-D data by setting the weights of the depth channel to the mean of the RGB channels
