### ISSUE TITLE
"variable was uninitialized" run-time error during balloon training

### ISSUE THREAD

**Issue by policheh** [matterport/Mask_RCNN#1897]
Hello!

I was trying to reproduce the balloon training exercise:
  python balloon.py train --dataset=./datasets/balloon --weights=coco

and got the following run-time error:

---------------------------------------------------------------------
Training network heads
Starting at epoch 0. LR=0.001

Selecting layers to train
In model:  rpn_model
mrcnn_bbox_fc          (TimeDistributed)

WARNING:tensorflow:Model failed to serialize as JSON. Ignoring... An op outside of the function building code is being passed
a "Graph" tensor. It is possible to have Graph tensors
leak out of the function building context by including a
tf.init_scope in your function building code.
For example, the following function will fail:
  @tf.function
  def has_init_scope():
    my_constant = tf.constant(1.)
    with tf.init_scope():
      added = my_constant * 2
The graph tensor has name: anchors/Variable:0

Epoch 1/30
Traceback (most recent call last):
  File "balloon.py", line 383, in <module>
    train(model)
  File "balloon.py", line 199, in train
    layers='mrcnn_bbox_fc')

tensorflow.python.framework.errors_impl.FailedPreconditionError: Error while reading resource variable anchors/Variable from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/anchors/Variable/N10tensorflow3VarE does not exist.
	 [[{{node ROI/ReadVariableOp}}]]

----------------------------------------------------------------------------

I used: 
TensorFlow 2.0.0, Python 3.6.1 on Mac OS X Mojave.

Thanks in advance , 
and best regards,
Boris

**Comment by marcfielding1** [comment]
Hrmm so I didn't get this to work on tensorflow 2.0 , on Ubuntu I created a virtual env and then did the following in requirements.txt

```
numpy
scipy
Pillow
cython
matplotlib
scikit-image
tensorflow-gpu==1.13.1
keras==2.1.3
opencv-python
h5py
imaug
IPython[all]

```

If you don't have a GPU just miss out the -gpu on that requirement

**Comment by juanmarvin** [comment]
Hi, I got the same problem. Using Tensorflow 2.0  Ubuntu18.0.4. Do you have the solution for this problem for Tensorflow 2.0 ?

I think someone better modifiy the Mask_RCNN to be easy to run under Tensorflow 2.0 and above. GPUs keep improving, CUDA version keeps increasing, Tensorflow version getting newer and newer too. It is difficult to get the old GPU driver and CUDA to run the old tensorflow version. Moreover I only have the RTX GPU, Which is not supported by old GPU driver.

**Comment by ianstath** [comment]
same problem here!

```
  (0) Failed precondition: Error while reading resource variable anchors/Variable from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/anchors/Variable/class tensorflow::Var does not exist.
	 [[{{node ROI/ReadVariableOp}}]]
	 [[ROI/strided_slice_21/_3011]]
```

Tf 2.1 , windows

Any update?

**Comment by akshat1136** [comment]
Facing the same problem. I tried to change all the `from keras.*` to `from tensorflow.keras.*`, but that create other lots of problems. Any solution for this?

**Comment by NeyoxDrago** [comment]
> Hi, I got the same problem. Using Tensorflow 2.0 Ubuntu18.0.4. Do you have the solution for this problem for Tensorflow 2.0 ?
> 
> I think someone better modifiy the Mask_RCNN to be easy to run under Tensorflow 2.0 and above. GPUs keep improving, CUDA version keeps increasing, Tensorflow version getting newer and newer too. It is difficult to get the old GPU driver and CUDA to run the old tensorflow version. Moreover I only have the RTX GPU, Which is not supported by old GPU driver.


in the beginning of model.py file.... 
change
import tensorflow as tf 
into
import tensorflow.comapt.v1 as tf

and run your code...it will work.

**Comment by NeyoxDrago** [comment]
> > Hi, I got the same problem. Using Tensorflow 2.0 Ubuntu18.0.4. Do you have the solution for this problem for Tensorflow 2.0 ?
> > I think someone better modifiy the Mask_RCNN to be easy to run under Tensorflow 2.0 and above. GPUs keep improving, CUDA version keeps increasing, Tensorflow version getting newer and newer too. It is difficult to get the old GPU driver and CUDA to run the old tensorflow version. Moreover I only have the RTX GPU, Which is not supported by old GPU driver.
> 
> in the beginning of model.py file....
> change
> import tensorflow as tf
> into
> import tensorflow.comapt.v1 as tf
> 
> and run your code...it will work.

if still your error occurs about session variables not initialized then add below code in model.py where the code is like something...self.keras_model.fit_generator.

import tensorflow.compat.v1  as tf
session = tf.keras.backend.get_session()
init = tf.global_variables_initializer()
session.run(init)

after this your code will be like..
self.keras_model.fit_generator(............
...........
)
