### ISSUE TITLE
Can't training my data because KeyError: 'height'

### ISSUE THREAD

**Issue by shandytp** [matterport/Mask_RCNN#1942]
Hi guys right i have project in brain tumor classification, but i'm dealing with this error for about 3 weeks, this is the error message

> ERROR:root:Error processing image {'id': 'tumor-44.png', 'source': 'Meningioma', 'path': 'D:\\Belajar Machine Learning\\Coba Mask Tumor\\dataset\\images\\tumor-44.png'}
Traceback (most recent call last):
  File "D:\Belajar Machine Learning\Coba Mask Tumor\mrcnn\model.py", line 1709, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "D:\Belajar Machine Learning\Coba Mask Tumor\mrcnn\model.py", line 1212, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "tumor.py", line 228, in load_mask
    mask = np.zeros([info["height"], info["width"], len(info["polygons"])],
KeyError: 'height'

i'm so confuse with that error message, some people say because something wrong with the json file when i'm mask the image because not using polygon masking, even though i already use polygon for masking.

this is the load_mask code
```
	def load_mask(self, imageID):
		"""Generate instance masks for an image.
       Returns:
        masks: A bool array of shape [height, width, instance count] with
            one mask per instance.
        class_ids: a 1D array of class IDs of the instance masks.
        """
		# If not a road dataset image, delegate to parent class.
		# image_info = self.image_info[image_id]
		# if image_info["source"] != "Meningioma":
		# 	return super(self.__class__, self).load_mask(image_id)

		# Convert polygons to a bitmap mask of shape
		# [height, width, instance_count]
		info = self.image_info[imageID]
		mask = np.zeros([info["height"], info["width"], len(info["polygons"])],
						dtype=np.uint8)
		for i, p in enumerate(info["polygons"]):
			# Get indexes of pixels inside the polygon and set them to 1
			rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
			print("mask.shape, min(mask),max(mask): {}, {},{}".format(mask.shape, np.min(mask), np.max(mask)))
			print("rr.shape, min(rr),max(rr): {}, {},{}".format(rr.shape, np.min(rr), np.max(rr)))
			print("cc.shape, min(cc),max(cc): {}, {},{}".format(cc.shape, np.min(cc), np.max(cc)))

			## Note that this modifies the existing array arr, instead of creating a result array
			## Ref: https://stackoverflow.com/questions/19666626/replace-all-elements-of-python-numpy-array-that-are-greater-than-some-value
			rr[rr > mask.shape[0] - 1] = mask.shape[0] - 1
			cc[cc > mask.shape[1] - 1] = mask.shape[1] - 1

			print("After fixing the dirt mask, new values:")
			print("rr.shape, min(rr),max(rr): {}, {},{}".format(rr.shape, np.min(rr), np.max(rr)))
			print("cc.shape, min(cc),max(cc): {}, {},{}".format(cc.shape, np.min(cc), np.max(cc)))

			mask[rr, cc, i] = 1

		# Return mask, and array of class IDs of each instance. Since we have
		# one class ID only, we return an array of 1s
		return mask.astype(np.bool), np.ones([mask.shape[-1]], dtype=np.int32)
```

I've succeeded the training but i achieve that with round masking, but i want it with polygon masking tho.
thank you so much, hopefully your answer can solve my problem

**Comment by truongtd6285** [comment]
Did you see this piece of code?
```
            # load_mask() needs the image size to convert polygons to masks.
            # Unfortunately, VIA doesn't include it in JSON, so we must read
            # the image. This is only managable since the dataset is tiny.
            image_path = os.path.join(dataset_dir, a['filename'])
            image = skimage.io.imread(image_path)
            height, width = image.shape[:2]
```

**Comment by shandytp** [comment]
> Did you see this piece of code?
> 
> ```
>             # load_mask() needs the image size to convert polygons to masks.
>             # Unfortunately, VIA doesn't include it in JSON, so we must read
>             # the image. This is only managable since the dataset is tiny.
>             image_path = os.path.join(dataset_dir, a['filename'])
>             image = skimage.io.imread(image_path)
>             height, width = image.shape[:2]
> ```

oh, i don't have that piece of code, where i should put that piece of code?
thank you

**Comment by truongtd6285** [comment]
It is in the function load_something() right upper the load_mask(). If you inherited code from the Splash of Color project, so that piece of code is inside the load_balloon() function.
