### ISSUE TITLE
Incompatible shape error

### ISSUE THREAD

**Issue by monocongo** [matterport/Mask_RCNN#1961]
I have TensorFlow 1.13 and Keras 2.2.5 installed in a conda environment:
```
$ conda list tensorflow; conda list keras
# packages in environment at /home/ubuntu/miniconda3/envs/maskrcnngpu:
#
# Name                    Version                   Build  Channel
tensorflow                1.13.1           py37h90a7d86_1    conda-forge
tensorflow-estimator      1.13.0                     py_0  
tensorflow-gpu            1.13.1               h0d30ee6_0  
# packages in environment at /home/ubuntu/miniconda3/envs/maskrcnngpu:
#
# Name                    Version                   Build  Channel
keras                     2.2.5                    py37_1    conda-forge
keras-applications        1.0.8                      py_1    conda-forge
keras-preprocessing       1.1.0                      py_0    conda-forge
```

The GPU on this EC2 instance is not found and so the code ends up running on CPU:
```
2020-01-19 16:20:58.980045: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55af403f4160 executing computations on platform Host. Devices:
2020-01-19 16:20:58.980071: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
```
The same thing happens outside of the context of this Mask R-CNN code so perhaps it has something to do with the overall Python/TF setup?
```
$ python 
>>> import tensorflow as tf
>>> tf.test.gpu_device_name()
2020-01-19 16:31:02.129543: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
2020-01-19 16:31:02.162018: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2499995000 Hz
2020-01-19 16:31:02.162266: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55ab97b533b0 executing computations on platform Host. Devices:
2020-01-19 16:31:02.162293: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
''
>>> tf.__version__
'1.13.1'
```
Apparently, there is an issue with my custom dataset code because for two separate datasets I get the following kind of error from Keras:
```
Traceback (most recent call last):
  File "maskrcnn/train.py", line 309, in <module>
    main()
  File "maskrcnn/train.py", line 292, in main
    args["viajson"],
  File "maskrcnn/train.py", line 197, in train_model
    augmentation=augmentation,
  File "/home/ubuntu/miniconda3/envs/maskrcnngpu/lib/python3.7/site-packages/mask_rcnn-2.1-py3.7.egg/mrcnn/model.py", line 2374, in train
  File "/home/ubuntu/miniconda3/envs/maskrcnngpu/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/maskrcnngpu/lib/python3.7/site-packages/keras/engine/training.py", line 1658, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/ubuntu/miniconda3/envs/maskrcnngpu/lib/python3.7/site-packages/keras/engine/training_generator.py", line 215, in fit_generator
    class_weight=class_weight)
  File "/home/ubuntu/miniconda3/envs/maskrcnngpu/lib/python3.7/site-packages/keras/engine/training.py", line 1449, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/ubuntu/miniconda3/envs/maskrcnngpu/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 2979, in __call__
    return self._call(inputs)
  File "/home/ubuntu/miniconda3/envs/maskrcnngpu/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 2937, in _call
    fetched = self._callable_fn(*array_vals)
  File "/home/ubuntu/miniconda3/envs/maskrcnngpu/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/home/ubuntu/miniconda3/envs/maskrcnngpu/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [9,4] vs. [13,4]
	 [[{{node training/SGD/gradients/rpn_bbox_loss/sub_grad/BroadcastGradientArgs}}]]
```
The code I am using for my dataset and training script is [here](https://github.com/monocongo/maskrcnn/).

Can anyone advise as to 1) whether or not I'm using the best versions of TensorFlow (GPU) and Keras for this, and 2) what may be causing the issue of the incompatible shape shown above?

Thanks in advance for any insight or suggestions.

**Comment by monocongo** [comment]
If I change the versions to 1.14 and 2.2.0 I get the following error from Keras:
```
2020-01-20 18:31:01.860940: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
2020-01-20 18:31:01.861030: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
2020-01-20 18:31:01.861039: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2020-01-20 18:31:02.779788: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-01-20 18:31:02.790206: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2020-01-20 18:31:02.790245: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ip-172-31-60-142): /proc/driver/nvidia/version does not exist
2020-01-20 18:31:02.790604: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2020-01-20 18:31:02.813767: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2499995000 Hz
2020-01-20 18:31:02.814001: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55cd8c06bab0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-01-20 18:31:02.814016: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Using TensorFlow backend.
Traceback (most recent call last):
  File "../maskrcnn/maskrcnn/train.py", line 309, in <module>
    main()
  File "../maskrcnn/maskrcnn/train.py", line 292, in main
    args["viajson"],
  File "../maskrcnn/maskrcnn/train.py", line 182, in train_model
    model = modellib.MaskRCNN(mode="training", config=config, model_dir=output_dir)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/mask_rcnn-2.1-py3.7.egg/mrcnn/model.py", line 1837, in __init__
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/mask_rcnn-2.1-py3.7.egg/mrcnn/model.py", line 1990, in build
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 75, in symbolic_fn_wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/keras/engine/base_layer.py", line 489, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/mask_rcnn-2.1-py3.7.egg/mrcnn/model.py", line 664, in call
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/mask_rcnn-2.1-py3.7.egg/mrcnn/utils.py", line 818, in batch_slice
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/mask_rcnn-2.1-py3.7.egg/mrcnn/model.py", line 663, in <lambda>
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/mask_rcnn-2.1-py3.7.egg/mrcnn/model.py", line 553, in detection_targets_graph
AttributeError: module 'tensorflow' has no attribute 'random_shuffle'
```
Versions info:
```
$ conda list tensorflow; conda list keras
# packages in environment at /home/ubuntu/miniconda3/envs/tf114k220:
#
# Name                    Version                   Build  Channel
tensorflow                1.14.0          gpu_py37h74c33d7_0  
tensorflow-base           1.14.0          gpu_py37he45bfe2_0  
tensorflow-estimator      1.14.0           py37h5ca1d4c_0    conda-forge
tensorflow-gpu            1.14.0               h0d30ee6_0  
# packages in environment at /home/ubuntu/miniconda3/envs/tf114k220:
#
# Name                    Version                   Build  Channel
keras                     2.2.0                    pypi_0    pypi
keras-applications        1.0.2                    pypi_0    pypi
keras-preprocessing       1.0.1                    pypi_0    pypi
```

**Comment by sbeesm** [comment]
@monocongo 

Hi! Try updating tensorflow and see if it works.
https://github.com/matterport/Mask_RCNN/blob/3deaec5d902d16e1daf56b62d5971d428dc920bc/mrcnn/model.py#L28

**Comment by monocongo** [comment]
Thanks @sbeesm. To what version(s)? I am already using TensorFlow 1.3+ and Keras 2.0.8+ (TF 1.13 and Keras 2.2)

**Comment by maxpaynestory** [comment]
Can you run 

```nvidia-smi```

command to check whether your nvidia gpu support cuda

**Comment by monocongo** [comment]
> Can you run
> 
> nvidia-smi
> 
> command to check whether your nvidia gpu support cuda

Thanks, @maxpaynestory 

```
$ nvidia-smi 
Sun Jan 26 01:24:47 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.87.01    Driver Version: 418.87.01    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:1E.0 Off |                    0 |
| N/A   33C    P8     9W /  70W |      0MiB / 15079MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

I have tried again using another conda environment with TensorFlow 1.13.2 and Keras 2.2.5:
```
$ conda list tensorflow; conda list keras
# packages in environment at /home/ubuntu/anaconda3/envs/mrcnn:
#
# Name                    Version                   Build  Channel
tensorflow                1.13.1               h76b4ce7_7    conda-forge
tensorflow-base           1.13.1           py36h76b4ce7_7    conda-forge
tensorflow-estimator      1.13.0                     py_0  
tensorflow-gpu            1.13.1               h0d30ee6_0  
# packages in environment at /home/ubuntu/anaconda3/envs/mrcnn:
#
# Name                    Version                   Build  Channel
keras                     2.2.5                    py36_1    conda-forge
keras-applications        1.0.8                      py_1    conda-forge
keras-preprocessing       1.1.0                      py_0    conda-forge
```

Now I get the following error (similar to the shape error I saw before, but now at least it's seeing the GPU):
```
Epoch 1/20
2020-01-26 01:22:22.389132: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally
Traceback (most recent call last):
  File "../segment_maskrcnn/maskrcnn/train.py", line 309, in <module>
    main()
  File "../segment_maskrcnn/maskrcnn/train.py", line 292, in main
    args["viajson"],
  File "../segment_maskrcnn/maskrcnn/train.py", line 197, in train_model
    augmentation=augmentation,
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 2376, in train
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1658, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/keras/engine/training_generator.py", line 215, in fit_generator
    class_weight=class_weight)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1449, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2979, in __call__
    return self._call(inputs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2937, in _call
    fetched = self._callable_fn(*array_vals)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [4,4] vs. [8,4]
	 [[{{node rpn_bbox_loss/sub}}]]
	 [[{{node mul_50}}]]
```
