### ISSUE TITLE
Duplicate node name in graph: 'mask_rcnn/proposal_targets/packed'

### ISSUE THREAD

**Issue by mrwu-mac** [matterport/Mask_RCNN#1969]
`Traceback (most recent call last):
  File "/Users/apple/PycharmProjects/design/venvnew/Mask_RCNN-master/mrcnn/mrcnn_train.py", line 225, in <module>
    layers='all')
  File "/Users/apple/PycharmProjects/design/venvnew/Mask_RCNN-master/mrcnn/new_model.py", line 574, in train
    use_multiprocessing=False,
  File "/Users/apple/Library/Python/3.7/lib/python/site-packages/tensorflow_core/python/keras/engine/training.py", line 1297, in fit_generator
    steps_name='steps_per_epoch')
  File "/Users/apple/Library/Python/3.7/lib/python/site-packages/tensorflow_core/python/keras/engine/training_generator.py", line 265, in model_iteration
    batch_outs = batch_function(*batch_data)
  File "/Users/apple/Library/Python/3.7/lib/python/site-packages/tensorflow_core/python/keras/engine/training.py", line 973, in train_on_batch
    class_weight=class_weight, reset_metrics=reset_metrics)
  File "/Users/apple/Library/Python/3.7/lib/python/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 264, in train_on_batch
    output_loss_metrics=model._output_loss_metrics)
  File "/Users/apple/Library/Python/3.7/lib/python/site-packages/tensorflow_core/python/keras/engine/training_eager.py", line 311, in train_on_batch
    output_loss_metrics=output_loss_metrics))
  File "/Users/apple/Library/Python/3.7/lib/python/site-packages/tensorflow_core/python/keras/engine/training_eager.py", line 252, in _process_single_batch
    training=training))
  File "/Users/apple/Library/Python/3.7/lib/python/site-packages/tensorflow_core/python/keras/engine/training_eager.py", line 127, in _model_loss
    outs = model(inputs, **kwargs)
  File "/Users/apple/Library/Python/3.7/lib/python/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 891, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/Users/apple/Library/Python/3.7/lib/python/site-packages/tensorflow_core/python/keras/engine/network.py", line 708, in call
    convert_kwargs_to_constants=base_layer_utils.call_context().saving)
  File "/Users/apple/Library/Python/3.7/lib/python/site-packages/tensorflow_core/python/keras/engine/network.py", line 860, in _run_internal_graph
    output_tensors = layer(computed_tensors, **kwargs)
  File "/Users/apple/Library/Python/3.7/lib/python/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 891, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/Users/apple/PycharmProjects/design/venvnew/Mask_RCNN-master/mrcnn/detect_target_layer.py", line 219, in call
    self.config.IMAGES_PER_GPU, names=names)
  File "/Users/apple/PycharmProjects/design/venvnew/Mask_RCNN-master/mrcnn/utils.py", line 822, in batch_slice
    output_slice = graph_fn(*inputs_slice)
  File "/Users/apple/PycharmProjects/design/venvnew/Mask_RCNN-master/mrcnn/detect_target_layer.py", line 218, in <lambda>
    w, x, y, z, self.config),
  File "/Users/apple/PycharmProjects/design/venvnew/Mask_RCNN-master/mrcnn/detect_target_layer.py", line 92, in detection_targets_graph
    crowd_overlaps = overlaps_graph(proposals, crowd_boxes)
  File "/Users/apple/PycharmProjects/design/venvnew/Mask_RCNN-master/mrcnn/detect_target_layer.py", line 21, in overlaps_graph
    [1, 1, tf.shape(boxes2)[0]]), [-1, 4])
  File "/Users/apple/Library/Python/3.7/lib/python/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 11293, in tile
    input, multiples, name=name, ctx=_ctx)
  File "/Users/apple/Library/Python/3.7/lib/python/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 11340, in tile_eager_fallback
    _attr_Tmultiples, (multiples,) = _execute.args_to_matching_eager([multiples], _ctx, _dtypes.int32)
  File "/Users/apple/Library/Python/3.7/lib/python/site-packages/tensorflow_core/python/eager/execute.py", line 257, in args_to_matching_eager
    t, dtype, preferred_dtype=default_dtype, ctx=ctx))
  File "/Users/apple/Library/Python/3.7/lib/python/site-packages/tensorflow_core/python/framework/ops.py", line 1296, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/Users/apple/Library/Python/3.7/lib/python/site-packages/tensorflow_core/python/ops/array_ops.py", line 1278, in _autopacking_conversion_function
    return _autopacking_helper(v, dtype, name or "packed")
  File "/Users/apple/Library/Python/3.7/lib/python/site-packages/tensorflow_core/python/ops/array_ops.py", line 1214, in _autopacking_helper
    return gen_array_ops.pack(elems_as_tensors, name=scope)
  File "/Users/apple/Library/Python/3.7/lib/python/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 6304, in pack
    "Pack", values=values, axis=axis, name=name)
  File "/Users/apple/Library/Python/3.7/lib/python/site-packages/tensorflow_core/python/framework/op_def_library.py", line 793, in _apply_op_helper
    op_def=op_def)
  File "/Users/apple/Library/Python/3.7/lib/python/site-packages/tensorflow_core/python/framework/func_graph.py", line 548, in create_op
    compute_device)
  File "/Users/apple/Library/Python/3.7/lib/python/site-packages/tensorflow_core/python/framework/ops.py", line 3429, in _create_op_internal
    op_def=op_def)
  File "/Users/apple/Library/Python/3.7/lib/python/site-packages/tensorflow_core/python/framework/ops.py", line 1773, in __init__
    control_input_ops)
  File "/Users/apple/Library/Python/3.7/lib/python/site-packages/tensorflow_core/python/framework/ops.py", line 1613, in _create_c_op
    raise ValueError(str(e))
ValueError: Duplicate node name in graph: 'mask_rcnn/proposal_targets/packed'
`
I am a newer in using tensorflow, my tensorflow version is 2.0.0, why this situation?

**Comment by lbininhbl** [comment]
Did you fix the issue? I faced the same problem.
