### ISSUE TITLE
MSCOCO Eavaluation

### ISSUE THREAD

**Issue by matiqul** [matterport/Mask_RCNN#205]
Hi I am trying to run the MSCOCO evaluation code but I find the following error:
Traceback (most recent call last):
  File "/home/kunolab/Matiqul/Mask_RCNN-master/coco.py", line 415, in <module>
    evaluate_coco(model, dataset_val, coco, "bbox", limit=10)
  File "/home/kunolab/Matiqul/Mask_RCNN-master/coco.py", line 285, in evaluate_coco
    coco_results = coco.loadRes(results)
  File "/usr/local/lib/python3.4/dist-packages/pycocotools/coco.py", line 308, in loadRes
    if type(resFile) == str or type(resFile) == unicode:
NameError: name 'unicode' is not defined

Please how I can solve this.....

**Comment by pandamax** [comment]
just remove `or type(resFile) == unicode` ,and run it again as the readme  says.

**Comment by matiqul** [comment]
Can you mention where to change it....

**Comment by pandamax** [comment]
As traceback shows: `File "/usr/local/lib/python3.4/dist-packages/pycocotools/coco.py", line 308`

**Comment by matiqul** [comment]
But this file is read only I can not change

**Comment by pandamax** [comment]
Then you can change the permission of the file

**Comment by chAwater** [comment]
You can try:

- Check this issue https://github.com/cocodataset/cocoapi/issues/49 and PR https://github.com/cocodataset/cocoapi/pull/50

Or

- Install `pycocotools` from waleedka's [repo](https://github.com/waleedka/coco)

**Comment by WillianaLeite** [comment]
Could you please explain to me how to calculate mAR from the "utils.compute_recall" function, I understand that it returns the AR, but how should I calculate the mAR? Please help me!!
