### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'image_ids'

### ISSUE THREAD

**Issue by Sarojini96** [matterport/Mask_RCNN#2051]
Epoch 1/1
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/sarojini/anaconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/sarojini/anaconda3/lib/python3.7/site-packages/keras/utils/data_utils.py", line 650, in next_sample
    return six.next(_SHARED_SEQUENCES[uid])
  File "/home/sarojini/ML projects/mask rnn test - cracks-weld/mrcnn/model.py", line 1683, in data_generator
    image_ids = np.copy(dataset.image_ids)
AttributeError: 'NoneType' object has no attribute 'image_ids'
"""

**Comment by Srini-1981** [comment]
@Sarojini96 Any progress on this one? I am also stuck with the same error and could not able to move forward, a little explanation where i posted in other repository too:

Data verification looks good with annotations and image files. Getting the same error as mentioned by above you. Also tried with various tensorflow and keras versions but no luck, still it is failing with same error during the training.
I have added a log statement before it fetches the training file, what I am suspecting is it is somehow utilizing the first file in the epoch and making short of one file for the steps, hence the error. For example: I am just doing the training with 5 files to narrow down the problem, epoch somehow using the first file and only 4 files remains for the 5 steps so might be the error? Below are the logs with masking some of the paths, any help will be greatly appreciated.

Epoch 1/2

training file in progress C:..\pdf-page-01.xml
1/5 [=====>........................] - ETA: 1:57 - loss: 4.1185 - rpn_class_loss: 0.0352 - rpn_bbox_loss: 0.4488 - mrcnn_class_loss: 1.2684 - mrcnn_bbox_loss: 0.6037 - mrcnn_mask_loss: 1.7625
training file in progress C:..\pdf-page-04.xml
2/5 [===========>..................] - ETA: 1:20 - loss: 4.5562 - rpn_class_loss: 0.3978 - rpn_bbox_loss: 0.8985 - mrcnn_class_loss: 1.1269 - mrcnn_bbox_loss: 0.6775 - mrcnn_mask_loss: 1.4555
training file in progress C:..\pdf-page-10.xml
3/5 [=================>............] - ETA: 51s - loss: 4.1844 - rpn_class_loss: 0.2664 - rpn_bbox_loss: 0.7914 - mrcnn_class_loss: 0.9270 - mrcnn_bbox_loss: 0.6436 - mrcnn_mask_loss: 1.5559
training file in progress C:..\pdf-page-1.xml
4/5 [=======================>......] - ETA: 25s - loss: 3.8967 - rpn_class_loss: 0.2041 - rpn_bbox_loss: 0.7172 - mrcnn_class_loss: 0.7498 - mrcnn_bbox_loss: 0.6495 - mrcnn_mask_loss: 1.5761
training file in progress C:..\pdf-page-2.xml
Traceback (most recent call last):

File "", line 1, in
model.train(train_set, None, learning_rate=config.LEARNING_RATE, epochs=2, layers='heads')

File "C:\Users\mommasani.srinivasul\AppData\Local\Continuum\anaconda3\envs\mask-rcnn\lib\site-packages\mask_rcnn-2.1-py3.7.egg\mrcnn\model.py", line 2374, in train
use_multiprocessing=True,

File "C:\Users\mommasani.srinivasul\AppData\Local\Continuum\anaconda3\envs\mask-rcnn\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
return func(*args, **kwargs)

File "C:\Users\mommasani.srinivasul\AppData\Local\Continuum\anaconda3\envs\mask-rcnn\lib\site-packages\keras\engine\training.py", line 2244, in fit_generator
max_queue_size=max_queue_size)

File "C:\Users\mommasani.srinivasul\AppData\Local\Continuum\anaconda3\envs\mask-rcnn\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
return func(*args, **kwargs)

File "C:\Users\mommasani.srinivasul\AppData\Local\Continuum\anaconda3\envs\mask-rcnn\lib\site-packages\keras\engine\training.py", line 2362, in evaluate_generator
generator_output = next(output_generator)

File "C:\Users\mommasani.srinivasul\AppData\Local\Continuum\anaconda3\envs\mask-rcnn\lib\site-packages\mask_rcnn-2.1-py3.7.egg\mrcnn\model.py", line 1675, in data_generator
image_ids = np.copy(dataset.image_ids)

AttributeError: 'NoneType' object has no attribute 'image_ids'

**Comment by Ahmad-Salem** [comment]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-62-5d28f7972cbb> in <module>()
      6             learning_rate=config.LEARNING_RATE,
      7             epochs=1,
----> 8             layers='all')

1 frames
/content/Mask_RCNN/mrcnn/model.py in __init__(self, dataset, config, shuffle, augmentation, random_rois, detection_targets)
   1682                  random_rois=0, detection_targets=False):
   1683 
-> 1684         self.image_ids = np.copy(dataset.image_ids)
   1685         self.dataset = dataset
   1686         self.config = config

AttributeError: 'CocoDataset' object has no attribute 'image_ids'

**Comment by Ahmad-Salem** [comment]
same error :(
