### ISSUE TITLE
Permisson Error

### ISSUE THREAD

**Issue by muhammetfaik** [matterport/Mask_RCNN#2054]
It's my code in google cloud vm: 
```
python3.7 samples/balloon/balloon.py train --dataset=balloon/ --weights=mask_rcnn_balloon.h5
```
But It's error about permisson:
```
Training network heads
Traceback (most recent call last):
  File "samples/balloon/balloon.py", line 364, in <module>
    train(model)
  File "samples/balloon/balloon.py", line 199, in train
    layers='heads')
  File "/usr/local/lib/python3.7/site-packages/mask_rcnn-2.1-py3.7.egg/mrcnn/model.py", line 2336, in train
  File "/usr/local/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/logs'
```
Help!!

**Comment by will-r-wang** [comment]
A bit late on this but I recently ran into the same error as well. It's not recommended since it's not the most secure but if you look at this thread https://discuss.cryosparc.com/t/errno-13-permission-denied/2999, `chmod -R 777 /home/` was the solution which worked for me.

**Comment by muhammetfaik** [comment]
Thanks @will-r-wang

**Comment by thedustyengineer** [comment]
A better solution is right above the model.train call, just override the log location:

model.log_dir = './logs/train'

Very simple.
