### ISSUE TITLE
AttributeError: 'Model' object has no attribute '_get_distribution_strategy' while training MaskRcnn model on GPU, any clue on solving this issue is appreciated

### ISSUE THREAD

**Issue by Niveditakatta** [matterport/Mask_RCNN#2070]
Traceback (most recent call last):
  File "guardrail.py", line 439, in <module>
    train(model, args.dataset, args.subset)
  File "guardrail.py", line 239, in train
    epochs=40,layers='heads')
  File "/data/vap/train-Mobilenet/Maskrcnn/mrcnn/model.py", line 2379, in train
    use_multiprocessing=False,
  File "/data/librarys/anaconda3/envs/Mask_RCNN/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/data/librarys/anaconda3/envs/Mask_RCNN/lib/python3.7/site-packages/keras/engine/training.py", line 1732, in fit_generator
    initial_epoch=initial_epoch)
  File "/data/librarys/anaconda3/envs/Mask_RCNN/lib/python3.7/site-packages/keras/engine/training_generator.py", line 100, in fit_generator
    callbacks.set_model(callback_model)
  File "/data/librarys/anaconda3/envs/Mask_RCNN/lib/python3.7/site-packages/keras/callbacks/callbacks.py", line 68, in set_model
    callback.set_model(model)
  File "/data/librarys/anaconda3/envs/Mask_RCNN/lib/python3.7/site-packages/keras/callbacks/tensorboard_v2.py", line 116, in set_model
    super(TensorBoard, self).set_model(model)
  File "/data/librarys/anaconda3/envs/Mask_RCNN/lib/python3.7/site-packages/tensorflow_core/python/keras/callbacks.py", line 1532, in set_model
    self.log_dir, self.model._get_distribution_strategy())  # pylint: disable=protected-access
AttributeError: 'Model' object has no attribute '_get_distribution_strategy'

**Comment by Niveditakatta** [comment]
I am trying to run maskrcnn using python 3.7 and 
Tensorflow 2.1.0 and ended up with the above problem while running on a GPU, any help or suggestions to resolve this issue please.

**Comment by huobanlqs** [comment]
I have also met this error， have you got some clues?

**Comment by huobanlqs** [comment]
Oh, I have found a solution:
add 
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
in Anaconda3\Lib\site-packages\keras\callbacks\tensorboard_v2.py file
and dont forget to comment out these when ur running other program.


the error is caused the difference between tf.keras and keras. Because that tf2 environment has used tensorboard_v2.py, in which the set_model have used the _get_distribution_strategy while the mask rcnn was built by tf1 and it use the kreas. Even though I have set tf.compat.v1.disable_v2_behavior() in the model.py, it still use the tensorboard_v2.py, so I add 
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
in the Anaconda3\Lib\site-packages\keras\callbacks\tensorboard_v2.py file. and solved.

**Comment by Niveditakatta** [comment]
@huobanlqs: Thank you so much for posting the fix, this worked out with the changes you have suggested, but ended up in different issue during training in epoch 1, looking into it.
Anyway thank you so much once again for your help on this.

**Comment by AkhilMokkapati** [comment]
@Niveditakatta  Fix suggested by @huobanlqs worked for Model Object has....  me too facing an issue after epoch 1. Is it the same as in the attached image ?? if so, are you able to overcome that??  

Epoch 1/25
2020-05-05 03:06:09.900903: I tensorflow/core/profiler/lib/profiler_session.cc:225] Profiler session started.
2020-05-05 03:06:09.913372: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cupti64_101.dll'; dlerror: cupti64_101.dll not found
2020-05-05 03:06:09.935992: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1307] function cupti_interface_->Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this)failed with error CUPTI could not be loaded or symbol could not be found.
2020-05-05 03:06:09.965625: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1346] function cupti_interface_->ActivityRegisterCallbacks( AllocCuptiActivityBuffer, FreeCuptiActivityBuffer)failed with error CUPTI could not be loaded or symbol could not be found.
2020-05-05 03:08:36.387899: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1329] function cupti_interface_->EnableCallback( 0 , subscriber_, CUPTI_CB_DOMAIN_DRIVER_API, cbid)failed with error CUPTI could not be loaded or symbol could not be found.
2020-05-05 03:08:36.407656: I tensorflow/core/profiler/internal/gpu/device_tracer.cc:88]  GpuTracer has collected 0 callback api events and 0 activity events.

![image](https://user-images.githubusercontent.com/7602200/81042842-068b3a80-8e7f-11ea-9f33-48a0c8b5aba0.png)

**Comment by Niveditakatta** [comment]
@mak8844 this looks like different issue, I got the following issue and couldn't resolve it so far.
Epoch 1/40
/data/librarys/anaconda3/envs/Mask_RCNN/lib/python3.7/site-packages/keras/utils/data_utils.py:718: UserWarning: An input could not be retrieved. It could be because a worker has died.We do not have any information on the lost sample.
  UserWarning)
2020-04-14 13:11:41.039269: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
Traceback (most recent call last):
  File "guardrail.py", line 439, in <module>
    train(model, args.dataset, args.subset)
  File "guardrail.py", line 239, in train
    epochs=40,layers='heads')
  File "/data/vap/train-Mobilenet/Maskrcnn/mrcnn/model.py", line 2379, in train
    use_multiprocessing=True,
  File "/data/librarys/anaconda3/envs/Mask_RCNN/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/data/librarys/anaconda3/envs/Mask_RCNN/lib/python3.7/site-packages/keras/engine/training.py", line 1732, in fit_generator
    initial_epoch=initial_epoch)
  File "/data/librarys/anaconda3/envs/Mask_RCNN/lib/python3.7/site-packages/keras/engine/training_generator.py", line 220, in fit_generator
    reset_metrics=False)
  File "/data/librarys/anaconda3/envs/Mask_RCNN/lib/python3.7/site-packages/keras/engine/training.py", line 1514, in train_on_batch
    outputs = self.train_function(ins)
  File "/data/librarys/anaconda3/envs/Mask_RCNN/lib/python3.7/site-packages/tensorflow_core/python/keras/backend.py", line 3567, in __call__
    run_metadata=self.run_metadata)
  File "/data/librarys/anaconda3/envs/Mask_RCNN/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1474, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Error while reading resource variable anchors/Variable from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/anchors/Variable/N10tensorflow3VarE does not exist.
         [[{{node ROI/ReadVariableOp}}]]

**Comment by rgold-136** [comment]
Regarding huobanlqs fix, I only had to change: import tensorflow as tf, to import tensorflow.compat.v1 as tf for mine to work. 

Unfortunately I don't have any advice for the above issue.
