### ISSUE TITLE
Please please guide me which version of Tensorflow-gpu, Keras and Python will work for training this model?

### ISSUE THREAD

**Issue by Akshay-Ijantkar** [matterport/Mask_RCNN#2073]
Currently, I am using GPU RTX 2070, CUDA 10. I have tried many combination fo TF and Keras to make it work but it's not working at all. I wish to make it work on GPU. I have referred to many issues from GitHub but my issue is not yet resolved.

I am always getting this error:
```
    from tensorflow.python.saved_model import model_utils as export_utils
ImportError: cannot import name 'model_utils' from 'tensorflow.python.saved_model' (C:\Users\aksha\Anaconda3\lib\site-packages\tensorflow\python\saved_model\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\core_rock.py", line 374, in <module>
    train(model)
  File ".\core_rock.py", line 203, in train
    layers='heads')
  File "D:\MMG_Files\OneDrive - MMG Limited\Core_Photos_Project\Core_Instance_Segmentation\MAIN_INSTANCE_SEG\Mask_RCNN-master\mrcnn\model.py", line 2341, in train
    histogram_freq=0, write_graph=True, write_images=False),
  File "C:\Users\aksha\Anaconda3\lib\site-packages\keras\callbacks.py", line 747, in __init__
    raise ImportError('You need the TensorFlow module installed to '
ImportError: You need the TensorFlow module installed to use TensorBoard.
```
I understand there are related issues in the forum but trust me I tried all solutions but no luck.
It will be great if anyone can please help me?****

**Comment by Akshay-Ijantkar** [comment]
Steps:
1. Cuda 10.0
2. Cudnn 7.6.5.32
3. Windows 10
4. Create a virtual environment 
5. python 3.6.10
6. Tensorflow-gpu 1.13.1
7. Keras 2.2.5

**Comment by x12901** [comment]
Hi！Is that problem solved?I have the same problem.
