### ISSUE TITLE
Training on 16 GPUs

### ISSUE THREAD

**Issue by Adblu** [matterport/Mask_RCNN#2164]
I managed to setup everything for training on 8 GPUs, Then I switched to machine with 16 GPUs and I got following error:

```
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/car/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/ubuntu/anaconda3/envs/car/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/ubuntu/anaconda3/envs/car/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Number of ways to split should evenly divide the split dimension, but got split_dim 0 (size = 8) and num_split 16
	 [[{{node split_2}}]]
	 [[{{node bn4h_branch2b/moving_variance/read}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "damage.py", line 142, in <module>
    train(model)
  File "damage.py", line 59, in train
    layers='heads')
  File "/home/ubuntu/car/mrcnn/model.py", line 2374, in train
    use_multiprocessing=True,
  File "/home/ubuntu/anaconda3/envs/car/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/car/lib/python3.6/site-packages/keras/engine/training.py", line 2177, in fit_generator
    class_weight=class_weight)
  File "/home/ubuntu/anaconda3/envs/car/lib/python3.6/site-packages/keras/engine/training.py", line 1849, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/ubuntu/anaconda3/envs/car/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2475, in __call__
    **self.session_kwargs)
  File "/home/ubuntu/anaconda3/envs/car/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/ubuntu/anaconda3/envs/car/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ubuntu/anaconda3/envs/car/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/ubuntu/anaconda3/envs/car/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Number of ways to split should evenly divide the split dimension, but got split_dim 0 (size = 8) and num_split 16
	 [[node split_2 (defined at /home/ubuntu/car/mrcnn/parallel_model.py:61) ]]
	 [[node bn4h_branch2b/moving_variance/read (defined at /home/ubuntu/anaconda3/envs/car/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:392) ]]

Caused by op 'split_2', defined at:
  File "damage.py", line 109, in <module>
    model_dir=args.logs)
  File "/home/ubuntu/car/mrcnn/model.py", line 1837, in __init__
    self.keras_model = self.build(mode=mode, config=config)
  File "/home/ubuntu/car/mrcnn/model.py", line 2062, in build
    model = ParallelModel(model, config.GPU_COUNT)
  File "/home/ubuntu/car/mrcnn/parallel_model.py", line 37, in __init__
    merged_outputs = self.make_parallel()
  File "/home/ubuntu/car/mrcnn/parallel_model.py", line 62, in make_parallel
    self.inner_model.inputs)}
  File "/home/ubuntu/car/mrcnn/parallel_model.py", line 61, in <dictcomp>
    for name, x in zip(self.inner_model.input_names,
  File "/home/ubuntu/anaconda3/envs/car/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1508, in split
    axis=axis, num_split=num_or_size_splits, value=value, name=name)
  File "/home/ubuntu/anaconda3/envs/car/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 8883, in split
    "Split", split_dim=axis, value=value, num_split=num_split, name=name)
  File "/home/ubuntu/anaconda3/envs/car/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/ubuntu/anaconda3/envs/car/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/car/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/ubuntu/anaconda3/envs/car/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Number of ways to split should evenly divide the split dimension, but got split_dim 0 (size = 8) and num_split 16
	 [[node split_2 (defined at /home/ubuntu/car/mrcnn/parallel_model.py:61) ]]
	 [[node bn4h_branch2b/moving_variance/read (defined at /home/ubuntu/anaconda3/envs/car/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:392) ]]
```

Does anybody had similar issue ?

**Comment by xxxming730** [comment]
Hello, I am trying to train with 4 RTX A6000 (48G), when I set it to gpu_count=4 Images_per_gpu=8 the memory overflow error occurs, the first graphics card video memory occupies almost full, the other three only occupy 15G, 13G, 13G, and gpu_count=1 Images_per_gpu=8 when there is no problem at all, can complete the training smoothly, I really don't know what the reason is , can you help me answer it, thank you very much!
