### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (1024,1024,4) (3,)

### ISSUE THREAD

**Issue by shepherd25** [matterport/Mask_RCNN#2237]
Processing 1 images
image                    shape: (600, 300, 4)         min:   23.00000  max:  255.00000  uint8
Traceback (most recent call last):
  File "blur.py", line 371, in <module>
    video_path=args.video)
  File "blur.py", line 236, in detect_and_color_splash
    r = model.detect([image], verbose=1)[0]
  File "D:\Projects\Aidc\Mask_RCNN\mrcnn\model.py", line 2503, in detect
    molded_images, image_metas, windows = self.mold_inputs(images)
  File "D:\Projects\Aidc\Mask_RCNN\mrcnn\model.py", line 2402, in mold_inputs
    molded_image = mold_image(molded_image, self.config)
  File "D:\Projects\Aidc\Mask_RCNN\mrcnn\model.py", line 2803, in mold_image
    return images.astype(np.float32) - config.MEAN_PIXEL
ValueError: operands could not be broadcast together with shapes (1024,1024,4) (3,)

**Comment by suchiz** [comment]
Hi there, trying to run it on PNG images ?

**Comment by shepherd25** [comment]
Yes actually for all image formats

**Comment by suchiz** [comment]
Checkout the wiki then :). Only images with 3 channels are accepted. Gray-scale too but you have to modify some parameters. Check the wiki, maybe there's for pngs
