### ISSUE TITLE
ValueError: shapes (400,327680) and (3136,12) not aligned: 327680 (dim 1) != 3136 (dim 0)

### ISSUE THREAD

**Issue by Basma-hash** [matterport/Mask_RCNN#2381]
Hello everyone,
I get this error whenever I delete the use_mini_mask from the argument list considering that I am using mrcnn2 (the one that works with tensorflow 2).
And I get this error TypeError: load_image_gt() got an unexpected keyword argument 'use_mini_mask' when I leave 'use_mini_mask'. .
Anyone can help???

**Comment by sirbastiano** [comment]
I also have your same problem

**Comment by GreeshmaManikandan** [comment]
Traceback (most recent call last):
  File "fish.py", line 331, in <module>
    model_dir=args.logs)
  File "/root/Mask_RCNN/mrcnn/model.py", line 1837, in __init__
    self.keras_model = self.build(mode=mode, config=config)
  File "/root/Mask_RCNN/mrcnn/model.py", line 1934, in build
    anchors = KL.Lambda(lambda x: tf.Variable(anchors), name="anchors")(input_image)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 926, in __call__
    input_list)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 1117, in _functional_construction_call
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/core.py", line 904, in call
    self._check_variables(created_variables, tape.watched_variables())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/core.py", line 931, in _check_variables
    raise ValueError(error_str)
ValueError: 
The following Variables were created within a Lambda layer (anchors)
but are not tracked by said layer:
  <tf.Variable 'anchors/Variable:0' shape=(2, 261888, 4) dtype=float32>
The layer cannot safely ensure proper Variable reuse across multiple
calls, and consquently this behavior is disallowed for safety. Lambda
layers are not well suited to stateful computation; instead, writing a
subclassed Layer is the recommend way to define layers with
Variables.


I always get this value_error whenever I use a higher tensorflow version. But the google colab  GPU supports  only the tensorflow version 2.3.0 (2.x). 
Can anybody please give me a solution that is compatible with GPU?????.....
