### ISSUE TITLE
TypeError: export_inference_graph() got an unexpected keyword argument 'use_side_inputs'

### ISSUE THREAD

**Issue by Vamshigoud784** [matterport/Mask_RCNN#2394]
Hey,
 I have issue with exporting inference graph i dont know what is the issue i have been trying to export but its not working. Thank you in advance. Help will be appreciated.

Command used:
python ../../models/research/object_detection/export_inference_graph.py  \
  --input_type image_tensor   \
    --pipeline_config_path /home/bigthinx/TensorFlow/workspace/training_demo/pre-trained-models/mask_rcnn_inception_resnet_v2_atrous_coco_2018_01_28/pipeline.config  \
      --trained_checkpoint_prefix /home/bigthinx/TensorFlow/workspace/training_demo/pre-trained-models/mask_rcnn_inception_resnet_v2_atrous_coco_2018_01_28/model.ckpt-340000 \
        --output_directory /home/bigthinx/TensorFlow/workspace/training_demo/inference_graph_5k

Log
:/home/bigthinx/.conda/envs/cloth_detection/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/bigthinx/.conda/envs/cloth_detection/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/bigthinx/.conda/envs/cloth_detection/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/bigthinx/.conda/envs/cloth_detection/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/bigthinx/.conda/envs/cloth_detection/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/bigthinx/.conda/envs/cloth_detection/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/bigthinx/.conda/envs/cloth_detection/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/bigthinx/.conda/envs/cloth_detection/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/bigthinx/.conda/envs/cloth_detection/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/bigthinx/.conda/envs/cloth_detection/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/bigthinx/.conda/envs/cloth_detection/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/bigthinx/.conda/envs/cloth_detection/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "../../models/research/object_detection/export_inference_graph.py", line 206, in <module>
    tf.app.run()
  File "/home/bigthinx/.conda/envs/cloth_detection/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/bigthinx/.conda/envs/cloth_detection/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/bigthinx/.conda/envs/cloth_detection/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "../../models/research/object_detection/export_inference_graph.py", line 202, in main
    side_input_types=side_input_types)
TypeError: export_inference_graph() got an unexpected keyword argument 'use_side_inputs'

**Comment by dsnsabari** [comment]
@Vamshigoud784  , check the check point file path in the config file. If the check point not in the mentioned path, you will get this error.
