### ISSUE TITLE
OperatorNotAllowedInGraphError in tf.debugging.Assert and tf.keras.Input

### ISSUE THREAD

**Issue by w-shimaya** [matterport/Mask_RCNN#2404]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**:
    - Yes
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
    - Linux Ubuntu 18.04.4 LTS
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**:
-   **TensorFlow installed from (source or binary)**:
    - `pip install tensorflow`
-   **TensorFlow version (use command below)**:
    - v2.3.0-54-gfcc4b966f1 2.3.1
-   **Python version**:
    - 3.6.9
-   **Bazel version (if compiling from source)**:
-   **GCC/Compiler version (if compiling from source)**:
-   **CUDA/cuDNN version**:
    - 10.1/7.6.5
-   **GPU model and memory**:
    - Geforce RTX 2080 SUPER (8GB)
-   **Exact command to reproduce**:
    - The minimal python script which can reproduce the issue is in the Source code / logs section below.

### Describe the problem
I would like to check if inputs to a `Model` is valid or not by using the `tf.debugging.Assert()` function.
But as you can see in the Source code/logs section, the straightforward implementation results in an OperatorNotAllowedInGraphError.
I believe such simple syntax will help many TensorFlow users.

### Source code / logs
```
import tensorflow as tf
import tensorflow.keras as K

if __name__ == "__main__":
    inputs = K.Input(shape=(10, 10))

    tf.debugging.Assert(
        tf.reduce_all(inputs >= 0.), 
        [inputs]
    )

    # any operations or model definitions follow
    # ...
```
when I ran this script, I got an error:
```
Traceback (most recent call last):
  File "reproduce_tfbug.py", line 9, in <module>
    [inputs]
  File "/home/shimaya/venv/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/shimaya/venv/lib/python3.6/site-packages/tensorflow/python/util/tf_should_use.py", line 247, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
  File "/home/shimaya/venv/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 151, in Assert
    if not condition:
  File "/home/shimaya/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 877, in __bool__
    self._disallow_bool_casting()
  File "/home/shimaya/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 490, in _disallow_bool_casting
    self._disallow_in_graph_mode("using a `tf.Tensor` as a Python `bool`")
  File "/home/shimaya/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 479, in _disallow_in_graph_mode
    " this function with @tf.function.".format(task))
tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.
```

**Comment by w-shimaya** [comment]
just mistake, sorry
