### ISSUE TITLE
Mask RCNN on Custom Dataset

### ISSUE THREAD

**Issue by cedric102** [matterport/Mask_RCNN#2421]
I could not find the comment section in your website : https://thebinarynotes.com/how-to-train-mask-r-cnn-on-the-custom-dataset/

The following message appears during training:
2020-11-12 21:39:57.729227: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "custom.py", line 346, in <module>
    train(model)
  File "custom.py", line 167, in train
    dataset_train.load_custom(args.dataset, "train")
  File "custom.py", line 100, in load_custom
    polygons = [r['shape_attributes'] for r in a['regions']]
  File "custom.py", line 100, in <listcomp>
    polygons = [r['shape_attributes'] for r in a['regions']]
TypeError: string indices must be integers

**Comment by nataliameira** [comment]
@cedric102 I have the same problem. Did you manage to resolve this?

**Comment by PrakharPrashantSingh** [comment]
hi, is this problem resolved?

Thanks

**Comment by cedric102** [comment]
Hello Prashant and Natalia,

I am not sure I understand what you mean.
Can you please explain?

Kind regards,
Cedric.
