### ISSUE TITLE
ModuleNotFoundError: Tensorflow

### ISSUE THREAD

**Issue by SamvdVoort** [matterport/Mask_RCNN#2454]
So I am trying to train MaskRCNN on my custom dataset of floorplans. I have used the MaskRCNN-TF2 repository (https://github.com/ahmedfgad/Mask-RCNN-TF2) and have used the following blog as a guide: https://engineering.matterport.com/splash-of-color-instance-segmentation-with-mask-r-cnn-and-tensorflow-7c761e238b46. 

I am trying to train on my custom dataset, but I get the following error regarding the file _model.py_;
```
(mask) C:\Users\samvd\Documents\Master\DataSystemsProject\MaskTF2\samples\balloon>python3 floorplan.py train --dataset=dataset --model=coco

C:\Users\samvd\Documents\Master\DataSystemsProject\MaskTF2\mrcnn\model.py:2363: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if os.name is 'nt':
Traceback (most recent call last):

  File "C:\Users\samvd\Documents\Master\DataSystemsProject\MaskTF2\samples\balloon\floorplan.py", line 50, in <module>
    from mrcnn import model as modellib, utils

  File "C:\Users\samvd\Documents\Master\DataSystemsProject\MaskTF2\mrcnn\model.py", line 19, in <module>
    import tensorflow as tf

ModuleNotFoundError: No module named 'tensorflow'`
```

I am trying to run the code in an anaconda environment (called _mask_) with the following packages installed:
```
tensorflow                2.0.0           gpu_py36hfdd5754_0
tensorflow-base           2.0.0           gpu_py36h390e234_0
tensorflow-estimator      2.0.0              pyh2649769_0
tensorflow-gpu            2.0.0                h0d30ee6_0
```

Does anybody know why this error appears? As it is clear I have installed tensorflow in my environment.

**Comment by Isamalatby** [comment]
have same problem with this
SyntaxWarning: "is" with a literal. Did you mean "=="?
  if os.name is 'nt':
guys, any help ?

**Comment by doilion** [comment]
I also has this problem.
