### ISSUE TITLE
ValueError: Tensor conversion requested dtype float32_ref for Tensor with dtype float32: <tf.Tensor 'training/SGD/SGD/fpn_c5p5/kernel/momentum/Initializer/zeros:0' shape=(1, 1, 2048, 256) dtype=float32>

### ISSUE THREAD

**Issue by LalinduWenasara** [matterport/Mask_RCNN#2490]
i am running on google colab ,keras==2.2.5 ,tensorflow_version 1.x   can anyone help me to fix this error 

Starting at epoch 0. LR=0.001

Checkpoint Path: /content/drive/MyDrive/mask/MaskRCNN/logs/object20210223T1300/mask_rcnn_object_{epoch:04d}.h5
Selecting layers to train
fpn_c5p5               (Conv2D)
fpn_c4p4               (Conv2D)
fpn_c3p3               (Conv2D)
fpn_c2p2               (Conv2D)
fpn_p5                 (Conv2D)
fpn_p2                 (Conv2D)
fpn_p3                 (Conv2D)
fpn_p4                 (Conv2D)
In model:  rpn_model
    rpn_conv_shared        (Conv2D)
    rpn_class_raw          (Conv2D)
    rpn_bbox_pred          (Conv2D)
mrcnn_mask_conv1       (TimeDistributed)
mrcnn_mask_bn1         (TimeDistributed)
mrcnn_mask_conv2       (TimeDistributed)
mrcnn_mask_bn2         (TimeDistributed)
mrcnn_class_conv1      (TimeDistributed)
mrcnn_class_bn1        (TimeDistributed)
mrcnn_mask_conv3       (TimeDistributed)
mrcnn_mask_bn3         (TimeDistributed)
mrcnn_class_conv2      (TimeDistributed)
mrcnn_class_bn2        (TimeDistributed)
mrcnn_mask_conv4       (TimeDistributed)
mrcnn_mask_bn4         (TimeDistributed)
mrcnn_bbox_fc          (TimeDistributed)
mrcnn_mask_deconv      (TimeDistributed)
mrcnn_class_logits     (TimeDistributed)
mrcnn_mask             (TimeDistributed)
/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/indexed_slices.py:424: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/indexed_slices.py:424: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/indexed_slices.py:424: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
WARNING:tensorflow:From /tensorflow-1.15.2/python3.6/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Traceback (most recent call last):
  File "/content/drive/MyDrive/mask/custom.py", line 198, in <module>
    train(model)			
  File "/content/drive/MyDrive/mask/custom.py", line 181, in train
    layers='heads')
  File "/content/drive/MyDrive/mask/mrcnn/model.py", line 2374, in train
    use_multiprocessing=True,
  File "/usr/local/lib/python3.6/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1658, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training_generator.py", line 42, in fit_generator
    model._make_train_function()
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 512, in _make_train_function
    loss=self.total_loss)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/keras/optimizer_v2/optimizer_v2.py", line 504, in get_updates
    return [self.apply_gradients(grads_and_vars)]
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/keras/optimizer_v2/optimizer_v2.py", line 433, in apply_gradients
    self._create_slots(var_list)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/keras/optimizer_v2/gradient_descent.py", line 100, in _create_slots
    self.add_slot(var, "momentum")
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/keras/optimizer_v2/optimizer_v2.py", line 585, in add_slot
    initial_value=initial_value)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/ops/variables.py", line 260, in __call__
    return cls._variable_v2_call(*args, **kwargs)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/ops/variables.py", line 254, in _variable_v2_call
    shape=shape)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/ops/variables.py", line 235, in <lambda>
    previous_getter = lambda **kws: default_variable_creator_v2(None, **kws)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/ops/variable_scope.py", line 2552, in default_variable_creator_v2
    shape=shape)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/ops/variables.py", line 262, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/ops/resource_variable_ops.py", line 1406, in __init__
    distribute_strategy=distribute_strategy)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/ops/resource_variable_ops.py", line 1538, in _init_from_args
    name="initial_value", dtype=dtype)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/ops.py", line 1184, in convert_to_tensor
    return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/ops.py", line 1242, in convert_to_tensor_v2
    as_ref=False)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/ops.py", line 1273, in internal_convert_to_tensor
    (dtype.name, value.dtype.name, value))
ValueError: Tensor conversion requested dtype float32_ref for Tensor with dtype float32: <tf.Tensor 'training/SGD/SGD/fpn_c5p5/kernel/momentum/Initializer/zeros:0' shape=(1, 1, 2048, 256) dtype=float32>

**Comment by AndySung320** [comment]
try using keras==2.2.4

**Comment by ronithsaju** [comment]
I replaced `%tensorflow_version 1.x` in my code with `!pip install tensorflow==1.15.5` and the error disappeared. Not limited to just version 1.15.5, it works for some other TensorFlow version 1s as well.
