### ISSUE TITLE
rror: (-215:Assertion failed) |  StopIteration: 

### ISSUE THREAD

**Issue by MLHafizur** [matterport/Mask_RCNN#2526]
Getting following error while training MRCNN 0.1 on custom dataset. Please help.

```
AssertionError: Assertion failed.
warning: source train not part of our classes, delegating to parent.
ERROR:root:Error processing image {'id': 'WIN_20210301_16_29_09_Pro.jpg', 'source': 'train', 'path': '/content/gdrive/MyDrive/vgg_promark/Image_Segmentation/train/train/WIN_20210301_16_29_09_Pro.jpg', 'width': 1280, 'height': 720, 'polygons': [{'name': 'polygon', 'all_points_x': [1175, 1180, 1214, 1233, 1241, 1239, 1229, 1205], 'all_points_y': [447, 466, 466, 467, 456, 445, 444, 444]}, {'name': 'polygon', 'all_points_x': [1141, 1162, 1211, 1229, 1245, 1256, 1267, 1267, 1276, 1279, 1279, 1260, 1243, 1198, 1180, 1174, 1164, 1161, 1120, 1103, 1073, 1066, 1054, 1041, 1026, 1022, 1026, 1040, 1052, 1058, 1059], 'all_points_y': [408, 398, 403, 404, 402, 395, 393, 404, 417, 430, 434, 438, 440, 441, 441, 441, 443, 443, 447, 447, 447, 447, 447, 451, 456, 442, 434, 411, 407, 406, 406]}], 'r_object_name': ['Copper', 'Belmouth']}
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mrcnn/model.py", line 1704, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/usr/local/lib/python3.7/dist-packages/mrcnn/model.py", line 1261, in load_image_gt
    hooks=imgaug.HooksImages(activator=hook))
  File "/usr/local/lib/python3.7/dist-packages/imgaug/augmenters/meta.py", line 470, in augment_image
    return self.augment_images([image], hooks=hooks)[0]
  File "/usr/local/lib/python3.7/dist-packages/imgaug/augmenters/meta.py", line 603, in augment_images
    hooks=hooks
  File "/usr/local/lib/python3.7/dist-packages/imgaug/augmenters/meta.py", line 2816, in _augment_images
    hooks=hooks
  File "/usr/local/lib/python3.7/dist-packages/imgaug/augmenters/meta.py", line 603, in augment_images
    hooks=hooks
  File "/usr/local/lib/python3.7/dist-packages/imgaug/augmenters/geometric.py", line 620, in _augment_images
    shear_samples, cval_samples, mode_samples, order_samples)
  File "/usr/local/lib/python3.7/dist-packages/imgaug/augmenters/geometric.py", line 689, in _augment_images_by_samples
    return_matrix=return_matrices,
  File "/usr/local/lib/python3.7/dist-packages/imgaug/augmenters/geometric.py", line 956, in _warp_cv2
    borderValue=cval
cv2.error: OpenCV(4.1.2) /io/opencv/modules/imgproc/src/imgwarp.cpp:2594: error: (-215:Assertion failed) src.cols > 0 && src.rows > 0 in function 'warpAffine'

Process Process-3:
---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
<ipython-input-29-616aafa67c99> in <module>()
----> 1 history = train(model, dataset_path, 5)

3 frames
<ipython-input-24-352f85fcab2e> in train(model, dataset_path, epochs)
     18                 epochs=epochs,
     19                 layers='heads',
---> 20                 augmentation=seq_of_aug
     21                 )
     22 

/usr/local/lib/python3.7/dist-packages/mrcnn/model.py in train(self, train_dataset, val_dataset, learning_rate, epochs, layers, augmentation)
   2350             max_queue_size=100,
   2351             workers=workers,
-> 2352             use_multiprocessing=True,
   2353         )
   2354         self.epoch = max(self.epoch, epochs)

/usr/local/lib/python3.7/dist-packages/keras/legacy/interfaces.py in wrapper(*args, **kwargs)
     85                 warnings.warn('Update your `' + object_name +
     86                               '` call to the Keras 2 API: ' + signature, stacklevel=2)
---> 87             return func(*args, **kwargs)
     88         wrapper._original_function = func
     89         return wrapper

/usr/local/lib/python3.7/dist-packages/keras/engine/training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   2009                 batch_index = 0
   2010                 while steps_done < steps_per_epoch:
-> 2011                     generator_output = next(output_generator)
   2012 
   2013                     if not hasattr(generator_output, '__len__'):

StopIteration: 
```

**Comment by TimNagle-McNaughton** [comment]
Check this? 

https://github.com/MaybeShewill-CV/CRNN_Tensorflow/issues/33
