### ISSUE TITLE
TypeError: Could not build a TypeSpec for <KerasTensor: shape=(None, None, 4) dtype=float32 (created by layer 'tf.math.truediv')> with type KerasTensor

### ISSUE THREAD

**Issue by Wizya** [matterport/Mask_RCNN#2557]
I got this error while trying to execute this command:
`python3 balloon.py train --dataset=/path/to/balloon/dataset --weights=last`

```
Traceback (most recent call last):
  File "balloon.py", line 330, in <module>
    model = modellib.MaskRCNN(mode="training", config=config,
  File "C:\Users\wiz\AppData\Roaming\Python\Python38\site-packages\mrcnn\model.py", line 1832, in __init__
    self.keras_model = self.build(mode=mode, config=config)
  File "C:\Users\wiz\AppData\Roaming\Python\Python38\site-packages\mrcnn\model.py", line 1870, in build
    gt_boxes = KL.Lambda(lambda x: norm_boxes_graph(
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 951, in __call__
    return self._functional_construction_call(inputs, args, kwargs,
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1090, in _functional_construction_call
    outputs = self._keras_tensor_symbolic_call(
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 822, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 868, in _infer_output_signature
    outputs = nest.map_structure(
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\util\nest.py", line 659, in map_structure
    structure[0], [func(*x) for x in entries],
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\util\nest.py", line 659, in <listcomp>
    structure[0], [func(*x) for x in entries],
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\keras_tensor.py", line 606, in keras_tensor_from_tensor
    out = keras_tensor_cls.from_tensor(tensor)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\keras_tensor.py", line 205, in from_tensor
    type_spec = type_spec_module.type_spec_from_value(tensor)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\type_spec.py", line 553, in type_spec_from_value
    raise TypeError("Could not build a TypeSpec for %r with type %s" %
TypeError: Could not build a TypeSpec for <KerasTensor: shape=(None, None, 4) dtype=float32 (created by layer 'tf.math.truediv')> with type [KerasTensor]
```

[out.txt](https://github.com/matterport/Mask_RCNN/files/6426809/out.txt)
Help me

**Comment by Wizya** [comment]
Now I have changed the libraries and now I have this error
```
  File "balloon.py", line 330, in <module>
    model = modellib.MaskRCNN(mode="training", config=config,
  File "C:\Users\wiz\AppData\Roaming\Python\Python38\site-packages\mrcnn\model.py", line 1832, in __init__
    self.keras_model = self.build(mode=mode, config=config)
  File "C:\Users\wiz\AppData\Roaming\Python\Python38\site-packages\mrcnn\model.py", line 1929, in build
    anchors = KL.Lambda(lambda x: tf.Variable(anchors), name="anchors")(input_image)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 925, in __call__
    return self._functional_construction_call(inputs, args, kwargs,
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1117, in _functional_construction_call
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\layers\core.py", line 904, in call
    self._check_variables(created_variables, tape.watched_variables())
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\layers\core.py", line 931, in _check_variables
    raise ValueError(error_str)
ValueError:
The following Variables were created within a Lambda layer (anchors)
but are not tracked by said layer:
  <tf.Variable 'anchors/Variable:0' shape=(2, 261888, 4) dtype=float32>
The layer cannot safely ensure proper Variable reuse across multiple
calls, and consquently this behavior is disallowed for safety. Lambda
layers are not well suited to stateful computation; instead, writing a
subclassed Layer is the recommend way to define layers with
Variables.
```

**Comment by bathibabud** [comment]
I am also facing the same issue. Can you please share what is changed?
