### ISSUE TITLE
"IndexError: list index out of range"

### ISSUE THREAD

**Issue by pra-dan** [matterport/Mask_RCNN#2561]
I use the current setup:

### Hardware:
- i7 based Acer system
- NVIDIA GEFORCE RTX
- NVIDIA Jetson Xavier (target)

### Software:
- Ubuntu 18.04
- TensorRT v7.2.2
- CUDA Version 10.2.89 
- cuDNN v8.1.1 
- GNU make >= v4.1
- cmake >= v3.13
- Python 3.6.5
- Uff 0.6.9
- graphsurgeon

---

## Attempt 1

 I followed the steps given in [sampleUffMaskRCNN README](https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/sampleUffMaskRCNN#generating-uff-model) and went on modifying the `conv2d_transpose` function in `/usr/lib/python3.6/dist-packages/uff/converters/tensorflow/converter_functions.py`. I also applied the `0001-Update-the-Mask_RCNN-model-from-NHWC-to-NCHW.patch` patch. 

For test, I used the same sample model provided in the instructions. In short, I replicated all the steps. 

The `config.py` and `model.py` I used, have been attached below 
[model_and_config_files.zip](https://github.com/matterport/Mask_RCNN/files/6449753/model_and_config_files.zip)

I get the error ending with: 
```console
Converting to UFF graph
Traceback (most recent call last):
  File "mrcnn_to_trt_single.py", line 164, in <module>
    main()
  File "mrcnn_to_trt_single.py", line 123, in main
    text=True, list_nodes=list_nodes)
  File "mrcnn_to_trt_single.py", line 157, in convert_model
    debug_mode = False
  File "/home/hotify/trt_sample_try/trt_sample/lib/python3.6/site-packages/uff/converters/tensorflow/conversion_helpers.py", line 276, in from_tensorflow_frozen_model
    return from_tensorflow(graphdef, output_nodes, preprocessor, **kwargs)
  File "/home/hotify/trt_sample_try/trt_sample/lib/python3.6/site-packages/uff/converters/tensorflow/conversion_helpers.py", line 225, in from_tensorflow
    debug_mode=debug_mode)
  File "/home/hotify/trt_sample_try/trt_sample/lib/python3.6/site-packages/uff/converters/tensorflow/converter.py", line 141, in convert_tf2uff_graph
    uff_graph, input_replacements, debug_mode=debug_mode)
  File "/home/hotify/trt_sample_try/trt_sample/lib/python3.6/site-packages/uff/converters/tensorflow/converter.py", line 126, in convert_tf2uff_node
    op, name, tf_node, inputs, uff_graph, tf_nodes=tf_nodes, debug_mode=debug_mode)
  File "/home/hotify/trt_sample_try/trt_sample/lib/python3.6/site-packages/uff/converters/tensorflow/converter.py", line 94, in convert_layer
    return cls.registry_[op](name, tf_node, inputs, uff_graph, **kwargs)
  File "/home/hotify/trt_sample_try/trt_sample/lib/python3.6/site-packages/uff/converters/tensorflow/converter_functions.py", line 87, in convert_add
    uff_graph.binary(inputs[0], inputs[1], 'add', name)
IndexError: list index out of range
```

How is it possible that the README leads to such common error. I found other people experiencing the same troubles [here](https://forums.developer.nvidia.com/t/error-in-converting-the-h5-model-to-the-uff-model-tensorrt-samples-opensource-sampleuffmaskrcnn-converted/108160/11).

**Comment by TimNagle-McNaughton** [comment]
This is really a tensorflow problem, since the error is coming from your tf package. Not sure how the maintainers of this repo would solve someone else's conversion.
