### ISSUE TITLE
Tensorflow / Keras Google Colab dependency problems `AttributeError: module 'tensorflow._api.v1.compat.v2' has no attribute '__internal__'`

### ISSUE THREAD

**Issue by bhsnada** [matterport/Mask_RCNN#2574]
I have running a MASK RCNN Model with tensorflow 1.15 and keras 2.1.6 every thing worked correctly but today when I want to run it again I get this error "module 'tensorflow._api.v1.compat.v2' has no attribute 'internal'"

![image](https://user-images.githubusercontent.com/33868302/119622590-92b02d00-be07-11eb-939e-42c0fdb3a6e6.png)

**Comment by aaronadb** [comment]
Even I am facing the same problem, the code was working fine yesterday but today for some reason Google Colab gives this error

**Comment by bhsnada** [comment]
> Even I am facing the same problem, the code was working fine yesterday but today for some reason Google Colab gives this error

Hello @aaronadb  if you find a solution inform me please I will appreciate your help

**Comment by peppyguy** [comment]
Me to facing the same issue......

**Comment by ddm06** [comment]
I have the same problem.

**Comment by francycar** [comment]
I have the same problem from yesterday and I have not found any solution.

**Comment by bhsnada** [comment]
> I have the same problem from yesterday and I have not found any solution.

Me  too I didn't find a solution, I am blocked :/

**Comment by paolopac** [comment]
I've got the same problem.
Yesterday no problem, today this error, without making changes to the code.
Thanks

**Comment by bhsnada** [comment]
> I've got the same problem.
> Yesterday no problem, today this error, without making changes to the code.
> Thanks

The same problem yesterday everything is Ok, but today I can't run mun code I am looking to find a solution

**Comment by QuanNguyenAUT** [comment]
Hi guys, I have the same issue. I managed to find out what happens but it's unsuccessful. When I try to do with various versions of Keras and TensorFlow, I get different error announcements. Have you fixed? Please let me know. Thanks a lot.

**Comment by peppyguy** [comment]
Guys I am tried with in build tensorflow/magic function of tensorflow 1x with different versions of keras but ended with some errors...If it is fixed please let us know

**Comment by nastaran-Ahmadi** [comment]
same here :(

**Comment by QuanNguyenAUT** [comment]
I don't know this issue comes from Keras, TF or Colab, or whatever

**Comment by nastaran-Ahmadi** [comment]
I tried to run my code on my machine, same error. so I think the issue hasn't caused by colab

**Comment by bhsnada** [comment]
I solved the problem when I try to  :

!pip uninstall keras-nightly
pip uninstall -y tensorflow 

and then install tensorflow and kerass with version you want to use

**Comment by nastaran-Ahmadi** [comment]
> 
> 
> I solved the problem when I try to :
> 
> !pip uninstall keras-nightly
> pip uninstall -y tensorflow
> 
> and then install tensorflow and kerass with version you want to use

could you please share keras and tensorflow version that you are using?

**Comment by bhsnada** [comment]
> > I solved the problem when I try to :
> > !pip uninstall keras-nightly
> > pip uninstall -y tensorflow
> > and then install tensorflow and kerass with version you want to use
> 
> could you please share keras and tensorflow version that you are using?

pip install tensorflow-gpu==1.15.0 
pip install keras==2.1.6

**Comment by peppyguy** [comment]
After Uninstalling using

!pip uninstall keras-nightly
!pip uninstall -y tensorflow

and Installing my required versions tensorflow == 1.15.0 and keras == 2.2.5 , while training i got below error

**Traceback (most recent call last):
  File "beagle.py", line 397, in <module>
    "mrcnn_bbox", "mrcnn_mask"])
  File "/usr/local/lib/python3.7/dist-packages/mask_rcnn-2.1-py3.7.egg/mrcnn/model.py", line 2130, in load_weights
  File "/usr/local/lib/python3.7/dist-packages/keras/engine/saving.py", line 1224, in load_weights_from_hdf5_group_by_name
    original_keras_version = f.attrs['keras_version'].decode('utf8')
 
<ctrl+b>**AttributeError: 'str' object has no attribute 'decode'**** <ctrl+b>




 
<ctrl+b>..................More details of error are below...............<ctrl+b>


Using TensorFlow backend.
Weights:  coco
Dataset:  beagle
Logs:  /content/logs

Configurations:
BACKBONE                       resnet101
BACKBONE_STRIDES               [4, 8, 16, 32, 64]
BATCH_SIZE                     2
BBOX_STD_DEV                   [0.1 0.1 0.2 0.2]
COMPUTE_BACKBONE_SHAPE         None
DETECTION_MAX_INSTANCES        100
DETECTION_MIN_CONFIDENCE       0.9
DETECTION_NMS_THRESHOLD        0.3
FPN_CLASSIF_FC_LAYERS_SIZE     1024
GPU_COUNT                      1
GRADIENT_CLIP_NORM             5.0
IMAGES_PER_GPU                 2
IMAGE_CHANNEL_COUNT            3
IMAGE_MAX_DIM                  1024
IMAGE_META_SIZE                19
IMAGE_MIN_DIM                  800
IMAGE_MIN_SCALE                0
IMAGE_RESIZE_MODE              square
IMAGE_SHAPE                    [1024 1024    3]
LEARNING_MOMENTUM              0.9
LEARNING_RATE                  0.001
LOSS_WEIGHTS                   {'rpn_class_loss': 1.0, 'rpn_bbox_loss': 1.0, 'mrcnn_class_loss': 1.0, 'mrcnn_bbox_loss': 1.0, 'mrcnn_mask_loss': 1.0}
MASK_POOL_SIZE                 14
MASK_SHAPE                     [28, 28]
MAX_GT_INSTANCES               100
MEAN_PIXEL                     [123.7 116.8 103.9]
MINI_MASK_SHAPE                (56, 56)
NAME                           beagle
NUM_CLASSES                    7
POOL_SIZE                      7
POST_NMS_ROIS_INFERENCE        1000
POST_NMS_ROIS_TRAINING         2000
PRE_NMS_LIMIT                  6000
ROI_POSITIVE_RATIO             0.33
RPN_ANCHOR_RATIOS              [0.5, 1, 2]
RPN_ANCHOR_SCALES              (32, 64, 128, 256, 512)
RPN_ANCHOR_STRIDE              1
RPN_BBOX_STD_DEV               [0.1 0.1 0.2 0.2]
RPN_NMS_THRESHOLD              0.7
RPN_TRAIN_ANCHORS_PER_IMAGE    256
STEPS_PER_EPOCH                100
TOP_DOWN_PYRAMID_SIZE          256
TRAIN_BN                       False
TRAIN_ROIS_PER_IMAGE           200
USE_MINI_MASK                  True
USE_RPN_ROIS                   True
VALIDATION_STEPS               50
WEIGHT_DECAY                   0.0001


WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/keras/backend/tensorflow_backend.py:541: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/keras/backend/tensorflow_backend.py:66: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/keras/backend/tensorflow_backend.py:4432: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/keras/backend/tensorflow_backend.py:2139: The name tf.nn.fused_batch_norm is deprecated. Please use tf.compat.v1.nn.fused_batch_norm instead.

WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/keras/backend/tensorflow_backend.py:4267: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/keras/backend/tensorflow_backend.py:2239: The name tf.image.resize_nearest_neighbor is deprecated. Please use tf.compat.v1.image.resize_nearest_neighbor instead.

WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensorflow_core/python/ops/array_ops.py:1475: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/mask_rcnn-2.1-py3.7.egg/mrcnn/model.py:553: The name tf.random_shuffle is deprecated. Please use tf.random.shuffle instead.

WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/mask_rcnn-2.1-py3.7.egg/mrcnn/utils.py:202: The name tf.log is deprecated. Please use tf.math.log instead.

WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/mask_rcnn-2.1-py3.7.egg/mrcnn/model.py:600: calling crop_and_resize_v1 (from tensorflow.python.ops.image_ops_impl) with box_ind is deprecated and will be removed in a future version.
Instructions for updating:
box_ind is deprecated, use box_indices instead
Downloading pretrained model to /content/mask_rcnn_coco.h5 ...
... done downloading pretrained model!
Loading weights  /content/mask_rcnn_coco.h5
Traceback (most recent call last):
  File "beagle.py", line 397, in <module>
    "mrcnn_bbox", "mrcnn_mask"])
  File "/usr/local/lib/python3.7/dist-packages/mask_rcnn-2.1-py3.7.egg/mrcnn/model.py", line 2130, in load_weights
  File "/usr/local/lib/python3.7/dist-packages/keras/engine/saving.py", line 1224, in load_weights_from_hdf5_group_by_name
    original_keras_version = f.attrs['keras_version'].decode('utf8')
AttributeError: 'str' object has no attribute 'decode'

**Comment by bhsnada** [comment]
> After Uninstalling using
> 
> !pip uninstall keras-nightly
> !pip uninstall -y tensorflow
> 
> and Installing my required versions tensorflow == 1.15.0 and keras == 2.2.5 , while training i got below error
> 
> **Traceback (most recent call last):
> File "beagle.py", line 397, in
> "mrcnn_bbox", "mrcnn_mask"])
> File "/usr/local/lib/python3.7/dist-packages/mask_rcnn-2.1-py3.7.egg/mrcnn/model.py", line 2130, in load_weights
> File "/usr/local/lib/python3.7/dist-packages/keras/engine/saving.py", line 1224, in load_weights_from_hdf5_group_by_name
> original_keras_version = f.attrs['keras_version'].decode('utf8')
> 
> <ctrl+b>**AttributeError: 'str' object has no attribute 'decode'**** <ctrl+b>
> 
> <ctrl+b>..................More details of error are below...............<ctrl+b>
> 
> Using TensorFlow backend.
> Weights: coco
> Dataset: beagle
> Logs: /content/logs
> 
> Configurations:
> BACKBONE resnet101
> BACKBONE_STRIDES [4, 8, 16, 32, 64]
> BATCH_SIZE 2
> BBOX_STD_DEV [0.1 0.1 0.2 0.2]
> COMPUTE_BACKBONE_SHAPE None
> DETECTION_MAX_INSTANCES 100
> DETECTION_MIN_CONFIDENCE 0.9
> DETECTION_NMS_THRESHOLD 0.3
> FPN_CLASSIF_FC_LAYERS_SIZE 1024
> GPU_COUNT 1
> GRADIENT_CLIP_NORM 5.0
> IMAGES_PER_GPU 2
> IMAGE_CHANNEL_COUNT 3
> IMAGE_MAX_DIM 1024
> IMAGE_META_SIZE 19
> IMAGE_MIN_DIM 800
> IMAGE_MIN_SCALE 0
> IMAGE_RESIZE_MODE square
> IMAGE_SHAPE [1024 1024 3]
> LEARNING_MOMENTUM 0.9
> LEARNING_RATE 0.001
> LOSS_WEIGHTS {'rpn_class_loss': 1.0, 'rpn_bbox_loss': 1.0, 'mrcnn_class_loss': 1.0, 'mrcnn_bbox_loss': 1.0, 'mrcnn_mask_loss': 1.0}
> MASK_POOL_SIZE 14
> MASK_SHAPE [28, 28]
> MAX_GT_INSTANCES 100
> MEAN_PIXEL [123.7 116.8 103.9]
> MINI_MASK_SHAPE (56, 56)
> NAME beagle
> NUM_CLASSES 7
> POOL_SIZE 7
> POST_NMS_ROIS_INFERENCE 1000
> POST_NMS_ROIS_TRAINING 2000
> PRE_NMS_LIMIT 6000
> ROI_POSITIVE_RATIO 0.33
> RPN_ANCHOR_RATIOS [0.5, 1, 2]
> RPN_ANCHOR_SCALES (32, 64, 128, 256, 512)
> RPN_ANCHOR_STRIDE 1
> RPN_BBOX_STD_DEV [0.1 0.1 0.2 0.2]
> RPN_NMS_THRESHOLD 0.7
> RPN_TRAIN_ANCHORS_PER_IMAGE 256
> STEPS_PER_EPOCH 100
> TOP_DOWN_PYRAMID_SIZE 256
> TRAIN_BN False
> TRAIN_ROIS_PER_IMAGE 200
> USE_MINI_MASK True
> USE_RPN_ROIS True
> VALIDATION_STEPS 50
> WEIGHT_DECAY 0.0001
> 
> WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/keras/backend/tensorflow_backend.py:541: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.
> 
> WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/keras/backend/tensorflow_backend.py:66: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.
> 
> WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/keras/backend/tensorflow_backend.py:4432: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.
> 
> WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/keras/backend/tensorflow_backend.py:2139: The name tf.nn.fused_batch_norm is deprecated. Please use tf.compat.v1.nn.fused_batch_norm instead.
> 
> WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/keras/backend/tensorflow_backend.py:4267: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.
> 
> WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/keras/backend/tensorflow_backend.py:2239: The name tf.image.resize_nearest_neighbor is deprecated. Please use tf.compat.v1.image.resize_nearest_neighbor instead.
> 
> WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensorflow_core/python/ops/array_ops.py:1475: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use tf.where in 2.0, which has the same broadcast rule as np.where
> WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/mask_rcnn-2.1-py3.7.egg/mrcnn/model.py:553: The name tf.random_shuffle is deprecated. Please use tf.random.shuffle instead.
> 
> WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/mask_rcnn-2.1-py3.7.egg/mrcnn/utils.py:202: The name tf.log is deprecated. Please use tf.math.log instead.
> 
> WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/mask_rcnn-2.1-py3.7.egg/mrcnn/model.py:600: calling crop_and_resize_v1 (from tensorflow.python.ops.image_ops_impl) with box_ind is deprecated and will be removed in a future version.
> Instructions for updating:
> box_ind is deprecated, use box_indices instead
> Downloading pretrained model to /content/mask_rcnn_coco.h5 ...
> ... done downloading pretrained model!
> Loading weights /content/mask_rcnn_coco.h5
> Traceback (most recent call last):
> File "beagle.py", line 397, in
> "mrcnn_bbox", "mrcnn_mask"])
> File "/usr/local/lib/python3.7/dist-packages/mask_rcnn-2.1-py3.7.egg/mrcnn/model.py", line 2130, in load_weights
> File "/usr/local/lib/python3.7/dist-packages/keras/engine/saving.py", line 1224, in load_weights_from_hdf5_group_by_name
> original_keras_version = f.attrs['keras_version'].decode('utf8')
> AttributeError: 'str' object has no attribute 'decode'

try with keras 2.1.6

**Comment by peppyguy** [comment]
@bhsnada 

The same issue repeats again after using keras 2.1.6


Traceback (most recent call last):
  File "beagle.py", line 397, in <module>
    "mrcnn_bbox", "mrcnn_mask"])
  File "/usr/local/lib/python3.7/dist-packages/mask_rcnn-2.1-py3.7.egg/mrcnn/model.py", line 2130, in load_weights
  File "/usr/local/lib/python3.7/dist-packages/keras/engine/topology.py", line 3418, in load_weights_from_hdf5_group_by_name
    original_keras_version = f.attrs['keras_version'].decode('utf8')
AttributeError: 'str' object has no attribute 'decode'

**Comment by peppyguy** [comment]
Issue sorted by downgrading  h5py to 2.10.0
@bhsnada

**Comment by QuanNguyenAUT** [comment]
@peppyguy, Could you detail it? only downgrading h5py or anything else?  Thanks

**Comment by nastaran-Ahmadi** [comment]
> 
> 
> > > I solved the problem when I try to :
> > > !pip uninstall keras-nightly
> > > pip uninstall -y tensorflow
> > > and then install tensorflow and kerass with version you want to use
> > 
> > 
> > could you please share keras and tensorflow version that you are using?
> 
> pip install tensorflow-gpu==1.15.0
> pip install keras==2.1.6

thanks a lot! worked for me.

**Comment by peppyguy** [comment]
> 
> 
> @peppyguy, Could you detail it? only downgrading h5py or anything else? Thanks

After following the steps suggested by @bhsnada , I downgraded the version of h5py to 2.10.0 then it works
Thanks @bhsnada

**Comment by QuanNguyenAUT** [comment]
Thank you so much, @peppyguy and @bhsnada 
Now it works fine

**Comment by dariodellamura** [comment]
For no tensorflow-gpu version, how can i fix It? Thanka for tour help.

**Comment by ddm06** [comment]
If you don't use tensorflow-gpu, try this tensorflow 1.14, keras 2.1.5 and h5py 2.10.0 (works for me)

**Comment by paolopac** [comment]
> I solved the problem when I try to :
> 
> !pip uninstall keras-nightly
> pip uninstall -y tensorflow
> 
> and then install tensorflow and kerass with version you want to use

Fixed, for me!
I added:
!pip uninstall h5py
!pip install h5py==2.10.0

Thanks so much

**Comment by ronithsaju** [comment]
```
!pip uninstall keras-nightly
!pip install h5py==2.10.0
```
I added this to the top of my code and the problem is now solved

**Comment by denashamss** [comment]
I added the code below in the beginning part and
!pip uninstall keras-nightly
!pip install h5py==2.10.0
then 
!pip uninstall keras-nightly
!pip uninstall keras
then 
!pip install keras==2.1.6
%tensorflow_version 1.x #this version is for google colab
and then probem is solved

**Comment by jasminjahanpuspo** [comment]
Hello, I also faced the same problem. But I got stuck when unstalling keras-nighty on colab. What to type on colab? 
1) --yes
2) -y
3)y

![10Capture](https://user-images.githubusercontent.com/51731547/120028052-fd36b800-c015-11eb-9d7f-093c1ee77f5b.PNG)

 Thanks in advance.

**Comment by denashamss** [comment]
just type y

**Comment by denashamss** [comment]
> Hello, I also faced the same problem. But I got stuck when unstalling keras-nighty on colab. What to type on colab?
> 
> 1. --yes
> 2. -y
>    3)y
> 
> ![10Capture](https://user-images.githubusercontent.com/51731547/120028052-fd36b800-c015-11eb-9d7f-093c1ee77f5b.PNG)
> 
> Thanks in advance.

just type y and click enter

**Comment by jasminjahanpuspo** [comment]
@denashamss 
yes I type y but it didn't work.
or it takes much time?

**Comment by denashamss** [comment]
> @denashamss
> yes I type y but it didn't work.
> or it takes much time?

did you wrote y and did you press enter? it does not take more than one minute

**Comment by puspo1997** [comment]
yes i did it 
still loading this cell
I also tried to avoid this
Can you suggest me another way or just downgrad the tf or keras?

**Comment by jasminjahanpuspo** [comment]
> > @denashamss
> > yes I type y but it didn't work.
> > or it takes much time?
> 
> did you wrote y and did you press enter? it does not take more than one minute

Thanks, @denashamss

**Comment by kimile599** [comment]
> I added the code below in the beginning part and
> !pip uninstall keras-nightly
> !pip install h5py==2.10.0
> then
> !pip uninstall keras-nightly
> !pip uninstall keras
> then
> !pip install keras==2.1.6
> %tensorflow_version 1.x #this version is for google colab
> and then probem is solved

It worked for me !!!
The first time i didn't factory reset runtime and it pop up another error.
BUt when i reset the run time, it worked.

**Comment by charlie6echo** [comment]
Here is the solution
%tensorflow_version 1.x
!pip uninstall -y keras-nightly
!pip install h5py==2.10.0
!pip install keras==2.2.5 # in colab i have to run this line 2 times to get keras 2.2.5

**Comment by AndySung320** [comment]
Try using tf=1.15.2
Keras=2.2.4
Python =3.6

**Comment by nataliameira** [comment]
Do you install this version (tf, keras, python and h5py) before or after requirements.txt?

**Comment by kimile599** [comment]
> Do you install this version (tf, keras, python and h5py) before or after requirements.txt?

after, otherwise it will install the newer version.

**Comment by arviinnd-5989** [comment]
!pip uninstall keras-nightly
!pip uninstall -y tensorflow
!pip install h5py=2.10.0

!pip install tensorflow-gpu==1.15.3
!pip install keras==2.2.4

Solved the issue for me. Thanks @bhsnada

**Comment by nataliameira** [comment]
Hey
I trained my model and visualized the data.
My training was held on June 3, 2021.
I used:

pip uninstall keras-nightly
pip uninstall -y tensorflow
h5py==2.10.0
tensorflow==1.15
tensorflow-gpu==1.15.0
keras==2.1.6

**Comment by pavpanda** [comment]
> Hey
> I trained my model and visualized the data.
> My training was held on June 3, 2021.
> I used:
> 
> pip uninstall keras-nightly
> pip uninstall -y tensorflow
> h5py==2.10.0
> tensorflow==1.15
> tensorflow-gpu==1.15.0
> keras==2.1.6

When I did this, I got an error message:
AttributeError: 'Model' object has no attribute 'metrics_tensors'

Any suggestions?

**Comment by sauravsolanki** [comment]
%tensorflow 1.x will fix this issue.

**Comment by marcofaga** [comment]
> Hey
> I trained my model and visualized the data.
> My training was held on June 3, 2021.
> I used:
> 
> pip uninstall keras-nightly
> pip uninstall -y tensorflow
> h5py==2.10.0
> tensorflow==1.15
> tensorflow-gpu==1.15.0
> keras==2.1.6

Worked for me to! Just have to put this line in the first cell afer start session.

**Comment by KainanSu** [comment]
> I added the code below in the beginning part and !pip uninstall keras-nightly !pip install h5py==2.10.0 then !pip uninstall keras-nightly !pip uninstall keras then !pip install keras==2.1.6 %tensorflow_version 1.x #this version is for google colab and then probem is solved

Using colab, add this to the top in demo.ipynb.

It works, and it can work **without** run `!pip3 install -r requirements.txt`
