### ISSUE TITLE
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### ISSUE THREAD

**Issue by connortran216** [matterport/Mask_RCNN#2591]
Hi every, a week ago, I trained my custom model as usually, but now it pop up this problem. 
I have tried change my tensorflow-gpu, keras, h5py,.. version as follow but nothing seem to work:
tensorflow-gpu==1.15.0
keras==2.2.5/2.1.6
h5py==2.10.0

If you have encountered this problem, please help me. Thanks for advanced.

Traceback (most recent call last):
  File "train.py", line 520, in <module>
    train(model)
  File "train.py", line 293, in train
    layers='heads')
  File "/usr/local/lib/python3.7/dist-packages/mask_rcnn-2.1-py3.7.egg/mrcnn/model.py", line 2424, in train
  File "/usr/local/lib/python3.7/dist-packages/mask_rcnn-2.1-py3.7.egg/mrcnn/model.py", line 2251, in compile
  File "/usr/local/lib/python3.7/dist-packages/mask_rcnn-2.1-py3.7.egg/mrcnn/model.py", line 2252, in <listcomp>
  File "/usr/local/lib/python3.7/dist-packages/keras/regularizers.py", line 41, in __call__
    if self.l2:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by Sunflower135** [comment]
Have you solved this problem yet?
