### ISSUE TITLE
ValueError: You are trying to load a weight file containing 233 layers into a model with 231 layers.

### ISSUE THREAD

**Issue by Nidhi397** [matterport/Mask_RCNN#2630]
I am trying to train a custom dataset with Mask RCNN.
Doing this on TF2 by using the mrcnn folder kindly open sourced by the owner of this repository: https://github.com/ahmedfgad/Mask-RCNN-TF2

But after the above change and also resolving a good number of bugs, I am getting this error:

```Loading weights  /content/drive/My Drive/Mask_RCNN/mask_rcnn_coco.h5
Traceback (most recent call last):
  File "pothole.py", line 361, in <module>
    "mrcnn_bbox", "mrcnn_mask"])
  File "/content/drive/My Drive/Mask_RCNN/mrcnn/model.py", line 2132, in load_weights
    hdf5_format.load_weights_from_hdf5_group(f, layers)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/saving/hdf5_format.py", line 686, in load_weights_from_hdf5_group
    ' layers.')
ValueError: You are trying to load a weight file containing 233 layers into a model with 231 layers.
```

Has anyone faced this error? Can anyone please guide me as to how can I solve this issue?

**Comment by CailynH** [comment]
I have the same quetion, did you solve it?

**Comment by IDW-du** [comment]
same here,help!

**Comment by chrishickey** [comment]
You might need to pass in "by_name=True" as an arg

model.load_weights(model_path, by_name=True)
