### ISSUE TITLE
Running coco.py in pycharm

### ISSUE THREAD

**Issue by swatinair123** [matterport/Mask_RCNN#276]
Hi,
I am running the code coco.py in pycharm . i have downloaded cocoapi and placed int the same directory as Mask_RCNN . this wokred for me in Jupyter notebook. But in pycharm i am getting this error as in the screenshot while importing the coco dataset. Please kindly advise . thanks in advance
![errors faced](https://user-images.githubusercontent.com/23516228/36588544-7f50992c-18ae-11e8-80e1-deb0a3caaf61.jpg)

**Comment by pratikshaandhare** [comment]
Hi, I am also facing same issue even I tried running the command "Python setup.py build_ext --inplace" for the setup file. Please help me out.

**Comment by swatinair123** [comment]
Hi, when i use the interpreter Python 3.6 (MaskRCNN) C:\Users\Swati\Anaconda\envs\Mask\python.exe
i get the following errors .
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:/Users/Swati/MaskRCNN_py/Mask_RCNN/coco.py", line 52, in <module>
    import model as modellib
  File "C:\Users\Swati\MaskRCNN_py\Mask_RCNN\model.py", line 35, in <module>
    assert LooseVersion(tf.__version__) >= LooseVersion("1.3")
AssertionError

Process finished with exit code 1

  But  when iuse the interpreters Python 3.5 C:\Users\Swati\Anaconda\envs\tensorflow\python.exe i get the above errors. Please advise

**Comment by bharathjatoth** [comment]
Looks like the same issue [https://github.com/matterport/Mask_RCNN/issues/6](url). You can try this and post your result here

**Comment by brianfarrar** [comment]
I am assuming you have already downloaded the cocapi-master and unzipped or used to git clone to obtain cocoapi-master.  Like you I am using pycharm (community edition).  I am running python 3.5.3 on mac os.

Here is what worked for me:
1) 'cd' to the cocoapi-master/PythonAPI folder
2) modify the Makefile to call the correct version of python (for me that was python3) and save 
3) type 'make'
4) when the make is complete type 'ls' and you should see a folder pycocotools
5) now type 'cp -r pycocotools to/your/project/folder'
6) verify that the cp worked and you now have this folder in your project folder

Thereafter the coco imports should work.

Hope that helps,

Brian.

**Comment by pratikshaandhare** [comment]
Hi, We tried to install pycocotools as suggested above. But we are facing the errors as in the screenshot. Please advise.

![errornew](https://user-images.githubusercontent.com/20615346/36666897-0f0271fc-1b12-11e8-9a06-2a742a999ca9.jpg)
