### ISSUE TITLE
Training custom data

### ISSUE THREAD

**Issue by Abderrahmen33** [matterport/Mask_RCNN#2841]
Hi guys, I'm facing this error when I do the training and the number of images in the val folder is 8, all the images are in JPG format, I don't understand what's happening, could you please help me?

C:\Users\Abderrahmen\PycharmProjects\pythonProject1\venv\Scripts\python.exe C:/Users/Abderrahmen/OneDrive/Bureau/Try/custom.py
C:\Users\Abderrahmen\PycharmProjects\pythonProject1\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Abderrahmen\PycharmProjects\pythonProject1\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Abderrahmen\PycharmProjects\pythonProject1\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Abderrahmen\PycharmProjects\pythonProject1\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\Abderrahmen\PycharmProjects\pythonProject1\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\Abderrahmen\PycharmProjects\pythonProject1\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
C:\Users\Abderrahmen\PycharmProjects\pythonProject1\venv\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Abderrahmen\PycharmProjects\pythonProject1\venv\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Abderrahmen\PycharmProjects\pythonProject1\venv\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Abderrahmen\PycharmProjects\pythonProject1\venv\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\Abderrahmen\PycharmProjects\pythonProject1\venv\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\Abderrahmen\PycharmProjects\pythonProject1\venv\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Using TensorFlow backend.
WARNING:tensorflow:From C:\Users\Abderrahmen\PycharmProjects\pythonProject1\venv\lib\site-packages\keras\backend\tensorflow_backend.py:541: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From C:\Users\Abderrahmen\PycharmProjects\pythonProject1\venv\lib\site-packages\keras\backend\tensorflow_backend.py:66: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From C:\Users\Abderrahmen\PycharmProjects\pythonProject1\venv\lib\site-packages\keras\backend\tensorflow_backend.py:4432: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

WARNING:tensorflow:From C:\Users\Abderrahmen\PycharmProjects\pythonProject1\venv\lib\site-packages\keras\backend\tensorflow_backend.py:2139: The name tf.nn.fused_batch_norm is deprecated. Please use tf.compat.v1.nn.fused_batch_norm instead.

WARNING:tensorflow:From C:\Users\Abderrahmen\PycharmProjects\pythonProject1\venv\lib\site-packages\keras\backend\tensorflow_backend.py:4267: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

WARNING:tensorflow:From C:\Users\Abderrahmen\PycharmProjects\pythonProject1\venv\lib\site-packages\keras\backend\tensorflow_backend.py:2239: The name tf.image.resize_nearest_neighbor is deprecated. Please use tf.compat.v1.image.resize_nearest_neighbor instead.

WARNING:tensorflow:From C:\Users\Abderrahmen\PycharmProjects\pythonProject1\venv\lib\site-packages\tensorflow\python\ops\array_ops.py:1354: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From C:\Users\Abderrahmen\OneDrive\Bureau\Try\mrcnn\model.py:553: The name tf.random_shuffle is deprecated. Please use tf.random.shuffle instead.

WARNING:tensorflow:From C:\Users\Abderrahmen\OneDrive\Bureau\Try\mrcnn\utils.py:202: The name tf.log is deprecated. Please use tf.math.log instead.

WARNING:tensorflow:From C:\Users\Abderrahmen\OneDrive\Bureau\Try\mrcnn\model.py:600: calling crop_and_resize_v1 (from tensorflow.python.ops.image_ops_impl) with box_ind is deprecated and will be removed in a future version.
Instructions for updating:
box_ind is deprecated, use box_indices instead
2022-06-07 16:21:03.602896: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
objects: ['pallet']
numids [1]
objects: ['pallet']
numids [1]
objects: ['pallet']
numids [1]
objects: ['pallet']
numids [1]
objects: ['pallet']
numids [1]
objects: ['pallet']
numids [1]
objects: ['pallet']
numids [1]
objects: ['pallet']
numids [1]
objects: ['pallet']
numids [1]
objects: ['pallet']
numids [1]
objects: ['pallet']
numids [1]
objects: ['pallet']
numids [1]
objects: ['pallet']
numids [1]
objects: ['pallet']
numids [1]
objects: ['pallet']
numids [1]
objects: ['pallet']
numids [1]
objects: ['pallet']
numids [1]
objects: ['pallet']
numids [1]
objects: ['pallet']
numids [1]
objects: ['pallet']
numids [1]
objects: ['pallet']
numids [1]
objects: ['pallet']
numids [1]
Traceback (most recent call last):
  File "C:/Users/Abderrahmen/OneDrive/Bureau/Try/custom.py", line 186, in <module>
    train(model)
  File "C:/Users/Abderrahmen/OneDrive/Bureau/Try/custom.py", line 159, in train
    dataset_val.load_custom("C:\\Users\\Abderrahmen\\OneDrive\\Bureau\\Try\\dataset", "val")
  File "C:/Users/Abderrahmen/OneDrive/Bureau/Try/custom.py", line 97, in load_custom
    image = skimage.io.imread(image_path)
  File "C:\Users\Abderrahmen\PycharmProjects\pythonProject1\venv\lib\site-packages\skimage\io\_io.py", line 48, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "C:\Users\Abderrahmen\PycharmProjects\pythonProject1\venv\lib\site-packages\skimage\io\manage_plugins.py", line 210, in call_plugin
    return func(*args, **kwargs)
  File "C:\Users\Abderrahmen\PycharmProjects\pythonProject1\venv\lib\site-packages\skimage\io\_plugins\imageio_plugin.py", line 10, in imread
    return np.asarray(imageio_imread(*args, **kwargs))
  File "C:\Users\Abderrahmen\PycharmProjects\pythonProject1\venv\lib\site-packages\imageio\__init__.py", line 97, in imread
    return imread_v2(uri, format=format, **kwargs)
  File "C:\Users\Abderrahmen\PycharmProjects\pythonProject1\venv\lib\site-packages\imageio\v2.py", line 200, in imread
    with imopen(uri, "ri", **imopen_args) as file:
  File "C:\Users\Abderrahmen\PycharmProjects\pythonProject1\venv\lib\site-packages\imageio\core\imopen.py", line 118, in imopen
    request = Request(uri, io_mode, format_hint=format_hint, extension=extension)
  File "C:\Users\Abderrahmen\PycharmProjects\pythonProject1\venv\lib\site-packages\imageio\core\request.py", line 248, in __init__
    self._parse_uri(uri)
  File "C:\Users\Abderrahmen\PycharmProjects\pythonProject1\venv\lib\site-packages\imageio\core\request.py", line 407, in _parse_uri
    raise FileNotFoundError("No such file: '%s'" % fn)
FileNotFoundError: No such file: 'C:\Users\Abderrahmen\OneDrive\Bureau\Try\dataset\val\9.jpg'

Process finished with exit code 1

**Comment by jeremiahscully** [comment]
Create an absolute file path for the validation folder. Similar to the training set file path e.g

    if subset == "train":
        annotations1 = json.load(open('/mask_r_cnn/Dataset/train/data_json.json'))
    elif subset == "val":
        annotations1 = json.load(open('D:/mask_r_cnn/Dataset/val/data_json.json'))
