### ISSUE TITLE
could anybody help?

### ISSUE THREAD

**Issue by STRUGGLE1999** [matterport/Mask_RCNN#2853]
![image](https://user-images.githubusercontent.com/66925708/178186579-5f16d045-6adf-46b0-a4b8-cbbb007691ff.png)

**Comment by Testbild** [comment]
As a strong guess I would say your image dimensions that you feed to the model and the ones the model expects are 3 pixels off (112 to 115). Do you have the chance to change them accordingly?

**Comment by STRUGGLE1999** [comment]
Thank you very much ,I have solved it.Would you please help loot at this error?
It says&nbsp;Library "GLU" not found.but I have install pyglet according to the instruction.


Traceback (most recent call last):
&nbsp; File "demo.py", line 68, in <module&gt;
&nbsp; &nbsp; visualize(renderer, original_img, params, vertices, cam, joints)
&nbsp; File "../visualise/vis_util.py", line 180, in visualize
&nbsp; &nbsp; img_overlay = renderer(vert_shifted, img=img, bg_color=np.array((255.0, 255.0, 255.0, 1)))
&nbsp; File "../visualise/trimesh_renderer.py", line 46, in __call__
&nbsp; &nbsp; image_bytes = scene.save_image(resolution=(w, h), background=bg_color, visible=True)
&nbsp; File "/home/XiaoLF/anaconda3/envs/hmr/lib/python3.6/site-packages/trimesh/scene/scene.py", line 873, in save_image
&nbsp; &nbsp; from ..viewer.windowed import render_scene
&nbsp; File "/home/XiaoLF/anaconda3/envs/hmr/lib/python3.6/site-packages/trimesh/viewer/windowed.py", line 32, in <module&gt;
&nbsp; &nbsp; import pyglet.gl as gl&nbsp; # NOQA
&nbsp; File "/home/XiaoLF/anaconda3/envs/hmr/lib/python3.6/site-packages/pyglet/gl/__init__.py", line 95, in <module&gt;
&nbsp; &nbsp; from pyglet.gl.gl import *
&nbsp; File "/home/XiaoLF/anaconda3/envs/hmr/lib/python3.6/site-packages/pyglet/gl/gl.py", line 45, in <module&gt;
&nbsp; &nbsp; from pyglet.gl.lib import link_GL as _link_function
&nbsp; File "/home/XiaoLF/anaconda3/envs/hmr/lib/python3.6/site-packages/pyglet/gl/lib.py", line 149, in <module&gt;
&nbsp; &nbsp; from pyglet.gl.lib_glx import link_GL, link_GLU, link_GLX
&nbsp; File "/home/XiaoLF/anaconda3/envs/hmr/lib/python3.6/site-packages/pyglet/gl/lib_glx.py", line 46, in <module&gt;
&nbsp; &nbsp; glu_lib = pyglet.lib.load_library('GLU')
&nbsp; File "/home/XiaoLF/anaconda3/envs/hmr/lib/python3.6/site-packages/pyglet/lib.py", line 168, in load_library
&nbsp; &nbsp; raise ImportError('Library "%s" not found.' % names[0])
ImportError: Library "GLU" not found.
(hmr) ***@***.*** visualise]$ pip install pyglet
Requirement already satisfied: pyglet in /home/XiaoLF/anaconda3/envs/hmr/lib/python3.6/site-packages (1.5.26)






***@***.***







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "matterport/Mask_RCNN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月14日(星期四) 下午4:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [matterport/Mask_RCNN] could anybody help? (Issue #2853)





 
As a strong guess I would say your image dimensions that you feed to the model and the ones the model expects are 3 pixels off (112 to 115). Do you have the chance to change them accordingly?
