### ISSUE TITLE
ERROR:root: Error processing image. 

### ISSUE THREAD

**Issue by yaoli1haoji** [matterport/Mask_RCNN#2903]
Hi, I am trying to run Maskrcnn on my custom dataset. I have the following issue in the training step. My images are 6000 X 4000 pixels. I am wondering whether it is due to the shape being incompatible with the default configuration 

Here is the config 

Configurations:
BACKBONE                       resnet101
BACKBONE_STRIDES               [4, 8, 16, 32, 64]
BATCH_SIZE                     1
BBOX_STD_DEV                   [0.1 0.1 0.2 0.2]
COMPUTE_BACKBONE_SHAPE         None
DETECTION_MAX_INSTANCES        100
DETECTION_MIN_CONFIDENCE       0.7
DETECTION_NMS_THRESHOLD        0.3
FPN_CLASSIF_FC_LAYERS_SIZE     1024
GPU_COUNT                      1
GRADIENT_CLIP_NORM             5.0
IMAGES_PER_GPU                 1
IMAGE_CHANNEL_COUNT            3
IMAGE_MAX_DIM                  1024
IMAGE_META_SIZE                15
IMAGE_MIN_DIM                  800
IMAGE_MIN_SCALE                0
IMAGE_RESIZE_MODE              square
IMAGE_SHAPE                    [1024 1024    3]
LEARNING_MOMENTUM              0.9
LEARNING_RATE                  0.001
LOSS_WEIGHTS                   {'rpn_class_loss': 1.0, 'rpn_bbox_loss': 1.0, 'mrcnn_class_loss': 1.0, 'mrcnn_bbox_loss': 1.0, 'mrcnn_mask_loss': 1.0}
MASK_POOL_SIZE                 14
MASK_SHAPE                     [28, 28]
MAX_GT_INSTANCES               100
MEAN_PIXEL                     [123.7 116.8 103.9]
MINI_MASK_SHAPE                (56, 56)
NAME                           braceroot_cfg_coco
NUM_CLASSES                    3
POOL_SIZE                      7
POST_NMS_ROIS_INFERENCE        1000
POST_NMS_ROIS_TRAINING         2000
PRE_NMS_LIMIT                  6000
ROI_POSITIVE_RATIO             0.33
RPN_ANCHOR_RATIOS              [0.5, 1, 2]
RPN_ANCHOR_SCALES              (32, 64, 128, 256, 512)
RPN_ANCHOR_STRIDE              1
RPN_BBOX_STD_DEV               [0.1 0.1 0.2 0.2]
RPN_NMS_THRESHOLD              0.7
RPN_TRAIN_ANCHORS_PER_IMAGE    256
STEPS_PER_EPOCH                100
TOP_DOWN_PYRAMID_SIZE          256
TRAIN_BN                       False
TRAIN_ROIS_PER_IMAGE           200
USE_MINI_MASK                  False
USE_RPN_ROIS                   True
VALIDATION_STEPS               50
WEIGHT_DECAY                   0.0001

Here is my error: 

ERROR:root: Error processing image {'id': 18, 'source': 'coco_like', 'path': '/scratch/hl46161/brace_root/CoCo_test_train/data/1302_plant_8A.jpg', 'width': 6000, 'height': 4000, ......}
Traceback (most recent call last):
  File "/home/hl46161/.conda/envs/Maskrcnn-TF2/lib/python3.7/site-packages/mask_rcnn_tf2-1.0-py3.7.egg/mrcnn/model.py", line 1709, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/hl46161/.conda/envs/Maskrcnn-TF2/lib/python3.7/site-packages/mask_rcnn_tf2-1.0-py3.7.egg/mrcnn/model.py", line 1211, in load_image_gt
    image = dataset.load_image(image_id)
  File "/home/hl46161/.conda/envs/Maskrcnn-TF2/lib/python3.7/site-packages/mask_rcnn_tf2-1.0-py3.7.egg/mrcnn/utils.py", line 359, in load_image
    image = skimage.io.imread(self.image_info[image_id]['path'])
  File "/home/hl46161/.conda/envs/Maskrcnn-TF2/lib/python3.7/site-packages/skimage/io/_io.py", line 48, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "/home/hl46161/.conda/envs/Maskrcnn-TF2/lib/python3.7/site-packages/skimage/io/manage_plugins.py", line 210, in call_plugin
    return func(*args, **kwargs)
  File "/home/hl46161/.conda/envs/Maskrcnn-TF2/lib/python3.7/site-packages/skimage/io/_plugins/imageio_plugin.py", line 10, in imread
    return np.asarray(imageio_imread(*args, **kwargs))
  File "/home/hl46161/.conda/envs/Maskrcnn-TF2/lib/python3.7/site-packages/imageio/__init__.py", line 97, in imread
    return imread_v2(uri, format=format, **kwargs)
  File "/home/hl46161/.conda/envs/Maskrcnn-TF2/lib/python3.7/site-packages/imageio/v2.py", line 226, in imread
    with imopen(uri, "ri", **imopen_args) as file:
  File "/home/hl46161/.conda/envs/Maskrcnn-TF2/lib/python3.7/site-packages/imageio/core/imopen.py", line 213, in imopen
    plugin_instance = candidate_plugin(request, **kwargs)
  File "/home/hl46161/.conda/envs/Maskrcnn-TF2/lib/python3.7/site-packages/imageio/config/plugins.py", line 107, in partial_legacy_plugin
    return LegacyPlugin(request, legacy_plugin)
  File "/home/hl46161/.conda/envs/Maskrcnn-TF2/lib/python3.7/site-packages/imageio/core/legacy_plugin_wrapper.py", line 80, in __init__
    if not self._format.can_read(request):
  File "/home/hl46161/.conda/envs/Maskrcnn-TF2/lib/python3.7/site-packages/imageio/core/format.py", line 242, in can_read
    return self._can_read(request)
  File "/home/hl46161/.conda/envs/Maskrcnn-TF2/lib/python3.7/site-packages/imageio/plugins/pillow_legacy.py", line 264, in _can_read
    Image = self._init_pillow()
  File "/home/hl46161/.conda/envs/Maskrcnn-TF2/lib/python3.7/site-packages/imageio/plugins/pillow_legacy.py", line 258, in _init_pillow
    Image.preinit()
  File "/home/hl46161/.local/lib/python3.7/site-packages/PIL/Image.py", line 361, in preinit
    from . import JpegImagePlugin
  File "/home/hl46161/.local/lib/python3.7/site-packages/PIL/JpegImagePlugin.py", line 44, in <module>
    from . import Image, ImageFile, TiffImagePlugin
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
EOFError: EOF read where object expected

**Comment by Densus100** [comment]
maybe you could change your config
IMAGE_MAX_DIM and IMAGE_MIN_DIM 
to match your dataset ?
