### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by lmmlzn** [matterport/Mask_RCNN#2907]
499/500 [============================>.] - ETA: 10s - loss: 12.0817 - rpn_class_loss: 0.0832 - rpn_bbox_loss: 1.8053 - mrcnn_class_loss: 0.0936 - mrcnn_bbox_loss: 0.6976 - mrcnn_mask_loss: 0.4940 - roi_alignment_loss: 7.6621 - row_adj_loss: 0.6728 - col_adj_loss: 0.5730/home/jinac/anaconda3/envs/struct/lib/python3.6/site-packages/imgaug/augmenters/base.py:59: SuspiciousSingleImageShapeWarning: You provided a numpy array of shape (1024, 1024, 220) as a single-image augmentation input, which was interpreted as (H, W, C). The last dimension however has a size of >=32, which indicates that you provided a multi-image array with shape (N, H, W) instead. If that is the case, you should use e.g. augmenter(imageS=<your input>) or augment_imageS(<your input>). Otherwise your multi-image input will be interpreted as a single image during augmentation.
  category=SuspiciousSingleImageShapeWarning)
Traceback (most recent call last):
  File "/home/jinac/anaconda3/envs/struct/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 2836, in data_generator
ZeroDivisionError: integer division or modulo by zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "samples/tabnet/tabnet.py", line 575, in <module>
    augmentation=augmentation)
  File "/home/jinac/anaconda3/envs/struct/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 4133, in train
  File "/home/jinac/anaconda3/envs/struct/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/jinac/anaconda3/envs/struct/lib/python3.6/site-packages/keras/engine/training.py", line 2250, in fit_generator
    max_queue_size=max_queue_size)
  File "/home/jinac/anaconda3/envs/struct/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/jinac/anaconda3/envs/struct/lib/python3.6/site-packages/keras/engine/training.py", line 2383, in eva

**Comment by lmmlzn** [comment]
how to solve it
