### ISSUE TITLE
TimeoutError: [WinError 10060] 

### ISSUE THREAD

**Issue by xiaobaiaaaaa** [matterport/Mask_RCNN#2948]
Traceback (most recent call last):
  File "D:/github/Mask_RCNN-2.1(01)/Mask_RCNN-2.1/samples/balloon/balloon.py", line 340, in <module>
    utils.download_trained_weights(weights_path)
  File "D:\github\Mask_RCNN-2.1(01)\Mask_RCNN-2.1\utils.py", line 726, in download_trained_weights
    with urllib.request.urlopen(COCO_MODEL_URL) as resp, open(coco_model_path, 'wb') as out:
  File "D:\anaconda3\envs\py37\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "D:\anaconda3\envs\py37\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "D:\anaconda3\envs\py37\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "D:\anaconda3\envs\py37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "D:\anaconda3\envs\py37\lib\urllib\request.py", line 1393, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "D:\anaconda3\envs\py37\lib\urllib\request.py", line 1353, in do_open
    r = h.getresponse()
  File "D:\anaconda3\envs\py37\lib\http\client.py", line 1373, in getresponse
    response.begin()
  File "D:\anaconda3\envs\py37\lib\http\client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "D:\anaconda3\envs\py37\lib\http\client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "D:\anaconda3\envs\py37\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "D:\anaconda3\envs\py37\lib\ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "D:\anaconda3\envs\py37\lib\ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

I have downloaded the h5 file and placed it in the file directory. What is the reason?

**Comment by YetaYu** [comment]
I also encountered such a problem, can you solve it, can you talk to me

**Comment by xiaobaiaaaaa** [comment]
> 

Hello, this problem was finally solved because the version of the library and the version of cuda are wrong. I installed cuda=10.1 and must correspond to other versions

**Comment by xiaobaiaaaaa** [comment]
> 

It feels a bit mystical in it.
