### ISSUE TITLE
Loading weights mask_rcnn_coco.h5 with h5py.h5f.open OSError

### ISSUE THREAD

**Issue by LiChongYan** [matterport/Mask_RCNN#2972]
Using TensorFlow backend.
Weights:  coco
Dataset:  ../../ballon
Logs:  C:\Users\lichongyan\Desktop\毕业论文资料\Mask_RCNN-master\Mask_RCNN-master\logs

Configurations:
BACKBONE                       resnet101
BACKBONE_STRIDES               [4, 8, 16, 32, 64]
BATCH_SIZE                     2
BBOX_STD_DEV                   [0.1 0.1 0.2 0.2]
COMPUTE_BACKBONE_SHAPE         None
DETECTION_MAX_INSTANCES        100
DETECTION_MIN_CONFIDENCE       0.9
DETECTION_NMS_THRESHOLD        0.3
FPN_CLASSIF_FC_LAYERS_SIZE     1024
GPU_COUNT                      1
GRADIENT_CLIP_NORM             5.0
IMAGES_PER_GPU                 2
IMAGE_CHANNEL_COUNT            3
IMAGE_MAX_DIM                  1024
IMAGE_META_SIZE                14
IMAGE_MIN_DIM                  800
IMAGE_MIN_SCALE                0
IMAGE_RESIZE_MODE              square
IMAGE_SHAPE                    [1024 1024    3]
LEARNING_MOMENTUM              0.9
LEARNING_RATE                  0.001
LOSS_WEIGHTS                   {'rpn_class_loss': 1.0, 'rpn_bbox_loss': 1.0, 'mrcnn_class_loss': 1.0, 'mrcnn_bbox_loss': 1.0, 'mrcnn_mask_loss': 1.0}
MASK_POOL_SIZE                 14
MASK_SHAPE                     [28, 28]
MAX_GT_INSTANCES               100
MEAN_PIXEL                     [123.7 116.8 103.9]
MINI_MASK_SHAPE                (56, 56)
NAME                           balloon
NUM_CLASSES                    2
POOL_SIZE                      7
POST_NMS_ROIS_INFERENCE        1000
POST_NMS_ROIS_TRAINING         2000
PRE_NMS_LIMIT                  6000
ROI_POSITIVE_RATIO             0.33
RPN_ANCHOR_RATIOS              [0.5, 1, 2]
RPN_ANCHOR_SCALES              (32, 64, 128, 256, 512)
RPN_ANCHOR_STRIDE              1
RPN_BBOX_STD_DEV               [0.1 0.1 0.2 0.2]
RPN_NMS_THRESHOLD              0.7
RPN_TRAIN_ANCHORS_PER_IMAGE    256
STEPS_PER_EPOCH                100
TOP_DOWN_PYRAMID_SIZE          256
TRAIN_BN                       False
TRAIN_ROIS_PER_IMAGE           200
USE_MINI_MASK                  True
USE_RPN_ROIS                   True
VALIDATION_STEPS               50
WEIGHT_DECAY                   0.0001

Loading weights  C:\Users\lichongyan\Desktop\毕业论文资料\Mask_RCNN-master\Mask_RCNN-master\mask_rcnn_coco.h5
Traceback (most recent call last):
  File "C:\Users\lichongyan\Desktop\毕业论文资料\Mask_RCNN-master\Mask_RCNN-master\samples\balloon\balloon.py", line 358, in <module>
    "mrcnn_bbox", "mrcnn_mask"])
  File "C:\Users\lichongyan\Desktop\毕业论文资料\Mask_RCNN-master\Mask_RCNN-master\mrcnn\model.py", line 2115, in load_weights
    f = h5py.File(filepath, mode='r')
  File "D:\software\anaconda\envs\py36\Lib\site-packages\h5py\_hl\files.py", line 408, in __init__
    swmr=swmr)
  File "D:\software\anaconda\envs\py36\Lib\site-packages\h5py\_hl\files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 88, in h5py.h5f.open
OSError

Downloaded mask_ Rcnn_ The coco.h5 file is at a size of 250m, and it is estimated to be complete. It has been repeated multiple times, but it still reported an error during runtime. May I ask if anyone can help answer?

**Comment by LiChongYan** [comment]
It has been resolved, just change h5py 2.10.0 to h5py 2.9.0
