### ISSUE TITLE
No module named 'keras.engine'

### ISSUE THREAD

**Issue by QQ3107887303** [matterport/Mask_RCNN#3024]
Traceback (most recent call last):
  File "E:\git\maskrcnn-balloon\samples\balloon\balloon.py", line 62, in <module>
    import model as modellib
  File "E:\git\maskrcnn-balloon\samples\balloon\model.py", line 28, in <module>
    import keras.engine  as KE
ModuleNotFoundError: No module named 'keras.engine'

**Comment by niuaoyu** [comment]
me too 
still not solved

**Comment by lailailee** [comment]
mee too
<img width="1165" alt="image" src="https://github.com/matterport/Mask_RCNN/assets/28286591/af4914b5-4245-4d37-b2b9-b812e1cb6f47">

**Comment by simone-agliano-dev** [comment]
I guess python3.4 is required, I've been trying to install it and give it a shot. BTW, do you have Python 3.4?

**Comment by SeeenyaOhar** [comment]
An obvious solution to this is use:
`keras.layers.Layer `instead of `KE.Layer`

**Comment by CRAZYACE1** [comment]
> An obvious solution to this is use: `keras.layers.Layer `instead of `KE.Layer`

This just creates the same issue for me: ModuleNotFoundError: No module named 'keras.layers.Layer'

**Comment by DevHawon** [comment]
using "keras.layers.Layer" is the solution
