### ISSUE TITLE
some random images are not added to the image_info

### ISSUE THREAD

**Issue by ChristophNeuner** [matterport/Mask_RCNN#304]
```
import os
import sys
import random
import math
import re
import time
import numpy as np
import cv2
import matplotlib
import matplotlib.pyplot as plt

import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.image as mpimg
import skimage.io
from tqdm import tqdm

from config import Config
import utils
import model as modellib
import visualize
from model import log

from PIL import Image


%matplotlib inline 

# Root directory of the project
ROOT_DIR = os.getcwd()

# Directory to save logs and model checkpoints, if not provided
# through the command line argument --logs
MODEL_DIR = os.path.join(ROOT_DIR, "logs")

# Local path to trained weights file
COCO_MODEL_PATH = os.path.join(ROOT_DIR, "mask_rcnn_coco.h5")
# Download COCO trained weights from Releases if needed
if not os.path.exists(COCO_MODEL_PATH):
    utils.download_trained_weights(COCO_MODEL_PATH)
    
dataTrainPath="./2018_Data_Science_Bowl/stage1_train_minus_validation/"
dataValPath="./2018_Data_Science_Bowl/stage1_val/"
dataTestPath="./2018_Data_Science_Bowl/stage1_test/"
challengeName = "nucleiChallenge"


####################################
# Config
####################################
class NucleiConfig(Config):
    """Configuration for training on the toy shapes dataset.
    Derives from the base Config class and overrides values specific
    to the toy shapes dataset.
    """
    # Give the configuration a recognizable name
    NAME = challengeName

    GPU_COUNT = 1
    IMAGES_PER_GPU = 1

    # Number of classes (including background)
    NUM_CLASSES = 1 + 1  # background + nucleus

    IMAGE_MIN_DIM = 256
    IMAGE_MAX_DIM = 256

    RPN_ANCHOR_SCALES = (8, 16, 32, 64, 128)  # anchor side in pixels

    TRAIN_ROIS_PER_IMAGE = 128

    STEPS_PER_EPOCH = 1

    VALIDATION_STEPS = 5
    
config = NucleiConfig()
#config.display()


####################################
# Dataset
####################################

class NucleiDataset(utils.Dataset):
     
    ###dataset_path: e.g. "./2018_Data_Science_Bowl/stage1_train/
    ###adds nucleus class as a possible detectable object type
    ###loads all images from the dataset
    def load_dataset(self, path):
        self.add_class(challengeName, 1, "nucleus")        
        dataset = os.listdir(path)
        for i in dataset:
            img_path = path + i + r"/images/" + i + ".png"
            self.add_image(challengeName, i, img_path)

            
    ###returns the image with the specified id
    ###if the image is grayscale, it gets converted to rgb
    def load_image(self, image_id):        
        image = skimage.io.imread(self.image_reference(image_id))
        #image = mpimg.imread(self.image_reference(image_id))
        #if image.ndim != 3:
            #image = skimage.color.gray2rgb(image)
        return image  
    
    ###returns the path to the image
    def image_reference(self, image_id):
        for i in self.image_info:
            if(i['id'] == image_id):
                return i.get('path')
            else:
                return "blub"
    
    
    ###Returns:
    ###masks: A bool array of shape [height, width, instance count] with
    ###a binary mask per instance.
    ###class_ids: a 1D array of class IDs of the instance masks.
    ###the method merges all masks of an image to one single image
    def load_mask(self, image_id):        
        dataset_path = self.image_reference(image_id).rsplit('/', 3)[0]
        
        rM,dM,fM=os.walk(dataset_path+ r"/" +image_id+"/masks/").__next__()
        maskList=[rM+mask for mask in fM]
        masks=skimage.io.imread_collection(maskList).concatenate()
        s=masks.shape
        # Start with a matrix of size the same as the image (or masks)
        labels=np.zeros((s[1],s[2]),np.uint16)
        for i in range(s[0]):
            labels[masks[i]>0]=i+1
        #because there is only on type of detectable object, all objects belong to class 1
        class_ids = np.ones((s[0],), dtype=np.int)
        return labels, class_ids
            

####################################
# Load Datasets
####################################
# Training dataset
dataset_train = NucleiDataset()
dataset_train.load_dataset(dataTrainPath)
dataset_train.prepare()

# Validation dataset
dataset_val = NucleiDataset()
dataset_val.load_dataset(dataValPath)
dataset_val.prepare()



####################################
# Model
####################################
# Create model in training mode
model = modellib.MaskRCNN(mode="training", config=config,
                          model_dir=MODEL_DIR)


# Which weights to start with?
init_with = "coco"  # imagenet, coco, or last


if init_with == "imagenet":
    model.load_weights(model.get_imagenet_weights(), by_name=True)
elif init_with == "coco":
    # Load weights trained on MS COCO, but skip layers that
    # are different due to the different number of classes
    # See README for instructions to download the COCO weights
    model.load_weights(COCO_MODEL_PATH, by_name=True,
                       exclude=["mrcnn_class_logits", "mrcnn_bbox_fc", 
                                "mrcnn_bbox", "mrcnn_mask"])
elif init_with == "last":
    # Load the last model you trained and continue training
    model.load_weights(model.find_last()[1], by_name=True)



# Train the head branches
# Passing layers="heads" freezes all layers except the head
# layers. You can also pass a regular expression to select
# which layers to train by name pattern.
model.train(dataset_train, dataset_val,
            learning_rate=config.LEARNING_RATE, 
            epochs=1, 
            layers='heads')
```

This is the error I get:

```
Starting at epoch 0. LR=0.001

Checkpoint Path: /home/Deep_Learner/work/Mask_RCNN/logs/nucleichallenge20180306T2206/mask_rcnn_nucleichallenge_{epoch:04d}.h5
Selecting layers to train
fpn_c5p5               (Conv2D)
fpn_c4p4               (Conv2D)
fpn_c3p3               (Conv2D)
fpn_c2p2               (Conv2D)
fpn_p5                 (Conv2D)
fpn_p2                 (Conv2D)
fpn_p3                 (Conv2D)
fpn_p4                 (Conv2D)
In model:  rpn_model
    rpn_conv_shared        (Conv2D)
    rpn_class_raw          (Conv2D)
    rpn_bbox_pred          (Conv2D)
mrcnn_mask_conv1       (TimeDistributed)
mrcnn_mask_bn1         (TimeDistributed)
mrcnn_mask_conv2       (TimeDistributed)
mrcnn_mask_bn2         (TimeDistributed)
mrcnn_class_conv1      (TimeDistributed)
mrcnn_class_bn1        (TimeDistributed)
mrcnn_mask_conv3       (TimeDistributed)
mrcnn_mask_bn3         (TimeDistributed)
mrcnn_class_conv2      (TimeDistributed)
mrcnn_class_bn2        (TimeDistributed)
mrcnn_mask_conv4       (TimeDistributed)
mrcnn_mask_bn4         (TimeDistributed)
mrcnn_bbox_fc          (TimeDistributed)
mrcnn_mask_deconv      (TimeDistributed)
mrcnn_class_logits     (TimeDistributed)
mrcnn_mask             (TimeDistributed)

ERROR:root:Error processing image {'source': 'nucleiChallenge', 'id': 'e856511ac1c34d24320eb7c56c05a4a3340d06667b4f5b8e8df615d415c7f650', 'path': './2018_Data_Science_Bowl/stage1_val/e856511ac1c34d24320eb7c56c05a4a3340d06667b4f5b8e8df615d415c7f650/images/e856511ac1c34d24320eb7c56c05a4a3340d06667b4f5b8e8df615d415c7f650.png'}
Traceback (most recent call last):
  File "/home/Deep_Learner/work/Mask_RCNN/model.py", line 1632, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/Deep_Learner/work/Mask_RCNN/model.py", line 1190, in load_image_gt
    image = dataset.load_image(image_id)
  File "<ipython-input-73-2cd3a75d0095>", line 99, in load_image
    image = skimage.io.imread(self.image_reference(image_id))
  File "/opt/conda/lib/python3.5/site-packages/skimage/io/_io.py", line 61, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "/opt/conda/lib/python3.5/site-packages/skimage/io/manage_plugins.py", line 211, in call_plugin
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/skimage/io/_plugins/pil_plugin.py", line 35, in imread
    with open(fname, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'blub'
ERROR:root:Error processing image {'source': 'nucleiChallenge', 'id': 'f952cc65376009cfad8249e53b9b2c0daaa3553e897096337d143c625c2df886', 'path': './2018_Data_Science_Bowl/stage1_val/f952cc65376009cfad8249e53b9b2c0daaa3553e897096337d143c625c2df886/images/f952cc65376009cfad8249e53b9b2c0daaa3553e897096337d143c625c2df886.png'}
Traceback (most recent call last):
  File "/home/Deep_Learner/work/Mask_RCNN/model.py", line 1632, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/Deep_Learner/work/Mask_RCNN/model.py", line 1190, in load_image_gt
    image = dataset.load_image(image_id)
  File "<ipython-input-73-2cd3a75d0095>", line 99, in load_image
    image = skimage.io.imread(self.image_reference(image_id))
  File "/opt/conda/lib/python3.5/site-packages/skimage/io/_io.py", line 61, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "/opt/conda/lib/python3.5/site-packages/skimage/io/manage_plugins.py", line 211, in call_plugin
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/skimage/io/_plugins/pil_plugin.py", line 35, in imread
    with open(fname, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'blub'
ERROR:root:Error processing image {'source': 'nucleiChallenge', 'id': 'ea94ba4b01d1bd5f7768d10e0ac547743791033df545c71fcec442d0cb5cb5e7', 'path': './2018_Data_Science_Bowl/stage1_val/ea94ba4b01d1bd5f7768d10e0ac547743791033df545c71fcec442d0cb5cb5e7/images/ea94ba4b01d1bd5f7768d10e0ac547743791033df545c71fcec442d0cb5cb5e7.png'}
Traceback (most recent call last):
  File "/home/Deep_Learner/work/Mask_RCNN/model.py", line 1632, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/Deep_Learner/work/Mask_RCNN/model.py", line 1190, in load_image_gt
    image = dataset.load_image(image_id)
  File "<ipython-input-73-2cd3a75d0095>", line 99, in load_image
    image = skimage.io.imread(self.image_reference(image_id))
  File "/opt/conda/lib/python3.5/site-packages/skimage/io/_io.py", line 61, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "/opt/conda/lib/python3.5/site-packages/skimage/io/manage_plugins.py", line 211, in call_plugin
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/skimage/io/_plugins/pil_plugin.py", line 35, in imread
    with open(fname, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'blub'
ERROR:root:Error processing image {'source': 'nucleiChallenge', 'id': 'f8e74d4006dd68c1dbe68df7be905835e00d8ba4916f3b18884509a15fdc0b55', 'path': './2018_Data_Science_Bowl/stage1_val/f8e74d4006dd68c1dbe68df7be905835e00d8ba4916f3b18884509a15fdc0b55/images/f8e74d4006dd68c1dbe68df7be905835e00d8ba4916f3b18884509a15fdc0b55.png'}
Traceback (most recent call last):
  File "/home/Deep_Learner/work/Mask_RCNN/model.py", line 1632, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/Deep_Learner/work/Mask_RCNN/model.py", line 1190, in load_image_gt
    image = dataset.load_image(image_id)
  File "<ipython-input-73-2cd3a75d0095>", line 99, in load_image
    image = skimage.io.imread(self.image_reference(image_id))
  File "/opt/conda/lib/python3.5/site-packages/skimage/io/_io.py", line 61, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "/opt/conda/lib/python3.5/site-packages/skimage/io/manage_plugins.py", line 211, in call_plugin
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/skimage/io/_plugins/pil_plugin.py", line 35, in imread
    with open(fname, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'blub'
ERROR:root:Error processing image {'source': 'nucleiChallenge', 'id': 'e66f25e175abab08ecb4e5f6859db64a211e0ddffb262d7e727b9d9bd4aad2d2', 'path': './2018_Data_Science_Bowl/stage1_val/e66f25e175abab08ecb4e5f6859db64a211e0ddffb262d7e727b9d9bd4aad2d2/images/e66f25e175abab08ecb4e5f6859db64a211e0ddffb262d7e727b9d9bd4aad2d2.png'}
Traceback (most recent call last):
  File "/home/Deep_Learner/work/Mask_RCNN/model.py", line 1632, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/Deep_Learner/work/Mask_RCNN/model.py", line 1190, in load_image_gt
    image = dataset.load_image(image_id)
  File "<ipython-input-73-2cd3a75d0095>", line 99, in load_image
    image = skimage.io.imread(self.image_reference(image_id))
  File "/opt/conda/lib/python3.5/site-packages/skimage/io/_io.py", line 61, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "/opt/conda/lib/python3.5/site-packages/skimage/io/manage_plugins.py", line 211, in call_plugin
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/skimage/io/_plugins/pil_plugin.py", line 35, in imread
    with open(fname, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'blub'
ERROR:root:Error processing image {'source': 'nucleiChallenge', 'id': 'e4537e7893e631f3ba6ae5b1023e24b233c78249a31c2f5e561f6c4cad88fcf6', 'path': './2018_Data_Science_Bowl/stage1_val/e4537e7893e631f3ba6ae5b1023e24b233c78249a31c2f5e561f6c4cad88fcf6/images/e4537e7893e631f3ba6ae5b1023e24b233c78249a31c2f5e561f6c4cad88fcf6.png'}
Traceback (most recent call last):
  File "/home/Deep_Learner/work/Mask_RCNN/model.py", line 1632, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/Deep_Learner/work/Mask_RCNN/model.py", line 1190, in load_image_gt
    image = dataset.load_image(image_id)
  File "<ipython-input-73-2cd3a75d0095>", line 99, in load_image
    image = skimage.io.imread(self.image_reference(image_id))
  File "/opt/conda/lib/python3.5/site-packages/skimage/io/_io.py", line 61, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "/opt/conda/lib/python3.5/site-packages/skimage/io/manage_plugins.py", line 211, in call_plugin
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/skimage/io/_plugins/pil_plugin.py", line 35, in imread
    with open(fname, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'blub'

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-73-2cd3a75d0095> in <module>()
    182             learning_rate=config.LEARNING_RATE,
    183             epochs=1,
--> 184             layers='heads')
    185 
    186 

~/work/Mask_RCNN/model.py in train(self, train_dataset, val_dataset, learning_rate, epochs, layers)
   2232             steps_per_epoch=self.config.STEPS_PER_EPOCH,
   2233             callbacks=callbacks,
-> 2234             validation_data=next(val_generator),
   2235             validation_steps=self.config.VALIDATION_STEPS,
   2236             max_queue_size=100,

~/work/Mask_RCNN/model.py in data_generator(dataset, config, shuffle, augment, random_rois, batch_size, detection_targets)
   1630             image, image_meta, gt_class_ids, gt_boxes, gt_masks = \
   1631                 load_image_gt(dataset, config, image_id, augment=augment,
-> 1632                               use_mini_mask=config.USE_MINI_MASK)
   1633 
   1634             # Skip images that have no instances. This can happen in cases

~/work/Mask_RCNN/model.py in load_image_gt(dataset, config, image_id, augment, use_mini_mask)
   1188     """
   1189     # Load image and mask
-> 1190     image = dataset.load_image(image_id)
   1191     mask, class_ids = dataset.load_mask(image_id)
   1192     shape = image.shape

<ipython-input-73-2cd3a75d0095> in load_image(self, image_id)
     97     ###if the image is grayscale, it gets converted to rgb
     98     def load_image(self, image_id):
---> 99         image = skimage.io.imread(self.image_reference(image_id))
    100         #image = mpimg.imread(self.image_reference(image_id))
    101         #if image.ndim != 3:

/opt/conda/lib/python3.5/site-packages/skimage/io/_io.py in imread(fname, as_grey, plugin, flatten, **plugin_args)
     59 
     60     with file_or_url_context(fname) as fname:
---> 61         img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
     62 
     63     if not hasattr(img, 'ndim'):

/opt/conda/lib/python3.5/site-packages/skimage/io/manage_plugins.py in call_plugin(kind, *args, **kwargs)
    209                                (plugin, kind))
    210 
--> 211     return func(*args, **kwargs)
    212 
    213 

/opt/conda/lib/python3.5/site-packages/skimage/io/_plugins/pil_plugin.py in imread(fname, dtype, img_num, **kwargs)
     33     """
     34     if isinstance(fname, string_types):
---> 35         with open(fname, 'rb') as f:
     36             im = Image.open(f)
     37             return pil_to_ndarray(im, dtype=dtype, img_num=img_num)

FileNotFoundError: [Errno 2] No such file or directory: 'blub'
```

Everytime I run the code, the error occurs with different images, but always only with images of the validation set.
For some reason these images are not present in the image_info list.

**Comment by fastlater** [comment]
Can you use the ` Insert code` option to edit your post? It is difficult to read with so many headlines.

**Comment by ChristophNeuner** [comment]
Oh i am sorry. I have edited it.

**Comment by fastlater** [comment]
Did you tried the inspect_data.ipynb  to examine your data loading?

**Comment by ChristophNeuner** [comment]
yes, but it does not help me

**Comment by ChristophNeuner** [comment]
I think i narrowed the problem to a small portion of my code but i really do not get why it is not working.
Probably it has something to do with some basic python string comparison operation.
The image_info dictionary objects get initialized correctly.
I did the following to check, if the image can be found in the image_info[] list:

`dataValPath="./2018_Data_Science_Bowl/stage1_val/"
setVal = NucleiDataset()
setVal.load_dataset(dataValPath)
setVal.prepare()

for i in setVal.image_info:
    print(i.get('id'))
    print(i.get('path'))
    image = skimage.io.imread(i.get('path'))
    plt.imshow(image)

    plt.show()
    image2 = skimage.io.imread(setVal.image_reference(i.get('id')))
    plt.imshow(image2)
    plt.show()
`
`###returns the path to the image
    def image_reference(self, image_id):
        for i in self.image_info:
            if(i.get('id') == image_id):
                return i.get('path')
            else:
                return "not found"`

For some reason the first way of getting the path to the image     i.get('path')     always works without a problem.
But the second way      setVal.image_reference(i.get('id')      only works for the first few and then at some random image it throws  "FileNotFoundError: [Errno 2] No such file or directory: 'not found'"

So i guess there is a problem with the image_reference(self, image_id)  method.
I think it is this exact line of code:  `if(i.get('id') == image_id):`
Could it be the case that == does not compare the content but the two objects?
I am coming from C# and am new to python.

**Comment by ronykalfarisi** [comment]
Hi @ChristophNeuner I have the same problem, how did you fix it? Thanks

**Comment by ChristophNeuner** [comment]
yeah, 
I think the problem was, that there are some hidden files created by jupyter that are not images.
Use the sample code here: https://github.com/matterport/Mask_RCNN/tree/master/samples/nucleus
That works fine.

**Comment by ronykalfarisi** [comment]
Hi @ChristophNeuner ,
Thanks for the suggestion, for my case, the problem is the path that I passed to train.py.
