### ISSUE TITLE
TypeError: Failed to convert object of type <class 'theano.tensor.var.TensorVariable'> to Tensor. Contents: Elemwise{add,no_inplace}.0. Consider casting elements to a supported type.

### ISSUE THREAD

**Issue by Anguliachao** [matterport/Mask_RCNN#305]
Hi everyone,
I am trying to run the code on my laptop, however everytime I run 
modellib.MaskRCNN it will raise the TypeError.
My settings:

1. Windows10
2. python 3.6.3
3. Anaconda 64bit
4. Tensorflow1.3 and Keras latest

and my error log is  : 

```
>>> modellib.MaskRCNN(mode="inference", model_dir=MODEL_DIR, config=config)
Traceback (most recent call last):
  File "C:\Users\AnguliaYang\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 460, in make_tensor_proto
    str_values = [compat.as_bytes(x) for x in proto_values]
  File "C:\Users\AnguliaYang\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 460, in <listcomp>
    str_values = [compat.as_bytes(x) for x in proto_values]
  File "C:\Users\AnguliaYang\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\util\compat.py", line 65, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got Elemwise{add,no_inplace}.0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Mask_RCNN\model.py", line 1763, in __init__
    self.keras_model = self.build(mode=mode, config=config)
  File "D:\Mask_RCNN\model.py", line 1854, in build
    len(config.RPN_ANCHOR_RATIOS), 256)
  File "D:\Mask_RCNN\model.py", line 874, in build_rpn_model
    outputs = rpn_graph(input_feature_map, anchors_per_location, anchor_stride)
  File "D:\Mask_RCNN\model.py", line 839, in rpn_graph
    lambda t: tf.reshape(t, [tf.shape(t)[0], -1, 2]))(x)
  File "C:\Users\AnguliaYang\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\engine\topology.py", line 603, in __call__
    output = self.call(inputs, **kwargs)
  File "C:\Users\AnguliaYang\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\layers\core.py", line 651, in call
    return self.function(inputs, **arguments)
  File "D:\Mask_RCNN\model.py", line 839, in <lambda>
    lambda t: tf.reshape(t, [tf.shape(t)[0], -1, 2]))(x)
  File "C:\Users\AnguliaYang\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 245, in shape
    return shape_internal(input, name, optimize=True, out_type=out_type)
  File "C:\Users\AnguliaYang\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 268, in shape_internal
    input_tensor = ops.convert_to_tensor(input)
  File "C:\Users\AnguliaYang\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 611, in convert_to_tensor
    as_ref=False)
  File "C:\Users\AnguliaYang\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 676, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\Users\AnguliaYang\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\constant_op.py", line 121, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "C:\Users\AnguliaYang\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "C:\Users\AnguliaYang\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 464, in make_tensor_proto
    "supported type." % (type(values), values))
TypeError: Failed to convert object of type <class 'theano.tensor.var.TensorVariable'> to Tensor. Contents: Elemwise{add,no_inplace}.0. Consider casting elements to a supported type.
```
It's always the typeError, I wonder whether this is my Python version too high?or some other approach to solve it ? Can anybody help me out? Thanks .

**Comment by Anguliachao** [comment]
i figure it out , the reason is I didn't change my backend from theano to tensorflow.

**Comment by oludash01** [comment]
How did you change the backend?

**Comment by Anguliachao** [comment]
@oludash01  My installed backend is theano by default, hence either to set 'KERAS_BACKEND = tensorflow'
or you can modiry ur code as 
`
os.environ['KERAS_BACKEND']='tensorflow'
`
