### ISSUE TITLE
Error utils.TrainingError: Invalid bounding box with area of zero

### ISSUE THREAD

**Issue by John1231983** [matterport/Mask_RCNN#351]
In the implementation of extract box from mask, the implementation used
```
def extract_bboxes(mask):
   ...
            x1, x2 = horizontal_indicies[[0, -1]]
            y1, y2 = vertical_indicies[[0, -1]]
            # x2 and y2 should not be part of the box. Increment by 1.
            x2 += 1 
            y2 += 1
...
```
I have changed it to
```
            x2 +=5
            y2 +=5
            x1 -= 5
            y1 -=5
```
And I got the error as below. How can I fix it? The reason is that I want to make a larger box from the mask, instead of different 1 pixel. 

```
ERROR:root:Error processing image {'id': 7, 'source': 'dsb-2018', 'path': 'stage1_train/1.png', 'mask_paths': 'stage1_train/masks/1.png'}
Traceback (most recent call last):
  File "/home/john/dsb/model.py", line 1700, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/john/dsb/model.py", line 1468, in load_image_gt
    mask = utils.minimize_mask(bbox, mask, config.MINI_MASK_SHAPE)
  File "/home/john/dsb/utils.py", line 470, in minimize_mask
    raise TrainingError("Invalid bounding box with area of zero")
utils.TrainingError: Invalid bounding box with area of zero
```

**Comment by vikas1902** [comment]
Hi @John1231983
I am getting the same error while training on  DSB. Did you find any solution?

**Comment by John1231983** [comment]
The solution is that check x1 and y1 before perform substraction. However, performance is lower than using original matterport. I don't know why

**Comment by vikas1902** [comment]
Thanks @John1231983 
Removing the blank mask can also help. 
see this link also. 
https://github.com/matterport/Mask_RCNN/issues/112

**Comment by John1231983** [comment]
@vikas1902 : I only use 1 image for training, so if I remove it, it has no images send to the network
```
GPU_COUNT = 1
IMAGES_PER_GPU = 1
```
Do you increase the padding likes below code?
```
def extract_bboxes(mask):
   ...
            x1, x2 = horizontal_indicies[[0, -1]]
            y1, y2 = vertical_indicies[[0, -1]]
            # x2 and y2 should not be part of the box. Increment by 1.
            x2 += 5 
            y2 += 5
           if (x1>5):
              x1-=5
           if (y1>5):
              y1-=5
...
I have tried above code but it gives bad result on DSB. Let me know if it works for you
```

**Comment by huaifeng1993** [comment]
when you extract bboxs ,you sholud limit the boards of bboxs in the image.

**Comment by John1231983** [comment]
@huaifeng1993: what does it mean? Could you explain it by code or how to solve my problem?
