### ISSUE TITLE
TypeError : integer argument expected, got float

### ISSUE THREAD

**Issue by ThreeBrother** [matterport/Mask_RCNN#353]
Processing 1 images
image                    shape: (1224, 1632, 3)       min:    0.00000  max:  255.00000
Traceback (most recent call last):
  File "demo_mine.py", line 84, in <module>
    results = model.detect([image], verbose=1)
  File "/home/fxd/sy3u/Mask_RCNN-master/model.py", line 2366, in detect
    molded_images, image_metas, windows = self.mold_inputs(images)
  File "/home/fxd/sy3u/Mask_RCNN-master/model.py", line 2269, in mold_inputs
    padding=self.config.IMAGE_PADDING)
  File "/home/fxd/sy3u/Mask_RCNN-master/utils.py", line 421, in resize_image
    image, (round(h * scale), round(w * scale)))
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/scipy/misc/pilutil.py", line 564, in imresize
    imnew = im.resize(size, resample=func[interp])
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 1747, in resize
    return self._new(self.im.resize(size, resample, box))
TypeError: integer argument expected, got float

Thanks for you to help me！

**Comment by tabelh** [comment]
Running in to the same problem has either one of you found a solution?

**Comment by jefflgaol** [comment]
You need to use Python 3.
