### ISSUE TITLE
Issue with loading COCO weights

### ISSUE THREAD

**Issue by mpsampat** [matterport/Mask_RCNN#389]
Hi @waleedka , 

I did a pull on master for Mask_RCNN. after this i get the stack-trace below which loading the weights for coco. Cannot figure out if it is a local issue or a bug in master ? 

my command is: 

elif init_with == "coco":
    # Load weights trained on MS COCO, but skip layers that
    # are different due to the different number of classes
    # See README for instructions to download the COCO weights
    model.load_weights(COCO_MODEL_PATH, by_name=True,
                       exclude=["mrcnn_class_logits", "mrcnn_bbox_fc",
                                "mrcnn_bbox", "mrcnn_mask"])

The stack-trace is:
  File "/home/mpsampat/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 686, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "/home/mpsampat/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 3 in both shapes must be equal, but are 12 and 6. Shapes are [1,1,512,12] and [1,1,512,6]. for 'Assign_642' (op: 'Assign') with input shapes: [1,1,512,12], [1,1,512,6].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./train_mask_rcnn.py", line 266, in <module>
    "mrcnn_bbox", "mrcnn_mask"])
  File "Mask_RCNN2/model.py", line 2075, in load_weights
    topology.load_weights_from_hdf5_group_by_name(f, layers)
  File "/home/mpsampat/miniconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 3468, in load_weights_from_hdf5_group_by_name
    K.batch_set_value(weight_value_tuples)
  File "/home/mpsampat/miniconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2368, in batch_set_value
    assign_op = x.assign(assign_placeholder)
  File "/home/mpsampat/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 599, in assign
    return state_ops.assign(self._variable, value, use_locking=use_locking)
  File "/home/mpsampat/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/state_ops.py", line 280, in assign
    validate_shape=validate_shape)
  File "/home/mpsampat/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_state_ops.py", line 58, in assign
    use_locking=use_locking, name=name)
  File "/home/mpsampat/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/mpsampat/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3273, in create_op
    compute_device=compute_device)
  File "/home/mpsampat/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3313, in _create_op_helper
    set_shapes_for_outputs(op)
  File "/home/mpsampat/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2501, in set_shapes_for_outputs
    return _set_shapes_for_outputs(op)
  File "/home/mpsampat/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2474, in _set_shapes_for_outputs
    shapes = shape_func(op)
  File "/home/mpsampat/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2404, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/home/mpsampat/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 627, in call_cpp_shape_fn
    require_shape_fn)
  File "/home/mpsampat/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 691, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimension 3 in both shapes must be equal, but are 12 and 6. Shapes are [1,1,512,12] and [1,1,512,6]. for 'Assign_642' (op: 'Assign') with input shapes: [1,1,512,12], [1,1,512,6].

**Comment by mpsampat** [comment]
Hi @waleedka , 
i found the cause. it is local issue. in my config i changed
RPN_ANCHOR_RATIOS = [0.5, 1, 2] to RPN_ANCHOR_RATIOS = [0.25 0.5, 0.75, 1, 1.5, 2]
Then i get the error above. so I just change it back and it works fine now.

**Comment by zekeriyyaa** [comment]
You should exclude some layers such as 'mrcnn_bbox_fc','mrcnn_class_logits’(fill the layer's name in the load_weights method), then start fine-tuning.

You can exclude these layers as given below: instead of

`model.load_weights(CUSTOM_MODEL_PATH, by_name=True)`

use

`model.load_weights(COCO_MODEL_PATH, by_name=True, exclude=["mrcnn_class_logits", "mrcnn_bbox_fc", "mrcnn_bbox", "mrcnn_mask", "rpn_model"])`
