### ISSUE TITLE
Receiving the following error: "IndexError: trying to index 2 dimensions of a 0 dimensional tensor"

### ISSUE THREAD

**Issue by omkar13** [matterport/Mask_RCNN#394]
I have used Mask RCNN module for many images and it worked nicely. However, I received the following error recently and I have no clue how to solve it. Could someone please help me? I have used the code from the github repo.

Traceback (most recent call last):
  File "/home/omkar/pycharm-community-2017.3.4/helpers/pydev/pydev_run_in_console.py", line 53, in run_file
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/omkar/pycharm-community-2017.3.4/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/omkar/PycharmProjects/mask_rcnn/demo.py", line 149, in <module>
    result = model.detect([image])
  File "/home/omkar/PycharmProjects/mask_rcnn/model.py", line 1599, in detect
    detections, mrcnn_mask = self.predict([molded_images, image_metas], mode='inference')
  File "/home/omkar/PycharmProjects/mask_rcnn/model.py", line 1674, in predict
    detections = detection_layer(self.config, rpn_rois, mrcnn_class, mrcnn_bbox, image_metas)
  File "/home/omkar/PycharmProjects/mask_rcnn/model.py", line 842, in detection_layer
    detections = refine_detections(rois, mrcnn_class, mrcnn_bbox, window, config)
  File "/home/omkar/PycharmProjects/mask_rcnn/model.py", line 787, in refine_detections
    keep = torch.nonzero(keep_bool)[:,0]
  File "/home/omkar/anaconda3/envs/mask_rcnn/lib/python3.6/site-packages/torch/autograd/variable.py", line 78, in __getitem__
    return Index.apply(self, key)
  File "/home/omkar/anaconda3/envs/mask_rcnn/lib/python3.6/site-packages/torch/autograd/_functions/tensor.py", line 89, in forward
    result = i.index(ctx.index)
IndexError: trying to index 2 dimensions of a 0 dimensional tensor

Thanking you in anticipation.
Regards,
Omkar.

**Comment by waleedka** [comment]
This looks like pytorch code. I think you're posting on the wrong repository.

**Comment by omkar13** [comment]
I am sorry! I completely forgot!

**Comment by zbl-96** [comment]
@omkar13 the same issue ，can you help me?
