### ISSUE TITLE
error with multi gpu training

### ISSUE THREAD

**Issue by aguang1201** [matterport/Mask_RCNN#420]
I want to train in samples/nucleus with multi gpu -> GPU_COUNT = 2(NucleusConfig)
but it's show following error :
Traceback (most recent call last):
  File "/home/panotech/PycharmProjects/Mask_RCNN/samples/nucleus/nucleus.py", line 455, in <module>
    model_dir=args.logs)
  File "/home/panotech/PycharmProjects/Mask_RCNN/mrcnn/model.py", line 1820, in __init__
    self.keras_model = self.build(mode=mode, config=config)
  File "/home/panotech/PycharmProjects/Mask_RCNN/mrcnn/model.py", line 2039, in build
    model = ParallelModel(model, config.GPU_COUNT)
  File "/home/panotech/PycharmProjects/Mask_RCNN/mrcnn/parallel_model.py", line 37, in __init__
    merged_outputs = self.make_parallel()
  File "/home/panotech/PycharmProjects/Mask_RCNN/mrcnn/parallel_model.py", line 81, in make_parallel
    outputs = self.inner_model(inputs)
  File "/usr/local/share/anaconda3/envs/zzg3.6/lib/python3.6/site-packages/keras/engine/topology.py", line 619, in __call__
    output = self.call(inputs, **kwargs)
  File "/usr/local/share/anaconda3/envs/zzg3.6/lib/python3.6/site-packages/keras/engine/topology.py", line 2085, in call
    output_tensors, _, _ = self.run_internal_graph(inputs, masks)
  File "/usr/local/share/anaconda3/envs/zzg3.6/lib/python3.6/site-packages/keras/engine/topology.py", line 2236, in run_internal_graph
    output_tensors = _to_list(layer.call(computed_tensor, **kwargs))
  File "/usr/local/share/anaconda3/envs/zzg3.6/lib/python3.6/site-packages/keras/layers/core.py", line 663, in call
    return self.function(inputs, **arguments)
  File "/home/panotech/PycharmProjects/Mask_RCNN/mrcnn/model.py", line 1913, in <lambda>
    anchors = KL.Lambda(lambda x: tf.constant(anchors), name="anchors")(input_image)
  File "/usr/local/share/anaconda3/envs/zzg3.6/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 214, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/local/share/anaconda3/envs/zzg3.6/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 433, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/usr/local/share/anaconda3/envs/zzg3.6/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 341, in _AssertCompatible
    raise TypeError("List of Tensors when single Tensor expected")
TypeError: List of Tensors when single Tensor expected

Training with Multi-GPUs is not supportted yet?

**Comment by kirk86** [comment]
@aguang1201 Check my solution [here](https://github.com/matterport/Mask_RCNN/issues/423)

**Comment by aguang1201** [comment]
@kirk86 
Thank you.I got it.
