### ISSUE TITLE
ValueError: input_image_meta shape

### ISSUE THREAD

**Issue by GustavZ** [matterport/Mask_RCNN#466]
When starting to rain i see following error:

```
Traceback (most recent call last):
  File "coco.py", line 552, in <module>
    augmentation=augmentation)
  File "/home/gustav/workspace/Mobile_Mask_RCNN/mrcnn/model.py", line 2852, in train
    use_multiprocessing=True,
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 2147, in fit_generator
    class_weight=class_weight)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1833, in train_on_batch
    check_batch_axis=True)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1414, in _standardize_user_data
    exception_prefix='input')
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 153, in _standardize_input_data
    str(array.shape))
ValueError: Error when checking input: expected input_image_meta to have shape (None, 14) but got array with shape (2, 93)
```

**Comment by qnkhuat** [comment]
any idea??

**Comment by GustavZ** [comment]
i solved all of them on my fork.
https://github.com/GustavZ/Mobile_Mask_RCNN

**Comment by qnkhuat** [comment]
@GustavZ thanks :D
