### ISSUE TITLE
How to set files of nucleus demo dataset?

### ISSUE THREAD

**Issue by qvduoduo1997** [matterport/Mask_RCNN#477]
i download stage1_test,stage1_train,stage1_train_labels.csv,stage2_test.However,it seems i still miss something.Can you show me how to set the files of the nucleus dataset which will be load in nucleus demo?thanks a lot.

**Comment by qvduoduo1997** [comment]
i try it in win10. And i meet the following words.
Traceback (most recent call last):
  File "nucleus.py", line 487, in <module>
    train(model, args.dataset, args.subset)
  File "nucleus.py", line 259, in train
    dataset_train.load_nucleus(dataset_dir, subset)
  File "nucleus.py", line 209, in load_nucleus
    image_ids = next(os.walk(dataset_dir))[1]
StopIteration
