### ISSUE TITLE
error when change NUM_CLASSES coco

### ISSUE THREAD

**Issue by qnkhuat** [matterport/Mask_RCNN#502]
I try to change num_classes and not use the last layer with
`model.load_weights(COCO_MODEL_PATH, by_name=True,
                           exclude=["mrcnn_class_logits", "mrcnn_bbox_fc",
                                    "mrcnn_bbox", "mrcnn_mask"])`

but i got this : 
`ValueError: Error when checking input: expected input_image_meta to have shape (16,) but got array with shape (93,)`

however it runs ok with NUM_CLASSES=81

**Comment by keineahnung2345** [comment]
Have you updated the argument NUM_CLASSES in your Config class?

**Comment by ghost** [comment]
Same problem here. But after leaving the 81 classes, although i only need 5 i still get an error with a simple dataset of 50 images and coco.py:

```Epoch 1/40
Traceback (most recent call last):
  File "coco.py", line 511, in <module>
    augmentation=augmentation)
  File "/Users/roi/Documents/Mask_RCNN/mrcnn/model.py", line 2374, in train
    use_multiprocessing=True,
  File "/Users/roi/Documents/Mask_RCNN/venv/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/Users/roi/Documents/Mask_RCNN/venv/lib/python3.6/site-packages/keras/engine/training.py", line 2042, in fit_generator
    class_weight=class_weight)
  File "/Users/roi/Documents/Mask_RCNN/venv/lib/python3.6/site-packages/keras/engine/training.py", line 1756, in train_on_batch
    check_batch_axis=True)
  File "/Users/roi/Documents/Mask_RCNN/venv/lib/python3.6/site-packages/keras/engine/training.py", line 1378, in _standardize_user_data
    exception_prefix='input')
  File "/Users/roi/Documents/Mask_RCNN/venv/lib/python3.6/site-packages/keras/engine/training.py", line 144, in _standardize_input_data
    str(array.shape))
ValueError: Error when checking input: expected input_image_meta to have shape (None, 93) but got array with shape (2, 18)```

**Comment by ZumelzuR** [comment]
Your are right, but you have edit the loading all coco dataset, you have to restrict just for your classes. In the coco example [https://github.com/matterport/Mask_RCNN/blob/master/samples/coco/coco.py](url)

you will have to change on load_coco the class_ids attribute. You have to put your classes (if you want to detect a some coco classes, if not you have to check the ballons example
 [https://github.com/matterport/Mask_RCNN/tree/master/samples/balloon](url)). For example for 2 classes could be (1,20) , where 1 and 20 are the ids of the classes of the coco dataset, you have to change that for the load_coco for train and val (also check that you put NUM_CLASSES = 1 + 2 in the case of you have 2 classes.

**Comment by Aassifh** [comment]
Even after updating all the config mentioned above i still get the same error for 4 classes, no working  solution found yet ?

**Comment by ZumelzuR** [comment]
> Even after updating all the config mentioned above i still get the same error for 4 classes, no working solution found yet ?

The solution that I put is the solution, maybe you miss some change on the file, can you share your code related with this?

**Comment by Aassifh** [comment]
It worked for me after getting the last version of Mask RCNN !

**Comment by comely0120** [comment]
same problem..please help
Error when checking input: expected input_image_meta to have shape (59,) but got array with shape (58,)

**Comment by leekwunfung817** [comment]
After I changed the number of classes, this error log doesn't change it's number.
