### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by ddurgaprasad** [matterport/Mask_RCNN#553]
Trying to install the library on Windows 10. I have python 3.6 and all tensorflow object detection dependencies are installed well. Getting errors during install

C:\maskRCNN>python setup.py install
```

running install
running bdist_egg
running egg_info
writing mask_rcnn.egg-info\PKG-INFO
writing requirements to mask_rcnn.egg-info\requires.txt
writing top-level names to mask_rcnn.egg-info\top_level.txt
writing dependency_links to mask_rcnn.egg-info\dependency_links.txt
reading manifest file 'mask_rcnn.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'mask_rcnn.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\mrcnn
copying build\lib\mrcnn\config.py -> build\bdist.win-amd64\egg\mrcnn
copying build\lib\mrcnn\model.py -> build\bdist.win-amd64\egg\mrcnn
copying build\lib\mrcnn\parallel_model.py -> build\bdist.win-amd64\egg\mrcnn
copying build\lib\mrcnn\utils.py -> build\bdist.win-amd64\egg\mrcnn
copying build\lib\mrcnn\visualize.py -> build\bdist.win-amd64\egg\mrcnn
copying build\lib\mrcnn\__init__.py -> build\bdist.win-amd64\egg\mrcnn
byte-compiling build\bdist.win-amd64\egg\mrcnn\config.py to config.cpython-35.pyc
byte-compiling build\bdist.win-amd64\egg\mrcnn\model.py to model.cpython-35.pyc
byte-compiling build\bdist.win-amd64\egg\mrcnn\parallel_model.py to parallel_model.cpython-35.pyc
byte-compiling build\bdist.win-amd64\egg\mrcnn\utils.py to utils.cpython-35.pyc
byte-compiling build\bdist.win-amd64\egg\mrcnn\visualize.py to visualize.cpython-35.pyc
byte-compiling build\bdist.win-amd64\egg\mrcnn\__init__.py to __init__.cpython-35.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying mask_rcnn.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying mask_rcnn.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying mask_rcnn.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying mask_rcnn.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying mask_rcnn.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist\mask_rcnn-2.1-py3.5.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing mask_rcnn-2.1-py3.5.egg
Removing c:\program files\anaconda3\lib\site-packages\mask_rcnn-2.1-py3.5.egg
Copying mask_rcnn-2.1-py3.5.egg to c:\program files\anaconda3\lib\site-packages
mask-rcnn 2.1 is already the active version in easy-install.pth

Installed c:\program files\anaconda3\lib\site-packages\mask_rcnn-2.1-py3.5.egg
Processing dependencies for mask-rcnn==2.1
Traceback (most recent call last):
  File "c:\program files\anaconda3\lib\site-packages\setuptools-27.2.0-py3.5.egg\pkg_resources\__init__.py", line 2523, in requires
KeyError: 'all'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 67, in <module>
    keywords="image instance segmentation object detection mask rcnn r-cnn tensorflow keras",
  File "C:\Program Files\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Program Files\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Program Files\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "c:\program files\anaconda3\lib\site-packages\setuptools-27.2.0-py3.5.egg\setuptools\command\install.py", line 67, in run
  File "c:\program files\anaconda3\lib\site-packages\setuptools-27.2.0-py3.5.egg\setuptools\command\install.py", line 117, in do_egg_install
  File "c:\program files\anaconda3\lib\site-packages\setuptools-27.2.0-py3.5.egg\setuptools\command\easy_install.py", line 409, in run
  File "c:\program files\anaconda3\lib\site-packages\setuptools-27.2.0-py3.5.egg\setuptools\command\easy_install.py", line 645, in easy_install
  File "c:\program files\anaconda3\lib\site-packages\setuptools-27.2.0-py3.5.egg\setuptools\command\easy_install.py", line 696, in install_item
  File "c:\program files\anaconda3\lib\site-packages\setuptools-27.2.0-py3.5.egg\setuptools\command\easy_install.py", line 741, in process_distribution
  File "c:\program files\anaconda3\lib\site-packages\setuptools-27.2.0-py3.5.egg\pkg_resources\__init__.py", line 862, in resolve
  File "c:\program files\anaconda3\lib\site-packages\setuptools-27.2.0-py3.5.egg\pkg_resources\__init__.py", line 2526, in requires
pkg_resources.UnknownExtra: ipython 5.1.0 has no such extra feature 'all'
```

**Comment by JJJackssson** [comment]
same error to you,have you solved it?

**Comment by chunguGuo** [comment]
same error, habe you solved it? pls reply here.

**Comment by bpinaya** [comment]
From this thread (https://github.com/ipython/ipython/issues/9968):
```
conda uninstall prompt_toolkit
pip uninstall prompt_toolkit  # Just to make sure it's not there
pip install jupyter ipython
```
That fixed it for me using conda for the env.

**Comment by Jeff-Winchell** [comment]
I have the same error message (also running Windows 10) though my conda install is a specific version Microsoft uses for SQL Server 2017, so I just did the pip uninstall and pip install for prompt_toolkit. That didn't fix this error.

**Comment by jobryant** [comment]
Try to upgrade Ipython
`pip install --upgrade "ipython[all]"`
That completely fix the problem for me.
