### ISSUE TITLE
TypeError: reduce_mean() got an unexpected keyword argument 'keepdims'

### ISSUE THREAD

**Issue by ZengyuanYu** [matterport/Mask_RCNN#572]
Like this , I am training bollon in GPUs occer this issues,in detiles:
Training network heads

Starting at epoch 0. LR=0.001

Checkpoint Path: /home/yu/Mask_RCNN/logs/balloon20180517T2146/mask_rcnn_balloon_{epoch:04d}.h5
Selecting layers to train
fpn_c5p5               (Conv2D)
fpn_c4p4               (Conv2D)
fpn_c3p3               (Conv2D)
fpn_c2p2               (Conv2D)
fpn_p5                 (Conv2D)
fpn_p2                 (Conv2D)
fpn_p3                 (Conv2D)
fpn_p4                 (Conv2D)
In model:  rpn_model
    rpn_conv_shared        (Conv2D)
    rpn_class_raw          (Conv2D)
    rpn_bbox_pred          (Conv2D)
mrcnn_mask_conv1       (TimeDistributed)
mrcnn_mask_bn1         (TimeDistributed)
mrcnn_mask_conv2       (TimeDistributed)
mrcnn_mask_bn2         (TimeDistributed)
mrcnn_class_conv1      (TimeDistributed)
mrcnn_class_bn1        (TimeDistributed)
mrcnn_mask_conv3       (TimeDistributed)
mrcnn_mask_bn3         (TimeDistributed)
mrcnn_class_conv2      (TimeDistributed)
mrcnn_class_bn2        (TimeDistributed)
mrcnn_mask_conv4       (TimeDistributed)
mrcnn_mask_bn4         (TimeDistributed)
mrcnn_bbox_fc          (TimeDistributed)
mrcnn_mask_deconv      (TimeDistributed)
mrcnn_class_logits     (TimeDistributed)
mrcnn_mask             (TimeDistributed)
Traceback (most recent call last):
  File "balloon.py", line 359, in <module>
    train(model)
  File "balloon.py", line 194, in train
    layers='heads')
  File "/home/yu/.virtualenvs/Mask_RCNN/local/lib/python3.5/site-packages/mask_rcnn-2.1-py3.5.egg/mrcnn/model.py", line 2308, in train
  File "/home/yu/.virtualenvs/Mask_RCNN/local/lib/python3.5/site-packages/mask_rcnn-2.1-py3.5.egg/mrcnn/model.py", line 2143, in compile
TypeError: reduce_mean() got an unexpected keyword argument 'keepdims'

tf = 1.4 keras =2.0.8 I hope anyone fix it .thank you!

**Comment by patrick-12sigma** [comment]
See [this commit](https://github.com/matterport/Mask_RCNN/commit/4129a27275c48c672f6fd8c6303a88ba1eed643b). You can go to this script and change it back to `keep_dims` or update to tf 1.5+.

**Comment by celsomilne** [comment]
Should requirements.txt be updated to reflect the need for tf>=1.5?
