### ISSUE TITLE
when set "GPU_COUNT=2" , got a TypeError: List of Tensors when single Tensor expected

### ISSUE THREAD

**Issue by lssily** [matterport/Mask_RCNN#574]
In order to speed up the training rate on coco dataset, i set "GPU_COUNT=2". But I got the following problem:

Command:  train
Model:  coco
Dataset:  /data/liaoshisha/Mask_RCNN-master/coco
Year:  2014
Logs:  /data/liaoshisha/Mask_RCNN-master/logs
Auto Download:  False

Configurations:
BACKBONE                       resnet101
BACKBONE_STRIDES               [4, 8, 16, 32, 64]
BATCH_SIZE                     4
BBOX_STD_DEV                   [0.1 0.1 0.2 0.2]
DETECTION_MAX_INSTANCES        100
DETECTION_MIN_CONFIDENCE       0.7
DETECTION_NMS_THRESHOLD        0.3
GPU_COUNT                      2
GRADIENT_CLIP_NORM             5.0
IMAGES_PER_GPU                 2
IMAGE_MAX_DIM                  1024
IMAGE_META_SIZE                93
IMAGE_MIN_DIM                  800
IMAGE_MIN_SCALE                0
IMAGE_RESIZE_MODE              square
IMAGE_SHAPE                    [1024 1024    3]
LEARNING_MOMENTUM              0.9
LEARNING_RATE                  0.001
MASK_POOL_SIZE                 14
MASK_SHAPE                     [28, 28]
MAX_GT_INSTANCES               100
MEAN_PIXEL                     [123.7 116.8 103.9]
MINI_MASK_SHAPE                (56, 56)
NAME                           coco
NUM_CLASSES                    81
POOL_SIZE                      7
POST_NMS_ROIS_INFERENCE        1000
POST_NMS_ROIS_TRAINING         2000
ROI_POSITIVE_RATIO             0.33
RPN_ANCHOR_RATIOS              [0.5, 1, 2]
RPN_ANCHOR_SCALES              (32, 64, 128, 256, 512)
RPN_ANCHOR_STRIDE              1
RPN_BBOX_STD_DEV               [0.1 0.1 0.2 0.2]
RPN_NMS_THRESHOLD              0.7
RPN_TRAIN_ANCHORS_PER_IMAGE    256
STEPS_PER_EPOCH                1000
TRAIN_BN                       False
TRAIN_ROIS_PER_IMAGE           200
USE_MINI_MASK                  True
USE_RPN_ROIS                   True
VALIDATION_STEPS               50
WEIGHT_DECAY                   0.0001

Traceback (most recent call last):
  File "coco.py", line 455, in <module>
    model = modellib.MaskRCNN(mode="training", config=config, model_dir=args.logs)
  File "/home/liaoshisha/anaconda3/envs/tensorflow/lib/python3.4/site-packages/mask_rcnn-2.1-py3.4.egg/mrcnn/model.py", line 1820, in __init__
  File "/home/liaoshisha/anaconda3/envs/tensorflow/lib/python3.4/site-packages/mask_rcnn-2.1-py3.4.egg/mrcnn/model.py", line 2039, in build
  File "/home/liaoshisha/anaconda3/envs/tensorflow/lib/python3.4/site-packages/mask_rcnn-2.1-py3.4.egg/mrcnn/parallel_model.py", line 37, in __init__
  File "/home/liaoshisha/anaconda3/envs/tensorflow/lib/python3.4/site-packages/mask_rcnn-2.1-py3.4.egg/mrcnn/parallel_model.py", line 81, in make_parallel
  File "/home/liaoshisha/anaconda3/envs/tensorflow/lib/python3.4/site-packages/keras/engine/topology.py", line 619, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/liaoshisha/anaconda3/envs/tensorflow/lib/python3.4/site-packages/keras/engine/topology.py", line 2085, in call
    output_tensors, _, _ = self.run_internal_graph(inputs, masks)
  File "/home/liaoshisha/anaconda3/envs/tensorflow/lib/python3.4/site-packages/keras/engine/topology.py", line 2236, in run_internal_graph
    output_tensors = _to_list(layer.call(computed_tensor, **kwargs))
  File "/home/liaoshisha/anaconda3/envs/tensorflow/lib/python3.4/site-packages/keras/layers/core.py", line 663, in call
    return self.function(inputs, **arguments)
  File "/home/liaoshisha/anaconda3/envs/tensorflow/lib/python3.4/site-packages/mask_rcnn-2.1-py3.4.egg/mrcnn/model.py", line 1913, in <lambda>
  File "/home/liaoshisha/anaconda3/envs/tensorflow/lib/python3.4/site-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/liaoshisha/anaconda3/envs/tensorflow/lib/python3.4/site-packages/tensorflow/python/framework/tensor_util.py", line 376, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/home/liaoshisha/anaconda3/envs/tensorflow/lib/python3.4/site-packages/tensorflow/python/framework/tensor_util.py", line 299, in _AssertCompatible
    raise TypeError("List of Tensors when single Tensor expected")
TypeError: List of Tensors when single Tensor expected

I don't know what's wrong. Look forward to your help!

NOTE: Even if i change from tf.constant to tf.Variable, but i didn't deal with this problem.

**Comment by lssily** [comment]
Downloading the newst mask rcnn code could solve this problem.

**Comment by amardeepjaiman** [comment]
I have the latest code but I still get this issue.

**Comment by Fred-Macdo** [comment]
I am also receiving this issue. Works fine when using 1 gpu but I get the 
TypeError: List of Tensors when single Tensor expected when I try to use the 8 GPU's on my AWS ps.8xlarge instance.
