### ISSUE TITLE
While trying to train I get error "zmq.error.ZMQError: Address already in use"

### ISSUE THREAD

**Issue by thephet** [matterport/Mask_RCNN#584]
I have been using this project for like 2 months, and it was fine. Suddenly since last week, I am getting the error:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/usr/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 448, in initialize
    self.init_sockets()
  File "/usr/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 238, in init_sockets
    self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
  File "/usr/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 180, in _bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "zmq/backend/cython/socket.pyx", line 495, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use

when trying to train with 

model.train(dataset, dataset, 
            learning_rate=config.LEARNING_RATE, 
            epochs=10, 
            layers='heads')

I am doing a very small variation of the shapes project in the demos, but with my own images.

I am using the GPU (Nvidia) and I am using arch-linux. I am running my code through a Jupyter Notebook, and eventually I receive a message saying that the kernel crashed.

As said, this code was working like 2-3 weeks ago, and as far as I can tell I didn't change anything.

Thanks for your help

**Comment by thephet** [comment]
I have isolated the error to RPN_ANCHOR_SCALES in the Config. It seems when I used small ones, such as 4 8 16 32 64, it failed.

**Comment by WanyiLi** [comment]
@thephet I met the error too, when I change the "init_with from "imagenet" to "coco", it works. It seems that the error is related to the size of gpu memory.

**Comment by jakefleisig** [comment]
I am getting this exact error while trying to perform road segmentation training on a dataset of just 100 images, all 832x832, on 2 GPUs.  I use the pretrained coco weights file, train the heads, and then fine tune.  Sometimes this error occurs while training the heads, sometimes it occurs during fine tuning.  I train for 10 epochs each (10 for the heads and 10 for fine tuning) with 100 steps per epoch.  Any help would be greatly appreciated.  Here is a snapshot of my configurations:

```
class RoadsConfig(Config):
    # Give the configuration a recognizable name
    NAME = "roads"
    
    # Network used
    BACKBONE = "resnet50"

    # Train on 2 GPUs w/ one image per gpu
    GPU_COUNT = 2
    IMAGES_PER_GPU = 1

    # Number of classes (including background)
    NUM_CLASSES = 1 + 1  # background + road

    # Number of color channels
    IMAGE_CHANNEL_COUNT = 3
    
    # Image size
    IMAGE_RESIZE_MODE = 'square'
    IMAGE_MAX_DIM = 832

    # Anchor scales
    RPN_ANCHOR_SCALES = (32, 64, 128, 256, 512)  # anchor size in pixels
    
    # Use mini-masks the size of roads
    USE_MINI_MASK = True
    MINI_MASK_SHAPE = (56, 56)
    
    # Detection threshold
    DETECTION_MIN_CONFIDENCE = 0.5

    # Maximum number of ground truth instances to use in one image
    MAX_GT_INSTANCES = 50
    
    # Max number of final detections
    DETECTION_MAX_INSTANCES = 50

    TRAIN_ROIS_PER_IMAGE = 128

    STEPS_PER_EPOCH = 100

    # Use small validation steps since the epoch is small
    VALIDATION_STEPS = 5
    
    # Change the learning rate and momentum
    LEARNING_RATE = 0.001
    LEARNING_MOMENTUM = 0.9
```

**Comment by jakefleisig** [comment]
Solved this issue.  I was running jupyter notebook with docker and did not allocate enough memory to the notebook.

**Comment by qubvel** [comment]
Hi @jakefleisig 
I have the same error, how did you allocate more memory for your notebook? 

P.S. also use docker
P.S.S. Solved TF 1.8.0 -> TF 1.9.0 (#521)

**Comment by jakefleisig** [comment]
Hey, @qubvel. You can allocate more memory to the note book by specifying it in a makefile like such:

```
docker:
        docker image build -t keras --network=host -f Dockerfile .

notebook:
        docker run -it --rm \
                --runtime=nvidia \
                -p $(JN_PORT):$(JN_PORT) \
                -v $(WORKING_DIR):/root \
                -v $(DATA_DIR):/xview_data \
                -w /root \
                --shm-size 2g \
                keras /bin/bash -c "jupyter notebook --no-browser --port $(JN_PORT) --ip 0.0.0.0 --allow-root --NotebookApp.token= --notebook-dir='/root'"
```

'--shm-size' is what allocates the memory and JN_PORT is just the local host number for the notebook.  I have not tried updating tensorflow, though. That could help too.  Thanks for the tip!
