### ISSUE TITLE
KeyError: 'id' 

### ISSUE THREAD

**Issue by world4jason** [matterport/Mask_RCNN#598]
when i want to train on cityscapes dataset
https://gist.github.com/world4jason/7dcd595894a15aeed85f3a575dba003c

        class CityscapesDataset(utils.Dataset):
            def load_cityscapes(self, dataset_dir, subset):

                for i in range(len(self.class_labels)):
                    self.add_class("cityscape", i, list(self.class_labels.keys())[i])

                for idx in range(len(self.image_info)):
                    self.add_image(
                           source = self.image_info[idx]['source'],
                           image_id = self.image_info[idx]['image_id'],
                           path=self.image_info[idx]['path'],
                           width=self.image_info[idx]['imgWidth'],
                           height=self.image_info[idx]['imgHeight']
                      )
I always got error message like this

Traceback (most recent call last):
  File "cityscape.py", line 338, in <module>
    dataset_train.prepare()
  File "/home/world4jason/Mask_RCNN/mrcnn/utils.py", line 316, in prepare
    for info, id in zip(self.image_info, self.image_ids)}
  File "/home/world4jason/Mask_RCNN/mrcnn/utils.py", line 316, in <dictcomp>
    for info, id in zip(self.image_info, self.image_ids)}
KeyError: 'id'

always stop here in utils.py

        self.class_from_source_map = {"{}.{}".format(info['source'], info['id']): id
                                      for info, id in zip(self.image_info, self.image_ids))}
is there any clue?

**Comment by world4jason** [comment]
i figured it out....
i shouldn't use 'self.image_info' here
