### ISSUE TITLE
KeyError: 'all_points_y'

### ISSUE THREAD

**Issue by eyildiz-ugoe** [matterport/Mask_RCNN#608]
Hi,

I am trying to make this work for two days with the dataset I have. I am using TF 1.7. CuDNN 7 and CUDA 9.

My dataset consists of devices and I have only 2 classes apart from the background. I've annotated the parts in the devices by naming them. Am I doing something wrong with the annotation, perhaps? [You can check the .json file here.](https://gist.github.com/eyildiz-ugoe/8ceb1f5f44d8d65f465818b324d7fd37)

I've downloaded the weights of ImageNet (since coco weights did not work for me, gave an error) and after launching the program I get to see the following:

```
Selecting layers to train
fpn_c5p5               (Conv2D)
fpn_c4p4               (Conv2D)
fpn_c3p3               (Conv2D)
fpn_c2p2               (Conv2D)
fpn_p5                 (Conv2D)
fpn_p2                 (Conv2D)
fpn_p3                 (Conv2D)
fpn_p4                 (Conv2D)
In model:  rpn_model
    rpn_conv_shared        (Conv2D)
    rpn_class_raw          (Conv2D)
    rpn_bbox_pred          (Conv2D)
mrcnn_mask_conv1       (TimeDistributed)
mrcnn_mask_bn1         (TimeDistributed)
mrcnn_mask_conv2       (TimeDistributed)
mrcnn_mask_bn2         (TimeDistributed)
mrcnn_class_conv1      (TimeDistributed)
mrcnn_class_bn1        (TimeDistributed)
mrcnn_mask_conv3       (TimeDistributed)
mrcnn_mask_bn3         (TimeDistributed)
mrcnn_class_conv2      (TimeDistributed)
mrcnn_class_bn2        (TimeDistributed)
mrcnn_mask_conv4       (TimeDistributed)
mrcnn_mask_bn4         (TimeDistributed)
mrcnn_bbox_fc          (TimeDistributed)
mrcnn_mask_deconv      (TimeDistributed)
mrcnn_class_logits     (TimeDistributed)
mrcnn_mask             (TimeDistributed)
/home/username/.local/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py:100: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
/home/username/.local/lib/python3.5/site-packages/keras/engine/training.py:2087: UserWarning: Using a generator with `use_multiprocessing=True` and multiple workers may duplicate your data. Please consider using the`keras.utils.Sequence class.
  UserWarning('Using a generator with `use_multiprocessing=True`'
ERROR:root:Error processing image {'path': '../../datasets/component_front/train/12_img.jpg', 'polygons': [{'name': 'rect', 'height': 1021, 'y': 153, 'x': 167, 'width': 709}, {'name': 'circle', 'r': 21, 'cy': 207, 'cx': 843}, {'name': 'circle', 'r': 21, 'cy': 1112, 'cx': 855}, {'name': 'circle', 'r': 22, 'cy': 741, 'cx': 851}, {'name': 'circle', 'r': 26, 'cy': 743, 'cx': 180}, {'name': 'circle', 'r': 21, 'cy': 1116, 'cx': 182}, {'name': 'circle', 'r': 20, 'cy': 208, 'cx': 188}], 'id': '12_img.jpg', 'height': 1433, 'source': 'component', 'width': 1075}
Traceback (most recent call last):
  File "/home/username/workspace/Mask_RCNN/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/username/workspace/Mask_RCNN/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "component_front.py", line 130, in load_mask
    rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
KeyError: 'all_points_y'
```

The full error message is too long to post here, but in short it keeps telling that there is an error with  "all_points_y". Any idea about what's going on?

**Comment by eyildiz-ugoe** [comment]
How should the annotations look like, if I have two classes to annotate? Is [this](https://ibb.co/fah9ay) correct for load function to work with? I have only two classes to annotate. How complicated can this get, seriously?

**Comment by zungam** [comment]
Your annotation looks fine. I dont know how you save it - in what format you annotation looks like. You should write a load_mask function which takes in your annotation (say .json), and convert it to a matrix which looks like this:

![image](https://user-images.githubusercontent.com/11159388/40733462-05a4d8bc-6436-11e8-91c1-30aa278c921f.png)

This is a three dimentional numpy bool array with three masks.
1 here is True,
0 here is False.
The shape would in this example would be (9, 15, 3) where 9 is the height of the total image and 15 is the width of the total image, 3 is the amount of masks.

**Comment by eyildiz-ugoe** [comment]
Well, I am using the very same implementation with `Balloon.py`. I haven't change a single thing in the load_mask function. It is not "homemade", it is what the repository provides. Nothing I constructed. I am just increasing the class number by 1 and it does not work. I guess I need to use another example which illustrates a multiple-class usage. Coco or shapes, perhaps.  I have also noticed that load_mask function of mine should be able to deal with overlays since I have overlaying annotations (screws are in the region of lid). `Balloon.py` may not be the best example to start with, therefore. I'll try adapting shapes to my example since at least there are multiple classes there. I'll see how it goes.

**Comment by zungam** [comment]
Did you use the same labeling program as the tutorial specified? Different labeling programs produce different types of .json files.

I believe mask_rcnn can do overlays automatically.

**Comment by zungam** [comment]
I would recomend looking into how the json file stores polygons.
It probably loops through all masks which is stored as a polygon,
        then it makes a numpy bool image with width/height=image width and height.
              then it loops through all pixels in the images and [checks if the pixel is inside the polygon](https://stackoverflow.com/questions/36399381/whats-the-fastest-way-of-checking-if-a-point-is-inside-a-polygon-in-python). (See link)
          Then it stores these pixels to the numpy bool array.
Lastly, it stacks all numpy arrays into a 3D numpy array containing all masks, using numpy.stack

**Comment by eyildiz-ugoe** [comment]
Thank you for explaining how it interpreted the annotated images, but my question was directed towards how the images were labeled in the first place, by the author. Did the author just click on the balloon outlines in the images without any regional attributes or naming? Because that's how I did with screws and it does not work. If there is an additional step taken while annotating the images, one must know it, otherwise the generated .json files would have different column/row specs and obviously the loader wouldn't work; would probably give an error like 'all_points_y' which is what I am getting.

**Comment by eyildiz-ugoe** [comment]
Okay, I've finally figured out what the problem was. For all those out there who experience the same:

The code handles polygonal annotations ONLY. This means, if you annotate your images using circles, rectangles, etc. it won't load them, since it looks for "polygons" only. That being said, try to annotate your images by using polygons then it works as it is.

**Comment by eyildiz-ugoe** [comment]
So after sometime, I've noticed that even after converting the circles to polygons, you get this error right in this line:

```
for i, p in enumerate(info["polygons"]):
            # Get indexes of pixels inside the polygon and set them to 1
            rr, cc = skimage.draw.polygon(p['all_points_y'], p['all_points_x'])
            mask[rr, cc, i] = 1
```

**Comment by mymultiverse** [comment]
I had same issue I tried this to convert. 
Thanks to [ref. ](https://github.com/matterport/Mask_RCNN/issues/928#issuecomment-421535356)

```
import json
from pprint import pprint
import numpy as np

N = 10

thita = np.linspace(0, 3.14, N)
with open('via_region_dataCir.json') as f:
    data = json.load(f)

    for attr, val in data.items():
        for attr2, val2 in val.items():
            if attr2 == 'regions':
                for attr3, val3 in val2.items():
                    if val3['shape_attributes']['name'] == 'circle':
                        cx = val3['shape_attributes']['cx']
                        cy = val3['shape_attributes']['cy']
                        r = val3['shape_attributes']['r']
                        
                        all_points_x = [r*np.cos(i) for i in thita]
                        all_points_y = [r*np.cos(i) for i in thita]
                        
                        val3['shape_attributes']['cx'] = all_points_x
                        val3['shape_attributes']['cy'] = all_points_y

                        val3['shape_attributes']['all_points_x'] = val3['shape_attributes'].pop('cx')
                        val3['shape_attributes']['all_points_y'] = val3['shape_attributes'].pop('cy')
                        val3['shape_attributes']['name'] = 'polygon'


pprint(data)

with open('via_region_data.json', 'w') as f:
    json.dump(data, f)
```
