### ISSUE TITLE
module 'setuptools.dist' has no attribute 'check_specifier'

### ISSUE THREAD

**Issue by seansun32** [matterport/Mask_RCNN#612]
When I run `python3 setup.py install`, the error log comes out
```
File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2237, in resolve
AttributeError: module 'setuptools.dist' has no attribute 'check_specifier'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 67, in <module>
    keywords="image instance segmentation object detection mask rcnn r-cnn tensorflow keras",
  File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/share/python-wheels/setuptools-20.7.0-py2.py3-none-any.whl/setuptools/dist.py", line 272, in __init__
  File "/usr/lib/python3.5/distutils/dist.py", line 281, in __init__
    self.finalize_options()
  File "/usr/share/python-wheels/setuptools-20.7.0-py2.py3-none-any.whl/setuptools/dist.py", line 327, in finalize_options
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2229, in load
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2239, in resolve
ImportError: module 'setuptools.dist' has no attribute 'check_specifier'
```

from `easy_install --version` ,below is my setup tools version
```setuptools 39.2.0 from /home/seansun/.local/lib/python3.5/site-packages (Python 3.5)```

somebody please give a help

**Comment by PratibhaT** [comment]
I'm getting same error. How did you resolve this?

**Comment by Jilliansea** [comment]
@seansun32 so where should i run the command? not maskrcnn root dir?

**Comment by seansun32** [comment]
@Jilliansea Mask_RCNN/samples/coco/

**Comment by acamargofb** [comment]
I am having the same problem, I follow the following steps:

1. Install dependencies
   ```bash
   pip3 install -r requirements.txt
   ```
2. Clone this repository
3. Run setup from the repository root directory
    ```bash
    python3 setup.py install
Traceback (most recent call last):
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2237, in resolve
AttributeError: module 'setuptools.dist' has no attribute 'check_specifier'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 67, in <module>
    keywords="image instance segmentation object detection mask rcnn r-cnn tensorflow keras",
  File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/share/python-wheels/setuptools-20.7.0-py2.py3-none-any.whl/setuptools/dist.py", line 272, in __init__
  File "/usr/lib/python3.5/distutils/dist.py", line 281, in __init__
    self.finalize_options()
  File "/usr/share/python-wheels/setuptools-20.7.0-py2.py3-none-any.whl/setuptools/dist.py", line 327, in finalize_options
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2229, in load
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2239, in resolve
ImportError: module 'setuptools.dist' has no attribute 'check_specifier'

**Comment by nhjkjh0608** [comment]
@acamargofb  @seansun32  @PratibhaT 
Hello
I solved this error.
This might be helpful.

pip install --upgrade pip
hash -r pip
pip3 install --upgrade pip
hash -r pip3
cd (Mask RCNN root folder)
python3 setup.py install
