### ISSUE TITLE
image file not found error even when the file is there

### ISSUE THREAD

**Issue by Suvi-dha** [matterport/Mask_RCNN#616]
I am training on my own dataset using imagenet pretrained weights. My image size is 512x512x3. I converted image masks into cocostyle json format and the annotation files for both training and validation loaded successfuly. However after that point I am getting file not found error on several files despite the files being present in the path. I checked my path several times to ensure that it is correct. The files on which error is occuring changes everytime i rerun the code. 
Posting the traceback

```
C:\Users\IIITA\Anaconda3\lib\site-packages\tensorflow\python\ops\gradients_impl.py:100: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Epoch 1/40
ERROR:root:Error processing image {'id': 20180006971, 'source': 'coco', 'path': 'C:/Users/IIITA/Documents/Mask_RCNN-master/Mask_RCNN-master/DATASET/BACH//train2018\\A04_0_14336_44032_INVASIVE CARCINOMA', 'width': 512, 'height': 512, 'annotations': [{'segmentation': [[44033.0, 14337.0, 44033.0, 14848.0, 44544.0, 14848.0, 44544.0, 14337.0]], 'area': 261121.0, 'iscrowd': 0, 'ignore': 0, 'image_id': 20180006971, 'bbox': [44033.0, 14337.0, 511.0, 511.0], 'category_id': 2, 'id': 7339}]}
Traceback (most recent call last):
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\mask_rcnn-2.1-py3.6.egg\mrcnn\model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\mask_rcnn-2.1-py3.6.egg\mrcnn\model.py", line 1209, in load_image_gt
    image = dataset.load_image(image_id)
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\mask_rcnn-2.1-py3.6.egg\mrcnn\utils.py", line 364, in load_image
    image = skimage.io.imread(self.image_info[image_id]['path'])
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\skimage\io\_io.py", line 61, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\skimage\io\manage_plugins.py", line 211, in call_plugin
    return func(*args, **kwargs)
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\skimage\io\_plugins\pil_plugin.py", line 35, in imread
    with open(fname, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/IIITA/Documents/Mask_RCNN-master/Mask_RCNN-master/DATASET/BACH//train2018\\A04_0_14336_44032_INVASIVE CARCINOMA'
ERROR:root:Error processing image {'id': 20180003246, 'source': 'coco', 'path': 'C:/Users/IIITA/Documents/Mask_RCNN-master/Mask_RCNN-master/DATASET/BACH//train2018\\A02_0_14848_41984_CARCINOMA INVASIVE', 'width': 512, 'height': 512, 'annotations': [{'segmentation': [[41985.0, 14849.0, 41985.0, 15360.0, 42496.0, 15360.0, 42496.0, 14849.0]], 'area': 261121.0, 'iscrowd': 0, 'ignore': 0, 'image_id': 20180003246, 'bbox': [41985.0, 14849.0, 511.0, 511.0], 'category_id': 4, 'id': 3511}]}
Traceback (most recent call last):
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\mask_rcnn-2.1-py3.6.egg\mrcnn\model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\mask_rcnn-2.1-py3.6.egg\mrcnn\model.py", line 1209, in load_image_gt
    image = dataset.load_image(image_id)
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\mask_rcnn-2.1-py3.6.egg\mrcnn\utils.py", line 364, in load_image
    image = skimage.io.imread(self.image_info[image_id]['path'])
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\skimage\io\_io.py", line 61, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\skimage\io\manage_plugins.py", line 211, in call_plugin
    return func(*args, **kwargs)
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\skimage\io\_plugins\pil_plugin.py", line 35, in imread
    with open(fname, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/IIITA/Documents/Mask_RCNN-master/Mask_RCNN-master/DATASET/BACH//train2018\\A02_0_14848_41984_CARCINOMA INVASIVE'
ERROR:root:Error processing image {'id': 20180007623, 'source': 'coco', 'path': 'C:/Users/IIITA/Documents/Mask_RCNN-master/Mask_RCNN-master/DATASET/BACH//train2018\\A04_0_16896_62464_INVASIVE CARCINOMA', 'width': 512, 'height': 512, 'annotations': [{'segmentation': [[62465.0, 16897.0, 62465.0, 17408.0, 62976.0, 17408.0, 62976.0, 16897.0]], 'area': 261121.0, 'iscrowd': 0, 'ignore': 0, 'image_id': 20180007623, 'bbox': [62465.0, 16897.0, 511.0, 511.0], 'category_id': 2, 'id': 7991}]}
Traceback (most recent call last):
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\mask_rcnn-2.1-py3.6.egg\mrcnn\model.py", line 1695, in data_generator
    **use_mini_mask=config.USE_MINI_MASK**)
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\mask_rcnn-2.1-py3.6.egg\mrcnn\model.py", line 1209, in load_image_gt
    image = dataset.load_image(image_id)
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\mask_rcnn-2.1-py3.6.egg\mrcnn\utils.py", line 364, in load_image
    image = skimage.io.imread(self.image_info[image_id]['path'])
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\skimage\io\_io.py", line 61, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\skimage\io\manage_plugins.py", line 211, in call_plugin
    return func(*args, **kwargs)
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\skimage\io\_plugins\pil_plugin.py", line 35, in imread
    with open(fname, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/IIITA/Documents/Mask_RCNN-master/Mask_RCNN-master/DATASET/BACH//train2018\\A04_0_16896_62464_INVASIVE CARCINOMA'
ERROR:root:Error processing image {'id': 20180020591, 'source': 'coco', 'path': 'C:/Users/IIITA/Documents/Mask_RCNN-master/Mask_RCNN-master/DATASET/BACH//train2018\\A07_0_20992_32256_INVASIVE CARCINOMA', 'width': 512, 'height': 512, 'annotations': [{'segmentation': [[32257.0, 20993.0, 32257.0, 21504.0, 32768.0, 21504.0, 32768.0, 20993.0]], 'area': 261121.0, 'iscrowd': 0, 'ignore': 0, 'image_id': 20180020591, 'bbox': [32257.0, 20993.0, 511.0, 511.0], 'category_id': 2, 'id': 21026}]}
Traceback (most recent call last):
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\mask_rcnn-2.1-py3.6.egg\mrcnn\model.py", line 1695, in data_generator
    **use_mini_mask=config.USE_MINI_MAS**K)
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\mask_rcnn-2.1-py3.6.egg\mrcnn\model.py", line 1209, in load_image_gt
    image = dataset.load_image(image_id)
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\mask_rcnn-2.1-py3.6.egg\mrcnn\utils.py", line 364, in load_image
    image = skimage.io.imread(self.image_info[image_id]['path'])
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\skimage\io\_io.py", line 61, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\skimage\io\manage_plugins.py", line 211, in call_plugin
    return func(*args, **kwargs)
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\skimage\io\_plugins\pil_plugin.py", line 35, in imread
    with open(fname, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/IIITA/Documents/Mask_RCNN-master/Mask_RCNN-master/DATASET/BACH//train2018\\A07_0_20992_32256_INVASIVE CARCINOMA'
ERROR:root:Error processing image {'id': 20180009682, 'source': 'coco', 'path': 'C:/Users/IIITA/Documents/Mask_RCNN-master/Mask_RCNN-master/DATASET/BACH//train2018\\A04_0_25600_45568_INVASIVE CARCINOMA', 'width': 512, 'height': 512, 'annotations': [{'segmentation': [[45569.0, 25601.0, 45569.0, 26112.0, 46080.0, 26112.0, 46080.0, 25601.0]], 'area': 261121.0, 'iscrowd': 0, 'ignore': 0, 'image_id': 20180009682, 'bbox': [45569.0, 25601.0, 511.0, 511.0], 'category_id': 2, 'id': 10050}]}
Traceback (most recent call last):
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\mask_rcnn-2.1-py3.6.egg\mrcnn\model.py", line 1695, in data_generator
    **use_mini_mask=config.USE_MINI_MASK**)
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\mask_rcnn-2.1-py3.6.egg\mrcnn\model.py", line 1209, in load_image_gt
    image = dataset.load_image(image_id)
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\mask_rcnn-2.1-py3.6.egg\mrcnn\utils.py", line 364, in load_image
    image = skimage.io.imread(self.image_info[image_id]['path'])
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\skimage\io\_io.py", line 61, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\skimage\io\manage_plugins.py", line 211, in call_plugin
    return func(*args, **kwargs)
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\skimage\io\_plugins\pil_plugin.py", line 35, in imread
    with open(fname, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/IIITA/Documents/Mask_RCNN-master/Mask_RCNN-master/DATASET/BACH//train2018\\A04_0_25600_45568_INVASIVE CARCINOMA'
ERROR:root:Error processing image {'id': 20180013305, 'source': 'coco', 'path': 'C:/Users/IIITA/Documents/Mask_RCNN-master/Mask_RCNN-master/DATASET/BACH//train2018\\A04_0_40960_42496_INVASIVE CARCINOMA', 'width': 512, 'height': 512, 'annotations': [{'segmentation': [[42497.0, 40961.0, 42497.0, 41472.0, 43008.0, 41472.0, 43008.0, 40961.0]], 'area': 261121.0, 'iscrowd': 0, 'ignore': 0, 'image_id': 20180013305, 'bbox': [42497.0, 40961.0, 511.0, 511.0], 'category_id': 2, 'id': 13673}]}
Traceback (most recent call last):
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\mask_rcnn-2.1-py3.6.egg\mrcnn\model.py", line 1695, in data_generator
    **use_mini_mask=config.USE_MINI_MASK)**
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\mask_rcnn-2.1-py3.6.egg\mrcnn\model.py", line 1209, in load_image_gt
    image = dataset.load_image(image_id)
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\mask_rcnn-2.1-py3.6.egg\mrcnn\utils.py", line 364, in load_image
    image = skimage.io.imread(self.image_info[image_id]['path'])
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\skimage\io\_io.py", line 61, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\skimage\io\manage_plugins.py", line 211, in call_plugin
    return func(*args, **kwargs)
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\skimage\io\_plugins\pil_plugin.py", line 35, in imread
    with open(fname, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/IIITA/Documents/PHD/ICIAR2018_BACH_Challenge/Mask_RCNN-master/Mask_RCNN-master/DATASET/BACH//train2018\\A04_0_40960_42496_INVASIVE CARCINOMA'
Traceback (most recent call last):
  File "bach.py", line 502, in <module>
    **augmentation=augmentation)**
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\mask_rcnn-2.1-py3.6.egg\mrcnn\model.py", line 2328, in train
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\keras\engine\training.py", line 2192, in fit_generator
    generator_output = next(output_generator)
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\mask_rcnn-2.1-py3.6.egg\mrcnn\model.py", line 1695, in data_generator
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\mask_rcnn-2.1-py3.6.egg\mrcnn\model.py", line 1209, in load_image_gt
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\mask_rcnn-2.1-py3.6.egg\mrcnn\utils.py", line 364, in load_image
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\skimage\io\_io.py", line 61, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\skimage\io\manage_plugins.py", line 211, in call_plugin
    return func(*args, **kwargs)
  File "C:\Users\IIITA\Anaconda3\lib\site-packages\skimage\io\_plugins\pil_plugin.py", line 35, in imread
    with open(fname, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/IIITA/Documents/Mask_RCNN-master/Mask_RCNN-master/DATASET/BACH//train2018\\A04_0_40960_42496_INVASIVE CARCINOMA'
```
What could be the possible cause of this error? it's wierd because everytime the image files are changing. Also, at two places this error is happening 
1. line 1695 of model.py 
2. line 502 of coco.py

**Comment by zungam** [comment]
I see you use

> `'C:/Users/IIITA/Documents/Mask_RCNN-master/Mask_RCNN-master/DATASET/BACH//train2018\\A04_0_14336_44032_INVASIVE CARCINOMA`

See the inconsistent use of backslash?

Depending on your operating system, documentation on correct using of slashes: [here](https://medium.com/@ageitgey/python-3-quick-tip-the-easy-way-to-deal-with-file-paths-on-windows-mac-and-linux-11a072b58d5f)

**Comment by Suvi-dha** [comment]
Nope, the error is not because of the backslash or forward slash because, it is loading annotation data using the same format successfully. Also, this should have meant error for all files but, it isn't the case. It is showing errors for some files at a time and  every time i rerun the code there are different set of files throwing this error. .

**Comment by ronykalfarisi** [comment]
Hi @Suvi-dha , I have the same problem how did you fix it? Thanks

**Comment by ronykalfarisi** [comment]
Hi @Suvi-dha ,
Thanks for the suggestion, for my case, the problem is the path that I passed to train.py

**Comment by baddemiya** [comment]
i am facing the same issue. i have both the file extension as well as the location right. but still i get below error:

Traceback (most recent call last):
  File "/home/pi/pygame_bg.py", line 9, in <module>
    bg_image = io.imread(fname = dir_files[0], as_grey=True)
  File "/usr/lib/python3/dist-packages/skimage/io/_io.py", line 61, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "/usr/lib/python3/dist-packages/skimage/io/manage_plugins.py", line 211, in call_plugin
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/skimage/io/_plugins/pil_plugin.py", line 35, in imread
    with open(fname, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'image_1.jpg'

**Comment by godiemp** [comment]
@baddemiya did you solve it?

**Comment by flit86** [comment]
@baddemiya , @diegoempi hi. i have the same error. Did you solve it?

**Comment by ronykalfarisi** [comment]
To everyone who come here because you got the error. The solution is to always print out the path of your training data for debugging purposes. Once you see the path, you'll always find the solution and realize the silly mistakes.

Good luck...

**Comment by flit86** [comment]
many thanks for your advice @ronykalfarisi

**Comment by torta24x** [comment]
For me, the problem was,m while manually splitting the dataset  into "train" and "val" I mistakenly put the JSON and jpg file in different folders 
For example -
 **"jpg" file in "val" and "json" file in "train"**
Hope this helps.

**Comment by steve7158** [comment]
I faced the same problem while i was training(In keras but dont worry this solution is workaround for generally for all frameworks ;*maybe*; given you have a big dataset to train on) by using a generator function. What i did was put the function preparing and producing the image for each batch, i placed it in a try block to overlook such errors. Use this as a final resort.

**Comment by steve7158** [comment]
```
def batch_generator(image_paths, batch_size):
    while True:
        batch_img=[]
        batch_names=[]

        for i in range(batch_size):
            random_index=random.randint(0, len(image_paths)-1)
            
            batch_names.append(image_paths[random_index])
            try:
                im=mpimg.imread(image_paths[random_index])
                im=cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
                im=cv2.resize(im, (124,124))
                im=np.reshape(im,(124, 124, 1))
                batch_img.append(im)
            except Exception as e:
                print(image_paths[random_index])
        yield(np.asarray(batch_img),np.asarray(batch_img))
```

and the fit_generator function:
```
from keras.callbacks import TensorBoard
batch_size=107
history=autoencoder.fit_generator(batch_generator(X_train, batch_size),
                        epochs=50,
                        steps_per_epoch=493,
                        shuffle=1,
                        verbose=1,
                        validation_data=batch_generator(X_test, batch_size),
                        validation_steps=165,
                        callbacks=[TensorBoard(log_dir='/tmp/autoencoder_AI')]
                        )
```

Hope this helps for anyone looking for an answer.

**Comment by steve7158** [comment]
In the end i solved mine, it was a silly mistake in the filepaths, 
So both ways works.

**Comment by malokroman** [comment]
I got the same error, but my case was instead that the file was corrupted. So it was okay after I removed it.
