### ISSUE TITLE
Unable to build pycocotools on windows

### ISSUE THREAD

**Issue by CptK1ng** [matterport/Mask_RCNN#621]
Hi,
i am currently try to install pycocotools on windows 10.
I tried to install MSBuild Tools 2017 (unable to find working 2015 version) and cython and use  `pip install git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI` to get the pycocotools but it didn't worked.

I tried to install after i cloned it running all methods 

i am running everytime in the same error messaged added below:

NOTE: Das System kann die angegebene Datei nicht finden = The system cannot find the specified file

```Building wheels for collected packages: pycocotools
  Running setup.py bdist_wheel for pycocotools ... error
  Complete output from command e:\username\documents\uni\bt\projects\mask_rcnn\mask_rcnn_venv\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\username\\AppData\\Local\\Temp\\pip-install-kkmb1vqh\\pycocotools\\PythonAPI\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\username\AppData\Local\Temp\pip-wheel-ifymsuk7 --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.5
  creating build\lib.win-amd64-3.5\pycocotools
  copying pycocotools\coco.py -> build\lib.win-amd64-3.5\pycocotools
  copying pycocotools\cocoeval.py -> build\lib.win-amd64-3.5\pycocotools
  copying pycocotools\mask.py -> build\lib.win-amd64-3.5\pycocotools
  copying pycocotools\__init__.py -> build\lib.win-amd64-3.5\pycocotools
  running build_ext
  building 'pycocotools._mask' extension
  error: [WinError 2] Das System kann die angegebene Datei nicht finden

  ----------------------------------------
  Failed building wheel for pycocotools
  Running setup.py clean for pycocotools
  Complete output from command e:\username\documents\uni\bt\projects\mask_rcnn\mask_rcnn_venv\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\username\\AppData\\Local\\Temp\\pip-install-kkmb1vqh\\pycocotools\\PythonAPI\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\username\AppData\Local\Temp\pip-install-kkmb1vqh\pycocotools\PythonAPI\setup.py", line 25, in <module>
      cythonize(ext_modules)
    File "e:\username\documents\uni\bt\projects\mask_rcnn\mask_rcnn_venv\lib\site-packages\Cython\Build\Dependencies.py", line 897, in cythonize
      aliases=aliases)
    File "e:\username\documents\uni\bt\projects\mask_rcnn\mask_rcnn_venv\lib\site-packages\Cython\Build\Dependencies.py", line 777, in create_extension_list
      for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
    File "e:\username\documents\uni\bt\projects\mask_rcnn\mask_rcnn_venv\lib\site-packages\Cython\Build\Dependencies.py", line 102, in nonempty
      raise ValueError(error_msg)
  ValueError: 'pycocotools/_mask.pyx' doesn't match any files

  ----------------------------------------
  Failed cleaning build dir for pycocotools
Failed to build pycocotools
Installing collected packages: pycocotools
  Running setup.py install for pycocotools ... error
    Complete output from command e:\username\documents\uni\bt\projects\mask_rcnn\mask_rcnn_venv\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\username\\AppData\\Local\\Temp\\pip-install-kkmb1vqh\\pycocotools\\PythonAPI\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\username\AppData\Local\Temp\pip-record-0dga2y1h\install-record.txt --single-version-externally-managed --compile --install-headers e:\username\documents\uni\bt\projects\mask_rcnn\mask_rcnn_venv\include\site\python3.5\pycocotools:
    running install
    running build
    running build_py
    running build_ext
    building 'pycocotools._mask' extension
    error: [WinError 2] Das System kann die angegebene Datei nicht finden

    ----------------------------------------
Command "e:\username\documents\uni\bt\projects\mask_rcnn\mask_rcnn_venv\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\username\\AppData\\Local\\Temp\\pip-install-kkmb1vqh\\pycocotools\\PythonAPI\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\username\AppData\Local\Temp\pip-record-0dga2y1h\install-record.txt --single-version-externally-managed --compile --install-headers e:\username\documents\uni\bt\projects\mask_rcnn\mask_rcnn_venv\include\site\python3.5\pycocotools" failed with error code 1 in C:\Users\username\AppData\Local\Temp\pip-install-kkmb1vqh\pycocotools\PythonAPI
```

I hope somebody of you can help. Please let me know if you need further informations. 

Best Regards CptK1ng

**Comment by RegivaldoCarvalho** [comment]
@CptK1ng  did you solve this problem? I have the same issue.
