### ISSUE TITLE
my own dataset train raise TypeError: Can't convert 'PngImageFile' object to str implicitly and StopIteration

### ISSUE THREAD

**Issue by ZengyuanYu** [matterport/Mask_RCNN#643]
Checkpoint Path: /home/yu/Mask_RCNN/logs/shapes20180605T2146/mask_rcnn_shapes_{epoch:04d}.h5
Selecting layers to train
fpn_c5p5               (Conv2D)
fpn_c4p4               (Conv2D)
fpn_c3p3               (Conv2D)
fpn_c2p2               (Conv2D)
fpn_p5                 (Conv2D)
fpn_p2                 (Conv2D)
fpn_p3                 (Conv2D)
fpn_p4                 (Conv2D)
In model:  rpn_model
    rpn_conv_shared        (Conv2D)
    rpn_class_raw          (Conv2D)
    rpn_bbox_pred          (Conv2D)
mrcnn_mask_conv1       (TimeDistributed)
mrcnn_mask_bn1         (TimeDistributed)
mrcnn_mask_conv2       (TimeDistributed)
mrcnn_mask_bn2         (TimeDistributed)
mrcnn_class_conv1      (TimeDistributed)
mrcnn_class_bn1        (TimeDistributed)
mrcnn_mask_conv3       (TimeDistributed)
mrcnn_mask_bn3         (TimeDistributed)
mrcnn_class_conv2      (TimeDistributed)
mrcnn_class_bn2        (TimeDistributed)
mrcnn_mask_conv4       (TimeDistributed)
mrcnn_mask_bn4         (TimeDistributed)
mrcnn_bbox_fc          (TimeDistributed)
mrcnn_mask_deconv      (TimeDistributed)
mrcnn_class_logits     (TimeDistributed)
mrcnn_mask             (TimeDistributed)
/home/yu/.local/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py:96: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
/home/yu/.local/lib/python3.5/site-packages/keras/engine/training.py:2039: UserWarning: Using a generator with `use_multiprocessing=True` and multiple workers may duplicate your data. Please consider using the`keras.utils.Sequence class.
  UserWarning('Using a generator with `use_multiprocessing=True`'
ERROR:root:Error processing image {'width': 2048, 'id': 6, 'mask_path': '/home/yu/Mask_RCNN/test/mask/fish_3.png', 'height': 1536, 'source': 'shapes', 'yaml_path': '/home/yu/Mask_RCNN/test/total/fish_3_json/info.yaml', 'path': '/home/yu/Mask_RCNN/test/fish/fish_3.bmp'}
Traceback (most recent call last):
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "train_shapes.py", line 137, in load_mask
    num_obj = self.get_obj_index('fish_'+img)
TypeError: Can't convert 'PngImageFile' object to str implicitly
ERROR:root:Error processing image {'width': 2048, 'id': 4, 'mask_path': '/home/yu/Mask_RCNN/test/mask/fish_6.png', 'height': 1536, 'source': 'shapes', 'yaml_path': '/home/yu/Mask_RCNN/test/total/fish_6_json/info.yaml', 'path': '/home/yu/Mask_RCNN/test/fish/fish_6.bmp'}
Traceback (most recent call last):
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "train_shapes.py", line 137, in load_mask
    num_obj = self.get_obj_index('fish_'+img)
TypeError: Can't convert 'PngImageFile' object to str implicitly
ERROR:root:Error processing image {'width': 2048, 'id': 5, 'mask_path': '/home/yu/Mask_RCNN/test/mask/fish_5.png', 'height': 1536, 'source': 'shapes', 'yaml_path': '/home/yu/Mask_RCNN/test/total/fish_5_json/info.yaml', 'path': '/home/yu/Mask_RCNN/test/fish/fish_5.bmp'}
Traceback (most recent call last):
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "train_shapes.py", line 137, in load_mask
    num_obj = self.get_obj_index('fish_'+img)
TypeError: Can't convert 'PngImageFile' object to str implicitly
ERROR:root:Error processing image {'width': 2048, 'id': 1, 'mask_path': '/home/yu/Mask_RCNN/test/mask/fish_2.png', 'height': 1536, 'source': 'shapes', 'yaml_path': '/home/yu/Mask_RCNN/test/total/fish_2_json/info.yaml', 'path': '/home/yu/Mask_RCNN/test/fish/fish_2.bmp'}
Traceback (most recent call last):
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "train_shapes.py", line 137, in load_mask
    num_obj = self.get_obj_index('fish_'+img)
TypeError: Can't convert 'PngImageFile' object to str implicitly
ERROR:root:Error processing image {'width': 2048, 'id': 1, 'mask_path': '/home/yu/Mask_RCNN/test/mask/fish_2.png', 'height': 1536, 'source': 'shapes', 'yaml_path': '/home/yu/Mask_RCNN/test/total/fish_2_json/info.yaml', 'path': '/home/yu/Mask_RCNN/test/fish/fish_2.bmp'}
Traceback (most recent call last):
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "train_shapes.py", line 137, in load_mask
    num_obj = self.get_obj_index('fish_'+img)
TypeError: Can't convert 'PngImageFile' object to str implicitly
ERROR:root:Error processing image {'width': 2048, 'id': 3, 'mask_path': '/home/yu/Mask_RCNN/test/mask/fish_7.png', 'height': 1536, 'source': 'shapes', 'yaml_path': '/home/yu/Mask_RCNN/test/total/fish_7_json/info.yaml', 'path': '/home/yu/Mask_RCNN/test/fish/fish_7.bmp'}
Traceback (most recent call last):
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "train_shapes.py", line 137, in load_mask
    num_obj = self.get_obj_index('fish_'+img)
TypeError: Can't convert 'PngImageFile' object to str implicitly
ERROR:root:Error processing image {'width': 2048, 'id': 6, 'mask_path': '/home/yu/Mask_RCNN/test/mask/fish_3.png', 'height': 1536, 'source': 'shapes', 'yaml_path': '/home/yu/Mask_RCNN/test/total/fish_3_json/info.yaml', 'path': '/home/yu/Mask_RCNN/test/fish/fish_3.bmp'}
Traceback (most recent call last):
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "train_shapes.py", line 137, in load_mask
    num_obj = self.get_obj_index('fish_'+img)
TypeError: Can't convert 'PngImageFile' object to str implicitly
ERROR:root:Error processing image {'width': 2048, 'id': 2, 'mask_path': '/home/yu/Mask_RCNN/test/mask/fish_4.png', 'height': 1536, 'source': 'shapes', 'yaml_path': '/home/yu/Mask_RCNN/test/total/fish_4_json/info.yaml', 'path': '/home/yu/Mask_RCNN/test/fish/fish_4.bmp'}
Traceback (most recent call last):
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "train_shapes.py", line 137, in load_mask
    num_obj = self.get_obj_index('fish_'+img)
TypeError: Can't convert 'PngImageFile' object to str implicitly
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yu/.local/lib/python3.5/site-packages/keras/utils/data_utils.py", line 630, in data_generator_task
    generator_output = next(self._generator)
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "train_shapes.py", line 137, in load_mask
    num_obj = self.get_obj_index('fish_'+img)
TypeError: Can't convert 'PngImageFile' object to str implicitly
ERROR:root:Error processing image {'width': 2048, 'id': 0, 'mask_path': '/home/yu/Mask_RCNN/test/mask/fish_1.png', 'height': 1536, 'source': 'shapes', 'yaml_path': '/home/yu/Mask_RCNN/test/total/fish_1_json/info.yaml', 'path': '/home/yu/Mask_RCNN/test/fish/fish_1.bmp'}
Traceback (most recent call last):
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "train_shapes.py", line 137, in load_mask
    num_obj = self.get_obj_index('fish_'+img)
TypeError: Can't convert 'PngImageFile' object to str implicitly
ERROR:root:Error processing image {'width': 2048, 'id': 2, 'mask_path': '/home/yu/Mask_RCNN/test/mask/fish_4.png', 'height': 1536, 'source': 'shapes', 'yaml_path': '/home/yu/Mask_RCNN/test/total/fish_4_json/info.yaml', 'path': '/home/yu/Mask_RCNN/test/fish/fish_4.bmp'}
Traceback (most recent call last):
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "train_shapes.py", line 137, in load_mask
    num_obj = self.get_obj_index('fish_'+img)
TypeError: Can't convert 'PngImageFile' object to str implicitly
ERROR:root:Error processing image {'width': 2048, 'id': 5, 'mask_path': '/home/yu/Mask_RCNN/test/mask/fish_5.png', 'height': 1536, 'source': 'shapes', 'yaml_path': '/home/yu/Mask_RCNN/test/total/fish_5_json/info.yaml', 'path': '/home/yu/Mask_RCNN/test/fish/fish_5.bmp'}
Traceback (most recent call last):
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "train_shapes.py", line 137, in load_mask
    num_obj = self.get_obj_index('fish_'+img)
TypeError: Can't convert 'PngImageFile' object to str implicitly
ERROR:root:Error processing image {'width': 2048, 'id': 4, 'mask_path': '/home/yu/Mask_RCNN/test/mask/fish_6.png', 'height': 1536, 'source': 'shapes', 'yaml_path': '/home/yu/Mask_RCNN/test/total/fish_6_json/info.yaml', 'path': '/home/yu/Mask_RCNN/test/fish/fish_6.bmp'}
Traceback (most recent call last):
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "train_shapes.py", line 137, in load_mask
    num_obj = self.get_obj_index('fish_'+img)
TypeError: Can't convert 'PngImageFile' object to str implicitly
ERROR:root:Error processing image {'width': 2048, 'id': 4, 'mask_path': '/home/yu/Mask_RCNN/test/mask/fish_6.png', 'height': 1536, 'source': 'shapes', 'yaml_path': '/home/yu/Mask_RCNN/test/total/fish_6_json/info.yaml', 'path': '/home/yu/Mask_RCNN/test/fish/fish_6.bmp'}
Traceback (most recent call last):
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "train_shapes.py", line 137, in load_mask
    num_obj = self.get_obj_index('fish_'+img)
TypeError: Can't convert 'PngImageFile' object to str implicitly
ERROR:root:Error processing image {'width': 2048, 'id': 1, 'mask_path': '/home/yu/Mask_RCNN/test/mask/fish_2.png', 'height': 1536, 'source': 'shapes', 'yaml_path': '/home/yu/Mask_RCNN/test/total/fish_2_json/info.yaml', 'path': '/home/yu/Mask_RCNN/test/fish/fish_2.bmp'}
Traceback (most recent call last):
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "train_shapes.py", line 137, in load_mask
    num_obj = self.get_obj_index('fish_'+img)
TypeError: Can't convert 'PngImageFile' object to str implicitly
ERROR:root:Error processing image {'width': 2048, 'id': 0, 'mask_path': '/home/yu/Mask_RCNN/test/mask/fish_1.png', 'height': 1536, 'source': 'shapes', 'yaml_path': '/home/yu/Mask_RCNN/test/total/fish_1_json/info.yaml', 'path': '/home/yu/Mask_RCNN/test/fish/fish_1.bmp'}
Traceback (most recent call last):
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "train_shapes.py", line 137, in load_mask
    num_obj = self.get_obj_index('fish_'+img)
TypeError: Can't convert 'PngImageFile' object to str implicitly
ERROR:root:Error processing image {'width': 2048, 'id': 3, 'mask_path': '/home/yu/Mask_RCNN/test/mask/fish_7.png', 'height': 1536, 'source': 'shapes', 'yaml_path': '/home/yu/Mask_RCNN/test/total/fish_7_json/info.yaml', 'path': '/home/yu/Mask_RCNN/test/fish/fish_7.bmp'}
Traceback (most recent call last):
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "train_shapes.py", line 137, in load_mask
    num_obj = self.get_obj_index('fish_'+img)
TypeError: Can't convert 'PngImageFile' object to str implicitly
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yu/.local/lib/python3.5/site-packages/keras/utils/data_utils.py", line 630, in data_generator_task
    generator_output = next(self._generator)
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "train_shapes.py", line 137, in load_mask
    num_obj = self.get_obj_index('fish_'+img)
TypeError: Can't convert 'PngImageFile' object to str implicitly
ERROR:root:Error processing image {'width': 2048, 'id': 6, 'mask_path': '/home/yu/Mask_RCNN/test/mask/fish_3.png', 'height': 1536, 'source': 'shapes', 'yaml_path': '/home/yu/Mask_RCNN/test/total/fish_3_json/info.yaml', 'path': '/home/yu/Mask_RCNN/test/fish/fish_3.bmp'}
Traceback (most recent call last):
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "train_shapes.py", line 137, in load_mask
    num_obj = self.get_obj_index('fish_'+img)
TypeError: Can't convert 'PngImageFile' object to str implicitly
ERROR:root:Error processing image {'width': 2048, 'id': 1, 'mask_path': '/home/yu/Mask_RCNN/test/mask/fish_2.png', 'height': 1536, 'source': 'shapes', 'yaml_path': '/home/yu/Mask_RCNN/test/total/fish_2_json/info.yaml', 'path': '/home/yu/Mask_RCNN/test/fish/fish_2.bmp'}
Traceback (most recent call last):
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "train_shapes.py", line 137, in load_mask
    num_obj = self.get_obj_index('fish_'+img)
TypeError: Can't convert 'PngImageFile' object to str implicitly
ERROR:root:Error processing image {'width': 2048, 'id': 0, 'mask_path': '/home/yu/Mask_RCNN/test/mask/fish_1.png', 'height': 1536, 'source': 'shapes', 'yaml_path': '/home/yu/Mask_RCNN/test/total/fish_1_json/info.yaml', 'path': '/home/yu/Mask_RCNN/test/fish/fish_1.bmp'}
Traceback (most recent call last):
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "train_shapes.py", line 137, in load_mask
    num_obj = self.get_obj_index('fish_'+img)
TypeError: Can't convert 'PngImageFile' object to str implicitly
ERROR:root:Error processing image {'width': 2048, 'id': 2, 'mask_path': '/home/yu/Mask_RCNN/test/mask/fish_4.png', 'height': 1536, 'source': 'shapes', 'yaml_path': '/home/yu/Mask_RCNN/test/total/fish_4_json/info.yaml', 'path': '/home/yu/Mask_RCNN/test/fish/fish_4.bmp'}
Traceback (most recent call last):
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "train_shapes.py", line 137, in load_mask
    num_obj = self.get_obj_index('fish_'+img)
TypeError: Can't convert 'PngImageFile' object to str implicitly
ERROR:root:Error processing image {'width': 2048, 'id': 5, 'mask_path': '/home/yu/Mask_RCNN/test/mask/fish_5.png', 'height': 1536, 'source': 'shapes', 'yaml_path': '/home/yu/Mask_RCNN/test/total/fish_5_json/info.yaml', 'path': '/home/yu/Mask_RCNN/test/fish/fish_5.bmp'}
Traceback (most recent call last):
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "train_shapes.py", line 137, in load_mask
    num_obj = self.get_obj_index('fish_'+img)
TypeError: Can't convert 'PngImageFile' object to str implicitly
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yu/.local/lib/python3.5/site-packages/keras/utils/data_utils.py", line 630, in data_generator_task
    generator_output = next(self._generator)
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "train_shapes.py", line 137, in load_mask
    num_obj = self.get_obj_index('fish_'+img)
TypeError: Can't convert 'PngImageFile' object to str implicitly
ERROR:root:Error processing image {'width': 2048, 'id': 4, 'mask_path': '/home/yu/Mask_RCNN/test/mask/fish_6.png', 'height': 1536, 'source': 'shapes', 'yaml_path': '/home/yu/Mask_RCNN/test/total/fish_6_json/info.yaml', 'path': '/home/yu/Mask_RCNN/test/fish/fish_6.bmp'}
Traceback (most recent call last):
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "train_shapes.py", line 137, in load_mask
    num_obj = self.get_obj_index('fish_'+img)
TypeError: Can't convert 'PngImageFile' object to str implicitly
ERROR:root:Error processing image {'width': 2048, 'id': 3, 'mask_path': '/home/yu/Mask_RCNN/test/mask/fish_7.png', 'height': 1536, 'source': 'shapes', 'yaml_path': '/home/yu/Mask_RCNN/test/total/fish_7_json/info.yaml', 'path': '/home/yu/Mask_RCNN/test/fish/fish_7.bmp'}
Traceback (most recent call last):
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "train_shapes.py", line 137, in load_mask
    num_obj = self.get_obj_index('fish_'+img)
TypeError: Can't convert 'PngImageFile' object to str implicitly
ERROR:root:Error processing image {'width': 2048, 'id': 6, 'mask_path': '/home/yu/Mask_RCNN/test/mask/fish_3.png', 'height': 1536, 'source': 'shapes', 'yaml_path': '/home/yu/Mask_RCNN/test/total/fish_3_json/info.yaml', 'path': '/home/yu/Mask_RCNN/test/fish/fish_3.bmp'}
Traceback (most recent call last):
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "train_shapes.py", line 137, in load_mask
    num_obj = self.get_obj_index('fish_'+img)
TypeError: Can't convert 'PngImageFile' object to str implicitly
Process Process-4:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yu/.local/lib/python3.5/site-packages/keras/utils/data_utils.py", line 630, in data_generator_task
    generator_output = next(self._generator)
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1695, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 1210, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "train_shapes.py", line 137, in load_mask
    num_obj = self.get_obj_index('fish_'+img)
TypeError: Can't convert 'PngImageFile' object to str implicitly
Epoch 1/1
Traceback (most recent call last):
  File "train_shapes.py", line 222, in <module>
    layers='heads')
  File "/home/yu/Mask_RCNN/mrcnn/model.py", line 2328, in train
    use_multiprocessing=True,
  File "/home/yu/.local/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/yu/.local/lib/python3.5/site-packages/keras/engine/training.py", line 2065, in fit_generator
    generator_output = next(output_generator)
StopIteration

What can I fix it and go on train?Thanks!

**Comment by anisin13** [comment]
Have you fixed this problem ?

**Comment by fastlater** [comment]
@ZengyuanYu @anisin13  did you solve the problem?
