### ISSUE TITLE
 OSError: Unable to open file (truncated file: eof = 74436151, sblock->base_addr = 0, stored_eof = 257557808)

### ISSUE THREAD

**Issue by farzadzare** [matterport/Mask_RCNN#653]
I want to use Mask-RCNN demo.py in my jupyter notebook but when i ran the the demo code , i faced such a problem
OSError                                   Traceback (most recent call last)
<ipython-input-3-138183a2a830> in <module>()
      3 
      4 # Load weights trained on MS-COCO
----> 5 model.load_weights(COCO_MODEL_PATH, by_name=True)

~/Mask_RCNN/mrcnn/model.py in load_weights(self, filepath, by_name, exclude)
   2102         if h5py is None:
   2103             raise ImportError('`load_weights` requires h5py.')
-> 2104         f = h5py.File(filepath, mode='r')
   2105         if 'layer_names' not in f.attrs and 'model_weights' in f:
   2106             f = f['model_weights']

~/anaconda3/envs/MaskRCNN/lib/python3.6/site-packages/h5py/_hl/files.py in __init__(self, name, mode, driver, libver, userblock_size, swmr, **kwds)
    310             with phil:
    311                 fapl = make_fapl(driver, libver, **kwds)
--> 312                 fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
    313 
    314                 if swmr_support:

~/anaconda3/envs/MaskRCNN/lib/python3.6/site-packages/h5py/_hl/files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
    140         if swmr and swmr_support:
    141             flags |= h5f.ACC_SWMR_READ
--> 142         fid = h5f.open(name, flags, fapl=fapl)
    143     elif mode == 'r+':
    144         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5f.pyx in h5py.h5f.open()

OSError: Unable to open file (truncated file: eof = 74436151, sblock->base_addr = 0, stored_eof = 257557808)

i can not solve my problem
can any body help me??
thank's

**Comment by farzadzare** [comment]
if you mean download the mask_rcnn_coco.h5 file 
i had downloaded it but i faced this error
AttributeError                            Traceback (most recent call last)
<ipython-input-6-138183a2a830> in <module>()
      3 
      4 # Load weights trained on MS-COCO
----> 5 model.load_weights(COCO_MODEL_PATH, by_name=True)

~/Downloads/Mask_RCNN/mrcnn/model.py in load_weights(self, filepath, by_name, exclude)
   2117 
   2118         if by_name:
-> 2119             topology.load_weights_from_hdf5_group_by_name(f, layers)
   2120         else:
   2121             topology.load_weights_from_hdf5_group(f, layers)

AttributeError: module 'keras.engine.topology' has no attribute 'load_weights_from_hdf5_group_by_name'

**Comment by freedom521jin** [comment]
I have the same error,do you solve the problem?

**Comment by farzadzare** [comment]
@freedom521jin,,,,, I coudn't solve it but i deleted all of anaconda and reinstall all of them and it solved

**Comment by freedom521jin** [comment]
@farzadzare ....oh!I have made it.I delete the old model   '  **.h5  ' , and re-download the pre-train model ,and it works.

**Comment by crookednoob** [comment]
@freedom521jin It worked

**Comment by vajpaye** [comment]
@freedom521jin  can u please tell me where is .h5 file is located

**Comment by DerOzean** [comment]
I had the same Problem. 
I coud fix it by changing the ROOT_DIR (the path to root) in balloon.py.
In the Example it is given by ROOT_DIR = '../../'
In my case it is ROOT_DIR='../../../'
So I just had to go on step futher.

**Comment by vajpaye** [comment]
TQ @DerOzean 

COCO_MODEL_PATH = os.path.join(ROOT_DIR, "mask_rcnn_balloon.h5")
print(COCO_MODEL_PATH)
# Download COCO trained weights from Releases if needed
if not os.path.exists(COCO_MODEL_PATH):
    utils.download_trained_weights(COCO_MODEL_PATH)-> this is the responsible for downloading mask_rcnn_ballon.h5 or mask_rcnn_coco.h5

**Comment by yiakwy** [comment]
I have the same problem each time I load coco pretrained model after I clean the data. (rm mask_rcnn_coco.h5). Is the pretrained model corrupted ?

**Comment by yiakwy** [comment]
@farzadzare Have you resolve the OSError problem?

**Comment by AniPrat** [comment]
I have the same issue of OSError in h5py.h5f.open(). I am using windows python 3.6 and latest h5py version.

**Comment by AniPrat** [comment]
I found the solution. The .h5 file was not downloaded completely so it was corrupt. I downloaded it manually by going to the model release page.

**Comment by pissw2016** [comment]
I have the same problem, and inspired by you guy.  Mine is because that I am training with coco.h5 and I copy this weight file to another dir sothat my demo.ipynb can read it. After I load the original version on demo.ipynb it worked perfect.

**Comment by sliawatimena** [comment]
OSError: Unable to open file (truncated file: eof = 218,644,480, sblock->base_addr = 0, stored_eof = 257,557,808)

the solution is:
`wget -c https://github.com/matterport/Mask_RCNN/releases/download/v2.0/mask_rcnn_coco.h5
`

**Comment by farabee22** [comment]
OSError: Unable to open file (truncated file: eof = 286720, sblock->base_addr = 0, stored_eof = 17225924)

**Comment by YeShangguan** [comment]
I've got the same error. And I checked the file name. I've downloaded the wrong file mask_rcnn_ballon.h5. Then I downloaded the right file mask_rcnn_coco.h5, it worked smoothly.

**Comment by yiakwy** [comment]
We solved the problem by downloading the file from microsoft coco website
manually. Actually you can use wget or curl to download it directly.

YeShangguan <notifications@github.com> 于2019年11月26日周二 下午4:05写道：

**Comment by yiakwy** [comment]
The thread should be marked as closed because this was resolved many many
months ago.

Yiak Wang Yi <yiak.wy@gmail.com> 于2019年12月3日周二 下午11:13写道：

**Comment by omdxp** [comment]
It is solved by deleting the old h5 and redownload it again

**Comment by shghahremani** [comment]
Solution!
You need to delet the corrupted h5 file first. If you want to see where it is located, jut print the path directly as follow;

VGG_Weights_path = keras.utils.get_file(
            pretrained_url.split("/")[-1], pretrained_url)
        **print(VGG_Weights_path)**

**Comment by massimobortolato** [comment]
You just need to clear the keras model cache
"del %USERPROFILE%\.keras\models\*"

**Comment by prashantmore277** [comment]
Traceback (most recent call last):
  
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 106, in h5py.h5f.open
OSError: Unable to open file (truncated file: eof = 218934659, sblock->base_addr = 0, stored_eof = 450781856)

**Comment by cyberkarim** [comment]
I'm still having the same issue while doing this in google colab. I already uploaded my model.h5 file in google drive, .made a simple script hosted in colab in the same directory as model.h5. Whenever I run my script, an error is returned. In my case its another model, not mask rcnn

![script](https://user-images.githubusercontent.com/58376217/184163956-b285054b-56d7-42a1-a03a-3db9580af143.PNG)
![error](https://user-images.githubusercontent.com/58376217/184163965-c9c5d3b0-f849-4bd2-b21e-b5c67920eabb.PNG)
![struct](https://user-images.githubusercontent.com/58376217/184163972-4c6bb2f4-cf1c-4eb3-9398-9960acc40ca7.PNG)

**Comment by Dhaval-Mainkar** [comment]
Hi I'm getting the same error did u resolve it?

**Comment by cyberkarim** [comment]
> Hi I'm getting the same error did u resolve it?
Yes, there was a problem with the .h5 file. It wasn't uploaded correctly to drive. I had to reupload the correct version of the file.

**Comment by prashantmore277** [comment]
> Hi I'm getting the same error did u resolve it?

@Dhaval-Mainkar 
Its happens due to intterupt during downloading files at starts👈
Hey if you are getting this error in G-colab then just use Above solution and if you get this error in your terminal in local machine then just go to cache folder and delete .ht5 cache files and then start the process of installing models again.

You can also Use This Method to delete cache👈
You just need to clear the keras model cache
"del %USERPROFILE%.keras\models*"

**Comment by xiaobaiaaaaa** [comment]
> Hi I'm

Re-download the h5 weight file

**Comment by abhinavaxid** [comment]
how and where can I download the .h5 file??

**Comment by prashantmore277** [comment]
just clear cache and start the process again no need to download .h5 file

**Comment by prashantmore277** [comment]
just clear cache and start the process again no need to download .h5 file
