### ISSUE TITLE
Compatibility issue with Keras 2.2.0

### ISSUE THREAD

**Issue by srk97** [matterport/Mask_RCNN#669]
In `demo.ipynb`, the line `model.load_weights(COCO_MODEL_PATH, by_name=True)` causes the error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Mask_RCNN/mrcnn/model.py", line 2119, in load_weights
    topology.load_weights_from_hdf5_group_by_name(f, layers)
AttributeError: module 'keras.engine.topology' has no attribute 'load_weights_from_hdf5_group_by_name'
```

This module isn't compatible with Keras 2.2.0 that was released a few days back. Switching back to Keras 2.1.6 fixed it for me. The code can either be updated to not use the deprecated module or the `requirements.txt` can exclude Keras 2.2 version.

**Comment by Vimos** [comment]
I guess it's fixed in [pull/662](https://github.com/matterport/Mask_RCNN/pull/662) which is refereed in [issues/566](https://github.com/matterport/Mask_RCNN/issues/566).

But I am not sure if it's backward compatible.

**Comment by talhasaruhan** [comment]
You should be able to replace all 'topology' occurrences with 'saving'. And it should work fine.

**Comment by mekomlusa** [comment]
I had the same issue before so I switched back to Keras 2.1.6 as suggested by others.
