### ISSUE TITLE
Making an environment.yml for anaconda

### ISSUE THREAD

**Issue by edulabrennes** [matterport/Mask_RCNN#699]
Hi all,
I would like to make an environment for anaconda for this project. With it, it should be easy to install this project with tree commands
    git clone https://github.com/matterport/Mask_RCNN.git
    cd Mask_RCNN/
    conda env create

Here is my first attemps with this file

```
name: mask_rcnn
channels:
- !!python/unicode
  'defaults'
dependencies:
- python
- scipy
- pillow
- cython
- matplotlib
- scikit-image
- h5py
- pip
- pip:
  - opencv-python
  - tensorflow-gpu
  - keras
  - git+https://github.com/aleju/imgaug
  - git+https://github.com/waleedka/coco.git#subdirectory=PythonAPI
```

But i've this error with opencv 

```
  Cloning https://github.com/aleju/imgaug to /tmp/pip-req-build-px5mad_1
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/tmp/pip-req-build-px5mad_1/setup.py", line 10, in <module>
        import cv2 # pylint: disable=locally-disabled, unused-import, line-too-long
    ModuleNotFoundError: No module named 'cv2'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-px5mad_1/setup.py", line 12, in <module>
        raise Exception("Could not find package 'cv2' (OpenCV). It cannot be automatically installed, so you will have to manually install it.")
    Exception: Could not find package 'cv2' (OpenCV). It cannot be automatically installed, so you will have to manually install it.
```

Thanks for help !

**Comment by cyprien-pixngraph** [comment]
Ok, it works now for me now :) After installing anaconda (or miniconda), you just need to do the following commands.

Clone the project

    git clone https://github.com/matterport/Mask_RCNN.git
    cd Mask_RCNN/

Perhaps you don't need this command anymore. In the file mrcnn/model.py, replace the "topology" with "saving" 

    sed -i 's/topology/saving/g' mrcnn/model.py

Create this file "environment.yml" in the Mask_RCNN directory with this content

name: mask_rcnn
channels:
- !!python/unicode
  'defaults'
dependencies:
- python
- scipy
- pillow
- cython
- matplotlib
- scikit-image
- h5py
- opencv
- jupyter
- msgpack-python
- pip
- pip:
  - tensorflow-gpu
  - keras
  - git+https://github.com/aleju/imgaug
  - git+https://github.com/waleedka/coco.git#subdirectory=PythonAPI

Create the conda environment

    conda env create

Then, you can run jupyter and launch samples/demo.ipynb

    juyter notebook

Can you test it ? Perhaps you need to install more packages on your system...

**Comment by sulydeni** [comment]
I am using sagemaker following the answers here but I had to do some edits.

`name: mask_rcnn
channels:
- !!python/unicode
  'defaults'
dependencies:
- cudatoolkit
- cudnn
- tensorflow-gpu
- cython
- keras
- python
- scipy
- pillow
- cython
- matplotlib
- scikit-image
- h5py
- opencv
- msgpack-python
- pip
- pip:
  - git+https://github.com/aleju/imgaug
  - git+https://github.com/waleedka/coco.git#subdirectory=PythonAPI
`

works! ... it would've been nice if someone added the environment.yml file

**Comment by workproduct** [comment]
did you have issues with using python 3.7 instead of python 3.4? my anaconda only supports back to 3.5 and having some issues with dependencies: 
`
CondaEnvException: Pip subcommand failed with 
output: Collecting git+https://github.com/aleju/imgaug (from -r C:\Users\WORKPR~1\AppData\Local\Temp\condaenv.s5cyjytj.requirements.txt (line 1))
Cloning https://github.com/aleju/imgaug to c:\users\workpr~1\appdata\local\temp\pip-req-build-vmriwnph
Collecting git+https://github.com/waleedka/coco.git#subdirectory=PythonAPI (from -r C:\Users\WORKPR~1\AppData\Local\Temp\condaenv.s5cyjytj.requirements.txt (line 2))
Cloning https://github.com/waleedka/coco.git to c:\users\workpr~1\appdata\local\temp\pip-req-build-xv63xc3_
Requirement already satisfied: scipy in c:\users\workproduct\anaconda3\lib\site-packages (from imgaug==0.2.8->-r C:\Users\WORKPR~1\AppData\Local\Temp\condaenv.s5cyjytj.requirements.txt (line 1)) (1.1.0)
Collecting scikit-image>=0.11.0 (from imgaug==0.2.8->-r C:\Users\WORKPR~1\AppData\Local\Temp\condaenv.s5cyjytj.requirements.txt (line 1))
Using cached https://files.pythonhosted.org/packages/a1/db/7e7c247ea1800b0b7f56a0d3614709b8328da34118265b6b9d8b9cefd204/scikit_image-0.14.2-cp37-none-win_amd64.whl
Requirement already satisfied: numpy>=1.15.0 in c:\users\workproduct\anaconda3\lib\site-packages (from imgaug==0.2.8->-r C:\Users\WORKPR~1\AppData\Local\Temp\condaenv.s5cyjytj.requirements.txt (line 1)) (1.15.1)
Requirement already satisfied: six in c:\users\workproduct\anaconda3\lib\site-packages (from imgaug==0.2.8->-r C:\Users\WORKPR~1\AppData\Local\Temp\condaenv.s5cyjytj.requirements.txt (line 1)) (1.11.0)
Requirement already satisfied: imageio in c:\users\workproduct\anaconda3\lib\site-packages (from imgaug==0.2.8->-r C:\Users\WORKPR~1\AppData\Local\Temp\condaenv.s5cyjytj.requirements.txt (line 1)) (2.4.1)
Requirement already satisfied: Pillow in c:\users\workproduct\anaconda3\lib\site-packages (from imgaug==0.2.8->-r C:\Users\WORKPR~1\AppData\Local\Temp\condaenv.s5cyjytj.requirements.txt (line 1)) (5.2.0)
Requirement already satisfied: matplotlib in c:\users\workproduct\anaconda3\lib\site-packages (from imgaug==0.2.8->-r C:\Users\WORKPR~1\AppData\Local\Temp\condaenv.s5cyjytj.requirements.txt (line 1)) (2.2.3)
Collecting Shapely (from imgaug==0.2.8->-r C:\Users\WORKPR~1\AppData\Local\Temp\condaenv.s5cyjytj.requirements.txt (line 1))
Using cached https://files.pythonhosted.org/packages/a2/fb/7a7af9ef7a35d16fa23b127abee272cfc483ca89029b73e92e93cdf36e6b/Shapely-1.6.4.post2.tar.gz
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "", line 1, in 
File "C:\Users\WORKPR~1\AppData\Local\Temp\pip-install-8ifkn_17\Shapely\setup.py", line 80, in 
from shapely._buildcfg import geos_version_string, geos_version, \
File "C:\Users\WORKPR~1\AppData\Local\Temp\pip-install-8ifkn_17\Shapely\shapely\_buildcfg.py", line 200, in 
lgeos = CDLL("geos_c.dll")
File "C:\Users\workproduct\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

----------------------------------------

error: The system cannot find the path specified.
Command "python setup.py egg_info" failed with error code 1 in C:\Users\WORKPR~1\AppData\Local\Temp\pip-install-8ifkn_17\Shapely\
You are using pip version 10.0.1, however version 19.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
`

**Comment by workproduct** [comment]
once i run the notebook I am getting 
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-e4a3b32e5dfc> in <module>
      5 import numpy as np
      6 import scipy
----> 7 import skimage.io
      8 #from scipy import skimage.io
      9 import matplotlib

**Comment by sulydeni** [comment]
N.B I tested that I have tested that on Amazon Linux machine and using python 3.6, it seems that your first error has something to do with some permissions.

try following this answer to resolve this shapely issue:
    https://stackoverflow.com/a/52968578/6247757
 
If you want to add this line to environment.yml file to run python 3.6 instead of 3.7 - go for it: 
`- python=3.6`
