### ISSUE TITLE
OpenBLAS blas_thread_init: pthread_create: Resource temporarily unavailable

### ISSUE THREAD

**Issue by jbk41** [matterport/Mask_RCNN#705]
Hardware: NIH Biowulf cluster node with a tesla P100 gpu and 40g of memory. 
Software: Tensorflow-gpu 1.8.0, CUDA 7.0, cuDNN 9.0, centOS 7
I am trying to train my own dataset using the coco weights as a starting point.
When I actually begin training the model with these lines, 

`
model = modellib.MaskRCNN(mode="training", config=config,
                     model_dir=MODEL_DIR)
model.load_weights(COCO_MODEL_PATH, by_name=True,
                           exclude=["mrcnn_class_logits", "mrcnn_bbox_fc",
                                    "mrcnn_bbox", "mrcnn_mask"])
with tf.device('/device:GPU:0'):
         model.train(dataset_train, dataset_test,
                     learning_rate=config.LEARNING_RATE,
                     epochs=1,
                     layers='heads')
`

Then I receive this error after running 99/100 steps on the first epoch. 

`OpenBLAS blas_thread_init: pthread_create: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 513778 max
`
I've tried updating software and checking dependencies but I don't know what else to do. Thanks.

**Comment by mekomlusa** [comment]
Hey I experienced the exactly same issue as you did! Looks like somebody has raised the same concern [earlier](https://github.com/matterport/Mask_RCNN/issues/611). So this is what I did:

Change the `fit_generator` in `model.py` to be the following: (line 2344)

```
self.keras_model.fit_generator(
            train_generator,
            initial_epoch=self.epoch,
            epochs=epochs,
            steps_per_epoch=self.config.STEPS_PER_EPOCH,
            callbacks=callbacks,
            validation_data=val_generator,
            validation_steps=self.config.VALIDATION_STEPS,
            max_queue_size=100,
            workers=1,
            use_multiprocessing=False,
        )
```

Disable multiprocessing should help you out here.

**Comment by sandyhsia** [comment]
I experienced the same thing on tensorflow-gpu=1.6, keras=2.1.6. This problems happened occasionally, but seems to be resolved with `use_multiprocessing=False, workers=1`. But I noticed the training efficiency decreased because of the i/o bottleneck maybe? So I really hope there're methods to resolve the problem with multiprocessing.

**Comment by mekomlusa** [comment]
Well, unfortunately I don't think the package supports multi threads (correct me if I'm wrong please). If you changed the `fit_generator` as I suggested above and use `GPU_COUNT=2` or more might help?

**Comment by nirandiw** [comment]
I set the following in `model.py` as you suggested. 

```
workers=1,
use_multiprocessing=False
```
But I am getting the following error. Any suggestions?

```
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/keras/engine/training_generator.py", line 122, in fit_generator
    max_queue_size=max_queue_size)
  File "/opt/anaconda3/lib/python3.6/site-packages/keras/utils/data_utils.py", line 476, in start
    self.run_thread.start()
  File "/opt/anaconda3/lib/python3.6/threading.py", line 846, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "epa_train.py", line 349, in <module>
    layers="heads")
  File "/notebooks/shared-datasets/shared-datasets/demos/mask-r-cnn/Mask_RCNN/mrcnn/model.py", line 2375, in train
    use_multiprocessing=False,
  File "/opt/anaconda3/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/opt/anaconda3/lib/python3.6/site-packages/keras/engine/training_generator.py", line 262, in fit_generator
    val_enqueuer.stop()
  File "/opt/anaconda3/lib/python3.6/site-packages/keras/utils/data_utils.py", line 496, in stop
    self.run_thread.join(timeout)
  File "/opt/anaconda3/lib/python3.6/threading.py", line 1051, in join
    raise RuntimeError("cannot join thread before it is started")
RuntimeError: cannot join thread before it is started
```
Any suggestions?
