### ISSUE TITLE
Balloon sample error: Softmax() got an unexpected keyword argument 'axis'

### ISSUE THREAD

**Issue by tluth** [matterport/Mask_RCNN#779]
Following the balloons read me, I downloaded the weightfile and dataset and moved them to the recommended directories. I then tried to run the following command from the root directory: 

```python3 balloon.py splash --weights=/full path/mask_rcnn_balloon.h5 --image=/full path/test_balloon.jpg```

Initially I get the error "ModuleNotFoundError: No module named 'mrcnn'" as mentioned in a previous issue. So I replaced the "../../" in balloon.py to the absolute path name for the root directory. 

I am now getting the following error: 

```Traceback (most recent call last):
  File "balloon.py", line 329, in <module>
    model_dir=args.logs)
  File "/Users/tomlutherborrow/Documents/TU_Berlin/WS_1718/GIS_Project/Mask_RCNN/mrcnn/model.py", line 1845, in __init__
    self.keras_model = self.build(mode=mode, config=config)
  File "/Users/tomlutherborrow/Documents/TU_Berlin/WS_1718/GIS_Project/Mask_RCNN/mrcnn/model.py", line 2046, in build
    fc_layers_size=config.FPN_CLASSIF_FC_LAYERS_SIZE)
  File "/Users/tomlutherborrow/Documents/TU_Berlin/WS_1718/GIS_Project/Mask_RCNN/mrcnn/model.py", line 946, in fpn_classifier_graph
    name="mrcnn_class")(mrcnn_class_logits)
  File "/Users/tomlutherborrow/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 619, in __call__
    output = self.call(inputs, **kwargs)
  File "/Users/tomlutherborrow/anaconda3/lib/python3.6/site-packages/keras/layers/wrappers.py", line 213, in call
    y = self.layer.call(inputs, **kwargs)
  File "/Users/tomlutherborrow/anaconda3/lib/python3.6/site-packages/keras/layers/core.py", line 304, in call
    return self.activation(inputs)
  File "/Users/tomlutherborrow/anaconda3/lib/python3.6/site-packages/keras/activations.py", line 29, in softmax
    return K.softmax(x)
  File "/Users/tomlutherborrow/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2963, in softmax
    return tf.nn.softmax(x, axis=axis)
TypeError: softmax() got an unexpected keyword argument 'axis' ```

**Comment by JoeLogan1981** [comment]
Which version of TF and Keras are you using?

**Comment by tluth** [comment]
Tensorflow 1.1.0 & Keras 2.1.6 so I guess I've just got to update TF. Will let you know if it works after updating.

**Comment by nikparmar** [comment]
same error!

**Comment by tluth** [comment]
I set up a new virtual env, reinstalled all the packages and somehow it's now fine.

**Comment by Raj7kumar7** [comment]
@tluth How to set a virtual env ??

**Comment by tluth** [comment]
@Raj7kumar7 

install anaconda, then use: 
`conda create -n yourenvname` and `conda activate yourenvname`

follow this: https://uoa-eresearch.github.io/eresearch-cookbook/recipe/2014/11/20/conda/

**Comment by Raj7kumar7** [comment]
@tluth thank you.it worked.

**Comment by gittigxuy** [comment]
So,which version of tensorflow and keras could run the code without any error?@tluth

**Comment by gittigxuy** [comment]
my environment is ubuntu14.04,my tf-gpu==1.4.0,keras==2.1.3,is ok@Raj7kumar7

**Comment by shuklam20** [comment]
Either change to Keras 2.0.8. However, if you want to work in your current Keras version, go to model.py and modify `from keras.engine import topology` to `from keras.engine import saving as topology`
inside the _load_weights_ function definition. (It works for my Keras 2.2.0 and TF 1.4.0)

**Comment by lalazari** [comment]
If you recently installed tensorflow-gpu try re-installing keras too.

For example:
Considering you have:
Tensorflow==1.3.0
Keras==2.0.8
And you recently installed tensorflow-gpu==1.3.0 via pip, you should definitely reinstall keras via pip too.
So, pip uninstall keras and then `pip install keras==2.0.8` or 2.1.0.

**Comment by Jordi-Gene-Mola** [comment]
@lalazari thank you. it worked!
