### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute '__version__'

### ISSUE THREAD

**Issue by harryyhw** [matterport/Mask_RCNN#795]
When I run the first part of the demo, I get the following error:  

Traceback (most recent call last):
  File "demo.py", line 16, in <module>
    import mrcnn.model as modellib
  File "/data/harryyhw/Mask_RCNN/mrcnn/model.py", line 31, in <module>
    assert LooseVersion(tf.__version__) >= LooseVersion("1.3")
AttributeError: module 'tensorflow' has no attribute '__version__'

How do I fix this?

**Comment by XetrovTornado** [comment]
try change `tf.version` to `tf.__version__` in the model.py code

**Comment by harryyhw** [comment]
it is `__version__` in the code, sorry! my previous post didn't show this because the underscores were treated as formatting by GitHub.

**Comment by preethamsridhar** [comment]
you might have tried to uninstall and install tensorflow. There are chances of the environment using 2 kinds of tensorflows. Try creating a new environment and start fresh it would work. And never place with the tensorflow versions again.

**Comment by jitendra42** [comment]
@preethamsridhar is right. at least in my case that was the root cause of this error.

**Comment by edglo98** [comment]
> 
> 
> you might have tried to uninstall and install tensorflow. There are chances of the environment using 2 kinds of tensorflows. Try creating a new environment and start fresh it would work. And never place with the tensorflow versions again.

This worked. Thank you. I did the installation like [this](https://365datascience.com/tutorials/machine-learning-tutorials/install-tensorflow-2-anaconda/)
