### ISSUE TITLE
Overflow error: Python int too large to convert to C ssize_t

### ISSUE THREAD

**Issue by jerofad** [matterport/Mask_RCNN#835]
Trying to implement Mask-RCNN on my own dataset using the balloon example, I am having the stack trace error below.

`Epoch 1/60
ERROR:root:Error processing image {'id': '015.jpg', 'source': 'pot_crack', 'path': 'datasets/pot-crack/train/015.jpg', 'width': 480, 'height': 320, 'polygons': [{'name': 'rect', 'x': 11, 'y': 140, 'width': 127, 'height': 43}, {'name': 'rect', 'x': 233, 'y': 138, 'width': 133, 'height': 42}], 'names': [{'Class': 'crack'}, {'Class': 'crack'}]}
Traceback (most recent call last):
  File "/content/Pothole-Crack-Detection_MRCNN/mrcnn/model.py", line 1699, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/content/Pothole-Crack-Detection_MRCNN/mrcnn/model.py", line 1213, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "pot_crack.py", line 169, in load_mask
    rr, cc = skimage.draw.polygon(p['y'], p['x'])
  File "/usr/local/lib/python3.6/dist-packages/skimage/draw/draw.py", line 457, in polygon
    return _polygon(r, c, shape)
  File "skimage/draw/_draw.pyx", line 217, in skimage.draw._draw._polygon
OverflowError: Python int too large to convert to C ssize_t
ERROR:root:Error processing image {'id': 'G0010033.JPG', 'source': 'pot_crack', 'path': 'datasets/pot-crack/train/G0010033.JPG', 'width': 3680, 'height': 2760, 'polygons': [{'name': 'rect', 'x': 1453, 'y': 1398, 'width': 120, 'height': 106}, {'name': 'rect', 'x': 1112, 'y': 1422, 'width': 87, 'height': 68}, {'name': 'rect', 'x': 909, 'y': 1408, 'width': 95, 'height': 74}, {'name': 'rect', 'x': 576, 'y': 1404, 'width': 128, 'height': 66}, {'name': 'rect', 'x': 315, 'y': 1414, 'width': 118, 'height': 66}], 'names': [{'Class': 'pothole'}, {'Class': 'pothole'}, {'Class': 'pothole'}, {'Class': 'pothole'}, {'Class': 'pothole'}]}
Traceback (most recent call last):
  File "/content/Pothole-Crack-Detection_MRCNN/mrcnn/model.py", line 1699, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/content/Pothole-Crack-Detection_MRCNN/mrcnn/model.py", line 1213, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "pot_crack.py", line 169, in load_mask
    rr, cc = skimage.draw.polygon(p['y'], p['x'])
  File "/usr/local/lib/python3.6/dist-packages/skimage/draw/draw.py", line 457, in polygon
    return _polygon(r, c, shape)
  File "skimage/draw/_draw.pyx", line 217, in skimage.draw._draw._polygon
OverflowError: Python int too large to convert to C ssize_t` 

Anyone come across this error while working on a different dataset? I am running this on google colab if it's of any use.

**Comment by Heena-S-Patel** [comment]
I have same issue...can anybody help me...?

**Comment by zuzaanto** [comment]
Same issue here, not in google colab tho

**Comment by lolitsgab** [comment]
Same issue here :( Did anyone ever resolve it?

**Comment by undayo** [comment]
I have same issue, I need help .

**Comment by lolitsgab** [comment]
> I have same issue, I need help .

The problem ended up being with how I was loading my dataset. Make sure that you are loading your dataset correctly!

**Comment by undayo** [comment]
Hi, 
Can you explain me the way you used to load your dataset.

Thank you.

**Comment by ejri** [comment]
Any updates on how this issue was solved?

**Comment by TimNagle-McNaughton** [comment]
@lolitsgab anything you can share?
