### ISSUE TITLE
NoneType when loading mask 

### ISSUE THREAD

**Issue by AlexTS1980** [matterport/Mask_RCNN#894]
I haven't run Mask R-CNN for a few months, rewrote some code today. The model initializes successfull, but when the masks start loading, something happens. The load_mask method finds the corresponding pickled file, unpickles into an array and returns it: 

 
```
   # load the mask
   # the input file is a pickle format: it outputs HxWxNumObj
   def load_mask(self, image_id):
       print ("IMMG", self.image_info[image_id],  image_id, self.image_info[image_id]['num_img'])
       if self.image_info[image_id]['stage'] == 'training':
          self.path = 'newtraining_maskrcnn/train_gt'
          # split the file name to get rid of the .png extension
          self.file_name = self.image_info[image_id]['num_img'].split('.')[0]
          self.gt = pickle.load(open(os.path.join(self.path, self.file_name + '.r'), "rb"))

       elif self.image_info[image_id]['stage'] == 'validation':
          self.path = 'newtraining_maskrcnn/validation_gt'
          # split the file name to get rid of the .png extension
          self.file_name = self.image_info[image_id]['num_img'].split('.')[0]
          self.gt = pickle.load(open(os.path.join(self.path, self.file_name+ '.r'), "rb"))

          # vector for corresponding classes, i.e. if there are 5 obj, class_ids = [1 1 1 1 1]
          self.class_ids = np.ones(self.gt.shape[2])
          print ("imgs", "maskss", self.gt.dtype, self.class_ids.dtype)
          return self.gt.astype(np.bool), self.class_ids.astype(np.int32)
```

The error I'm getting is that `image_id` is NoneType:

```
  File "/usr/local/lib/python3.4/dist-packages/keras/utils/data_utils.py", line 677, in _data_generator_task
    generator_output = next(self._generator)
  File "Mask_RCNN/model.py", line 1529, in data_generator
    load_image_gt(dataset, config, image_id, augment=augment, use_mini_mask=config.USE_MINI_MASK)
  File "Mask_RCNN/model.py", line 1122, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "train_on_other_cow_data.py", line 139, in <module>
    model.train(train_dataset, val_dataset, learning_rate = config.LEARNING_RATE, epochs=1, layers='all')
  File "Mask_RCNN/model.py", line 2093, in train
    **fit_kwargs
  File "/usr/local/lib/python3.4/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/keras/engine/training.py", line 2192, in fit_generator
    generator_output = next(output_generator)
  File "/usr/local/lib/python3.4/dist-packages/keras/utils/data_utils.py", line 793, in get
    six.reraise(value.__class__, value, value.__traceback__)
  File "/usr/local/lib/python3.4/dist-packages/six.py", line 693, in reraise
    raise value
TypeError: 'NoneType' object is not iterable
Exception ignored in: <bound method Session.__del__ of <tensorflow.python.client.session.Session object at 0x7f6d591d1e80>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 712, in __del__
TypeError: 'NoneType' object is not callable
```

I'm very much at loss here: hacking into `model.py` didn't help, and I don't see the loop over which it is iteratred. Any help?

**Comment by jrosebr1** [comment]
Cool, thanks @AlexTS1980. I played around with it as well and found out it was an issue with the dataset class not properly returning masks. I hope this help others who run into the same issue!

**Comment by Sarojini96** [comment]
UserWarning('Using a generator with `use_multiprocessing=True`'
Epoch 1/1
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/sarojini/anaconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/sarojini/anaconda3/lib/python3.7/site-packages/keras/utils/data_utils.py", line 650, in next_sample
    return six.next(_SHARED_SEQUENCES[uid])
  File "/home/sarojini/ML projects/mask rnn test - cracks-weld/mrcnn/model.py", line 1683, in data_generator
    image_ids = np.copy(dataset.image_ids)
AttributeError: 'NoneType' object has no attribute 'image_ids'
"""

The above exception was the direct cause of the following exception:

AttributeError                            Traceback (most recent call last)
<ipython-input-20-993070627a92> in <module>
      6              learning_rate=config.LEARNING_RATE,
      7              epochs=1,
----> 8              layers='heads')

~/ML projects/mask rnn test - cracks-weld/mrcnn/model.py in train(self, train_dataset, val_dataset, learning_rate, epochs, layers, augmentation, custom_callbacks, no_augmentation_sources)
   2379             max_queue_size=100,
   2380             workers=workers,
-> 2381             use_multiprocessing=True,
   2382         )
   2383         self.epoch = max(self.epoch, epochs)

~/anaconda3/lib/python3.7/site-packages/keras/legacy/interfaces.py in wrapper(*args, **kwargs)
     89                 warnings.warn('Update your `' + object_name + '` call to the ' +
     90                               'Keras 2 API: ' + signature, stacklevel=2)
---> 91             return func(*args, **kwargs)
     92         wrapper._original_function = func
     93         return wrapper

~/anaconda3/lib/python3.7/site-packages/keras/engine/training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   1730             use_multiprocessing=use_multiprocessing,
   1731             shuffle=shuffle,
-> 1732             initial_epoch=initial_epoch)
   1733 
   1734     @interfaces.legacy_generator_methods_support

~/anaconda3/lib/python3.7/site-packages/keras/engine/training_generator.py in fit_generator(model, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
    183             batch_index = 0
    184             while steps_done < steps_per_epoch:
--> 185                 generator_output = next(output_generator)
    186 
    187                 if not hasattr(generator_output, '__len__'):

~/anaconda3/lib/python3.7/site-packages/keras/utils/data_utils.py in get(self)
    740                     "`use_multiprocessing=False, workers > 1`."
    741                     "For more information see issue #1638.")
--> 742             six.reraise(*sys.exc_info())

~/anaconda3/lib/python3.7/site-packages/six.py in reraise(tp, value, tb)
    701             if value.__traceback__ is not tb:
    702                 raise value.with_traceback(tb)
--> 703             raise value
    704         finally:
    705             value = None

~/anaconda3/lib/python3.7/site-packages/keras/utils/data_utils.py in get(self)
    709                 try:
    710                     future = self.queue.get(block=True)
--> 711                     inputs = future.get(timeout=30)
    712                     self.queue.task_done()
    713                 except mp.TimeoutError:

~/anaconda3/lib/python3.7/multiprocessing/pool.py in get(self, timeout)
    655             return self._value
    656         else:
--> 657             raise self._value
    658 
    659     def _set(self, i, obj):

AttributeError: 'NoneType' object has no attribute 'image_ids'

**Comment by Sarojini96** [comment]
AttributeError: 'NoneType' object has no attribute 'image_ids'

**Comment by Bourne-M** [comment]
> AttributeError: 'NoneType' object has no attribute 'image_ids'

did you find a solution?
