### ISSUE TITLE
multiprocess broken pipe

### ISSUE THREAD

**Issue by jinfagang** [matterport/Mask_RCNN#905]
There are some errror:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/keras/utils/data_utils.py", line 678, in _data_generator_task
    self.queue.put((True, generator_output))
  File "<string>", line 2, in put
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 756, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 397, in _send_bytes
    self._send(header)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Process Process-16:
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

```

When training on cityscapes dataset.
Any idea why this happen?

**Comment by Sparkofska** [comment]
I'm getting the exact same Error. Also on cityscapes dataset.
Looks to me as if my gpu memory (12GB) is not sufficient for the large images (2048x1024).
I gonna try to lower the IMAGES_PER_GPU from 2 to 1.
I'm already using mini-masks.
Any further ideas how to decrease ram consumption?

**Comment by fauzanzaid** [comment]
@jinfagang You can try changing line 2375 in [model.py](https://github.com/matterport/Mask_RCNN/blob/b29b32c7e402254595ae6819cd9ebaa0ddddde8e/mrcnn/model.py#L2375) to `use_multiprocessing=False`. That worked for me.
