### ISSUE TITLE
Can't save parallel model with multi-gpu after training

### ISSUE THREAD

**Issue by zieitokk** [matterport/Mask_RCNN#918]
Hi, I have encounter one problem. I tried to use 2 gpu to train the network from the beginning. I'm using the coco 2017 datasets which has 117266 training images and 4952 validation images. After having completed one training epoch, it couldn't save the model and outputted

> Epoch 00001: saving model to /mnt/3d48e0b9-40a9-42ab-95a8-44a0a6d88180/home/terry/Mask-RCNN/Mask_RCNN/logs/coco20180910T1508/mask_rcnn_coco_0001.h5
Traceback (most recent call last):
  File "shibaba.py", line 64, in <module>
    layers="all")
  File "/mnt/3d48e0b9-40a9-42ab-95a8-44a0a6d88180/home/terry/Mask-RCNN/Mask_RCNN/mrcnn/model.py", line 2386, in train
    workers=workers,
  File "/home/software/anaconda3/envs/carnd-term1/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/software/anaconda3/envs/carnd-term1/lib/python3.5/site-packages/keras/engine/training.py", line 2213, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/software/anaconda3/envs/carnd-term1/lib/python3.5/site-packages/keras/callbacks.py", line 76, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/software/anaconda3/envs/carnd-term1/lib/python3.5/site-packages/keras/callbacks.py", line 429, in on_epoch_end
    self.model.save(filepath, overwrite=True)
  File "/home/software/anaconda3/envs/carnd-term1/lib/python3.5/site-packages/keras/engine/topology.py", line 2573, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "/home/software/anaconda3/envs/carnd-term1/lib/python3.5/site-packages/keras/models.py", line 111, in save_model
    'config': model.get_config()
  File "/home/software/anaconda3/envs/carnd-term1/lib/python3.5/site-packages/keras/engine/topology.py", line 2414, in get_config
    return copy.deepcopy(config)
  File "/home/software/anaconda3/envs/carnd-term1/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/home/software/anaconda3/envs/carnd-term1/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/software/anaconda3/envs/carnd-term1/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/home/software/anaconda3/envs/carnd-term1/lib/python3.5/copy.py", line 218, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/home/software/anaconda3/envs/carnd-term1/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/home/software/anaconda3/envs/carnd-term1/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/software/anaconda3/envs/carnd-term1/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/home/software/anaconda3/envs/carnd-term1/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/software/anaconda3/envs/carnd-term1/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/home/software/anaconda3/envs/carnd-term1/lib/python3.5/copy.py", line 223, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/home/software/anaconda3/envs/carnd-term1/lib/python3.5/copy.py", line 223, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/home/software/anaconda3/envs/carnd-term1/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/home/software/anaconda3/envs/carnd-term1/lib/python3.5/copy.py", line 223, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/home/software/anaconda3/envs/carnd-term1/lib/python3.5/copy.py", line 223, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/home/software/anaconda3/envs/carnd-term1/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/home/software/anaconda3/envs/carnd-term1/lib/python3.5/copy.py", line 297, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/software/anaconda3/envs/carnd-term1/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/home/software/anaconda3/envs/carnd-term1/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/software/anaconda3/envs/carnd-term1/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/home/software/anaconda3/envs/carnd-term1/lib/python3.5/copy.py", line 297, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/software/anaconda3/envs/carnd-term1/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/home/software/anaconda3/envs/carnd-term1/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/software/anaconda3/envs/carnd-term1/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/home/software/anaconda3/envs/carnd-term1/lib/python3.5/copy.py", line 297, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/software/anaconda3/envs/carnd-term1/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/home/software/anaconda3/envs/carnd-term1/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/software/anaconda3/envs/carnd-term1/lib/python3.5/copy.py", line 174, in deepcopy
    rv = reductor(4)
TypeError: can't pickle SwigPyObject objects

Since I have modified the network by adding pooling layer in ROIAlign layer, I can't utilize the transfer learning method. 
My question is that WHAT SHOULD I DO TO SAVE THE MODEL UNDER THE MULTI-GPU TRAINING?

**Comment by angelbaowei** [comment]
Have you solved it?

**Comment by yamuna83** [comment]
Anyone resolve this issue?
I am trying to same model with weight to deploy to Google cloud Platform.
Any help would be appreciated. Thanks.

**Comment by zieitokk** [comment]
> @zieitokk: do you resolve this problem? thanks

I stored only the weights instead of storing model and weights. You can check the reply above about what I have done to the network. 

What comes to my mind is that there is already a `keras.callback.Tensorboard` in the code. It's `write_graph` parameter is settled as True. So you can monitor the graph by using Tensorboard. 

And also, there is another way you may try. You can construct a list and store the structure in the list.
For example:
```
        sources = list()

        loc = list()

        conf = list()

        # apply vgg up to conv4_3 relu
        for k in range(23):
            x = self.base[k](x)

        s = self.Norm(x)
        sources.append(s)

        # apply vgg up to fc7
        for k in range(23, len(self.base)):
            x = self.base[k](x)

        # apply extra layers and cache source layer outputs
        for k, v in enumerate(self.extras):
            x = v(x)
            if k < self.indicator or k%2 ==0:
                sources.append(x)

        for (x, l, c) in zip(sources, self.loc, self.conf):
            loc.append(l(x).permute(0, 2, 3, 1).contiguous())
            conf.append(c(x).permute(0, 2, 3, 1).contiguous())
```
Where `self.base[i]` is pytorch-based layer. You can append the sequential layers into the list and print it after you compile your model.  

Hope this will help you to solve the problem. Thank you.

**Comment by zieitokk** [comment]
> Anyone resolve this issue?
> I am trying to same model with weight to deploy to Google cloud Platform.
> Any help would be appreciated. Thanks.

Please see the reply above. Thank you.

**Comment by xDzai94** [comment]
> > Have you solved it?
> 
> I have one workaround approach to this issue. Since I modified the model, I couldn't transfer learning from the pre-trained model. So I trained my model for **'all'** layers.
> 
> `model.train(dataset_train, dataset_val, learning_rate=config.LEARNING_RATE / 10, epochs=2, layers="all")`
> 
> And also, I changed the **save_weight_only** flag into **True** in model.py.
> 
> `keras.callbacks.ModelCheckpoint(self.checkpoint_path, monitor='val_loss', verbose=1, save_weights_only=True),`
> 
> This could allow the model to save its weights. But as what I concerned, if I want to save the model, I should train my model from the scratch instead of using load_weights from coco or imagenet.

If I not mistaken what you mean, so I train the network without using weight from coco or image-net, it will able to save the model through the keras callback function ?

**Comment by zieitokk** [comment]
@xDzai94 Yes. If you train the network from the scratch, you will be able to save the model.

**Comment by zakiahmedkgp** [comment]
Same case with me. I am trying to save the complete model by changing:
`keras.callbacks.ModelCheckpoint(self.checkpoint_path, monitor='val_loss', verbose=1, save_weights_only=False),`
but I keep getting the error:
TypeError: can't pickle _thread.RLock objects
I have tried searching for the error but unable to solve the problem.
I want my model to save not only the weights but the complete architecture of it since I want to convert my model to TFLite.
Thanks!

**Comment by zakiahmedkgp** [comment]
> @xDzai94 Yes. If you train the network from the scratch, you will be able to save the model.

Is there any way to save the complete model(not only weights) without training it from scratch?

**Comment by zieitokk** [comment]
> > @xDzai94 Yes. If you train the network from the scratch, you will be able to save the model.
> 
> Is there any way to save the complete model(not only weights) without training it from scratch?

Hi, you may try this [https://github.com/matterport/Mask_RCNN/issues/1299#issuecomment-492968111](url).

**Comment by zakiahmedkgp** [comment]
> > > @xDzai94 Yes. If you train the network from the scratch, you will be able to save the model.
> > 
> > 
> > Is there any way to save the complete model(not only weights) without training it from scratch?
> 
> Hi, you may try this [https://github.com/matterport/Mask_RCNN/issues/1299#issuecomment-492968111](url).

Thank you for replying. But the problem still exists. I have also tried saving the model using:
`KM.save_model(self.keras_model,
                    filepath,
                    overwrite=True,
                    include_optimizer=True)`

and it gives the same error since the:
`keras.callbacks.ModelCheckpoint(self.checkpoint_path, monitor='val_loss', verbose=1, save_weights_only=False)`
also saves with the same model.save method.

I have also tried saving weights and architecture separately using:
```
# Save JSON config to disk
        json_config = self.keras_model.to_json()
        with open('model_config.json', 'w') as json_file:
            json_file.write(json_config)
        
        # Save weights to disk
        print ('saving final weights file once again')
        self.keras_model.save_weights('new_final_weights.h5')
```
and still the error remains as it is.:
TypeError: can't pickle _thread.RLock objects

**Comment by kvnptl** [comment]
> > > > @xDzai94 Yes. If you train the network from the scratch, you will be able to save the model.
> > > 
> > > 
> > > Is there any way to save the complete model(not only weights) without training it from scratch?
> > 
> > 
> > Hi, you may try this [https://github.com/matterport/Mask_RCNN/issues/1299#issuecomment-492968111](url).
> 
> Thank you for replying. But the problem still exists. I have also tried saving the model using:
> `KM.save_model(self.keras_model, filepath, overwrite=True, include_optimizer=True)`
> 
> and it gives the same error since the:
> `keras.callbacks.ModelCheckpoint(self.checkpoint_path, monitor='val_loss', verbose=1, save_weights_only=False)`
> also saves with the same model.save method.
> 
> I have also tried saving weights and architecture separately using:
> 
> ```
> # Save JSON config to disk
>         json_config = self.keras_model.to_json()
>         with open('model_config.json', 'w') as json_file:
>             json_file.write(json_config)
>         
>         # Save weights to disk
>         print ('saving final weights file once again')
>         self.keras_model.save_weights('new_final_weights.h5')
> ```
> 
> and still the error remains as it is.:
> TypeError: can't pickle _thread.RLock objects

same error here, too.

**Comment by kaanaykutkabakci** [comment]
Is there any solution for saving complete model? I am getting same error as "TypeError: can't pickle _thread.RLock objects".

**Comment by cairomo** [comment]
same error here when using the model checkpoint with save_weights_only = False

**Comment by raficabral** [comment]
same error here, too.
