### ISSUE TITLE
when i train , it often come error : MemoryError , fianly it broken quit

### ISSUE THREAD

**Issue by JaosonMa** [matterport/Mask_RCNN#954]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1717, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/usr/local/lib/python3.6/dist-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1219, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "lkk_with_others.py", line 184, in load_mask
    image_info["width"])
  File "lkk_with_others.py", line 244, in annToMask
    m = maskUtils.decode(rle)
  File "/home/jasonma/.local/lib/python3.6/site-packages/pycocotools-2.0-py3.6-linux-x86_64.egg/pycocotools/mask.py", line 91, in decode
    return _mask.decode([rleObjs])[:,:,0]
  File "pycocotools/_mask.pyx", line 150, in pycocotools._mask.decode
MemoryError
Traceback (most recent call last):
  File "/home/jasonma/.local/lib/python3.6/site-packages/keras/utils/data_utils.py", line 678, in _data_generator_task
    self.queue.put((True, generator_output))
  File "<string>", line 2, in put
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 772, in _callmethod
    raise convert_to_error(kind, result)
multiprocessing.managers.RemoteError: 
---------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 228, in serve_client
    request = recv()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
MemoryError
---------------------------------------------------------------------------
 360/1000 [=========>....................] - ETA: 10:01 - loss: 1.4038 - rpn_class_loss: 0.0164 - rpn_bbox_loss: 0.1168 - mrcnn_class_loss: 0.5269 - mrcnn_bbox_loss: 0.2843 - mrcnn_mask_loss: 0.4594ERROR:root:Error processing image {'id': 20180010804, 'source': 'coco', 'path': '/home/jasonma/dev_sdb/data/mask-rcnn-data/lkk/JPEGImages/5586248_103589_1531625416350_010697E9.jpg', 'width': 3024, 'height': 4032, 'annotations': [{'segmentation': [[600, 1106, 600, 1461, 686, 1461, 686, 1106]], 'area': 30530, 'iscrowd': 0, 'ignore': 0, 'image_id': 20180010804, 'bbox': [600, 1106, 86, 355], 'category_id': 1, 'id': 651486}, {'segmentation': [[2049, 1071, 2049, 1493, 2130, 1493, 2130, 1071]], 'area': 34182, 'iscrowd': 0, 'ignore': 0, 'image_id': 20180010804, 'bbox': [2049, 1071, 81, 422], 'category_id': 1, 'id': 651487}, {'segmentation': [[2363, 541, 2363, 835, 2451, 835, 2451, 541]], 'area': 25872, 'iscrowd': 0, 'ignore': 0, 'image_id': 20180010804, 'bbox': [2363, 541, 88, 294], 'category_id': 1, 'id': 651488}, {'segmentation': [[472, 1014, 472, 1480, 585, 1480, 585, 1014]], 'area': 52658, 'iscrowd': 0, 'ignore': 0, 'image_id': 20180010804, 'bbox': [472, 1014, 113, 466], 'category_id': 1, 'id': 651489}, {'segmentation': [[385, 1018, 385, 1483, 489, 1483, 489, 1018]], 'area': 48360, 'iscrowd': 0, 'ignore': 0, 'image_id': 20180010804, 'bbox': [385, 1018, 104, 465],}

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1717, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/usr/local/lib/python3.6/dist-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1219, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "lkk_with_others.py", line 202, in load_mask
    mask = np.stack(instance_masks, axis=2).astype(np.bool)
  File "/home/jasonma/.local/lib/python3.6/site-packages/numpy/core/shape_base.py", line 360, in stack
    return _nx.concatenate(expanded_arrays, axis=axis, out=out)
MemoryError
Traceback (most recent call last):
  File "/home/jasonma/.local/lib/python3.6/site-packages/keras/utils/data_utils.py", line 677, in _data_generator_task
    generator_output = next(self._generator)
  File "/usr/local/lib/python3.6/dist-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1717, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/usr/local/lib/python3.6/dist-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 1219, in load_image_gt
    mask, class_ids = dataset.load_mask(image_id)
  File "lkk_with_others.py", line 202, in load_mask
    mask = np.stack(instance_masks, axis=2).astype(np.bool)
  File "/home/jasonma/.local/lib/python3.6/site-packages/numpy/core/shape_base.py", line 360, in stack
    return _nx.concatenate(expanded_arrays, axis=axis, out=out)
MemoryError
Traceback (most recent call last):
  File "lkk_with_others.py", line 452, in <module>
    layers='all')
  File "/usr/local/lib/python3.6/dist-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py", line 2381, in train
  File "/home/jasonma/.local/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/jasonma/.local/lib/python3.6/site-packages/keras/engine/training.py", line 1415, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/jasonma/.local/lib/python3.6/site-packages/keras/engine/training_generator.py", line 177, in fit_generator
    generator_output = next(output_generator)
  File "/home/jasonma/.local/lib/python3.6/site-packages/keras/utils/data_utils.py", line 793, in get
    six.reraise(value.__class__, value, value.__traceback__)
  File "/home/jasonma/.local/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
multiprocessing.managers.RemoteError: 
---------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 228, in serve_client
    request = recv()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
MemoryError
---------------------------------------------------------------------------

MemoryError comes lot of times, some time it can go on training ,but end it quit 

-----------------------
config my triain

class CocoConfig(Config):
    """Configuration for training on MS COCO.
    Derives from the base Config class and overrides values specific
    to the COCO dataset.
    """
    # Give the configuration a recognizable name
    NAME = "coco"

    # We use a GPU with 12GB memory, which can fit two images.
    # Adjust down if you use a smaller GPU.
    IMAGES_PER_GPU = 1

    # Uncomment to train on 8 GPUs (default is 1)
    GPU_COUNT = 1

    # Number of classes (including background)
    NUM_CLASSES = 1 + 163  # COCO has 80 classes
    
    TRAIN_ROIS_PER_IMAGE = 512
    # VALIDATION_STEPS = 75
    RPN_ANCHOR_RATIOS = [0.5, 0.75, 2]
    DETECTION_MIN_CONFIDENCE = 0.7
    DETECTION_MAX_INSTANCES = 400
    POST_NMS_ROIS_INFERENCE = 2000

one TiTan X : 12GB 
@waleedka @champs @PavlosMelissinos @haeric @rymalia

**Comment by miladm** [comment]
Was this issue resolved? I see the same problem when training on GPU.

**Comment by ghost** [comment]
Same problem here on GPU
