### ISSUE TITLE
AttributeError: 'ParallelModel' object has no attribute '_is_graph_network'

### ISSUE THREAD

**Issue by linquanxu** [matterport/Mask_RCNN#958]
hi, when I run 'python3 parallel_model.py ', an error has happened.any ideas?

**Comment by zymale** [comment]
I had the same problem.Have you solved it?

**Comment by zymale** [comment]
The code is updated. Please look at Pull requests.My problem has been solved.

**Comment by zymale** [comment]
> hi, when I run 'python3 parallel_model.py ', an error has happened.any ideas?
The code is updated. Please look at Pull requests.My problem has been solved.

**Comment by keineahnung2345** [comment]
The problems happens to me when I was using keras 2.2.2, when I downgraded to keras 2.1.3, the problem runs away.

**Comment by linquanxu** [comment]
> The problems happens to me when I was using keras 2.2.2, when I downgraded to keras 2.1.3, the problem runs away.

thanks,you are right!

**Comment by lunasdejavu** [comment]
I am using keras 2.2.4 tensorflow1.14.0
@dcyoung  there is a new error that 
```
    def __getattribute__(self, attrname):
        """Redirect loading and saving methods to the inner model. That's where
        the weights are stored."""
        if 'load' in attrname or 'save' in attrname:
            return getattr(self.inner_model, attrname)
        return super(ParallelModel, self).__getattribute__(attrname)
```
it showed
```
Traceback (most recent call last):
  File "lpr_train.py", line 283, in <module>
    layers='all',augmentation=augmentation)
  File "/data/workspace/willy_sung/Mask_RCNN/mrcnn/model.py", line 2369, in train
    use_multiprocessing=True,
  File "/usr/local/lib/python3.6/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training_generator.py", line 251, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/usr/local/lib/python3.6/dist-packages/keras/callbacks.py", line 79, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/usr/local/lib/python3.6/dist-packages/keras/callbacks.py", line 444, in on_epoch_end
    self.model.save_weights(filepath, overwrite=True)
  File "/data/workspace/willy_sung/Mask_RCNN/mrcnn/parallel_model.py", line 98, in __getattribute__
    return getattr(self.inner_model, attrname)
  File "/data/workspace/willy_sung/Mask_RCNN/mrcnn/parallel_model.py", line 99, in __getattribute__
    return super(ParallelModel, self).__getattribute__(attrname)
AttributeError: 'ParallelModel' object has no attribute 'inner_model'
```
it seems ttaht there is no innwe_model anymore  
how to modify it

**Comment by lovehell** [comment]
@lunasdejavu did you find a solution without changing keras version ? 
I'm facing the same issue
Thanks !
